### ISSUE TITLE
[FR] GPU metrics

### ISSUE THREAD

**Issue by monellz** [google/benchmark#1024]
**Is your feature request related to a problem? Please describe.**
I want to benchmark different CUDA kernels and the execution time and various metrics from profilers are both significant to my optimization. nvprof is a good tool to get such metrics but it's hard to benchmark CUDA kernels with different input, while this repo(google/benchmark) is good at easy benchmark but cannot give the metrics of kernels. 

Maybe the support for CUDA kernel benchmarking can be improved so that we can easily get the metrics and execution time under the framework.

**Describe the solution you'd like**
We can register different CUDA kernels and specify what metrics we want to collect. And the exectuion time and collected metrics will be both reported in the end. 

For example
`Kernel->Metrics(gld_throughput)->Metrics(gst_throughput)`

**Describe alternatives you've considered**

**Additional context**

**Comment by dominichamon** [comment]
The existing workaround we have for this is to use [Manual Timing](https://github.com/google/benchmark#manual-timing). Ie, use some other way to time the CUDA kernel (using some sort of barrier for the end of the workload i guess?) and setting the iteration time. Does that work for your use-case or is CUDA special?

**Comment by monellz** [comment]
> The existing workaround we have for this is to use [Manual Timing](https://github.com/google/benchmark#manual-timing). Ie, use some other way to time the CUDA kernel (using some sort of barrier for the end of the workload i guess?) and setting the iteration time. Does that work for your use-case or is CUDA special?

This method dose give the accurate execution time. But the metrics (such as the instruction_issued, gld_utilization) for kernels are also important to kernel optimization. The repo dosen't support reporting kernel metrics.... 

For example, I implement many CUDA kernels which do the same thing. And I want to benchmark them while get the metrics  (such as the instruction_issued, gld_utilization) for comperation. If I use this repo, I have to use 'nvprof --metrics=xxx ./output_exe' to get the metrics which might be wrong due to the benchmark iterations. If I do not use this repo, I have to manually deal with the time measure and other things.

**Comment by dominichamon** [comment]
I see. Can you combine the manual timing with [Custom counters](https://github.com/google/benchmark#custom-counters) to cover the other metrics? ie, can you get the `instruction_issued` metric at runtime and stick it in the custom counter map?

**Comment by monellz** [comment]
> I see. Can you combine the manual timing with [Custom counters](https://github.com/google/benchmark#custom-counters) to cover the other metrics? ie, can you get the `instruction_issued` metric at runtime and stick it in the custom counter map?

Yes, I can get the metrics at runtime based on [CUPTI](https://docs.nvidia.com/cupti/Cupti/index.html), which follows the 'register->collect metrics->unregister' pattern. But their are many details to deal with. For example, some metrics have multiple run pass to get the final result and might be influenced by co-executing GPU kernels launched by other threads. So maybe it is better to encapsulate the logic into the framework and make it a great tool for CUDA optimization.

I can try to add the feature into the framework and give a PR but I don't know it is consistent with the design of the repo.

**Comment by LebedevRI** [comment]
I think it would not be the best course of action to pile every way out there to measure performance (CUDA/OpenCL/HSA/OpenGL/DirectX/Vulkan/PAPI/???) into the library.

I think instead the current state should be put on it's head - custom timers should be more easily pluggable,
they should be first-class citizen much like custom user counters.

**Comment by monellz** [comment]
It make sense.. It's more pluggable to use custom counters.
Thanks a lot for the helpful reply~
