### ISSUE TITLE
[BUG] internal compiler error when building benchmark on CentOS7

### ISSUE THREAD

**Issue by jmay-objy** [google/benchmark#1044]
**Describe the bug**
Compilation fails on file timers.cc with an "internal compiler error" and no additional information. 

"[ 22%] Building CXX object third_party/googletest/build/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
cd benchmark/build/third_party/googletest/build/googletest && /opt/rh/devtoolset-4/root/usr/bin/c++  -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -DHAVE_STEADY_CLOCK -Ibenchmark/include -Ibenchmark/googletest/googletest/include -Ibenchmark/googletest/googletest  -std=c++11  -Wall  -Wextra  -Wshadow  -fstrict-aliasing  -Wno-deprecated-declarations  -Wstrict-aliasing -O2 -DNDEBUG  -Werror  -Wno-deprecated   -Wall -Wshadow -Werror -DGTEST_HAS_PTHREAD=1 -fexceptions -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -pthread -std=c++11 -o CMakeFiles/gtest.dir/src/gtest-all.cc.o -c benchmark/googletest/googletest/src/gtest-all.cc
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,"

**System**
CentOS Linux release 7.6.1810 (Core)
Linux 3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
c++(GCC) 5.3.1 20160406 (Red Hat 5.3.1-6) - (RedHat DevKit 4)
cmake version 3.17.3

**To reproduce**
git clone https://github.com/google/benchmark
git clone https://github.com/google/googletest benchmark/googletest
cd benchmark
cmake -B build -DCMAKE_VERBOSE_MAKEFILE=TRUE -DCMAKE_CXX_EXTENSIONS=ON -DCMAKE_BUILD_TYPE=Release
cmake --build build --config Release -j
cmake --install build --prefix install/benchmark

**Expected behavior**
Successfully build.

**Screenshots**
n/a

**Additional context**
I have tried enabling/disabling C++ extensions but received same error.
[CMakeCache.txt](https://github.com/google/benchmark/files/5241239/CMakeCache.txt)
[build.txt](https://github.com/google/benchmark/files/5241248/build.txt)

**Comment by LebedevRI** [comment]
That is a compiler bug, it's an upstream issue.
Please report that either to CentOS, or GCC.
