### ISSUE TITLE
[BUG] cmake gets benchmark's version wrong.

### ISSUE THREAD

**Issue by germasch** [google/benchmark#1045]
When running cmake on the current (`v1.5.2`) version of benchmark:

```
-- Found Git: /usr/bin/git (found version "2.17.1")
-- git Version: v1.5.0-73d4d5e8
-- Version: 1.5.0
```
While it should be, obviously, `Version 1.5.2`.

The reason is that you use `git describe` to find the version, but that by default only looks at annotated tags, and the last time an annotated tag was made was 1.5.0.

I think there are various options to fix it:
* turn 1.5.2 into an annotated tag (https://stackoverflow.com/questions/5002555/can-a-lightweight-tag-be-converted-to-an-annotated-tag)
* make sure to release 1.5.3 and later with annotated tags
* add `--tags` to `git describe`, which will make things work with the current lightweight tags.

**Comment by dominichamon** [comment]
hm. the tags are meant to be annotated. i must have missed something.

i just checked locally and mine are annotated so it's possible i forgot to push the tags. i've done that now. let me know if you still see the issue.

**Comment by germasch** [comment]
It works correctly now -- thanks!
