### ISSUE TITLE
[BUG] installed benchmark thinks it's version 0.0.0

### ISSUE THREAD

**Issue by germasch** [google/benchmark#1046]
When downloading a release (e.g., 1.5.2) and building/installing it via cmake, it ends up recording its version as `0.0.0` in its installed cmake config (`lib/cmake/benchmark/benchmarkConfigVersion.cmake`):

```
set(PACKAGE_VERSION "0.0.0")

if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
  set(PACKAGE_VERSION_COMPATIBLE FALSE)
```

The consequence of this is that unfortunately something like `find_package(benchmark 1.5.2)` will fail, since `0.0.0` is considered not compatible.

This is caused by benchmark usually automatically getting its version from `git describe`, but that doesn't work when building a tarball.

**Comment by dominichamon** [comment]
either something [here](https://github.com/google/benchmark/blob/master/cmake/GetGitVersion.cmake#L29) where we fail to identify a git version, or [here](https://github.com/google/benchmark/blob/01c0ab7cbb8afdf8af46baed06514f8fae7ee2fb/CMakeLists.txt#L82) checking if we fail to find a git version would need to be changed.

one option might be to write the git version out to a file as part of the release process and read it from there if the current git version isn't found.

**Comment by germasch** [comment]
Well, the question is how you'd prefer to handle it.

Here's one suggestion (I can make a PR): If the `VERSION` is set in the project command, it'll be used. If it is not set, it'll get the version from git instead. So with this option, in the git tree you'd continue to not provide a `VERSION` to `project()` (you wouldn't merge that hunk). In the release process, you'd add `VERSION x.y.z` to the `project()` command and that'll get picked up when using the tarball.

```diff
--- benchmark/CMakeLists.txt	2020-09-22 10:36:09.000000000 -0400
+++ benchmark-1.5.2/CMakeLists.txt	2020-09-24 08:26:10.000000000 -0400
@@ -13,7 +13,7 @@
   endif()
 endforeach()

-project (benchmark CXX)
+project (benchmark VERSION 1.5.2 LANGUAGES CXX)

 option(BENCHMARK_ENABLE_TESTING "Enable testing of the benchmark library." ON)
 option(BENCHMARK_ENABLE_EXCEPTIONS "Enable the use of exceptions in the benchmark library." ON)
@@ -77,12 +77,16 @@
 list(APPEND CMAKE_MODULE_PATH "${CMAKE_CURRENT_SOURCE_DIR}/cmake")


-# Read the git tags to determine the project version
-include(GetGitVersion)
-get_git_version(GIT_VERSION)
-
+# If the version hasn't been set in the project() command, read the
+# git tags to determine the project version
+if (NOT benchmark_VERSION)
+  include(GetGitVersion)
+  get_git_version(GIT_VERSION)
+  string(REGEX MATCH "[0-9]+\\.[0-9]+\\.[0-9]+" VERSION ${GIT_VERSION})
+else()
+  set(VERSION ${benchmark_VERSION})
+endif()
 # Tell the user what versions we are using
-string(REGEX MATCH "[0-9]+\\.[0-9]+\\.[0-9]+" VERSION ${GIT_VERSION})
 message(STATUS "Version: ${VERSION}")

 # The version of the libraries
```

**Comment by dominichamon** [comment]
This means having the release in a separate branch or doing the release locally each time (to avoid accidentally setting the project). i wonder if the other way round is better: always set the project version to the latest release, and use it iff the git version returns nothing?

**Comment by germasch** [comment]
I can do that, too. Though in the end, that will do just the same as not using the version info from git at all (which would be fine with me):

At the release, the version will be set to, say, 1.5.3 and will be tagged correspondingly. So the two versions give the same answer. During follow-up development, the cmake release will remain at 1.5.3, and git will return 1.5.3-dirty, which gets simplified into 1.5.3 anyway. So easiest would be to just remove getting the git version in the first place.

**Comment by dominichamon** [comment]
The only benefit will be when i forget to update the version in the depot
but remember the git tag and the development version at least is correct :D

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong
<http://www.poorlydrawnlines.com/comic/ideas-2/>.*
