### ISSUE TITLE
Reset Linux kernel cpufreq governor to its previous value rather than `powersave`

### ISSUE THREAD

**Issue by cedric-sun** [google/benchmark#1048]
In #466 a description about how to "disable" CPU performance scaling on Linux was added. It works by setting the cpufreq governor to `performance` (which is arguably not the only way to stabilize CPU frequency) and, later after the benchmark is done, setting that to `powersave`.

I personally think it's more appropriate to memorize what the previous governor was by a simple shell variable, and later restore to that governor, since `powersave` might not be what most users want. [From kernel doc](https://www.kernel.org/doc/html/v5.8/admin-guide/pm/cpufreq.html#powersave):
> powersave
When attached to a policy object, this governor causes the lowest frequency, within the scaling_min_freq policy limit, to be requested for that policy.

Current governor for each logical CPU can be queried from `sysfs` by:
```bash
cat /sys/devices/system/cpu/cpu?/cpufreq/scaling_governor
```

**Comment by dominichamon** [comment]
This sounds reasonable.
