### ISSUE TITLE
[FR] Running google benchmark without pthread

### ISSUE THREAD

**Issue by Denzelmon** [google/benchmark#1055]
My target platform doesn't support threads. Is there any options I can use to disable pthread like `gtest_disable_pthreads` for googletest ?

**Comment by LebedevRI** [comment]
Note that google benchmark doesn't actually use pthread itself, it uses `std::thread`.
On that platform, does `std::thread` not work either? (perhaps it uses a different backend)

**Comment by Denzelmon** [comment]
That platform doesn't support it at all.

**Comment by Denzelmon** [comment]
In other words, can I use the library for single threaded system?

**Comment by dominichamon** [comment]
The library assumes the existence of `<thread>` and `std::thread` to build. However, it only runs things in threads if the benchmark is configured as a [multi-threaded benchmark](https://github.com/google/benchmark#multithreaded-benchmarks).

In other words, if you have a built version for your platform (which platform?) then you can run it without it trying to spawn threads. 

We could extract that out and not support multi-threaded benchmarks on a given platform but it would required some careful surgery to wrap bits in `#define` blocks based on platform support.
