### ISSUE TITLE
[FR] Please provide shorter versions of command line options

### ISSUE THREAD

**Issue by romanwerpachowski** [google/benchmark#1057]
**Is your feature request related to a problem? Please describe.**

Benchmark CLI options are very long. Typing `--benchmark_repetitions=3 --benchmark_report_aggregates_only=true` gets old quickly.

**Describe the solution you'd like**

1. get rid of the `--benchmark` prefix - the user knows that they're running a benchmark.
2. add shorter versions, e.g. `-reps 3` instead of `--benchmark_repetitions=3`.

**Describe alternatives you've considered**

You can set an environment with options, but what if I need to use different options at each run?

**Additional context**

**Comment by dominichamon** [comment]
The benchmark prefix is there to namespace the command line flags. As this is a library and can be included in executables, we need to disambiguate the library's flags from any others that might be linked in.

We could shorten it to `--bm_` i suppose, as an alternative.

**Comment by LebedevRI** [comment]
> The benchmark prefix is there to namespace the command line flags. As this is a library and can be included in executables, we need to disambiguate the library's flags from any others that might be linked in.

+1.
