### ISSUE TITLE
[FR] z/OS XL compiler inline assembly support in CycleTimer

### ISSUE THREAD

**Issue by fanbo-meng** [google/benchmark#1062]
**Is your feature request related to a problem? Please describe.**

Build is failing with z/OS XL compiler with following error message because the inline assembly code in cycleclock.h under s390 arch. z/OS XL compiler uses HLASM syntax. 
```
INFORMATIONAL: Inline assembly statements caused HLASM RC=8 with the following messages:
                                       8 stck     2256(4)
 ASMA141E Bad character in operation code - 2256(4)
 ASMA435I Record 8 in sysinfo.cc(__asm) on volume: ASMA96
                                      12 stck     2256(4)
 ASMA141E Bad character in operation code - 2256(4)
 ASMA435I Record 12 in sysinfo.cc(__asm) on volume: ASMA96
 ERROR: Inline assembly statements caused HLASM RC=8. Compilation terminated.
```
**Describe the solution you'd like**

Need to fix the inline assembly code and define new macros for the z/OS operating system and XL compiler in internal_macros.h and use them to distinguish different OS and compiler under s390 architecture. I will deliver a patch for this issue.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dominichamon** [comment]
all yours. i don't have the means to test that combination but hopefully it'll be a relatively straightforward change.
