### ISSUE TITLE
[BUG] How to limit the number of benchmark iterations for GPU-accelerated computing

### ISSUE THREAD

**Issue by alephpiece** [google/benchmark#1064]
**Describe the bug**
The number of iterations taken by some benchmarks didn't change as expected when I was benchmarking a simple SAXPY code taken from the Nvidia Thrust guide. Some of the benchmarks (compute-intensive) keep running for **10000** times. I've tried to set a manual timer but it doesn't work. Is there any way to limit the number of iterations?

**System**
Which OS, compiler, and compiler version are you using:
  - OS: CentOS Linux release 7.6.1810
  - Compiler and version: GCC-7.3.1, HIP-3.3

**To reproduce**
- Requirements: ROCm-3.3.0, HIPCC, rocPrim, and rocThrust
- SAXPY in hip: [saxpy.hip.cpp](https://gist.github.com/alephpiece/7a014ec6752f08244fc2db2ab35830c8), taken from *[Thrust Quick Start Guide](https://docs.nvidia.com/cuda/pdf/Thrust_Quick_Start_Guide.pdf)*
- Benchmarks: [bm_saxpy.hip.cpp](https://gist.github.com/alephpiece/a5fcc81ba2bb7801b9901bf2ce9f726e)
- Timer: RealTime

**Expected behavior**
Less number of iterations for longer benchmarks.

**Screenshots**
![image](https://user-images.githubusercontent.com/22237751/96747444-dfa7cd00-13fa-11eb-94ec-50ac2af62205.png)

**Comment by LebedevRI** [comment]
Since the actual computations are done on GPU, i'm going to guess that CPU timers are incorrect.
You probably want to propagate actual GPU timings to the manual timer, and actually use it.

**Comment by alephpiece** [comment]
> Since the actual computations are done on GPU, i'm going to guess that CPU timers are incorrect.
> You probably want to propagate actual GPU timings to the manual timer, and actually use it.

I thought the default timer could just figure out the proper number of iterations from the wall time. So I have to setup a GPU timer, or just put a barrier after the function call?

**Comment by alephpiece** [comment]
Alright, I just put a barrier on it and everything looks fine.
```
------------------------------------------------------------------------------
Benchmark                                    Time             CPU   Iterations
------------------------------------------------------------------------------
bm_saxpy_fast<int>/1/real_time           0.046 ms        0.046 ms        15473
bm_saxpy_fast<int>/4/real_time           0.105 ms        0.105 ms         6647
bm_saxpy_fast<int>/16/real_time          0.355 ms        0.212 ms         1974
bm_saxpy_fast<int>/64/real_time           1.34 ms        0.226 ms          511
bm_saxpy_fast<int>/256/real_time          5.33 ms        0.230 ms          100
bm_saxpy_fast<int>/512/real_time          13.4 ms        0.231 ms           41
```

**Comment by LebedevRI** [comment]
I suppose ensuring

> > Since the actual computations are done on GPU, i'm going to guess that CPU timers are incorrect.
> > You probably want to propagate actual GPU timings to the manual timer, and actually use it.
> 
> I thought the default timer could just figure out the proper number of iterations from the wall time. So I have to setup a GPU timer, or just put a barrier after the function call?

I thought there already was a barrier https://gist.github.com/alephpiece/a5fcc81ba2bb7801b9901bf2ce9f726e#file-bm_saxpy-hip-cpp-L25

**Comment by alephpiece** [comment]
> > > Since the actual computations are done on GPU, i'm going to guess that CPU timers are incorrect.
> > > You probably want to propagate actual GPU timings to the manual timer, and actually use it.
> > 
> > 
> > I thought the default timer could just figure out the proper number of iterations from the wall time. So I have to setup a GPU timer, or just put a barrier after the function call?
> 
> I thought there already was a barrier https://gist.github.com/alephpiece/a5fcc81ba2bb7801b9901bf2ce9f726e#file-bm_saxpy-hip-cpp-L25

Yes. That's what I just added. Many thanks :)

**Comment by LebedevRI** [comment]
I see. I assume this can be closed then?
