### ISSUE TITLE
Compare two benchmarks without command line?

### ISSUE THREAD

**Issue by sneppy** [google/benchmark#1065]
I'm not sure if this is already possible, but I was only able to find documentation about the `compare.py` tool. I'd like to compare two benchmarks simply by invoking the program:

```cpp
// Something like this
BENCHMARK_COMPARE(BM_baseline, BM_contender)->Range(8, 8<<10);
```

Rather than:

```console
$ ./compare.py filters ./a.out BM_baseline BM_contender
```

Is it possible?

**Comment by LebedevRI** [comment]
It is not possible, no.
Personally, 
1. that would be duplicating existing functionality
2. it would be extremely limited, and not work for 98% of my uses (because almost always i want to compare different binaries)

**Comment by sneppy** [comment]
With all due respect, 98% of the tests I am working on right now consist in comparing two or more implementations of the sams feature.

Maybe that's not a priority for you, but this would really ease my workflow, running multiple tests and seeing a comparison table for each defined comparison (could even be made to support more than two tests, which I believe it's not even possible with the tool).

But if no on else believes this could be a meaningful addition, so be it.

**Comment by dominichamon** [comment]
We try to keep the benchmark library focused on the bare minimum required to generate the benchmark results. This keeps it as lean and unintrusive as possible. This is why we created the external python tooling for comparison (and why we're trying to move away from CSV exports :) ).

Your use case is completely reasonable, but you should be able to use the compare tooling to run the benchmarks and compare the results (see example 3 [here](https://github.com/google/benchmark/blob/master/docs/tools.md#modes-of-operation)) which is still a single command.

**Comment by LebedevRI** [comment]
@sneppy yep, that exactly was my comment, note the word "Personally"
