### ISSUE TITLE
[BUG] benchmark's CXX feature check fails to detect POSIX_REGEX | GNU_POSIX_REGEX

### ISSUE THREAD

**Issue by n8v8R** [google/benchmark#1072]
**Describe the bug**
trying to compile llvm 11 from source with cmake 3.19 and a llvm 11 toolchain on a X86 debian userland based node
llvm source code pulls in llvm Google’s benchmarking but trying to configure the compilation ends with

```
LLVM FileCheck Found: /usr/lib/llvm-11/bin/FileCheck
 -- Version: 0.0.0
 -- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES -- failed to compile
 -- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
 -- Performing Test HAVE_POSIX_REGEX -- failed to compile
 CMake Warning at utils/benchmark/CMakeLists.txt:244 (message):
   Using std::regex with exceptions disabled is not fully supported
```

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Linux 5.10 rc5 X64
  - package distro: Debian
  - Compiler and version: llvm11 toolchain
  - Cmake version: 3.19.0
  - libpcre2-dev & libpcre2-posix2 version:  10.34-7

**To reproduce**
Steps to reproduce the behaviour:
1. install the llvm 11 toolchain from distro (and all other relevant dependencies for compilation, incl. libpcre2)
2. git clone the llvm source code
3. cmake for the llvm source code
4. See failure

**Expected behaviour**
CXXFeatureCheck.cmake to properly detect _POSIX_REGEX_ as provided through _libpcre2_

**Additional context**
https://pcre.org provides its own native API, as well as a set of wrapper functions that correspond to the POSIX regular expression API.

The CXX feature check is not sufficiently verbose to understand what is failing in the context of checking for GNU_POSIX_REGEX | _POSIX_REGEX_

**Comment by dominichamon** [comment]
The cmake logs should be verbose enough. Can you attach them please? Essentially, we attempt to compile _and  run_ [this source for posix](https://github.com/google/benchmark/blob/master/cmake/posix_regex.cpp). If you want it to work with pcre i suggest you'd need to somehow set the include/library as necessary.

Having said that, i'm not sure we want to keep expanding the set of regex options (ideally we'd get to just std::regex at some point...). I'd have thought your setup would use std::regex and judging by [the error](https://github.com/google/benchmark/blob/master/CMakeLists.txt#L263) we did identify that. You'll just need to enable exceptions to build.

Is there a reason you want the benchmark library to use pcre in particular?

**Comment by LebedevRI** [comment]
Is this really a bug report, or a feature request?
I'm failing to find in `regex.h(7POSIX)` that one needs to `-lpcre` when using `REGEX(3)` functions.
Which to me says that we don't support standalone PCRE in the first place.

**Comment by n8v8R** [comment]
>You'll just need to enable exceptions to build.

That is done.
___

>I'd have thought your setup would use std::regex and judging by the error we did identify that.

Correct but that does not satisfy:

https://github.com/google/benchmark/blob/master/CMakeLists.txt#L263

___

>Is there a reason you want the benchmark library to use pcre in particular?

No, just installed those hoping (desperate measure) to satisfy _POSIX_REGEX_ since the benchmark failed (to detect) without it
___

>Essentially, we attempt to compile and run this source for posix.

dpkg -L libstdc++-10-dev | grep regex.h
/usr/include/c++/10/bits/regex.h

Is there a way to test/debug from the command line.
____
>The cmake logs should be verbose enough. Can you attach them please?

Sure [CMakeFiles.zip](https://github.com/google/benchmark/files/5584087/CMakeFiles.zip)


this is how I get started:

```
cd /srv/build ;
export PATH=$PATH:/usr/lib/llvm-11/bin ;
rm -Rf {*,.*} ;
ccmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_DEFAULT_CMP0114=NEW -DCMAKE_AR=/usr/lib/llvm-11/bin/llvm-ar -DCMAKE_ADDR2LINE=/usr/lib/llvm-11/bin/llvm-addr2line -DCMAKE_C_COMPILER=/usr/lib/llvm-11/bin/clang -DCMAKE_CXX_COMPILER=/usr/lib/llvm-11/bin/clang -DCMAKE_LINKER=/usr/lib/llvm-11/bin/lld -DCMAKE_NM=/usr/lib/llvm-11/bin/llvm-nm -DCMAKE_OBJCOPY=/usr/lib/llvm-11/bin/llvm-objcopy -DCMAKE_OBJDUMP=/usr/lib/llvm-11/bin/llvm-objdump -DCMAKE_RANLIB=/usr/lib/llvm-11/bin/llvm-ranlib -DCMAKE_READELF=/usr/lib/llvm-11/bin/llvm-readelf -DCMAKE_STRIP=/usr/lib/llvm-11/bin/llvm-strip -DBENCHMARK_ENABLE_EXCEPTIONS=1 -DBENCHMARK_ENABLE_LTO=1 -DBENCHMARK_USE_LIBCXX=1 -DENABLE_EXPERIMENTAL_NEW_PASS_MANAGER=1 -DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-PC-linux-gnu -DLLVM_ENABLE_ASSERTIONS=1 -DLLVM_ENABLE_EH=1 -DLLVM_ENABLE_EXPENSIVE_CHECKS=1 -DLLVM_ENABLE_FFI=1 -DLLVM_ENABLE_IDE=1 -DLLVM_ENABLE_LIBCXX=1 -DLLVM_ENABLE_LLD=1 -DLLVM_ENABLE_MODULES=1 -DLLVM_ENABLE_LTO=ON -DLLVM_ENABLE_OCAMLDOC=0 -DLLVM_ENABLE_PER_TARGET_RUNTIME=1 -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra;compiler-rt;debuginfo-tests;libc;libclc;libcxx;libcxxabi;lld;lldb;parallel-libs;polly;pstl;flang' -DLLVM_ENABLE_RTTI=1 -DLLVM_ENABLE_Z3_SOLVER=1 -DLLVM_HOST_TRIPLE=x86_64-pc-linux-gnu -DLLVM_INCLUDE_DOCS=0 -DLLVM_INCLUDE_EXAMPLES=0 -DLLVM_INSTALL_MODULEMAPS=1 -DLLVM_INSTALL_UTILS=1 -DLLVM_LINK_LLVM_DYLIB=1 -DLLVM_OPTIMIZED_TABLEGEN=1 -DLLVM_PARALLEL_COMPILE_JOBS=5 -DLLVM_PARALLEL_LINK_JOBS=5 -DLLVM_TARGETS_TO_BUILD='X86;ARM' -DLLVM_USE_PERF=1 -DLLVM_USE_SPLIT_DWARF=1 -DPython3_EXECUTABLE=/usr/bin/python3 -DINCLUDE_DIRECTORIES=/usr/local/lib/python3.8/dist-packages -DCPACK_BINARY_DEB=1 -DCPACK_BINARY_FREEBSD=0 -DCPACK_BINARY_IFW=0 -DCPACK_BINARY_NSIS=0 -DCPACK_BINARY_RPM=0 -DCPACK_BINARY_STGZ=0 -DCPACK_BINARY_TBZ2=0 -DCPACK_BINARY_TGZ=0 -DCPACK_BINARY_TXZ=0 -DCPACK_BINARY_TZ=0 -DCPACK_SOURCE_RPM=0 -DCPACK_SOURCE_TBZ2=0 -DCPACK_SOURCE_TGZ=0 -DCPACK_SOURCE_TXZ=0 -DCPACK_SOURCE_TZ=0 -DCPACK_SOURCE_ZIP=0 -DCPACK_PACKAGE_CONTACT=km -DCLANG_ENABLE_PROTO_FUZZER=1 -DCLANG_SPAWN_CC1=1 -DCLANG_TEST_USE_VG=1 -DCLANG_TOOLS_TEST_USE_VG=1 -DCOMPILER_RT_INTERCEPT_LIBDISPATCH=1 -DENABLE_LINKER_BUILD_ID=1 -DLIBCLANG_INCLUDE_CLANG_TOOLS_EXTRA=1 -DLIBCXXABI_ENABLE_STATIC_UNWINDER=1 -DLIBCXXABI_HERMETIC_STATIC_LIBRARY=1 -DLIBCXX_CONFIGURE_IDE=1 -DLIBCXX_ENABLE_ASSERTIONS=1 -DLIBCXX_ENABLE_PARALLEL_ALGORITHMS=1 -DLIBCXX_ENABLE_PEDANTIC=1 -DLIBCXX_HAS_MUSL_LIBC=1 -DLIBCXX_HERMETIC_STATIC_LIBRARY=1 -DLIBCXX_HIDE_FROM_ABI_PER_TU_BY_DEFAULT=1 -DLIBCXX_TEST_GDB_PRETTY_PRINTER=1 -DPSTL_HIDE_FROM_ABI_PER_TU=1 -DPSTL_PARALLEL_BACKEND=tbb /srv/src/llvm/llvm
```

**Comment by n8v8R** [comment]
As additional measure installed from the distro the `gnulib` package 

```
dpkg -L gnulib | grep regex.h
/usr/share/gnulib/lib/regex.h
```

which one expect to satisfy then _GNU_POSIX_REGEX_ but it does not either, least the outcome is the same.

One thing I noticed that enabling `BENCHMARK_ENABLE_EXCEPTIONS` it gets automatically disabled however after each benchmark run.

**Comment by dominichamon** [comment]
> One thing I noticed that enabling `BENCHMARK_ENABLE_EXCEPTIONS` it gets automatically disabled however after each benchmark run.

This is a compile-time option. What do you mean "after each run"? Do you have a `CMakeCache.txt` anywhere? that should have a line `BENCHMARK_ENABLE_EXCEPTIONS:BOOL=ON` in there somewhere (if you want to use std::regex).

**Comment by dominichamon** [comment]
> > You'll just need to enable exceptions to build.
> 
> That is done.

it's not in your below command line

> 
> > I'd have thought your setup would use std::regex and judging by the error we did identify that.
> 
> Correct but that does not satisfy:
> 
> https://github.com/google/benchmark/blob/master/CMakeLists.txt#L263
> 

Right, because `BENCHMARK_ENABLE_EXCEPTIONS` is not ON.

> > Is there a reason you want the benchmark library to use pcre in particular?
> 
> No, just installed those hoping (desperate measure) to satisfy _POSIX_REGEX_ since the benchmark failed (to detect) without it

pcre is not posix_regex. I mean, it satisfies that API, but we're looking for which regex engine is available on the system.

> 
> > Essentially, we attempt to compile and run this source for posix.
> 
> ```
> dpkg -L libstdc++-10-dev | grep regex.h
> /usr/include/c++/10/bits/regex.h
> ```
> 
> Is there a way to test/debug from the command line?
> 
> > The cmake logs should be verbose enough. Can you attach them please?
> 
> Sure [CMakeFiles.zip](https://github.com/google/benchmark/files/5584087/CMakeFiles.zip)
> 
> this is how I get started:
> 
> ```
> cd /srv/build ;
> export PATH=$PATH:/usr/lib/llvm-11/bin ;
> rm -Rf {*,.*} ;
> ccmake -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_POLICY_DEFAULT_CMP0114=NEW -DCMAKE_AR=/usr/lib/llvm-11/bin/llvm-ar -DCMAKE_ADDR2LINE=/usr/lib/llvm-11/bin/llvm-addr2line -DCMAKE_C_COMPILER=/usr/lib/llvm-11/bin/clang -DCMAKE_CXX_COMPILER=/usr/lib/llvm-11/bin/clang -DCMAKE_LINKER=/usr/lib/llvm-11/bin/lld -DCMAKE_NM=/usr/lib/llvm-11/bin/llvm-nm -DCMAKE_OBJCOPY=/usr/lib/llvm-11/bin/llvm-objcopy -DCMAKE_OBJDUMP=/usr/lib/llvm-11/bin/llvm-objdump -DCMAKE_RANLIB=/usr/lib/llvm-11/bin/llvm-ranlib -DCMAKE_READELF=/usr/lib/llvm-11/bin/llvm-readelf -DCMAKE_STRIP=/usr/lib/llvm-11/bin/llvm-strip -DBENCHMARK_ENABLE_EXCEPTIONS=1 -DBENCHMARK_ENABLE_LTO=1 -DBENCHMARK_USE_LIBCXX=1 -DENABLE_EXPERIMENTAL_NEW_PASS_MANAGER=1 -DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-PC-linux-gnu -DLLVM_ENABLE_ASSERTIONS=1 -DLLVM_ENABLE_EH=1 -DLLVM_ENABLE_EXPENSIVE_CHECKS=1 -DLLVM_ENABLE_FFI=1 -DLLVM_ENABLE_IDE=1 -DLLVM_ENABLE_LIBCXX=1 -DLLVM_ENABLE_LLD=1 -DLLVM_ENABLE_MODULES=1 -DLLVM_ENABLE_LTO=ON -DLLVM_ENABLE_OCAMLDOC=0 -DLLVM_ENABLE_PER_TARGET_RUNTIME=1 -DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra;compiler-rt;debuginfo-tests;libc;libclc;libcxx;libcxxabi;lld;lldb;parallel-libs;polly;pstl;flang' -DLLVM_ENABLE_RTTI=1 -DLLVM_ENABLE_Z3_SOLVER=1 -DLLVM_HOST_TRIPLE=x86_64-pc-linux-gnu -DLLVM_INCLUDE_DOCS=0 -DLLVM_INCLUDE_EXAMPLES=0 -DLLVM_INSTALL_MODULEMAPS=1 -DLLVM_INSTALL_UTILS=1 -DLLVM_LINK_LLVM_DYLIB=1 -DLLVM_OPTIMIZED_TABLEGEN=1 -DLLVM_PARALLEL_COMPILE_JOBS=5 -DLLVM_PARALLEL_LINK_JOBS=5 -DLLVM_TARGETS_TO_BUILD='X86;ARM' -DLLVM_USE_PERF=1 -DLLVM_USE_SPLIT_DWARF=1 -DPython3_EXECUTABLE=/usr/bin/python3 -DINCLUDE_DIRECTORIES=/usr/local/lib/python3.8/dist-packages -DCPACK_BINARY_DEB=1 -DCPACK_BINARY_FREEBSD=0 -DCPACK_BINARY_IFW=0 -DCPACK_BINARY_NSIS=0 -DCPACK_BINARY_RPM=0 -DCPACK_BINARY_STGZ=0 -DCPACK_BINARY_TBZ2=0 -DCPACK_BINARY_TGZ=0 -DCPACK_BINARY_TXZ=0 -DCPACK_BINARY_TZ=0 -DCPACK_SOURCE_RPM=0 -DCPACK_SOURCE_TBZ2=0 -DCPACK_SOURCE_TGZ=0 -DCPACK_SOURCE_TXZ=0 -DCPACK_SOURCE_TZ=0 -DCPACK_SOURCE_ZIP=0 -DCPACK_PACKAGE_CONTACT=km -DCLANG_ENABLE_PROTO_FUZZER=1 -DCLANG_SPAWN_CC1=1 -DCLANG_TEST_USE_VG=1 -DCLANG_TOOLS_TEST_USE_VG=1 -DCOMPILER_RT_INTERCEPT_LIBDISPATCH=1 -DENABLE_LINKER_BUILD_ID=1 -DLIBCLANG_INCLUDE_CLANG_TOOLS_EXTRA=1 -DLIBCXXABI_ENABLE_STATIC_UNWINDER=1 -DLIBCXXABI_HERMETIC_STATIC_LIBRARY=1 -DLIBCXX_CONFIGURE_IDE=1 -DLIBCXX_ENABLE_ASSERTIONS=1 -DLIBCXX_ENABLE_PARALLEL_ALGORITHMS=1 -DLIBCXX_ENABLE_PEDANTIC=1 -DLIBCXX_HAS_MUSL_LIBC=1 -DLIBCXX_HERMETIC_STATIC_LIBRARY=1 -DLIBCXX_HIDE_FROM_ABI_PER_TU_BY_DEFAULT=1 -DLIBCXX_TEST_GDB_PRETTY_PRINTER=1 -DPSTL_HIDE_FROM_ABI_PER_TU=1 -DPSTL_PARALLEL_BACKEND=tbb /srv/src/llvm/llvm
> ```

**Comment by n8v8R** [comment]
@LebedevRI It appears to be a bug, forget about the PCRE library (red herring) - that just been a desperate attempt for benchmark to detect `GNU_POSIX_REGEX` or `POSIX_REGEX`

as exhibited in the previous post either should be detected since the respective `regex.h` is provided for.

**Comment by dominichamon** [comment]
i really want to know what the build failure is for the posix_regex test. i'm sure we used to log that but i can't find it.

**Comment by n8v8R** [comment]
> > > You'll just need to enable exceptions to build.
> > 
> > 
> > That is done.
> 
> it's not in your below command line

It is, see `-DLLVM_ENABLE_EH=1`

Enclosed [CMakeCache.txt](https://github.com/google/benchmark/files/5584293/CMakeCache.txt), exhibiting:

```
LIBCXXABI_ENABLE_EXCEPTIONS:BOOL=ON
LIBCXX_ENABLE_EXCEPTIONS:BOOL=ON
LLVM_ENABLE_EH:BOOL=1
```

**Comment by dominichamon** [comment]
Ahah, if you add something like this to the `cmake/CXXFeatureCheck.cmake` file in the `try_run` block around line 52:

`              COMPILE_OUTPUT_VARIABLE COMPILE_OUTPUT
               RUN_OUTPUT_VARIABLE RUN_OUTPUT)
`

and then add these to the messages ~15 lines further down, we can see exactly why it's failing.

**Comment by dominichamon** [comment]
> > > > You'll just need to enable exceptions to build.
> > > 
> > > 
> > > That is done.
> > 
> > 
> > it's not in your below command line
> 
> It is, see `-DLLVM_ENABLE_EH=1`

`-DBENCHMARK_ENABLE_EXCEPTIONS=ON` should be there too. we don't read that option from anywhere else.

> 
> Enclosed [CMakeCache.txt](https://github.com/google/benchmark/files/5584293/CMakeCache.txt), exhibiting:
> 
> ```
> LIBCXXABI_ENABLE_EXCEPTIONS:BOOL=ON
> LIBCXX_ENABLE_EXCEPTIONS:BOOL=ON
> LLVM_ENABLE_EH:BOOL=1
> ```


here's a replacement CXXFeatureCheck.cmake with logging:

https://gist.github.com/dominichamon/1a8a0601ed39742c69380f01e1249622

**Comment by n8v8R** [comment]
> This is a compile-time option. What do you mean "after each run"? Do you have a `CMakeCache.txt` anywhere? that should have a line `BENCHMARK_ENABLE_EXCEPTIONS:BOOL=ON` in there somewhere (if you want to use std::regex).

It is set in in the initial command line - see `-DBENCHMARK_ENABLE_EXCEPTIONS=1`

And when run in ccmake it shows OFF again - I am going to make a screen cast.

**Comment by n8v8R** [comment]
Here is the screen-cast (exceeding the 10 MB GH limit, hence the link) https://gofile.io/d/snIPba

Despite `-DBENCHMARK_ENABLE_EXCEPTIONS=1` (alternatively tried `-DBENCHMARK_ENABLE_EXCEPTIONS=ON`) set and even through the ccmake gui repeatedly set to ON it does not stick and repeatedly being reset to OFF...

**Comment by n8v8R** [comment]
>here's a replacement CXXFeatureCheck.cmake with logging:

CXXFeatureCheck.cmake appears twice in the llvm source code, which one to patch?


```
diff -au /srv/src/llvm/llvm/utils/benchmark/cmake/CXXFeatureCheck.cmake /srv/src/llvm/libcxx/utils/google-benchmark/cmake/CXXFeatureCheck.cmake
--- /srv/src/llvm/llvm/utils/benchmark/cmake/CXXFeatureCheck.cmake      2020-11-21 16:27:15.277335929 +0100
+++ /srv/src/llvm/libcxx/utils/google-benchmark/cmake/CXXFeatureCheck.cmake     2020-11-21 16:27:11.280708830 +0100
@@ -28,7 +28,7 @@
   endif()

   if (NOT DEFINED COMPILE_${FEATURE})
-    message("-- Performing Test ${FEATURE}")
+    message(STATUS "Performing Test ${FEATURE}")
     if(CMAKE_CROSSCOMPILING)
       try_compile(COMPILE_${FEATURE}
               ${CMAKE_BINARY_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/cmake/${FILE}.cpp
@@ -42,7 +42,7 @@
         set(RUN_${FEATURE} 1)
       endif()
     else()
-      message("-- Performing Test ${FEATURE}")
+      message(STATUS "Performing Test ${FEATURE}")
       try_run(RUN_${FEATURE} COMPILE_${FEATURE}
               ${CMAKE_BINARY_DIR} ${CMAKE_CURRENT_SOURCE_DIR}/cmake/${FILE}.cpp
               CMAKE_FLAGS ${BENCHMARK_CXX_LINKER_FLAGS}
@@ -51,14 +51,14 @@
   endif()

   if(RUN_${FEATURE} EQUAL 0)
-    message("-- Performing Test ${FEATURE} -- success")
+    message(STATUS "Performing Test ${FEATURE} -- success")
     set(HAVE_${VAR} 1 PARENT_SCOPE)
     add_definitions(-DHAVE_${VAR})
   else()
     if(NOT COMPILE_${FEATURE})
-      message("-- Performing Test ${FEATURE} -- failed to compile")
+      message(STATUS "Performing Test ${FEATURE} -- failed to compile")
     else()
-      message("-- Performing Test ${FEATURE} -- compiled but failed to run")
+      message(STATUS "Performing Test ${FEATURE} -- compiled but failed to run")
     endif()
   endif()
 endfunction()
```

**Comment by n8v8R** [comment]
Anyway, for good measure patched both instances, here are the logs [CMakeFiles.zip](https://github.com/google/benchmark/files/5584890/CMakeFiles.zip) - though that probably does not help with BENCHMARK_ENABLE_EXCEPTIONS being reset

**Comment by n8v8R** [comment]
Solved the mystery of BENCHMARK_ENABLE_EXCEPTIONS being turned OFF repeatedly:

https://github.com/llvm/llvm-project/blob/master/llvm/CMakeLists.txt#L1134

`set(BENCHMARK_ENABLE_EXCEPTIONS OFF CACHE BOOL "Disable benchmark exceptions" FORCE)`

commented that line and it is not being turned off anymore.

However, that does not change the outcome of the issue as reported initially.
___

Next I also commented

`set(HAVE_STD_REGEX ON CACHE BOOL "OK" FORCE)`

and now the benchmark also fails detection for _STD_REGEX_:

```
LLVM FileCheck Found: /usr/lib/llvm-11/bin/FileCheck
 -- Version: 0.0.0
 -- Performing Test HAVE_THREAD_SAFETY_ATTRIBUTES -- failed to compile
 -- Performing Test HAVE_STD_REGEX -- failed to compile
 -- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
 -- Performing Test HAVE_POSIX_REGEX -- failed to compile
 CMake Error at utils/benchmark/CMakeLists.txt:240 (message):
   Failed to determine the source files for the regular expression backend
```

**Comment by n8v8R** [comment]
switching from the _llvm-11_ to a _gcc-10.2_ toolchain the outcome is different

```
LLVM FileCheck Found: /usr/lib/llvm-11/bin/FileCheck
 -- Version: 0.0.0
 -- Performing Test HAVE_STD_REGEX -- success
 -- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
 -- Performing Test HAVE_POSIX_REGEX -- success
 -- Performing Test HAVE_STEADY_CLOCK -- success
```

**Comment by dominichamon** [comment]
this is beginning to seem like the llvm project has overridden things in a specific way that break with the newer versions. @EricWF who has a foot in both camps.

from that output above, you're still not logging the compile errors from the failed _REGEX checks even with the patched cmake so you might have missed somewhere. I don't know much about how llvm have integrated the library so i can't help much more.

so is this an issue with the llvm-11 project failing due to the integration, or the benchmark project failing independently?

**Comment by n8v8R** [comment]
> from that output above, you're still not logging the compile errors from the failed _REGEX checks even with the patched cmake so you might have missed somewhere

Another try then, steps taken:

* fresh/clean git worktree from the llvm-11 source code with tag llvmorg-11.0.0
* patched llvm/llvm/CMakeLists.txt

```
-  set(BENCHMARK_ENABLE_TESTING OFF CACHE BOOL "Disable benchmark testing" FORCE)
-  set(BENCHMARK_ENABLE_EXCEPTIONS OFF CACHE BOOL "Disable benchmark exceptions" FORCE)
+  # set(BENCHMARK_ENABLE_TESTING OFF CACHE BOOL "Disable benchmark testing" FORCE)
+  # set(BENCHMARK_ENABLE_EXCEPTIONS OFF CACHE BOOL "Disable benchmark exceptions" FORCE)
-  set(BENCHMARK_ENABLE_GTEST_TESTS OFF CACHE BOOL "Disable Google Test in benchmark" FORCE)
+  # set(BENCHMARK_ENABLE_GTEST_TESTS OFF CACHE BOOL "Disable Google Test in benchmark" FORCE)
```
* patched _only_ /llvm/libcxx/utils/google-benchmark/cmake/CXXFeatureCheck.cmake with the provided patch
* adjusted the cli by adding `-DBENCHMARK_ENABLE_GTEST_TESTS=1 -BENCHMARK_ENABLE_TESTING=1`, the full cli now reads

Well, here it stops, since now it requires path values

```
GTEST_LIBRARY
GTEST_INCLUDE_DIR
GTEST_MAIN_LIBRARY
```

in order to run the Google Benchmark, but I would know what is expected there in order to get it going.
____
>this is beginning to seem like the llvm project has overridden things in a specific way that break with the newer versions

It is weird but appears that llvm-11 cannot be compiled with a llvm-11 toolchain.
____
> I don't know much about how llvm have integrated the library so i can't help much more

without being able to run the Google Benchmark test it seems that the bug report is misplaced here

**Comment by dominichamon** [comment]
> > from that output above, you're still not logging the compile errors from the failed _REGEX checks even with the patched cmake so you might have missed somewhere
> 
> Another try then, steps taken:
> 
> * fresh/clean git worktree from the llvm-11 source code with tag llvmorg-11.0.0
> * patched llvm/llvm/CMakeLists.txt
> 
> ```
> -  set(BENCHMARK_ENABLE_TESTING OFF CACHE BOOL "Disable benchmark testing" FORCE)
> -  set(BENCHMARK_ENABLE_EXCEPTIONS OFF CACHE BOOL "Disable benchmark exceptions" FORCE)
> +  # set(BENCHMARK_ENABLE_TESTING OFF CACHE BOOL "Disable benchmark testing" FORCE)
> +  # set(BENCHMARK_ENABLE_EXCEPTIONS OFF CACHE BOOL "Disable benchmark exceptions" FORCE)
> -  set(BENCHMARK_ENABLE_GTEST_TESTS OFF CACHE BOOL "Disable Google Test in benchmark" FORCE)
> +  # set(BENCHMARK_ENABLE_GTEST_TESTS OFF CACHE BOOL "Disable Google Test in benchmark" FORCE)
> ```
> 
> * patched _only_ /llvm/libcxx/utils/google-benchmark/cmake/CXXFeatureCheck.cmake with the provided patch
> * adjusted the cli by adding `-DBENCHMARK_ENABLE_GTEST_TESTS=1 -BENCHMARK_ENABLE_TESTING=1`
> 
> Well, here it stops, since now it requires path values
> 
> ```
> GTEST_LIBRARY
> GTEST_INCLUDE_DIR
> GTEST_MAIN_LIBRARY
> ```
> 
> in order to run the Google Benchmark, but I would not know what is expected there in order to get it going.

you can safely remove the two overrides on the CLI regarding testing. if you do want those, and you don't want to pass in the gtest stuff, you can add `-DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON`, but you're getting further from the llvm version.

> 
> > this is beginning to seem like the llvm project has overridden things in a specific way that break with the newer versions
> 
> It is weird but appears that llvm-11 cannot be compiled with a llvm-11 toolchain.
> 
> > I don't know much about how llvm have integrated the library so i can't help much more
> 
> without being able to run the Google Benchmark test it seems that the bug report is misplaced here

**Comment by n8v8R** [comment]
> but you're getting further from the llvm version

I do not not mind, I want to see if it passes the GTest (then being a llvm code issue), or not (then being GTest code issue).
____


> you can safely remove the two overrides on the CLI regarding testing. if you do want those, and you don't want to pass in the gtest stuff, you can add `-DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON`

I want to try the GTest but not knowing what sort of path values are wanted for

```
GTEST_LIBRARY
GTEST_INCLUDE_DIR
GTEST_MAIN_LIBRARY
```

![Screenshot 2020-11-24 152732](https://user-images.githubusercontent.com/13611490/100107121-9ae3db80-2e69-11eb-9182-0daf61a4aaa2.jpg)

**Comment by dominichamon** [comment]
if you set the benchmark library to 'download the dependencies' as above it will automatically download and find the googletest libraries.

**Comment by n8v8R** [comment]
missed llvm's override `set(BENCHMARK_DOWNLOAD_DEPENDENCIES OFF CACHE BOOL "Don't download dependencies" FORCE)`...

then also removed `-DBENCHMARK_ENABLE_GTEST_TESTS=1 -BENCHMARK_ENABLE_TESTING=1` from the cli.

the output appears to be more verbose now, thus assume that the provided patch kicked in, logs [CMakeFiles.zip](https://github.com/google/benchmark/files/5590733/CMakeFiles.zip)

Since I am in the process of lodging a bug report with llvm I would appreciate your feedback whether you reckon this an issue of GTest or rather llvm

**Comment by dominichamon** [comment]
GTEST and BENCHMARK are two different projects (and BENCHMARK can optionally depend on GTEST).

independently of that, your pasted log above doesn't have the check for HAVE_STD_REGEX at all any more, and on compile failure they're not printing the expected log with the error.

your cmake logs you attached don't contain anything useful either.

this doesn't seem to me like an issue with benchmark but i don't have an llvm-11 toolchain to hand to test on.

**Comment by n8v8R** [comment]
I duly apologise for having wasted your time/energy as it turned out to be just another case of user stupidity...

despite the frontend compiler binary for C and C++ being the same
```

# stat /usr/lib/llvm-11/bin/clang++
  File: /usr/lib/llvm-11/bin/clang++ -> clang
  Size: 5               Blocks: 0          IO Block: 4096   symbolic link
Device: 800h/2048d      Inode: 185564      Links: 1 
```

and having declared `CMAKE_CXX_COMPILER=/usr/lib/llvm-11/bin/clang` the compiler chasing down its C lane behavioural structure lane instead of C++

Adjusted to `CMAKE_CXX_COMPILER=/usr/lib/llvm-11/bin/clang++` it then works as can be expected.

**Comment by LebedevRI** [comment]
I also periodically fail into that trap :(
One would think CMake would be checking for that...

**Comment by n8v8R** [comment]
Such check would be useful indeed, on the other hand the user is perhaps not supposed trying to outsmart the compiler command structure by taking a shortcut and circumventing the softlink...

**Comment by LebedevRI** [comment]
It might be good to report this to CMake itself, this seems like an ugly pitfail

**Comment by n8v8R** [comment]
Done https://gitlab.kitware.com/cmake/cmake/-/issues/21496

**Comment by LebedevRI** [comment]
Thank you!

**Comment by dominichamon** [comment]
That's great, thank you for tracking it down. and also for raising that issue; i also make that mistake a lot.

It does have me wondering about making our build logging a bit more verbose, especially if we reach a critical error (no regex engine).
