### ISSUE TITLE
[FR]Add option to report benchmark time in seconds

### ISSUE THREAD

**Issue by vasil-pashov** [google/benchmark#1075]
**Is your feature request related to a problem? Please describe.**
Benchmark currently supports nanoseconds, microseconds and milliseconds. Benchmarks which take several seconds are really hard on the eyes. Support for reporting in seconds could be added.

**Describe the solution you'd like**
Add TimeUnit::kSeconds and update the functions taking TimeUnit so that reporting in seconds could be allowed in console, json and csv

**Comment by dominichamon** [comment]
Sounds reasonable to me. PR welcome.

**Comment by feserr** [comment]
I have made a PR for it #1076.
