### ISSUE TITLE
Missing quotation mark in filename output

### ISSUE THREAD

**Issue by aprokop** [google/benchmark#1082]
When output file cannot be opened, the filename is printed out only with a leading single quote, but not with the closing. The following easily fixes it:
```diff
--- a/src/benchmark.cc
+++ b/src/benchmark.cc
@@ -377,7 +377,7 @@ size_t RunSpecifiedBenchmarks(BenchmarkReporter* display_reporter,
   if (!fname.empty()) {
     output_file.open(fname);
     if (!output_file.is_open()) {
-      Err << "invalid file name: '" << fname << std::endl;
+      Err << "invalid file name: '" << fname << "'" << std::endl;
       std::exit(1);
     }
     if (!file_reporter) {
```
It would also be very helpful it this printed the reason for failure, for example, using `errno` like
```c++
#include <errno.h>
...
  if (!output_file.is_open()) {
    Err << "file '" << fname << "' could not be opened. reason: " << strerror(errno) << std::endl;
```
In my situation, I could not figure out the situation when running benchmark on a cluster, until I added this and found out that the filesystem was mounted read-only on compute nodes.

**Comment by LebedevRI** [comment]
Patches welcomed.
I don't think the `errno` change is correct though - where is it guaranteed that `std::ofstream` sets it?

**Comment by vincenzopalazzo** [comment]
Mh, I think this problem is already fixed? @dominichamon https://github.com/google/benchmark/blob/7d0d9061d83b663ce05d9de5da3d5865a3845b79/src/benchmark.cc#L406

**Comment by dominichamon** [comment]
yes, and the errno is not set as ofstream only sets the failbit on the stream.
