### ISSUE TITLE
[BUG] clang-11 compile error

### ISSUE THREAD

**Issue by natale-p** [google/benchmark#1083]
**Describe the bug**
Cannot compile benchmark due to a configuration error during the cmake phase.

**System**
Which OS, compiler, and compiler version are you using:
  - OS: ArchLinux (Linux 5.10.4)
  - Compiler and version: CLANG 11.0.0

**To reproduce**

```
$ cmake .. -DCMAKE_BUILD_TYPE=Debug
```

Error:
https://imgur.com/a/X5meZ2F

(the error is the same as #914), but compiling the software alone (not as a dependency).

CMakeError.log:

```
Performing C++ SOURCE FILE Test HAVE_CXX_FLAG_WD654 failed with the following output:
Change Dir: /home/asd/Work/asd/src/benchmark-1.5.2/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_078e5/fast && /usr/bin/make  -f CMakeFiles/cmTC_078e5.dir/build.make CMakeFiles/cmTC_078e5.dir/build
make[1]: Entering directory '/home/asd/Work/asd/src/benchmark-1.5.2/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_078e5.dir/src.cxx.o
/usr/bin/clang++ -DHAVE_CXX_FLAG_WD654  -std=c++11  -Wall  -Wextra  -Wshadow  -Wshorten-64-to-32  -fstrict-aliasing  -Wno-deprecated-declarations  -Wstrict-aliasing  -wd654   -wd654 -o CMakeFiles/cmTC_078e5.dir/src.cxx.o -c /home/asd/Work/asd/src/benchmark-1.5.2/build/CMakeFiles/CMakeTmp/src.cxx
clang-11: error: unknown argument: '-wd654'
clang-11: error: unknown argument: '-wd654'
make[1]: *** [CMakeFiles/cmTC_078e5.dir/build.make:85: CMakeFiles/cmTC_078e5.dir/src.cxx.o] Error 1
make[1]: Leaving directory '/home/asd/Work/asd/src/benchmark-1.5.2/build/CMakeFiles/CMakeTmp'
make: *** [Makefile:140: cmTC_078e5/fast] Error 2


Source file was:
int main() { return 0; }
```

CMakeOutput.txt in this pastebin

https://pastebin.com/h19NwVWc

**Expected behavior**
Be able to compile benchmark

**Screenshots**
https://imgur.com/a/X5meZ2F

Thanks

**Comment by dominichamon** [comment]
There's a possible solution in https://github.com/pytorch/glow/issues/2624 but it's not clear to me why it would help.

**Comment by intractabilis** [comment]
> There's a possible solution in pytorch/glow#2624 but it's not clear to me why it would help.

If you look at the screenshot, the real error is about a failure to find a regex engine:
```
-- Performing Test HAVE_STD_REGEX -- compiled but failed to run
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- compiled but failed to run
CMake Error at CMakeLists.txt:260 (message):
  Failed to determine the source files for the regular expression backend
```

The content of CMakeError.log is irrelevant.

**Comment by intractabilis** [comment]
I have the same problem with Clang 12.

**Comment by dominichamon** [comment]
no-one else has raised this as an issue, and we can't repro on our CI bots, so i think this must be something local.

please feel free to reach out or reopen if you still are getting the error.
