### ISSUE TITLE
[BUG] Benchmark does not see Google Test sources

### ISSUE THREAD

**Issue by gasabr** [google/benchmark#1086]
**Describe the bug**
benchmark's cmake script does not detect google test sources.

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Ubuntu 18.04
  - Compiler and version: The CXX compiler identification is GNU 7.5.0

**To reproduce**
I'm aware that it's not fully reproducible example, will provide one, if needed, but probably someone will be able to help me knowing just that.

Here is the relevant part of my cmakelists.txt:

```cmake
find_package(Threads REQUIRED)

ExternalProject_Add(googletest-external
        GIT_REPOSITORY https://github.com/google/googletest.git
        GIT_TAG release-1.10.0
        PREFIX googletest-external
        INSTALL_COMMAND ""
        )

ExternalProject_Get_Property(googletest-external source_dir binary_dir)

add_library(gtest IMPORTED STATIC GLOBAL)
add_dependencies(gtest googletest-external)


set_target_properties(gtest PROPERTIES
        IMPORTED_LOCATION "${binary_dir}/lib/libgtest.a"
        IMPORTED_LINK_INTERFACE_LIBRARIES "${CMAKE_THREAD_LIBS_INIT}"
        INTERFACE_INCLUDE_DIRECTORIES "${source_dir}/googletest/include"
        )

add_library(gmock IMPORTED STATIC GLOBAL)
add_dependencies(gmock googletest-external)

set_target_properties(gmock PROPERTIES
        IMPORTED_LOCATION "${binary_dir}/lib/libgmock.a"
        IMPORTED_LINK_INTERFACE_LIBRARIES "${CMAKE_THREAD_LIBS_INIT}"
        INTERFACE_INCLUDE_DIRECTORIES "${source_dir}/googlemock/include"
        )

ExternalProject_Get_Property(googletest-external source_dir binary_dir)
ExternalProject_Add(gbench-external
        GIT_REPOSITORY https://github.com/google/benchmark.git
        GIT_TAG v1.5.2
        PREFIX gbench-external
        INSTALL_COMMAND ""
        CMAKE_ARGS -DGOOGLETEST_PATH=${source_dir}/googletest/
        )

add_dependencies(gbench-external googletest-external)
add_library(gbench IMPORTED STATIC GLOBAL)
add_dependencies(gbench googletest-external gbench-external)


ExternalProject_Get_Property(gbench-external source_dir binary_dir)
set_target_properties(gbench PROPERTIES
        IMPORTED_LOCATION ${binary_dir}/src/libbenchmark.a
        INTERFACE_INCLUDE_DIRECTORIES ${source_dir}/include/
        )
```

**Expected behavior**
Google Benchmark should be able to find sources of Google Test

**Screenshots**
![Screenshot from 2021-01-12 16-06-33](https://user-images.githubusercontent.com/10960369/104318318-4adfd780-54f0-11eb-9b63-386e9f8c3b46.png)

**Additional context**
* this method works with `CMAKE_ARGS -DBENCHMARK_ENABLE_GTEST_TESTS=OFF`, but I'm not able to run the benchmarks with CTest, only as a binary
* the directory that is searched for gtest sources contains them after the build (verified that by running `ls`)
* googletest-external is being downloaded before gbench-external, from that I conclude that files are there when gbench-external runs
* why not fetch_content? -- we have to specify flags for build sometimes
* why not find_package? -- all the dependencies are being downloaded while running configuring project, so find_package() won't be able to locate them without additional step

**Comment by dominichamon** [comment]
i think you may have a bug but it could just be in your example:

```
ExternalProject_Get_Property(googletest-external source_dir binary_dir)
ExternalProject_Add(gbench-external
        GIT_REPOSITORY https://github.com/google/benchmark.git
        GIT_TAG v1.5.2
        PREFIX gbench-external
        INSTALL_COMMAND ""
        CMAKE_ARGS -DGOOGLETEST_PATH=${source_dir}/googletest/
        )
```

that first line should be `ExternalProject_Get_Property(gbench-external source_dir binary_dir)`

i'm not sure it will help but it might :)

**Comment by gasabr** [comment]
Thanks for response!

oops, i don't remember, how did i put this CMake together, but the problem was solved, probably by fixing the name:)
