### ISSUE TITLE
[help wanted] How to correctly benchmark asynchronous method?

### ISSUE THREAD

**Issue by mbonaventura** [google/benchmark#1108]
Hi, 

I am trying to benchmark an asynchronous API: there is a Save method which returns almost immediately and a callback is executed on a different thread when it completes. 
I would like to measure submitting several Save and measure the time it takes for all of them to complete, letting the framework decide how many to submit (not using ->Iterations(...) )

**Describe alternatives you've considered**
If I force the number of iterations then I can block the last iteration waiting for all Save to complete. But forcing the number of iterations is not optimal: different setups might need different amount of iterations/running time
As follows:

```
#define ITERATIONS 1000*100
static void Write(benchmark::State& state) {
	// Benchmark starts here
	auto io_size = state.range(0); // parameter is io_sizes
	char* write_buffer[io_size]; // TODO: setup buffer
	std::atomic<int> total_writes(0);
	int iteration =0;
	for (auto _ : state){
		fs.Save(write_buffer, io_size, /*callback*/[&total_writes]() {
			total_writes++; // executes on a different thread when save completes
		});
		iteration++;
		// last iteration
		if(iteration == ITERATIONS){
			fs.Flush(); // blocks current thread until all operations complete
		}
	}	
}
BENCHMARK(Write)->Iterations(ITERATIONS)->UseRealTime();
```

I tried using state.iterations() but it is unset inside the for loop. Also KeepRunning is always true inside the loop.

**Expected behavior**
I would like to use MinTime() instead of Iterations(), but I would need that the 'teardown' is also time measured to account for all operations.

```
static void Write(benchmark::State& state) {
	// Benchmark starts here
	auto io_size = state.range(0); // parameter is io_sizes
	char* write_buffer[io_size]; // TODO: setup buffer
	std::atomic<int> total_writes(0);
	for (auto _ : state){
		fs.Save(write_buffer, io_size, /*callback*/[&total_writes]() {
			total_writes++; // executes on a different thread
		});
	}
	std::cout << state.iterations() << " submitted operations, but only " << total_writes << " completed" << std::endl
	// TODO: how do I include this in the time measurements?
	fs.Flush(); // blocks current thread until all operations complete	
}
BENCHMARK(Write)->MinTime(2)->UseRealTime();
```

SetIterationTime() says it has to be called exactly once per iteration, so I can not call it once more manually measuring the Flush time.

Thanks in advance for any ideas!

**Comment by dominichamon** [comment]
(updated your comment to have the code blocks a little neater... hope you don't mind)

So one thing you could try is in the second example, have the `fs.Flush()` call inside the loop but guarded by

```c++
if (state.thread_index == 0) {
  fs.Flush();
}
```

I don't actually know if it'll work, but what it might do is block the loop from exiting until all saves have completed.

**Comment by mbonaventura** [comment]
Thanks for the fast reply!

More of less: that makes all saves to be completed at the end of the loop, but it is flushing on every loop (thread_index is always 0). 
That makes the Saves to be done serially: Write, Flush, Write, Flush, etc, which is not what I am looking for (it is much slower). I would like to submit several Saves, then Flush.

**Comment by dominichamon** [comment]
Oh right, sorry. `thread_index` only changes if you're running the benchmark as multi-threaded.

So you have a single-threaded benchmark but you want to stay in the loop until all threads complete, and they complete when the `Flush` call happens.

it's a bit weird that you're using the number of iterations to control the number of saves. i wonder if you'd be better off having an inner loop over a range from state that controls the number of Saves. so:

```c++
static void BM(benchmark::State& state) {
  for (auto _ : state) {
    for (int i = 0; i < state.range(0); ++i) {
      fs.Save(....);
    }
    fs.Flush();
  }
}
BENCHMARK(BM)->DenseRange(1, 100);
```

This would give you a good sense of how the timing changes as the number of saves going in parallel increases.

**Comment by mbonaventura** [comment]
Thanks a lot Dominic!

Yes, the benchmark is single-thread. But the library I am benchmarking uses mutiple threads: the save callback is executed in a different thread, and Flush blocks the calling thread (in this case the benchmark) until all callbacks has been executed.

What you propose would work for testing how fast it works as a function of parallel saves. But what I really want to test is the max throughput it can achieve (with as many parallel saves as it can be). 

This morning I found that State::max_iterations is public and equals state.iterations() when called the end of the loop. Is there any condition where max_iterations can be less than the total iterations?
With that I can go back to my initial solution of flushing in the last iteration, but letting the framework decide the number of iterations:

```
for (auto _ : state){
                iteration++;
		fs.Save(write_buffer, io_size, /*callback*/[&total_writes]() {
			total_writes++; // executes on a different thread when save completes
		});
				
		if(iteration == state.max_iterations){ // last iteration
			fs.Flush(); // blocks current thread until all operations complete
		}
	}	
```
 
Cheers

**Comment by dominichamon** [comment]
That should work. Though you don't need to count the iterations as you can just call `state.iterations()` instead in the loop. that necessarily returns something < `max_iterations`.

**Comment by mbonaventura** [comment]
That is true! thanks a lot
