### ISSUE TITLE
How to execute slow setup code only once?

### ISSUE THREAD

**Issue by mbonaventura** [google/benchmark#1112]
Hi, 

I have a few benchmarks for which the setup (code before the for loop) takes quite some more time than the code I want to  benchmark (code inside the loop).  
When I set the MinTime to 20s, I see that the complete benchmark (including the slow setup) is executed multiple times, each time increasing the number of iterations. In my case, the slow setup is run 8 times so running the benchmark takes much more time than I was expecting.

Is it possible to execute a setup code only once per benchmark, independently of how many times the iteration estimations need to run?

Thanks in advance
Matias

**Comment by dominichamon** [comment]
Only by moving the setup outside the benchmark entirely, either to main (you'll need a custom main... it's not that hard. [This example](https://github.com/google/benchmark#using-registerbenchmarkname-fn-args) but you don't need to do the registration bit) or to global/static construction (fraught with danger unless the setup can be captured as a const{expr}).

**Comment by mbonaventura** [comment]
Thanks @dominichamon,

I see your point, but  a setup in main would allow me to have just one single setup/teardown for all benchmarks, right? I would need different setups for different benchmarks, like you do for unit tests.

Actually if I fix the number of iterations the setup will be executed just once as expected. So I was wondering why setting MinTime requires running the full benchmark (including setup multiple times) to search for the right number of iterations? 
Can't it just run for at least the specified time and count how many iterations where performed (now seems to be doing the other way around)?

Maybe I am over simplifying but wouldn't some like this be possible?:

```
setup()// just once, don't measure its time

start = now
elapsed =0
while (elapsed < MinTime){ // and the other conditions that guarantee statistical stability
     do_stuff() 
     elapsed = now - start // if getting the time so often has implications, do it only every few hundred iterations
}

teardown() // just once, don't measure its time
```

Thanks again!

**Comment by dominichamon** [comment]
Mixing the iteration limit and mintime is surprisingly complicated as they depend on each other.

We do have the notion of a fixture, but i believe the setup/teardown is also run for each repetition (as opposed to iteration). We could consider moving the fixture setup/teardown to run once per repetition but i think as fixtures can be reused  between benchmarks that may not be a good idea.

**Comment by matta** [comment]
My pull request https://github.com/google/benchmark/pull/1113 improves the situation here a little bit.  With the fix a benchmark can use `KeepRunningBatch` to enforce a of minimum iteration count, and the runner will arrive at an appropriate iteration count much faster than it did before.

**Comment by mbonaventura** [comment]
Thanks @matta and @dominichamon, sorry I took so long but I had to take care of other things.

I actually tried using KeepRunningBatch and it actually reduces the number of ramp up repetitions a lot. 

Thanks!

**Comment by dominichamon** [comment]
Fab!
