### ISSUE TITLE
[FR] rename default branch

### ISSUE THREAD

**Issue by dominichamon** [google/benchmark#1116]
It's time to rename the master branch to main. I have been waiting for a couple of pull requests to land to minimize disruption but I don't want to wait much longer.

So I will do this next week.

**Comment by dominichamon** [comment]
Done

**Comment by maslick** [comment]
This was a bad decision, since many projects (e.g. https://github.com/census-instrumentation/opencensus-cpp) depend on the existence of master branch. You could have left master branch (and having both master and main at the same time)...

**Comment by dominichamon** [comment]
those projects should probably start migrating then, given that new github projects don't have a master branch.

**Comment by maslick** [comment]
@dominichamon I agree with you, but migration takes time, any chance you could leave master branch for backward compatibility? thanks :pray:

**Comment by dominichamon** [comment]
I can't have two default branches, and i don't believe that github supports symbolic-refs as branch aliases for remotes (i'd like to be proved wrong), so i can't think of a way to have a remote master branch that tracks main.

i could have a master branch that is frozen if that would help.

**Comment by maslick** [comment]
No, I meant you could let master branch be in the state that it were when it was renamed to main. Main branch will remain default.

**Comment by dominichamon** [comment]
done. master is back but will get stale. i will remove it in a couple of releases to give some people time to migrate.
