### ISSUE TITLE
[FR] BSD ConanCenter targets

### ISSUE THREAD

**Issue by mcandre** [google/benchmark#1120]
**Is your feature request related to a problem? Please describe.**

The available targets for benchmark on ConanCenter are fairly complete, but do lack some niche UNIX targets such as FreeBSD, OpenBSD, NetBSD, Haiku, MINIX, and MirOS.

**Describe the solution you'd like**

Publish more UNIX targets to ConanCenter.

**Describe alternatives you've considered**

* Skipping the conan package and reverting to vintage package management.

**Comment by LebedevRI** [comment]
I think you need to report that to the Conan itself.
In-repo conan files were dropped.
