### ISSUE TITLE
[FR] Clarify ExtraArgs usage

### ISSUE THREAD

**Issue by mcandre** [google/benchmark#1123]
**Is your feature request related to a problem? Please describe.**

As a C++ novice, I have no idea how to extract parameters from an ExtraArgs entity. The snippet given in the README completely elides this critical syntax.

Is this a vararg? What is this? Even the example test code is confusing: It either does a big fat NOP for the entire benchmark, or fails to bind the parameters to usable names:

https://github.com/google/benchmark/blob/master/test/benchmark_test.cc

**Describe the solution you'd like**

Add a basic extraction example for the provided ExtraArgs arguments, so that the code is closer to real, executable code instead of dummy code. For people unfamiliar with unpacking variadics.

**Comment by dominichamon** [comment]
https://github.com/google/benchmark#passing-arbitrary-arguments-to-a-benchmark could be improved. i'm happy to take a PR that offers an improvement.

no, it is a [parameter pack](https://en.cppreference.com/w/cpp/language/parameter_pack).

something like:

```c++
template <class... Args>                                                          
void BM_with_args(benchmark::State& state, Args&&... args) {                                                                                             
  auto args_tuple = std::make_tuple(std::move(args)...);                          
  for (auto _ : state) {                                                          
    std::cout << std::get<0>(args_tuple) << ": " << std::get<1>(args_tuple)       
              << "\n";                                                            
  }                                                                               
}                                                                                 
BENCHMARK_CAPTURE(BM_with_args, int_test, 42, 43, 44);                            
BENCHMARK_CAPTURE(BM_with_args, int_string_and_pair_test, 42,                     
                  std::string("abc"), std::pair<int, double>(42, 3.8)); 
```

might help?
