### ISSUE TITLE
[FR] Simplify ExtraArgs example

### ISSUE THREAD

**Issue by mcandre** [google/benchmark#1124]
**Is your feature request related to a problem? Please describe.**

There is no need to introduce templates or variadics or complex C++ code in the "ExtraArgs" README snippet. This is confusing and incomplete.

**Describe the solution you'd like**

Just use ordinary function parameters and actually do something with them in the benchmark.

**Describe alternatives you've considered**

nanobench

**Comment by dominichamon** [comment]
unfortunately that's not how parameter packs work or how capturing of arguments works.
