### ISSUE TITLE
[FR] clang-tidy

### ISSUE THREAD

**Issue by mcandre** [google/benchmark#1126]
**Is your feature request related to a problem? Please describe.**

Please adjust the API and inner code to pass clang-tidy. Right now, attempts to use Google Benchmark trigger hundreds of clang-tidy warnings.

For example, the `state` variable is observed by clang-tidy to violate Google's C++ guidelines, specifically the `google-runtime-references` rule.

**Describe the solution you'd like**

* Configure a `.clang-tidy` file for Google Benchmark's inner code.
* Design the API so that user code will not trigger clang-tidy, even if all the rules are turned on.

**Comment by dominichamon** [comment]
The API has been defined with an explicit exception to the runtime reference rule (and that rule has been softened more generally, even if it hasn't made its way to clang-tidy yet).

I would like to see more use of clang-format against the code, but the churn on local versions from making syntactical changes that have no functional benefit is a lot of burden to put on people. we'll incrementally get clang-format clean, i hope.

I have no expectations that people are running clang-tidy, but if you or anyone else feels passionate about it then seeing it get clang-tidy clean, and supporting that with tooling at the git commit level, would be fantastic.

**Comment by LebedevRI** [comment]
> The API has been defined with an explicit exception to the runtime reference rule (and that rule has been softened more generally, even if it hasn't made its way to clang-tidy yet).

That rule is gone nowadays anyways (for almost a year), and said clang-tidy check was removed entirely.

**Comment by dominc8** [comment]
Hi, is this issue still valid? If yes, what is the scope of the task, adding clang-tidy check to github actions and fixing chosen clang-tidy warnings?

**Comment by dominichamon** [comment]
that seems to be about right.

i recently added clang-format linter to actions and then fixed up whatever was necessary.  my only concern with clang-tidy is that we may be violating some rules on purpose.

one option is to set it up with all the exceptions and then we can work through removing each exception in turn..

**Comment by dominc8** [comment]
I created PR with clang-tidy action and some basic checks enabled. Feel free to suggest other checks that could/should be enabled.
