### ISSUE TITLE
[BUG] Not using libpfm causes unnecessary error logs

### ISSUE THREAD

**Issue by debashish-ghosh** [google/benchmark#1134]
Build benchmark without enabling BENCHMARK_ENABLE_LIBPFM produces a library which prints unnecessary error logs.

Output:
```
Load Average: 1.34, 0.60, 0.41
Performance counters not supported.----------------------------------------------------------------------
Benchmark                            Time             CPU   Iterations
----------------------------------------------------------------------
BM_find_list_middle_1ptr/1        1.77 ns         1.77 ns    374956344
Performance counters not supported.BM_find_list_middle_1ptr/8        8.44 ns         8.44 ns     78583785
Performance counters not supported.BM_find_list_middle_1ptr/50       62.0 ns         62.0 ns     10803703
Performance counters not supported.BM_find_list_middle_2ptr/1       0.888 ns        0.888 ns    756329941
Performance counters not supported.BM_find_list_middle_2ptr/8        5.50 ns         5.50 ns    124390045
Performance counters not supported.BM_find_list_middle_2ptr/50       46.4 ns         46.4 ns     14951023
```

Buiding **with** libpfm causes this:
```
Load Average: 1.69, 0.52, 0.32
A counter name was the empty string
----------------------------------------------------------------------
Benchmark                            Time             CPU   Iterations
----------------------------------------------------------------------
BM_find_list_middle_1ptr/1        2.41 ns         2.41 ns    288904260
A counter name was the empty string
BM_find_list_middle_1ptr/8        8.92 ns         8.92 ns     75432254
A counter name was the empty string
BM_find_list_middle_1ptr/50       64.8 ns         64.8 ns      9954366
A counter name was the empty string
BM_find_list_middle_2ptr/1       0.889 ns        0.889 ns    781518116
A counter name was the empty string
BM_find_list_middle_2ptr/8        4.97 ns         4.97 ns    134435190
A counter name was the empty string
BM_find_list_middle_2ptr/50       47.0 ns         47.0 ns     15090207
```

**Comment by debashish-ghosh** [comment]
Using ```stderr```-to bit-bucket-redirect workaround. But it's not a practical solution.

**Comment by LebedevRI** [comment]
Yep, that doesn't look good.
Patches welcomed. It should be easily avoidable.

**Comment by dominichamon** [comment]
@mtrofin ^^

**Comment by debashish-ghosh** [comment]
I've made some changes. It seems to work. Can I raise a PR?

**Comment by dominichamon** [comment]
Yes please!

**Comment by debashish-ghosh** [comment]
I tested this change and it looks better now.

However, there is still an issue of error logs at each benchmark if you give a wrong counter name.
Furthermore, if you provide a comma separated list of counters, some of which are invalid (e.g. typo), then it ignores the entire list.

What I was expecting is that the error should be printed before the first benchmark is run. And whatever counters were valid, should be included in the benchmark results.

**Comment by mtrofin** [comment]
> I tested this change and it looks better now.
> 
> However, there is still an issue of error logs at each benchmark if you give a wrong counter name.

So I better understand, the issue is the one you mention below, i.e. that if a counter name is incorrect, the whole list is ignored, correct? Or is there another issue.

> Furthermore, if you provide a comma separated list of counters, some of which are invalid (e.g. typo), then it ignores the entire list.
> 
> What I was expecting is that the error should be printed before the first benchmark is run. And whatever counters were valid, should be included in the benchmark results.

I think it would be more in the spirit of the feature - precision - to fail fast: if the user asks for counters but none are given, or if some/all the counters are wrong, log and exit. The user can then correct and re-run. wdyt?

**Comment by debashish-ghosh** [comment]
I can accept that. But at least the error logs should be at one place (not interleaved with the benchmark results). Otherwise I would still have to use the ```stderr```-to-bit-bucket hack.

**Comment by mtrofin** [comment]
> I can accept that. But at least the error logs should be at one place (not interleaved with the benchmark results). Otherwise I would still have to use the `stderr`-to-bit-bucket hack.

@dominichamon - any reason we can't exit(1) instead of logging and continuing on? I remember vaguely we touched on that in the original PR, hence my asking.

**Comment by dominichamon** [comment]
they are going to different output streams though. it's not a hack to redirect either stdout or stderr to a different location, is it?

**Comment by mtrofin** [comment]
Right, but because we set up the runner a few times during the execution of the benchmark suite binary, I could see how it gets odd to see the error message repeated - even if on stderr. I *think* fastfail is easier to implement cleanly, compared to avoiding that duplication, but not sure what the negative of fastfail is.
