### ISSUE TITLE
[BUG] CMake release mode build fails due to Werror with Nvidia PGI compiler

### ISSUE THREAD

**Issue by PhilipDeegan** [google/benchmark#1139]
**Describe the bug**
CMake release mode build fails due to Werror with Nvidia PGI compiler

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Debian/Fedora/Linux
  - Compiler and version: Nvidia PGI compiler / 21.3

**To reproduce**
1. from master
2. export CC=pgcc; export CXX=pgc++
2. cmake -DCMAKE_BUILD_TYPE=Release .
3. make 

**Expected behavior**
Build doesn't fail

**Additional context**
These may be false positives from pgc++
Nvidia provide a docker container with pgc++: nvcr.io/nvidia/nvhpc:21.3-devel-cuda11.2-ubuntu20.04

**Comment by dominichamon** [comment]
can you paste the error you're seeing please?

**Comment by PhilipDeegan** [comment]
sure I'll get a few examples

**Comment by dominichamon** [comment]
it seems to be a much stricter compiler than those we run on CI. I will take patches to fix any valid errors, or disable the strictness for pgi builds.
