### ISSUE TITLE
BUILD_SHARED_LIBS isn't available

### ISSUE THREAD

**Issue by mattyclarkson** [google/benchmark#114]
The project uses `BENCHMARK_ENABLE_SHARED` to create a shared library _rather_ than a static library. Usually the [`BUILD_SHARED_LIBS`](http://www.cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html#build-shared-libs) global variable is used for that.

I'm not saying anything is right or wrong, just a suggestions that:
 * if there is a `BENCHMARK_ENABLE_SHARED` then should there be a `BENCHMARK_ENABLE_STATIC` (default `ON`) so you can build both libraries in one build?
 * Should the `BENCHMARK_ENABLE_SHARED` respects `BUILD_SHARED_LIBS` and is set to `YES` if `BUILD_SHARED_LIBS=YES`

Happy to put up a PR for either if you think they are decent suggestions.

**Comment by dominichamon** [comment]
I'm not sure how often you need to build both libraries.. what use case do you have?

given BUILD_SHARED_LIBS is a builtin variable, we probably should respect it.

**Comment by mattyclarkson** [comment]
I don't really have a use case :blush: it's just if you look at autotools you can do `--enabled-shared` `--enable-static` which is what I assumed `BENCHMARK_ENABLE_SHARED` was implementing.

If we are just going with the BUILD_SHARED_LIBS so the each build does only one linkage type we need to modify @EricWF  5b41e128 changes that overrided the changes I did in #39.

That commit added [`BENCHMARK_ENABLE_SHARED`](https://github.com/google/benchmark/blob/5b41e128b359900264464c480dfd4f107625f3c9/CMakeLists.txt#L4) and the [`if`/`else`](https://github.com/google/benchmark/blob/5b41e128b359900264464c480dfd4f107625f3c9/src/CMakeLists.txt#L20-26). Need @EricWF, comments here though as he probably changed that for a reason.

I would expect if we only want the build to produce _either_ a static or shared library then `BECNHMARK_ENABLE_SHARED` should set `BUILD_SHARED_LIBS` to `YES` when enabled and `cmake` will just do the right thing. The `if`/`else` block could just be:

```
# Don't need to specify `static` or `shared` here as cmake respects the BUILD_SHARED_LIBS
add_library(benchmark ${SOURCE_FILES} ${RE_FILES})

# Not sure why we only need to link the threads when shared, maybe Eric has more insight.
if (BUILD_SHARED_LIBS)
  find_package(Threads REQUIRED)
  target_link_libraries(benchmark ${CMAKE_THREAD_LIBS_INIT})
endif()
```

**Comment by EricWF** [comment]
I think some of my changes were inadvertent. I was unaware of the CMake option `BUILD_SHARED_LIBS`.

I *think* I have a use-case for building both shared and static version of benchmark in the same build, but I wouldn't want the shared and static libraries being output with the same name. For that reason I don't know how much sense `BENCHMARK_ENABLE_STATIC` makes.

For now I think it makes the most sense to simply remove `BENCHMARK_ENABLE_SHARED` and respect `BUILD_SHARED_LIBS` instead.

**Comment by mattyclarkson** [comment]
@EricWF, they would be output as `libbenchmark.a` and `libbenchmark.so` so you _could_ have a build that does both if you wanted.

OK I'll get a patch together. @EricWF do you know why you move the linking of threading into the shared only branch [here](https://github.com/google/benchmark/blob/5b41e128b359900264464c480dfd4f107625f3c9/src/CMakeLists.txt#L22-23)

**Comment by EricWF** [comment]
I've already got a patch in the works.

**Comment by mattyclarkson** [comment]
@EricWF, nice!
