### ISSUE TITLE
[FR] Is it possible to benchmark multiple stages?

### ISSUE THREAD

**Issue by cakebytheoceanLuo** [google/benchmark#1140]
**Is your feature request related to a problem? Please describe.**
Image benchmarking a hashtable. It would be nice to benchmark the build phase and the probe phase individually.
Is such a feature already supported? An output with multiple timers for multiple phases would be great.

EDIT:
Following output is an example of my wish:
```
Benchmark              **BUILD** Time    **PROBE** Time
-----------------------------------------------------------------
hashtable                         10s                     20s
```

**Comment by dominichamon** [comment]
you can benchmark anything that is available as an API into an object or library.

**Comment by cakebytheoceanLuo** [comment]
> you can benchmark anything that is available as an API into an object or library.

Could you check my new edit above? Is such output is possible with our tool?

**Comment by dominichamon** [comment]
ah, i see. no that's not currently possible[0]. instead, you'd want to have the API set so that the build and probe methods are separated and can be reported independently.

0. so there might be a way with manual/custom timers but then you're not really using the features of the library.

**Comment by cakebytheoceanLuo** [comment]
Thanks for the reply.
Is a Getter of the timer is possible? Like following code:
```
for(auto _ : state) {
    hashtable.build();
    auto t0 = Getter_Time(); // A Custom Counter
    state.counters["BUILD Time"]  = t0;
    hashtable.probe();
    state.counters["Probe Time"] = Getter_Time() - t0; // Another Custom Counter
  }
```

**Comment by dominichamon** [comment]
That isn't possible today. We'd need that getter to pause the timer and return the current time, also we'd need to know if you want real vs cpu vs manual time. The pause would introduce overhead to the timer too.

The core loop is pretty sensitive so i think it's best to just have two benchmarks, one for each phase.
