### ISSUE TITLE
[FR] Update release note of 1.5.4

### ISSUE THREAD

**Issue by DimRochette** [google/benchmark#1175]
I think the release notes are missing a big change in 1.5.4
It is that it's now building with gcc-11 with pull request #1060

I personally found the cause and the fix on [gentoo.org](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=4add4f893cf2fb16b18d3c15bc9948a80802b66f) I guess it will be easier for many to have this here

**Comment by dominichamon** [comment]
done. thank you for pointing that out!
