### ISSUE TITLE
[FR] Support Python 3.9 and macOS by adding compatible wheels

### ISSUE THREAD

**Issue by njunge94** [google/benchmark#1177]
**Is your feature request related to a problem? Please describe.**
Hello! I started a small CLI project on benchmarking Python code across different git branches and wanted to use GB's Python shim. When trying to `pip install google-benchmark` (macOS 11.4 + Python 3.9), I get an error due to no compatible wheels existing on PyPI for either macOS or Python 3.9.

**Describe the solution you'd like**
Updating the wheels on PyPI to include macOS and Python 3.9 options, so that a Python 3.9 / Mac user can just `pip install google-benchmark` and start hacking.

**Describe alternatives you've considered**
Installing Bazel and building from source instead seems to work, e.g. doing it like this:
```
brew install bazel
pip install git+https://github.com/google/benchmark.git
```

If there's anything I can do to help accomplish this, please let me know, I'd love to contribute on this. Thanks for reading :-)

**Comment by dominichamon** [comment]
I know nothing about deploying wheels so feel free to either let me know what to do or just do what needs to be done.

I'm not sure the python has been migrated to be v3 compliant btw.

**Comment by njunge94** [comment]
Thank you! It looks like this can be handled via GitHub Actions, more specifically using [cibuildwheel](https://github.com/pypa/cibuildwheel). I am gonna do a little more digging, but I think I can work out and submit a solution in form of a GH Action yaml for this. 

Your second comment I did not quite get. Did you mean that new C++ features added after the last Python revision (0.2.0?) are not present yet in the Python bindings?

**Comment by dominichamon** [comment]
ah no (though some of that is true), i mean that the python itself in the bindings and tooling may be written for python2 rather than python3.
