### ISSUE TITLE
[BUG] Semicolon error while compiling

### ISSUE THREAD

**Issue by mhepeyiler** [google/benchmark#1202]
Hi, I tried to install it on my WSL 1 machine. However, it failed in compile process due to a semicolon error. It think it is related to macros.

`In file included from /home/murat/benchmark/benchmark/googletest/googletest/src/gtest-all.cc:38:0:                                                                     /home/murat/benchmark/benchmark/googletest/googletest/include/gtest/gtest.h:79:45: error: extra ‘;’ [-Wpedantic]                                                        GTEST_DECLARE_bool_(also_run_disabled_tests);`

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Ubuntu 18.04 WSL1
  - Compiler and version: `gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0` - `cmake version 3.10.2`
  
I have only followed the steps given in readme.md.

Thanks in advance.

**Comment by dominichamon** [comment]
i'm seeing this at HEAD too, our build bots are failing. looks like googletest doesn't built with -Wpedantic.

**Comment by dominichamon** [comment]
we can disable pedantic for the project, or maybe just for googletest?

**Comment by pleroy** [comment]
The googletest people have recently changed their macros to expand to a namespace.  The semicolon at the end of the namespace is the source of the problem.

**Comment by dominichamon** [comment]
https://github.com/google/googletest/pull/3492

and https://github.com/google/benchmark/pull/new/fix_1202
