### ISSUE TITLE
Enable appveyor

### ISSUE THREAD

**Issue by mattyclarkson** [google/benchmark#123]
Is it possible to enable appveyor to keep the Windows build from breaking? The `appveyor.yml` is ready and waiting.

**Comment by mattyclarkson** [comment]
It's still [working on my account](https://ci.appveyor.com/project/mattyclarkson/benchmark/build/50)

**Comment by dominichamon** [comment]
I haven't been able to get permission to give access to the repo from appveyor. I will try again some day.

**Comment by dominichamon** [comment]
It seems that we may have permission after all. Want to put up the pull request again?

**Comment by mattyclarkson** [comment]
@dominichamon, it's all ready to go - just have to enable it in appveyor and it'll read the `appveyor.yml` and start building.

**Comment by mattyclarkson** [comment]
Once it's going you could add the building badge to the `README.md` like the travis one?

**Comment by dominichamon** [comment]
Done, i think.

**Comment by mattyclarkson** [comment]
Looks like it - https://ci.appveyor.com/project/google/benchmark

Nice work, thanks for that!
