### ISSUE TITLE
undefined reference to `__imp_SHGetValueA'

### ISSUE THREAD

**Issue by C0C41N** [google/benchmark#1232]
I am trying to run this command

`g++ src/benchmark.cpp -std=c++11 -lbenchmark -lpthread -o x.exe`

but when I do I get this error

_C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../lib/libbenchmark.a(sysinfo.cc.obj):sysinfo.cc:(.text+0x637): undefined reference to `__imp_SHGetValueA'
collect2.exe: error: ld returned 1 exit status_

Here's the benchmark.cpp file

```
#include <benchmark/benchmark.h>

static void BM_StringCreation(benchmark::State& state) {
	for (auto _ : state) std::string empty_string;
}
// Register the function as a benchmark
BENCHMARK(BM_StringCreation);

// Define another benchmark
static void BM_StringCopy(benchmark::State& state) {
	std::string x = "hello";
	for (auto _ : state) std::string copy(x);
}
BENCHMARK(BM_StringCopy);

BENCHMARK_MAIN();
```

**System**
Windows 10
g++ (Rev2, Built by MSYS2 project) 10.3.0
gtest & benchmark libraries are included. (gtest works fine btw)

![image](https://user-images.githubusercontent.com/51693606/134703995-dfaf71da-7a04-4575-b494-9e89f1635dc8.png)

**Comment by dominichamon** [comment]
`SHGetValueA` is part of the shlwapi.h and per the docs you may need to link against Shlwapi.lib on some configurations: https://google.github.io/benchmark/platform_specific_build_instructions.html

**Comment by C0C41N** [comment]
Thanks for the tip @dominichamon

I just added -lShlwapi and now it's working fine

`g++ src/benchmark.cpp -std=c++11 -lbenchmark -lpthread -lShlwapi -o x.exe`

**Comment by dominichamon** [comment]
#imstillworthy
