### ISSUE TITLE
[BUG] Segfault running any benchmark on macOS when using GCC (via Homebrew)

### ISSUE THREAD

**Issue by jgreitemann** [google/benchmark#1234]
When running any kind of benchmark, even an empty one, on macOS (armv8 "M1"), I experience a segmentation fault if the benchmark program (and Google Benchmark itself) have been built by GCC (11.1). The problem is absent when Apple Clang (13.0.0) is used instead.

I obtained Google Benchmark through Conan, specifically the `benchmark/1.6.0` package. Since Conan Center did not yet provide binaries for this version and configuration, I ended up building Google Benchmark from source using Conan (details below). While I was at it, I built a debug version of the library, too, and was able to reproduce the problem also with a debugger attached. The offending access seems to occur here:
https://github.com/google/benchmark/blob/0baacde3618ca617da95375e0af13ce1baadea47/src/benchmark_register.cc#L455
Specifically, `func_` does not seem to point to a valid function.

**System**
  - Arch: armv8 (Apple M1)
  - OS: macOS Big Sur 11.6
  - Google Benchmark 1.6.0 (via Conan)
  - GCC via Homebrew:
```
$ /opt/homebrew/Cellar/gcc/11.2.0/bin/gcc-11 --version
gcc-11 (Homebrew GCC 11.2.0) 11.1.0
```

**To reproduce**
1.  Install GCC via Homebrew.
2. Install Conan via Homebrew.
3. Create a new profile in `~/.conan/profiles/homebrew-gcc-debug` with the following contents:
```ini
[settings]
os=Macos
os_build=Macos
arch=armv8
arch_build=armv8
compiler=gcc
compiler.version=11.1
compiler.libcxx=libstdc++
build_type=Debug
[options]
[build_requires]
[env]
```
4.  Install the `benchmark/1.6.0` package through Conan. I had to specify the `--build=benchmark` flag to build the package from source as no binary packages are available at time of writing for the above configuration. In order for CMake to pick up the compiler matching the profile, I set the env vars `$CC` and `$CXX` first. Otherwise Conan would complain about the mismatch.
```
$ export CC=/opt/homebrew/Cellar/gcc/11.2.0/bin/gcc-11
$ export CXX=/opt/homebrew/Cellar/gcc/11.2.0/bin/g++-11
$ conan install -pr homebrew-gcc-debug benchmark/1.6.0@ --build=benchmark
```
5. Create a minimal program using Google Benchmark, e.g. the following `main.cpp`:
```cpp
#include <benchmark/benchmark.h>

static void NoOp(benchmark::State& state) {
}
BENCHMARK(NoOp);

BENCHMARK_MAIN();
```
6. Compile and link with GCC:
```
$ /opt/homebrew/Cellar/gcc/11.2.0/bin/g++-11 \
        -I ~/.conan/data/benchmark/1.6.0/_/_/build/0d5717357613986c2fc12c41eb3c39b1acec49ac/source_subfolder/include \
        main.cpp \
        -L ~/.conan/data/benchmark/1.6.0/_/_/build/0d5717357613986c2fc12c41eb3c39b1acec49ac/build_subfolder/lib \
        -lbenchmark
```
7. Execute the program:
```
$ ./a.out
Unable to determine clock rate from sysctl: hw.cpufrequency: No such file or directory
2021-09-29T20:22:57+02:00
Running ./a.out
Run on (8 X 24.1224 MHz CPU s)
CPU Caches:
  L1 Data 64 KiB (x8)
  L1 Instruction 128 KiB (x8)
  L2 Unified 4096 KiB (x8)
Load Average: 1.23, 1.41, 1.35
***WARNING*** Library was built as DEBUG. Timings may be affected.
[1]    51404 segmentation fault  ./a.out
```

**Screenshots**
<img width="1347" alt="image" src="https://user-images.githubusercontent.com/8759541/135327463-38b75774-fa17-4431-8d48-4bf92f817300.png">

**Stacktrace**
```
<unknown> 0x0000000100000034
benchmark::internal::FunctionBenchmark::Run(benchmark::State&) benchmark_register.cc:455
benchmark::internal::BenchmarkInstance::Run(unsigned long long, int, benchmark::internal::ThreadTimer*, benchmark::internal::ThreadManager*, benchmark::internal::PerfCountersMeasurement*) const benchmark_api_internal.cc:89
::RunInThread(const BenchmarkInstance *, IterationCount, int, ThreadManager *, PerfCountersMeasurement *) benchmark_runner.cc:126
benchmark::internal::BenchmarkRunner::DoNIterations() benchmark_runner.cc:191
benchmark::internal::BenchmarkRunner::DoOneRepetition() benchmark_runner.cc:282
::RunBenchmarks(const vector<BenchmarkInstance, allocator<> > &, BenchmarkReporter *, BenchmarkReporter *) benchmark.cc:351
benchmark::RunSpecifiedBenchmarks(benchmark::BenchmarkReporter*, benchmark::BenchmarkReporter*) benchmark.cc:497
benchmark::RunSpecifiedBenchmarks() benchmark.cc:438
main benchmark_main.cc:17
start 0x00000001884b1430
```

**Comment by dominichamon** [comment]
i haven't been able to repro this on my local mac.  i'd love some help.

**Comment by jgreitemann** [comment]
Hi Dominic,

I finally had some time to do a bit more digging and found that the issue was absent when compiling benchmark from sources and only affected my Conan install. I then reinstalled using Conan and manually ran `make VERBOSE=1` and noticed that it built with `-D_GLIBCXX_USE_CXX11_ABI=0`. It then struck me that my Conan profile sets `compiler.libcxx=libstdc++` which causes Conan to use the pre-C++11 ABI of libstdc++; one needs to put `compiler.libcxx=libstdc++11` to get the "modern" ABI. Alas, I even _knew_ about this in theory but somehow didn't connect the dots. Sorry about wasting your time.
