### ISSUE TITLE
[BUG] Cmake warnings on windows

### ISSUE THREAD

**Issue by mtrofin** [google/benchmark#1236]
Tracking https://bugs.llvm.org/show_bug.cgi?id=38874

**Comment by dominichamon** [comment]
there's been a few PRs landing to resolve warnings. have they helped enough that we can close this @mtrofin ?

**Comment by mtrofin** [comment]
I believe so, a290770fa848cfe9b46dcc2c44e06e15cafd0f23 should have taken care on the llvm side.

**Comment by dominichamon** [comment]
thanks
