### ISSUE TITLE
cmake  issue on MacOs

### ISSUE THREAD

**Issue by dcoeurjo** [google/benchmark#124]
When doing a fresh ```cmake```, an error is raised.

    [...]
    -- Performing Test HAVE_STEADY_CLOCK -- success
    -- Looking for include file pthread.h
    -- Looking for include file pthread.h - found
    -- Looking for pthread_create
    -- Looking for pthread_create - found
    -- Found Threads: TRUE
    CMake Error at test/CMakeLists.txt:48 (string):
      string no output variable specified

    -- Configuring incomplete, errors occurred!
    See also "/Users/davidcoeurjolly/local/src/benchmark/build/CMakeFiles/CMakeOutput.log".
    See also "/Users/davidcoeurjolly/local/src/benchmark/build/CMakeFiles/CMakeError.log".

**Comment by dominichamon** [comment]
Hm. Looks like CMAKE_BUILD_TYPE was empty?

can you retry with 'cmake -DCMAKE_BUILD_TYPE=Release' and let me know what happens?

**Comment by dcoeurjo** [comment]
Oh you're right... no more cmake error when I specify a build type.
BTW, it is a bit odd to get an error when using default cmake settings.

**Comment by dominichamon** [comment]
I agree completely. I wonder if we never saw this because we set the build type explicitly in the travis build, and each of us has built at least once which has cached the build type. It's definitely worth looking in to but I'll drop the priority a little as you have a workaround.

**Comment by dcoeurjo** [comment]
sure..

**Comment by dcoeurjo** [comment]
done in #125

**Comment by dominichamon** [comment]
Thanks so much!
