### ISSUE TITLE
[BUG] cmake trying to build cxx03_test with C++11

### ISSUE THREAD

**Issue by PhilipDeegan** [google/benchmark#1247]
**Describe the bug**
Compiler error for cxx03_test when passed flag "-std=c++11"

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Debian 10
  - Compiler and version: 
 ```
/opt/nvidia/hpc_sdk/Linux_x86_64/21.3/compilers/bin/pgc++  -v
Export PGI_CURR_CUDA_HOME=/opt/nvidia/hpc_sdk/Linux_x86_64/21.3/cuda/
Export NVCOMPILER=/opt/nvidia/hpc_sdk/Linux_x86_64/21.3
Export PGI=/opt/nvidia/hpc_sdk
pgc++-Warning-No files to process

```

**To reproduce**
- download master
- export CC=export CC=/opt/nvidia/hpc_sdk/Linux_x86_64/21.3/compilers/bin/pgcc
- export CXX=export CC=/opt/nvidia/hpc_sdk/Linux_x86_64/21.3/compilers/bin/pgc++
- mkdir build
- cd build
- cmake .. -G Ninja -DBENCHMARK_ENABLE_GTEST_TESTS=OFF; ninja
- error

**Expected behavior**
No compile error

**Screenshots**
 ```
 /opt/nvidia/hpc_sdk/Linux_x86_64/21.3/compilers/bin/pgc++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -DHAVE_STEADY_CLOCK -DTEST_BENCHMARK_LIBRARY_HAS_NO_ASSERTIONS -I../include -I../src/../include -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -fstrict-aliasing  -Wno-deprecated-declarations  -Wstrict-aliasing -fast -O3    -UNDEBUG --gnu_extensions -o test/CMakeFiles/cxx03_test.dir/cxx03_test.cc.o -c ../test/cxx03_test.cc
"../test/cxx03_test.cc", line 8: catastrophic error: #error directive: C++11 or greater detected. Should be C++03.
  #error C++11 or greater detected. Should be C++03.
```

**Additional context**

**Comment by PhilipDeegan** [comment]
why it it building?

**Comment by dominichamon** [comment]
well it's working as intended _if_ the scripts are doing what they're meant to and not building it if c++11 is specified.

this is working on the CI bots and locally for me so i'm not sure what's different in your case. can you share more about your setup or build process?

**Comment by PhilipDeegan** [comment]
Even when commenting out https://github.com/google/benchmark/blob/main/CMakeLists.txt#L167

I get 

```
/opt/nvidia/hpc_sdk/Linux_x86_64/21.3/compilers/bin/pgc++ -DHAVE_POSIX_REGEX -DHAVE_STD_REGEX -DHAVE_STEADY_CLOCK -DTEST_BENCHMARK_LIBRARY_HAS_NO_ASSERTIONS -I../include -I../src/../include -std=c++0x  -Wall  -Wextra  -Wshadow  -pedantic  -fstrict-aliasing  -Wno-deprecated-declarations  -Wstrict-aliasing   -UNDEBUG --gnu_extensions -o test/CMakeFiles/cxx03_test.dir/cxx03_test.cc.o -c ../test/cxx03_test.cc
"../test/cxx03_test.cc", line 8: catastrophic error: #error directive: C++11 or greater detected. Should be C++03.
```

I would guess, the compiler is defaulting to C++11, regardless of which arguments are being used.
