### ISSUE TITLE
[BUG] ArgNames results in running a family of benchmarks with the same name

### ISSUE THREAD

**Issue by LeonScroggins** [google/benchmark#1257]
**Describe the bug**
The first `std::string` in the vector passed to `ArgNames` is used for all benchmarks in the same family.

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Android
  - Compiler and version: Not sure - whatever my Android checkout is using

**To reproduce**
1. sync to commit `ea5a5bbff491fd625c6e3458f6edd680b8bd5452`
2. Write a benchmark that takes two arguments and two names. e.g.

```
  void BM_phony(benchmark::State& benchState) {
      int64_t x = 0;
      const int64_t inc = benchState.range();
      for (auto _ : benchState) {
          x += inc;
      }
  }
  BENCHMARK(BM_phony)->Arg(1)->Arg(2)->ArgNames({"one", "two"});
```
3. make && run

**Expected behavior**
I would expect to see the benchmark run twice, once with the name "one" and once with "two".

**Actual behavior**
Although the second run uses the proper number at the end (`2`), it uses the first string (`"one"`).
```
BM_phony/one:1        0.000 ns        0.000 ns   1000000000
BM_phony/one:2        0.000 ns        0.000 ns   1000000000
```

**Comment by LebedevRI** [comment]
Please refer to https://github.com/google/benchmark/blob/main/docs/user_guide.md#passing-arguments,
you want `->Args({1, 2})->ArgNames({"one", "two"})` i think.
Also, looks like `ArgNames` isn't documented there, might be good to document it (aka, patches welcomed).

**Comment by LeonScroggins** [comment]
It turns out there's already a way to achieve what I wanted to do:

```
BENCHMARK(BM_phony)->Arg(1)->ArgName("one")
                   ->Arg(2)->ArgName("two");
```

**Comment by LebedevRI** [comment]
> It turns out there's already a way to achieve what I wanted to do:
> 
> ```
> BENCHMARK(BM_phony)->Arg(1)->ArgName("one")
>                    ->Arg(2)->ArgName("two");
> ```

Would it be useful to document that?

**Comment by raccoonmonk** [comment]
> It turns out there's already a way to achieve what I wanted to do:
> 
> ```
> BENCHMARK(BM_phony)->Arg(1)->ArgName("one")
>                    ->Arg(2)->ArgName("two");
> ```

Since when? it doesn't work for me
```
BENCHMARK(BM_TabSelect)
  ->Arg(Type::Raw)->ArgName("Raw")
  ->Arg(Type::IntegratedBuffer)->ArgName("IntegratedBuffer")
  ->Arg(Type::ExternalBuffer)->ArgName("ExternalBuffer");
```
Output:
```
------------------------------------------------------------------------
Benchmark                              Time             CPU   Iterations
------------------------------------------------------------------------
BM_TabSelect/ExternalBuffer:0  626130360 ns    626125604 ns            1
BM_TabSelect/ExternalBuffer:1        210 ns          112 ns      4600533
BM_TabSelect/ExternalBuffer:2        220 ns          116 ns      4426287
```

**Comment by raccoonmonk** [comment]
nvm, this one does work. Thanks!
I've found it in one of your comments:
```
BENCHMARK(BM_phony)->Arg(1)->ArgName("one");
BENCHMARK(BM_phony)->Arg(2)->ArgName("two");
```
