### ISSUE TITLE
[BUG] `-DBENCHMARK_ENABLE_INSTALL=OFF` build broken

### ISSUE THREAD

**Issue by xdxiao** [google/benchmark#1275]
**Describe the bug**
I am compiling the benchmark as a git submodule in my project. The lastest version give this error:
```
CMake Error at benchmark/src/CMakeLists.txt:153 (export):
  export Export set "benchmarkTargets" not found.
```

**System**
Which OS, compiler, and compiler version are you using:
  - OS:  linux
  - Compiler and version:  g++ 11

**To reproduce**
In my current project CMakeLists.txt, I have:
```
set(BENCHMARK_ENABLE_INSTALL OFF)
set(BENCHMARK_ENABLE_GTEST_TESTS OFF)
set(BENCHMARK_ENABLE_TESTING OFF)
set(BENCHMARK_ENABLE_TESTING OFF)
set(BENCHMARK_INSTALL_DOCS OFF)
 ...
add_subdirectory(benchmark)

...
```

Runing `cmake` to configure my build folder will give the above error.

**Possible Fix**
Place the  "export" command in the line 153-154 of src/CMakeLists.txt  in the if-block:
```
if (BENCHMARK_ENABLE_INSTALL) 
    export (EXPORT ${targets_export_name} NAMESPACE "${namespace}"
       FILE ${generated_dir}/${targets_export_name}.cmake)
endif()
```

**Comment by dominichamon** [comment]
can you try it, @xdxiao, and let me know if it works locally?

**Comment by LebedevRI** [comment]
I don't believe that fix is what we want. It should still be there even if it's not going to be installed.

**Comment by xdxiao** [comment]
@dominichamon, 
Do you mean my "possible-fix"? Yes, it works for me. The problem is due probably to an undefined export set when the install is not turn on. 

Thanks for looking into it.

Xudong
