### ISSUE TITLE
[FR] New release request upon Gtest branch renaming

### ISSUE THREAD

**Issue by vicentebolea** [google/benchmark#1288]
**Is your feature request related to a problem? Please describe.**

With the latest rename of the the principal branch at Google test from `master` -> `main`, Google Benchmark users which depends on Google Benchmark pulling Google Test on its own are now finding that unless you are in the current head, Google Benchmark build will fail since it will try to pull master in Google Test.

**Describe the solution you'd like**.
There is nothing much that can be done for previous releases, however, many projects which depend on this would irremediably prefer to depend on a new release tag rather than: on either an specific commit or on the current master.

**Describe alternatives you've considered**

**Additional context**

**Comment by dominichamon** [comment]
both the bazel and cmake builds depend on release tags for googletest  (currently `release-1.11.0`).  i think this resolves the issue.
