### ISSUE TITLE
[FR] tools/compare.py should show labels from benchmarks

### ISSUE THREAD

**Issue by nimrod-gileadi** [google/benchmark#1294]
**Is your feature request related to a problem? Please describe.**
I have a benchmark test where I call state.SetLabel to give a readable name to each benchmark run. My benchmark are parameterized, and the default naming `BM_MyBenchmark/0` is not so clear.

When I use compare.py to compare results from my benchmark, this readable label is gone, which makes the results harder to read.

**Describe the solution you'd like**
The output of compare.py should include benchmark labels.

**Describe alternatives you've considered**
Running a sed script on the output of compare.py to manually add labels.

**Comment by dominichamon** [comment]
the label is already in the JSON output so it should be simple enough to plumb through the reporting scripts
