### ISSUE TITLE
`ThreadRange` not documented

### ISSUE THREAD

**Issue by ShawnZhong** [google/benchmark#1297]
`ThreadRange` is a neat method to use, but it is not documented in any of the markdown files. It would be nice if this method could be documented somewhere so people know to use it. 

https://github.com/google/benchmark/blob/b5bb9f0675acb7d4093d482e89883febae75d103/include/benchmark/benchmark.h#L1067-L1079

Also, I found this comment on https://github.com/google/benchmark/issues/282:
> P.S.: Is ThreadRange() not documented? I only came across it while reading the source.

**Comment by dominichamon** [comment]
this is likely a mistake as the documentation used to be _only_ in the header, and then we built up the markdown docs. now we have the markdown docs and they're installed as part of an install, i wonder if we should remove all the documentation from the header (and make sure it's present in markdown, of course).
