### ISSUE TITLE
[BUG] enumerator value is not representable in the underlying type 'int'

### ISSUE THREAD

**Issue by ThePhD** [google/benchmark#1299]
**Describe the bug**
Building with Clang on Windows for the MSVC platform produces an error regarding enumeration values, particularly for `class Counter`'s nested `enum Flags` value. It has problems, in particularly, with the maximum `kInvert` value that uses `1U << 31U`.

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Windows 10
  - Compiler and version: Clang 13.0.0, x86_64-pc-windows-msvc

**To reproduce**
1. Pull latest google/benchmark
2. Launch CMake build
3. Use benchmark.h from any header with warnings as errors
4. Observe compiler error at Line 397 of benchmark.h for the enumeration `Counter::Flags`:
> enumerator value is not representable in the underlying type 'int' [-Werror,-Wmicrosoft-enum-value]

**Expected behavior**
It builds just fine.

**Additional context**
Enumeration values, when they have no given type, are required to be representable as `int` in older versions of the C and C++ Standard. Microsoft seemed to have never quite fix the problem or adapt their underlying representation properly, so Clang warns on it (and errors under `-Werror`). There are two ways, I know of, to fix this problem:

- Use `1U << 30U` to have the flags value fit in an enumeration (I don't know what serialization looks like)
- Change to using `1 << 31` and simply assume shifting into the sign bit is not illegal for the given platform.

In local testing, both fixes work. I don't know which flavor is preferred.

**Comment by LebedevRI** [comment]
Wasn't that just fixed/broken by https://github.com/google/benchmark/pull/1227?

**Comment by ThePhD** [comment]
Oh, my apologies! This does seem to be fixed but my git seems to be... intentionally pulling the wrong history? I keep ending up with what looks like old sources: maybe it's still pulling `master` by default...?

Either way, thank you for catching that, it should be fine now, thank you for your help!

**Comment by dominichamon** [comment]
i'd really like to delete `master` but i think some downstream folks are still depending on it.

one more version and i'll pull it again i think.
