### ISSUE TITLE
[Question] Is there a new release planned, because of the GoogleTest.cmake.in GIT_TAG change: master -> main -> release-1.11.0

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [google/benchmark#1307]
I ask because I am using benchmark-1.6.0.zip where GIT_TAG is master and that tag does not exist any more on googletest.
Thanks for the help / info, 
Andreas.

**Comment by dominichamon** [comment]
i don't have one planned, but i think it makes sense to do one.

i'll try to get to it over the holidays, if noone else gets there first (@LebedevRI)

**Comment by LebedevRI** [comment]
Ack, but i'm not sure if we have some more bugs that we deem in need of fixing beforehand.

**Comment by dominichamon** [comment]
i did not get to it.  i don't think there are any bugs we want to fix (i normally label them with #next-release).

**Comment by dominichamon** [comment]
starting on this now

**Comment by dominichamon** [comment]
v1.6.1  now released.

**Comment by Andreas-Schniertshauer** [comment]
Thank you very much, I removed my workaround and rebuild all successfully with Visual Studio Prof. 2019 16.11.8.
