### ISSUE TITLE
Benchmark should release version 1.0

### ISSUE THREAD

**Issue by EricWF** [google/benchmark#132]
Hi Dominic,

I am hoping to put a copy of "benchmark" within the LLVM repository soon. It would be nice if Benchmark reached a state that we would be happy to call a 

What do you think "Benchmark" needs to do before we could release version 1.0?

**Comment by dominichamon** [comment]
Looking at the delta between the current release and HEAD, we have 43 commits. Broadly speaking, they cover some minor bug fixes and documentation fixes, filters, fixtures, and cmake improvements. Oh, and coverage support.

This seems to me like it's enough for a release.

Looking at the outstanding issues, we have this one, one to deprecate the KeepRunning loop, and windows support. I'm happy to release v1.0 with these outstanding. Anyone have an alternative opinion?

**Comment by dominichamon** [comment]
waiting a few more days for dissension.

**Comment by jll63** [comment]
Quite a few days have elapsed since then and here at Bloomberg we would like to package it for internal use. Our packaging process requires a tagged revision though, and the last tag dates back to March 2015. If not ready for 1.0, can you make an intermediate release please?

**Comment by dominichamon** [comment]
tagging and creating 1.0.0 now
