### ISSUE TITLE
[BUG] user guide has a suboptimal script for managing CPU scaling

### ISSUE THREAD

**Issue by matta** [google/benchmark#1327]
**Describe the bug**

The script for managing CPU scaling in the user guide doesn't work. If it did I don't think it would not be a recommendable idiom.

**System**

Linux

**To reproduce**

See https://github.com/google/benchmark/commit/9e859f5bf55073a2b4c785b97b9cb78cbdaf127e

The current sample script:

1. Won't disable CPU scaling on all CPUs because it uses a single ? rather than a * in the glob.
2. It'll run the benchmark up to 10 times, since it runs the benchmark within the for loop and that is how many CPUs it might match.
3. ...so it'll run the benchmark N times with only one CPU set to "performance" each time.
4. It may encourage people to run benchmarks as root, since that is usually what it takes to modify CPU scaling.
5. Omits mention of the `cpupower` command. I learned of that command from this user guide many years ago, so I think it is good to mention it.  In fact, this is how I noticed the problem.  I forgot what the command was called so I came back here looking for it.  :-)

**Expected behavior**

The script:

1. Remembers the CPU scaling for the first CPU
2. Sets CPU scaling to performance on all CPUs
3. Runs the benchmark
4. Sets CPU scaling to the original value on all CPUs

However, the cpupower scripts make that hard because they don't provide a nice scriptable way to get the current governor.  Maybe suggest a script like this, named something like `with_performance`:

```
#!/bin/sh
read prior_governor < /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
sudo cpupower frequency-set --governor performance
"$@"
sudo cpupower frequency-set --governor "$prior_governor"
```

And then people can run benchmarks like this in their shell:

```
$ with_performance ./my_benchmark
```

**Additional context**

This changed very recently.  See #1325 and #1048.

**Comment by dominichamon** [comment]
you have discovered my lack of talent for shell scripting.  patch very welcome :)
