### ISSUE TITLE
[FR] Setting the time unit globally

### ISSUE THREAD

**Issue by zchrissirhcz** [google/benchmark#1328]
**Is your feature request related to a problem? Please describe.**
The benchmark output time unit is `ns` on default. I would like do make all my benchmarks time cost reported in `ms` time unit.
I can modify each benchmark:
```
BENCHMARK(BM_test)->Unit(benchmark::kMillisecond);
```
But modifying to each benchmark makes me frustrated, so much duplicated work.

**Describe the solution you'd like**
`./my_benchmark --benchmark_time_unit=ms`

**Describe alternatives you've considered**
Support environment variable `BENCHMARK_TIME_UNIT`.
Also support globally setup this time unit in C++ code.

**Additional context**

**Comment by dominichamon** [comment]
Fixed by #1337
