### ISSUE TITLE
[FR] Command line help hook

### ISSUE THREAD

**Issue by yurikhan** [google/benchmark#1329]
**Is your feature request related to a problem? Please describe.**
In #597, it is noted that a benchmark program can access command line arguments not recognized by the library.

A benchmark program ought to document the arguments it recognizes in the `--help` output.

However, the library handles the `--help` argument [by printing a hardcoded string literal and exiting](https://github.com/google/benchmark/blob/6d74c0625b8e88c1afce72b4f383c91b9a99dbe6/src/benchmark.cc#L597-L599), without any way for the program to add its own help.

**Describe the solution you'd like**
Declare a hook, perhaps as a function pointer variable initially set to `fprintf`, that the program could point to its own function. Call that hook instead of `fprintf` in `PrintUsageAndExit`.

**Describe alternatives you've considered**
The unsatisfactory alternative is to pre-parse the command line for the `--help` flag before `benchmark::Initialize` has a chance to see it.

**Comment by dominichamon** [comment]
if `BENCHMARK_MAIN` can also use this hook to continue to print the current help, that sounds great.

**Comment by yurikhan** [comment]
`BENCHMARK_MAIN` would expand into a definition of `main` that calls `benchmark::Initialize` without changing the default value of the hook, so it would continue to work as is.

**Comment by yurikhan** [comment]
Sorry for not chiming in earlier. Unfortunately, #1342 does not satisfactorily solve the issue. The calling program’s function is now called when `--help` is encountered or when usage error is detected, but it does not receive the library’s help string so it cannot meaningfully print help for the library’s options. (Or, rather, it can, by copying the help string out of the library source, which will silently break when the library is updated.)

What I meant in the initial comment was to pass the default help string into the hook function, so that it could output it as is or augment it with other options the calling program recognizes.

For good measure, I think the stream to output help to should also be passed to the hook. This will make it easier to adapt if the library later wants to print help to stdout in the `--help` case but to stderr in case of usage errors.

I have prepared a draft PR, please review.

**Comment by yurikhan** [comment]
It’s me again, and it looks like neither of us two contributors to this particular feature has ever actually tested the functionality.

In the initial implementation [here](https://github.com/google/benchmark/pull/1342/files#diff-97f1e611ff7214a383308d0211e5058467b8a6e673a10e867789754e8efb1bd6R629), the helper function hook is assigned after the call to `ParseCommandLineFlags`. By that time, it is too late — the command line parser has already seen the `--help` switch, tried to call the hook, and crashed of segmentation fault by calling through an uninitialized function pointer variable.

Before my improvement [here](https://github.com/google/benchmark/pull/1425/files#diff-97f1e611ff7214a383308d0211e5058467b8a6e673a10e867789754e8efb1bd6R570), the parser only attempted to call the hook if the application actually provided a hook function. After, it calls it every time help is requested.

For the last three weeks, I see no way the library could have worked at all (as in, it crashes every time on `--help`), yet I do not hear anyone with pitchforks outside my doors. Does no one ever ask for --help?

Anyway, [new PR](https://github.com/google/benchmark/pull/1447).

**Comment by dominichamon** [comment]
> Does no one ever ask for --help

that would be my guess. and we don't test this codepath either :)
