### ISSUE TITLE
[FR] Expose the verbosity command line option value

### ISSUE THREAD

**Issue by yurikhan** [google/benchmark#1330]
**Is your feature request related to a problem? Please describe.**
The benchmark library recoginzes a command line option `--v` to set verbosity.

A benchmark program might want to set its own verbosity based on that flag.

**Describe the solution you'd like**
Have a declaration in the public interface that lets the calling program know the verbosity value.

**Describe alternatives you've considered**
* The calling program could pre-parse the command line for the `--v` option before handing it off to `benchmark::Initialize`. It would then have to duplicate the splitting, integer conversion, and range checking code for that option’s value.
* The calling program could declare `extern int32_t FLAGS_v;`. This basically breaks encapsulation and will break if the library’s representation of the option changes.
* The calling program could have a separate verbosity option. This is awkward for the user who will have to understand why a program has two verbosity options.

**Comment by Matthdonau** [comment]
Can be closed i guess?

**Comment by dominichamon** [comment]
fixed by #1397
