### ISSUE TITLE
benchmark won't build on debian wheezy

### ISSUE THREAD

**Issue by mathieuk** [google/benchmark#134]
I've been on a mission to get https://github.com/facebook/osquery to build on Debian Wheezy. One of the issues I ran into was building benchmark, a dependency for osquery. Turns out that the libstd++ on Debian Wheezy doesn't have ```is_trivially_destructable``` and this situation is quite tricky to work around.  I found (like, literally :)) a workaround, which basically selects ```is_trivially_destructable``` or ```has_trivial_destructor``` based on availability.

OSQuery had a separate project to provide dependencies like benchmark and that fix has been applied there. But they've understandably moved to just using vanilla builds of benchmark to prevent unnecessary forking. 

The pull request I submitted for OSQuery is here https://github.com/osquery/third-party/pull/7 . Could that be added to benchmark?

**Comment by EricWF** [comment]
Urg, std::is_trivially_destructible is the cause of a lot of pain. I think we can safely just remove the static_assert in walltime.cc though. I don't think that Walltime::now() is used at all during program termination. 

I'll submit a patch that removes the static_assert.

**Comment by dominichamon** [comment]
We might. If StartTimer is called by a thread during termination we might try to access it.

A better fix would be to allocate the WallTimeImp on the heap as a pointer and never free it.

**Comment by mathieuk** [comment]
So, what would be the best way to move this forward?

**Comment by EricWF** [comment]
This has already been fixed. Please reopen if you disagree.
