### ISSUE TITLE
[FR] Provide an option to run all the benchmark routine *once*

### ISSUE THREAD

**Issue by oontvoo** [google/benchmark#1343]
**Is your feature request related to a problem? Please describe.**

Use case: 
It would be used as "unit test" for benchmarks (ie., ensuring they still run properly and don't crash at runtime).
This would be equivalent with running all the benchmarks with max_iters set to 1.

**Describe the solution you'd like**

Proposed a `RunSpecifiedBenchmarksOnce(...)`

**Describe alternatives you've considered**

**Additional context**

**Comment by oontvoo** [comment]
cc'ing @dominichamon

**Comment by LebedevRI** [comment]
I'm not sure option/api proliferation is a sustainable stratetegy.
When adding benchmark binary as a test, just specify `--benchmark_min_time=0` ?

**Comment by dominichamon** [comment]
can confirm that @LebedevRI has a solution that works today without any extension required.
