### ISSUE TITLE
[BUG] MSVC2017+ (clang-cl) build fails.

### ISSUE THREAD

**Issue by yzazik** [google/benchmark#1345]
**Describe the bug**
MSVC2017 (same for 2019 and 2022 since same Win10SDK is used) with LLVM (clang-cl, 12.0) fails to build with error at:

```make
In file included from ../src/benchmark.cc:18:
In file included from ../src/benchmark_runner.h:22:
../src/internal_macros.h:47:7: error: function-like macro 'WINAPI_FAMILY_PARTITION' is not defined
  #if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
      ^
../src/internal_macros.h:49:9: error: function-like macro 'WINAPI_FAMILY_PARTITION' is not defined
  #elif WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
        ^
2 errors generated.

```
MSVC (cl) is producing a warning (warning C4067) there too but continues to build and succeeds, IntelliSence complains 'function call is not allowed in a constant expression'.
The reason I believe is that `WINAPI_FAMILY` define is not defined, could be set to `WINAPI_FAMILY_DESKTOP_APP` for example, then the build would succeed.

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Windows 10 21H2
  - Compiler and version: MSVC2017 (latest), LLVM(clang-cl 12.0)

**To reproduce**
1. Install "LLVM Compiler Toolchain" using Visual Studio Installer
2. Create StaticLibrary MSVC project.
3. Change Platform toolset to 'LLVM (ckang-cl)
4. Try to build

**Comment by nidefawl** [comment]
Same problem here using llvm-mingw64

**Comment by dominichamon** [comment]
https://github.com/tpn/winsdk-10/blob/master/Include/10.0.10240.0/shared/winapifamily.h#L85 seems like the relevant macro.

it's unclear to me if the library should set this or the calling code though.

**Comment by sergiud** [comment]
Looks like this MSVC complaint seems to be related:
```console
D:\a\benchmark\benchmark\src\internal_macros.h(47,30): warning C4067: unexpected tokens following preprocessor directive - expected a newline [D:\a\benchmark\benchmark\_build\src\benchmark.vcxproj]
D:\a\benchmark\benchmark\src\internal_macros.h(49,32): warning C4067: unexpected tokens following preprocessor directive - expected a newline [D:\a\benchmark\benchmark\_build\src\benchmark.vcxproj]
```

**Comment by sergiud** [comment]
A first shot at fixing the issue would be the following changes:
```patch
diff --git a/src/internal_macros.h b/src/internal_macros.h
index 48968d0..112190b 100644
--- a/src/internal_macros.h
+++ b/src/internal_macros.h
@@ -44,13 +44,12 @@
   #define BENCHMARK_OS_CYGWIN 1
 #elif defined(_WIN32)
   #define BENCHMARK_OS_WINDOWS 1
-  #if WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_DESKTOP)
-    #define BENCHMARK_OS_WINDOWS_WIN32 1
-  #elif WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
+  #if defined(WINAPI_FAMILY_PARTITION) && WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
     #define BENCHMARK_OS_WINDOWS_RT 1
-  #endif
-  #if defined(__MINGW32__)
+  #elif defined(__MINGW32__)
     #define BENCHMARK_OS_MINGW 1
+  #else
+    #define BENCHMARK_OS_WINDOWS_WIN32 1
   #endif
 #elif defined(__APPLE__)
   #define BENCHMARK_OS_APPLE 1
```
@yzazik @nidefawl Could anyone of you test this?

**Comment by yzazik** [comment]
This does not build:
```js
#if defined(WINAPI_FAMILY_PARTITION) && WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
```

Looks like preprocessor is similar to compiler here, needs to "compile" (translate) entire `#if` first, then evaluate it, same error:
```lua
In file included from ../src/benchmark.cc:18:
In file included from ../src/benchmark_runner.h:22:
../src/internal_macros.h:50:43: error: function-like macro 'WINAPI_FAMILY_PARTITION' is not defined
  #if defined(WINAPI_FAMILY_PARTITION) && WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
                                          ^
1 error generated.
```

So I guess it needs an extra separate nested `#if` for the `WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)`.

**Comment by sergiud** [comment]
> Looks like preprocessor is similar to compiler here, needs to "compile" (translate) entire #if first, then evaluate it, same error:

No, the preprocessor short circuits logical expressions. Thus, the second expression in
```cpp
#if defined(WINAPI_FAMILY_PARTITION) && WINAPI_FAMILY_PARTITION(WINAPI_PARTITION_APP)
```
should not be evaluated if the first one evaluates to false. Clearly, `WINAPI_FAMILY_PARTITION` is not defined but I'm not sure why this still fails.

**Comment by yzazik** [comment]
I'm just telling what I see, and what I see is
```cpp
#if 0 && SOMETHING_NOT_DEFINED    // this builds
#endif

#if 0 && SOMETHING_NOT_DEFINED(0) // this doesn't
#endif

```

**Comment by sergiud** [comment]
Ah, yes. You're right. `SOMETHING_NOT_DEFINED` will be substituted first before it is evaluated to `0(0)` which is not a valid logical expression. Besides, #1347 has been merged which supposedly fixes the issue.

**Comment by yzazik** [comment]
there is another issue now:

```cpp
In file included from ../src/benchmark.cc:15:
../include\benchmark/benchmark.h:190:10: fatal error: 'benchmark/export.h' file not found
#include "benchmark/export.h"
         ^~~~~~~~~~~~~~~~~~~~
1 error generated.

```

**Comment by yzazik** [comment]
@sergiud @dominichamon 
With #1347 it builds ok, so I'm closing this, thank you all.

**Comment by sergiud** [comment]
@yzazik I'm confused. Is the missing `benchmark/export.h` an issue or not?

**Comment by yzazik** [comment]
@sergiud Yes, it is, but it is another one.
I can't seem to find export.h, cloned, downloaded as ZIP, it's not there, not in the web view.
I guess it should be in the same place as benchmark/benchmark.h?

**Comment by yzazik** [comment]
@sergiud Ah, it's generated.
Well, no dllexport, no visibility control.
I don't not quite see the point having it, apart from ditching it and create my own instead.
Is that what the annotation was for?
googletest has it right, why not leverage that?

**Comment by sergiud** [comment]
Yes, you're entirely missing the point. It is meaningless maintaining a file that can be generated. Visibility control reduces the shared library size which is exactly the opposite of what you're claiming. See for #1321 why these changes are essential. Further discussion seems to be pointless given you bypass the only supported build systems.

What problem are you trying to solve anyway?

**Comment by yzazik** [comment]
@sergiud 
> Yes, you're entirely missing the point. It is meaningless maintaining a file that can be generated.

But the content of this generated file doesn't have to be dynamic, it could be fixed, then there is no point generating it, it adds extra build step, and there is a bit of a hassle in integrating, benchmark.h in one place, library binary in another, export.h in a third. Does the install copy export.h into the same install folder as benchmark.h?

> Visibility control reduces the shared library size which is exactly the opposite of what you're claiming.

I didn't claim that, I know it helps to reduce the symbol table, but still even with it there are well over 200 symbol entries exported (223 to be exact).

> Further discussion seems to be pointless given you bypass the only supported build systems.

No support for dllexport, so it asks to be bypassed.

> What problem are you trying to solve anyway?

Opened a new issue for that.

**Comment by junyer** [comment]
I came across this issue while investigating breakage for RE2 with Bazel under Windows:

```
…
ERROR: C:/users/runneradmin/_bazel_runneradmin/w7nhswsh/external/com_github_google_benchmark/BUILD.bazel:38:11: Compiling src/sleep.cc failed: (Exit 2): cl.exe failed: error executing command C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\14.30.30705\bin\HostX64\x64\cl.exe /nologo /DCOMPILER_MSVC /DNOMINMAX /D_WIN32_WINNT=0x0601 /D_CRT_SECURE_NO_DEPRECATE ... (remaining 22 arguments skipped)
C:\users\runneradmin\_bazel_runneradmin\w7nhswsh\execroot\com_googlesource_code_re2\bazel-out\x64_windows-dbg\bin\external\com_github_google_benchmark\_virtual_includes\benchmark\benchmark/benchmark.h(294): error C3861: 'visibility': identifier not found
C:\users\runneradmin\_bazel_runneradmin\w7nhswsh\execroot\com_googlesource_code_re2\bazel-out\x64_windows-dbg\bin\external\com_github_google_benchmark\_virtual_includes\benchmark\benchmark/benchmark.h(294): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\users\runneradmin\_bazel_runneradmin\w7nhswsh\execroot\com_googlesource_code_re2\bazel-out\x64_windows-dbg\bin\external\com_github_google_benchmark\_virtual_includes\benchmark\benchmark/benchmark.h(294): error C2062: type 'void' unexpected
…
```

(The full logs are [here](https://github.com/google/re2/runs/5211806834?check_suite_focus=true).)

Is that breakage related to this issue? Or should I file a separate issue?
