### ISSUE TITLE
[BUG] Crash at BenchmarkInstance::Setup()

### ISSUE THREAD

**Issue by yzazik** [google/benchmark#1346]
**Describe the bug**
In here:

```cpp
void BenchmarkRunner::DoOneRepetition() {
  assert(HasRepeatsRemaining() && "Already done all repetitions?");

  const bool is_the_first_repetition = num_repetitions_done == 0;
  IterationResults i;

  // We *may* be gradually increasing the length (iteration count)
  // of the benchmark until we decide the results are significant.
  // And once we do, we report those last results and exit.
  // Please do note that the if there are repetitions, the iteration count
  // is *only* calculated for the *first* repetition, and other repetitions
  // simply use that precomputed iteration count.
  for (;;) {
    b.Setup();     // <-- HERE
    i = DoNIterations();
    b.Teardown();

```

`BenchmarkInstance::Setup()` is called with "empty" state which has neither  manager_ no timer_:

```cpp
void BenchmarkInstance::Setup() const {
  if (setup_) {
    State st(/*iters*/ 1, args_, /*thread_id*/ 0, threads_, nullptr, nullptr,
             nullptr);   // <-- this one has nullptrs for manager_ and timer_
    setup_(st);          // <-- this is user benchmark function call
  }
}

```

so `setup_(st)` get's into user's benchmark function where there is a `for (auto _ : state)` loop which calls state's `.begin()` and `.end()`.
And in the `.end()` there is `StartKeepRunning()` call that accesses `manager_` and things start to blow up really loud.

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Windows 10 21H2
  - Compiler and version: MSVC2017+

**Comment by dominichamon** [comment]
given our tests aren't all failing right now, i wonder if this is a bug with how the benchmark is being registered.  can you post a bit of your code that is calling the library please?

**Comment by yzazik** [comment]
I which I can explain it, very bizarre, this is what I have in my main:

```cpp
#include <benchmark/benchmark.h>

static void BM_TestCode(benchmark::State& state)
{
	// run benchmark
	for (auto _ : state)
	{
		strncmp("one", "two", 3);
	}
}

BENCHMARK(BM_TestCode);
BENCHMARK_MAIN();

```

nothing else, just dependency on benchmark.lib and shlwapi.lib, that's it.

I'll try to play with SDKs (Windows and CRT) and toolchains (2017,2019,2022).

**Comment by yzazik** [comment]
@dominichamon
Ok, totally my fault, with all other issues I had, I cloned several benchmark versions.
So I ended up linking with newer (bigger) `Benchmark` object while including older (smaller) one.
Not sure what's the lesson here, either I need to be more careful or start doing some version checks (maybe both :-)).
Regardless, thank you for being patient, closing this.
