### ISSUE TITLE
[FR] State of PyPI wheel uploads

### ISSUE THREAD

**Issue by nicholasjng** [google/benchmark#1358]
**Is your feature request related to a problem? Please describe.**
Not a problem, but a question: What is the state of PyPI uploads of the wheels, now that they are working (also on macOS ARM)? PyPI uploads eliminate the need for the end user to build from source every time.

**Describe the solution you'd like**
In my opinion, either a commit to uploading manually after each release or a CI/CD upload job triggering on new releases works. :)

**Comment by dominichamon** [comment]
running a CI job on every release SGTM. the knowledge i have about wheels and PyPl is pitiful so i'll mark this as 'help wanted'.

**Comment by nicholasjng** [comment]
No worries, I wanted to assign myself, anyway :)

So the solution is already spelled out [here](https://cibuildwheel.readthedocs.io/en/stable/deliver-to-pypi/#github-actions), with a PyPI token for the `google-benchmark` project's PyPI account added to this GitHub repo's secrets. I can prepare a PR implementing that if it's feasible. Let me know if that works out.

**Comment by dominichamon** [comment]
that's completely fine. i can add the password (and have though it's a placeholder) but i don't think i have access to the google-benchmark PyPl account.

**Comment by nicholasjng** [comment]
Thanks! PyPI treats releases strictly, i.e. there is no deletion mechanism once uploaded (you can at most yank a release, forcing `pip install` to fall back to earlier releases if possible). So if we try a "dry-run" for this job with the current release, we actually only have one shot if it succeeds. 
Due to the wheel builds taking quite long (apparently >1h last time), some wait might not be avoidable, and if the credentials do not work, we look at at least double that wait period. But if we succeed, we do immediately get working wheels for the current release. I'll try to come up with a PR until the end of the day.

**Comment by nicholasjng** [comment]
Any news on the PyPI credentials @dominichamon ?

**Comment by dominichamon** [comment]
no news, no response. sorry.

thinking about if i should just create a new PyPI account and shift over to that...

**Comment by nicholasjng** [comment]
Okay, makes sense. Do you have an alternative name for the package in mind? (We can't use `google-benchmark` anymore, since that's taken by the account in question here)

**Comment by nicholasjng** [comment]
Wanna try another run with the new Bazel config @dominichamon ?

**Comment by dominichamon** [comment]
https://github.com/google/benchmark/actions/runs/1982115208

**Comment by nicholasjng** [comment]
Ach, stupid me, I forgot to change / comment out the `if` trigger. I can make a small commit (since we need to run from `main` as we saw last time, I'm afraid). Let me know what you think.

**Comment by dominichamon** [comment]
yes, we do need to run from main.

**Comment by nicholasjng** [comment]
Thanks for the merge!

**Comment by nicholasjng** [comment]
We did it @dominichamon ! Great job :)

**Comment by dominichamon** [comment]
"we" is doing a lot of heavy lifting. thanks for everything, @nicholasjng .
