### ISSUE TITLE
[FR] Prefixing a benchmark with DISABLED_ should disable it

### ISSUE THREAD

**Issue by batortaller** [google/benchmark#1365]
**Is your feature request related to a problem? Please describe.**
Temporarily disabling a benchmark is not possible atm.

**Describe the solution you'd like**
Similarly to Google Test, prefixing a benchmark with `DISABLED_` should disable that test. Also passing the `--benchmark_also_run_disabled_tests` argument ignores the prefix.

Prefix should work for test names and fixture names as well.

https://github.com/google/googletest/blob/main/docs/advanced.md#temporarily-disabling-tests

**Describe alternatives you've considered**
Alternatively benchmark could provide `DISABLED_BENCHMARK` and `DISABLED_BENCHMARK_F` macros. Possibly this would be easier to implement but not consistent with gtest.

**Additional context**

**Comment by dominichamon** [comment]
there are, broadly, two approaches we could take:

1. skip benchmark registration if the name starts with "DISABLED_"
2. "fail" to find the benchmark if it's registered with a name that starts with "DISABLED_"

the latter is conceptually more correct (the benchmark should still be registered, we just don't want to run it) but we end up wasting some memory in registering a benchmark we know we won't run.
