### ISSUE TITLE
[BUG] Linker errors during wheel builds on Windows

### ISSUE THREAD

**Issue by nicholasjng** [google/benchmark#1367]
**Describe the bug**
Building a wheel for the Python bindings on Windows with an MSVC toolchain fails with a large number of linker errors.

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Win10, x64
  - Compiler and version: MSVC bundled with Visual Studio 22

**To reproduce**
1. sync to main@HEAD (`git checkout main`)
2. Using a system Python (I tried with Python 3.9, assumed available on the command line as "python"):
3. `python -m venv venv --system-site-packages --upgrade-deps`
4. .\venv\Scripts\Activate.ps1
5. `python -m pip install wheel`
6. `python -m pip wheel .`

**Expected behavior**
The wheel is built and deposited in the `build` folder.

**Additional context**
This issue is Windows-specific, Linux and macOS wheels build properly.

This was discovered yesterday by @dominichamon and I when trying to build wheels for PyPI releases, check the pull request discussion [here](https://github.com/google/benchmark/pull/1359). I have since been able to repro this on my local machine as well.

This regression likely comes from the recent work on creating export headers in #1321 and #1355. Pinging the authors of the PRs @sergiud and @junyer for visibility / ideas. (Since the c++ library can be built under Windows, I assume that something in the Bazel config of the Python bindings broke.)

Logs / traceback of the GitHub job: https://github.com/google/benchmark/runs/5499504439?check_suite_focus=true

**Comment by sergiud** [comment]
Does the Python module link again a static or a shared library version of benchmark?

**Comment by nicholasjng** [comment]
https://github.com/google/benchmark/blob/705202d22a10154ebc8bf0975e94e1a93f08ce98/bindings/python/build_defs.bzl#L6-L17

According to the [Bazel docs](https://docs.bazel.build/versions/main/be/c-cpp.html#cc_binary), `linkstatic=1` links the binary in static mode, apparently, though this does _not_ stop dynamic linking of libraries full stop (e.g., if no static library exists).

**Comment by sergiud** [comment]
I'm not a Bazel expert, but it looks like the Python module enables `__declspec(dllimport)` (by assuming a build against a shared library) while trying to link against a static library which is not correct.

**Comment by junyer** [comment]
Try setting `local_defines = ["BENCHMARK_STATIC_DEFINE"]` on the `cc_binary` target that `py_extension()` generates?

**Comment by nicholasjng** [comment]
> Try setting `local_defines = ["BENCHMARK_STATIC_DEFINE"]` on the `cc_binary` target that `py_extension()` generates?

This worked! Thank you for your input, I will send in a fix shortly, would you like me to credit you for this in the commit?

Secondly, I also managed to fix this earlier by substituting `defines` for `local_defines` in this select block:

https://github.com/google/benchmark/blob/4a1943d6116e12d0ca777ef1ee632579b97c7020/BUILD.bazel#L58-L61

But I assume that this has wider-ranging consequences since it's in the actual C++ library's build file, so I will go with plumbing the local define into the `cc_binary` instead.

**Comment by junyer** [comment]
> This worked! Thank you for your input, I will send in a fix shortly, would you like me to credit you for this in the commit?

Thanks, that would be nice. Thanks also for taking care of the fix. :)

**Comment by nicholasjng** [comment]
Right, do you have a preferred way for me to do this? Scientific citation-style link to the discussion comment / or a co-authored-by line at the end? (Asking due to inexperience with this.)

**Comment by junyer** [comment]
Just something like "Thanks for the suggestion, @junyer." would be fine.

Oh, and regarding your second point earlier, compare the documentation for [`defines`](https://bazel.build/reference/be/c-cpp#cc_library.defines):

> _[…]_ Each string, which must consist of a single Bourne shell token, is prepended with `-D` and added to the compile command line to this target, as well as to every rule that depends on it. Be very careful, since this may have far-reaching effects. When in doubt, add define values to `local_defines` instead.

with the documentation for [`local_defines`](https://bazel.build/reference/be/c-cpp#cc_library.local_defines):

> _[…]_ Each string, which must consist of a single Bourne shell token, is prepended with `-D` and added to the compile command line for this target, but not to its dependents.

In this case, we really want `benchmark_EXPORTS` to be defined only when building the library itself (and to be undefined under all other circumstances) whereas I think that `BENCHMARK_STATIC_DEFINE` exists to solve the exact problem that we have here.

**Comment by nicholasjng** [comment]
Done! Thank you for the explanation using the docs, by the way, that makes things very clear.
