### ISSUE TITLE
[BUG] LNK4217 and LNK4286 warnings when linking //:benchmark_main

### ISSUE THREAD

**Issue by junyer** [google/benchmark#1372]
```
…
INFO: From Linking regexp_benchmark.exe:
   Creating library bazel-out\x64_windows-dbg\bin\regexp_benchmark.lib and object bazel-out\x64_windows-dbg\bin\regexp_benchmark.exp
LINK : warning LNK4217: symbol '?RegisterBenchmarkInternal@internal@benchmark@@YAPEAVBenchmark@12@PEAV312@@Z (class benchmark::internal::Benchmark * __cdecl benchmark::internal::RegisterBenchmarkInternal(class benchmark::internal::Benchmark *))' defined in 'benchmark.lib(benchmark_register.obj)' is imported by 'regexp_benchmark.obj' in function '"void __cdecl re2::`dynamic initializer for 'benchmark_uniq_100_benchmark_''(void)" (??__Ebenchmark_uniq_100_benchmark_@re2@@YAXXZ)'
LINK : warning LNK4217: symbol '?InitializeStreams@internal@benchmark@@YAHXZ (int __cdecl benchmark::internal::InitializeStreams(void))' defined in 'benchmark.lib(benchmark.obj)' is imported by 'regexp_benchmark.obj' in function '"void __cdecl benchmark::internal::`dynamic initializer for 'stream_init_anchor''(void)" (??__Estream_init_anchor@internal@benchmark@@YAXXZ)'
LINK : warning LNK4286: symbol '?InitializeStreams@internal@benchmark@@YAHXZ (int __cdecl benchmark::internal::InitializeStreams(void))' defined in 'benchmark.lib(benchmark.obj)' is imported by 'benchmark_main.lib(benchmark_main.obj)'
…
```

(The full logs are [here](https://github.com/google/re2/runs/5558969232?check_suite_focus=true).)

**Comment by junyer** [comment]
Oh, and I just noticed this too:

```
…
INFO: From Compiling src/benchmark_main.cc:
external/com_github_google_benchmark/src/benchmark_main.cc(18): warning C4273: 'main': inconsistent dll linkage
external/com_github_google_benchmark/src/benchmark_main.cc(17): note: see previous definition of 'main'
…
```

What's up with that? O_o

**Comment by sergiud** [comment]
I don't know what `local_defines` does, but when building and consuming a static library version of benchmark, `BENCHMARK_EXPORT` should never expand to `__declspec(dllimport|dllexport)` while `BENCHMARK_STATIC_DEFINE` should be set both when building and consuming benchmark.

To summarize, the following rules apply:
* Static library:
  * `BENCHMARK_STATIC_DEFINE` set the during the library build and propagated to dependencies
  * `BENCHMARK_EXPORT` is empty
  * (`benchmark_EXPORTS` not relevant)
* Shared library:
  *  `benchmark_EXPORTS` set only during the build but not propagated to dependencies
  * `BENCHMARK_EXPORT` expands to `__declspec(dllexport)` during the build and `__declspec(dllimport)` when propagated to dependencies

There might be an inconsistency in the way Bazel propagates defines.

**Comment by junyer** [comment]
Do we need Bazel to create the dynamic library? I'm asking because I'm not aware of any way to make Bazel follow such rules, but we can easily stop Bazel from ever creating the dynamic library by setting `linkstatic = True` on the `cc_library` target. (The documentation for [`linkstatic`](https://bazel.build/reference/be/c-cpp#cc_library.linkstatic) describes this behaviour towards the end.)

**Comment by sergiud** [comment]
This is the easy way out. Alternatively, one could build two library variants separately.

**Comment by dominichamon** [comment]
when building benchmark_main, i think either a dynamic or static library would be appropriate.  i don't think there's much of an expectation either way more broadly.

**Comment by junyer** [comment]
Posted https://github.com/google/benchmark/pull/1373 for review. :)

**Comment by junyer** [comment]
After following up with https://github.com/google/benchmark/pull/1374, I reran the CI job for RE2 and it's now showing zero warnings related to the benchmark library across Linux, macOS and Windows. Thanks!
