### ISSUE TITLE
[BUG] build fails with libstdc++ 12.1.0

### ISSUE THREAD

**Issue by jdoubleu** [google/benchmark#1398]
**Describe the bug**
When I compile the Google benchmark library with g++ 12.1 (using libstdc++ 12.1) in C++20 mode, I get the following error:
```
In file included from /usr/local/include/c++/12.1.0/string:40,
                 from /__w/googletest-issue/googletest-issue/build/_deps/google-benchmark-src/include/benchmark/benchmark.h:186,
                 from /__w/googletest-issue/googletest-issue/build/_deps/google-benchmark-src/src/benchmark.cc:15:
In static member function 'static constexpr std::char_traits<char>::char_type* std::char_traits<char>::copy(char_type*, const char_type*, std::size_t)',
    inlined from 'static constexpr void std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_S_copy(_CharT*, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/local/include/c++/12.1.0/bits/basic_string.h:423:21,
    inlined from 'constexpr std::__cxx11::basic_string<_CharT, _Traits, _Allocator>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_M_replace(size_type, size_type, const _CharT*, size_type) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/local/include/c++/12.1.0/bits/basic_string.tcc:532:22,
    inlined from 'constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::assign(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/local/include/c++/12.1.0/bits/basic_string.h:1647:19,
    inlined from 'constexpr std::__cxx11::basic_string<_CharT, _Traits, _Alloc>& std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::operator=(const _CharT*) [with _CharT = char; _Traits = std::char_traits<char>; _Alloc = std::allocator<char>]' at /usr/local/include/c++/12.1.0/bits/basic_string.h:815:28,
    inlined from 'size_t benchmark::RunSpecifiedBenchmarks(BenchmarkReporter*, BenchmarkReporter*, std::string)' at /__w/googletest-issue/googletest-issue/build/_deps/google-benchmark-src/src/benchmark.cc:459:12:
/usr/local/include/c++/12.1.0/bits/char_traits.h:431:56: error: 'void* __builtin_memcpy(void*, const void*, long unsigned int)' accessing 9223372036854775810 or more bytes at offsets [2, 9223372036854775807] and 1 may overlap up to 9223372036854775813 bytes at offset -3 [-Werror=restrict]
  431 |         return static_cast<char_type*>(__builtin_memcpy(__s1, __s2, __n));
```

**System**
Which OS, compiler, and compiler version are you using:
  - OS: linux
  - Compiler and version: gcc 12.1.0

**To reproduce**
I've prepared a repository to reproduce the issue: https://github.com/jdoubleu/googlebenchmark-issue-1398
You can checkout the build output from the CI here: https://github.com/jdoubleu/googlebenchmark-issue-1398/runs/6505920315?check_suite_focus=true

1. checkout the latest version
2. build (and link) the library
3. See error

**Expected behavior**
The library compiles with the latest gcc version (including libstdc++).

**Additional context**
Interestingly, I get a [similar error](https://github.com/jdoubleu/googlebenchmark-issue-1398/runs/6505920330?check_suite_focus=true#step:5:89) when compiling [`googletest`](https://github.com/google/googletest). However, the build doesn't fail (see).

The error looks like some sort of an underflow in `__builtin_memcpy(void*, const void*, long unsigned int)` (notice the "accessing 9223372036854775810 or more bytes"). Since it is called from `std::__cxx11::basic_string<_CharT, _Traits, _Alloc>::_S_copy(_CharT*, const _CharT*, size_type)`, it may have something to do with Unicode used with `std::string`?

**Comment by LebedevRI** [comment]
I'm 99% sure it's an GCC/libstdc++ bug. Could you reduce the reproducer further, down to a single 10-line function?

**Comment by jdoubleu** [comment]
> I'm 99% sure it's an GCC/libstdc++ bug.

Yes, something like this. clang 14 with libc++ and VS 2022 look fine.

> down to a single 10-line function?

what do you mean?

**Comment by H-G-Hristov** [comment]
Looks like it builds on Ubuntu 22.04 with the provided 12.0.

**Comment by jdoubleu** [comment]
You were right! It's a bug in gcc 12+. See the following tickets:
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105651
* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105329
