### ISSUE TITLE
The meaning of Iterms_per_seconds and Why need fixture?

### ISSUE THREAD

**Issue by EasyLuck** [google/benchmark#1411]
1. What is the meaning of Iterms_per_seconds in google bench? Is it stands the throuput?
2. Why need the fixture to test benchmark? In this way , can we get more convenience?

**Comment by dominichamon** [comment]
1. items_per_second is a shorthand for a custom metric.  if you tell the library that you have processed X things, then we will report a rate of X/second derived from X and the benchmark time
2. https://google.github.io/benchmark/user_guide.html#fixtures
