### ISSUE TITLE
main is wrongly declared

### ISSUE THREAD

**Issue by dominichamon** [google/benchmark#142]
according to standard 3.6.1.2, the signature of `main` should be `int main(int argc, char* argv[])`.

documentation has it right, `BENCHMARK_MAIN` is wrong.

this hinders integration with other libraries.

**Comment by deiuch** [comment]
Hello! Found this issue out of curiosuty, and have a question...
What is the problem with `const` here? If the function itself is never actually changing data, it is normal to mark it as a constant. And where exactly it makes an integration with other libraries harder?
I see no problem with passing non-const versions to function accepting `const`. So, we still have no problem using it with "standard" `main` signature (which also can be written with `const`, don't see any problem here). And I see no real need to reflect an example signature from the standard.

**Comment by dominichamon** [comment]
the PR has a deeper explanation, but broadly speaking: following the standard provides maximum alignment with expectations of programs that would like to integrate. 

"I see no problem with passing non-const versions to function accepting const. "
https://godbolt.org/z/81eKGz3rr

"error: invalid conversion from 'char**' to 'const char**'"

**Comment by deiuch** [comment]
> "I see no problem with passing non-const versions to function accepting const. " https://godbolt.org/z/81eKGz3rr
> 
> "error: invalid conversion from 'char**' to 'const char**'"
Oh, it was quite unexpected for my vision of const-correctness. I'll go and look at it more carefully, thank you very much!
