### ISSUE TITLE
[BUG] Can't find package with `cmake --find-package`

### ISSUE THREAD

**Issue by zaufi** [google/benchmark#1422]
**Describe the bug**
Trying to detect the package with `cmake --find-package -DNAME=benchmark ...`  ends with failure.

**System**
Which OS, compiler, and compiler version are you using:
  - OS:  any
  - Compiler and version: N/A

**To reproduce**
1. install the package
2. `cmake --find-package -DNAME=benchmark ...`

**Expected behavior**
`benchmark found.` output.

**Screenshots**
```
CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FindThreads.cmake:66 (message):
  FindThreads only works if either C or CXX language is enabled
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.24/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  google-benchmark.1.6.1/share/cmake/benchmarkConfig.cmake:12 (find_dependency)
  C:/Program Files/CMake/share/cmake-3.24/Modules/CMakeFindPackageMode.cmake:183 (find_package)
```

**Additional context**
Need to fix the `benchmarkConfig.cmake` to be tolerated to [CMake Find Package mode](https://cmake.org/cmake/help/latest/manual/cmake.1.html#run-the-find-package-tool).

**Comment by sergiud** [comment]
This is not a benchmark issue, see https://gitlab.kitware.com/cmake/cmake/-/issues/20849. Quoting CMake maintainer:

> Limitations like that you encountered are the reason --find-package mode is deprecated.
>
> This is not supported.
