### ISSUE TITLE
[BUG] benchmark/export.h not found (dependency of benchmark.h)

### ISSUE THREAD

**Issue by RylanYancey** [google/benchmark#1423]
**Describe the bug**

**System**
Which OS, compiler, and compiler version are you using:
  - Ubuntu 22.04 LTS
  - GCC  11.2.0
  - cmake 3.22.1
  - GNU make 4.3 (I am using GNU make in my project)

**To reproduce**
1. Follow instructions in the "Installation" section of the README, (did  this twice, reinstalled, no issues either time while installing)
2. Add -I../../lib/benchmark/include/ to my makefile (path to the library)
3. Add #include "benchmark/benchmark.h" to my main.cpp
4. Get this error:
```cpp
In file included from source/main.cpp:6:
../../lib/benchmark/include/benchmark/benchmark.h:190:10: fatal error: benchmark/export.h: No such file or directory
  190 | #include "benchmark/export.h"
      | 
```
5. :(

**Expected behavior**
At this point, I would expect the code to compile and be usable. 

**Additional context**
Looking in the file, lib/benchmark/ file, it seems that there is no export.h at all in it, nor on the github repository. using Nano, I confirmed that this #include did in fact exist in benchmark.h on line 190, but I don't know where it is supposed to come from. 

I ran the tests indicated in the readme, `0 tests failed out of 72`.

Thanks for any help,
         Rylan Yancey

**Comment by dominichamon** [comment]
are you building the library and installing it before linking to it? or linking to a local checkout of the library?

the `export.h` is generated by the build, so you'd want to be pointing your -I flag at the _output_ of the installation not the _input_.

**Comment by RylanYancey** [comment]
> are you building the library and installing it before linking to it? or linking to a local checkout of the library?
> 
> the `export.h` is generated by the build, so you'd want to be pointing your -I flag at the _output_ of the installation not the _input_.

Ok, I release now. I changed  my command to look like this:

```make
CFLAGS = -c -I./header -std=c++11 -I../../lib/benchmark/build/include/ -I../../lib/benchmark/include/
```

This makes the compiler errors go away, when I try to compile:

```cpp
g++ -o run bin/main.o 
/usr/bin/ld: bin/main.o: in function `__static_initialization_and_destruction_0(int, int)':
main.cpp:(.text+0x118): undefined reference to `benchmark::internal::InitializeStreams()'
collect2: error: ld returned 1 exit status
make: *** [makefile:78: all] Error 1
```

Heres my makefile
```make
LIBRARIES = -L../../lib/benchmark/build/src -isystem -lpthread
CFLAGS = -c -I./header -std=c++11 -I../../lib/benchmark/build/include/ -I../../lib/benchmark/include/
CC = g++
