### ISSUE TITLE
CMake fails without Git

### ISSUE THREAD

**Issue by ulvgard** [google/benchmark#144]
CMake fails if Git is not installed on the host system. 

There is no check if Git is present in the system before running Git to find out this project version from tags in Benchmark. See cmake/GetGitVersion.cmake.

Running CMake without Git yields:
```
CMake Error at cmake/GetGitVersion.cmake:28 (string):
  string sub-command STRIP requires two arguments.
Call Stack (most recent call first):
  CMakeLists.txt:11 (get_git_version)


CMake Error at cmake/GetGitVersion.cmake:29 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
Call Stack (most recent call first):
  CMakeLists.txt:11 (get_git_version)


-- git Version: 
CMake Error at CMakeLists.txt:14 (string):
  string sub-command REGEX, mode MATCH needs at least 5 arguments total to
  command.


-- Version: 
CMake Error at CMakeLists.txt:19 (string):
  string sub-command SUBSTRING requires four arguments.
```

Im using CMake 2.8.11 (also tested CMake 3.0.2) on Linux and Windows.

I can submit a pull request, but before I want to check with you guys that this is an issue.

**Comment by dominichamon** [comment]
it's just not something that occurred to me might happen, given we're git-hosted. I'm more than happy to consider a PR. How do you intend to fix it, ie, what will you return for the version?

**Comment by ulvgard** [comment]
Using find_package which sets GIT_EXECUTABLE. If Git is found then proceed to check the tags, otherwise define version to v0.0.0 as the scripts do today. I tried this today and made it work.

https://cmake.org/cmake/help/v2.8.12/cmake.html#command:find_package
https://cmake.org/cmake/help/v2.8.12/cmake.html#module:FindGit

**Comment by dominichamon** [comment]
perfect. i look forward to the PR.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by EricWF** [comment]
I don't understand why we do this at all. What do we gain over simply writing the version number in the CMake file?

**Comment by ulvgard** [comment]
I've initiated the process of signing the CLA irrespectively of if we ditch the Git-version check feature or not.

**Comment by dominichamon** [comment]
@EricWF it's one less piece of maintenance. we release through git with a version tag (signed) and it becomes the de facto version. a minor convenience.

**Comment by EricWF** [comment]
This seems like maintenance to me. I would prefer to do the simple thing and just embed the version numbers and tag the release. Then, however they checkout the source code, they will get the right version.

**Comment by dominichamon** [comment]
perhaps there's a way to pull out the release version when tagging so we don't tag the wrong version.

i agree it's cleaner and more obvious to have it in the code (and it can be logged on startup easier!), but i'm old and forgetful and prefer to automate whatever i can.
