### ISSUE TITLE
Can't run/debug on visual studio 2022

### ISSUE THREAD

**Issue by khlorz** [google/benchmark#1443]
I've managed to build the library by following the install manual. I've tried running the sample code on visual studio 2022. It runs however, it always throws an exception. An access violation reading location on StartKeepRunning() function inside inline BECNHMARK_ALWAYS_INLINE State::StateIterator State::end() when it runs on Release mode. An access violation reading location on some mutex header when it runs on Debug mode. Is there a way to fix this?

**Comment by imrichardcole** [comment]
Hi @khlorz could you please confirm your build commands and which version of benchmark you were building at the time?

Thanks

Rich.

**Comment by imrichardcole** [comment]
Appreciate this issue is 2+ years old, but I've been unable to reproduce.  I would propose this issue is closed @dmah42 unless @khlorz responds with any updates.

**Comment by khlorz** [comment]
Sorry for not replying as soon as possible @imrichardcole, but it's been two years and the source has already been deleted since I never got an answer before. But still thankful for the reply. However, I would try to reproduce it in case I'll try to use it again, and the error persists.

**Comment by imrichardcole** [comment]
@khlorz no worries at all.  Just drop a comment here if you're still able to reproduce and I'll look into it
