### ISSUE TITLE
benchmark::RunSpecifiedBenchmarks() should play nicely with googletest RUN_ALL_TESTS

### ISSUE THREAD

**Issue by devjgm** [google/benchmark#145]
Given a simple foo_test.cc file that uses both [Google Test](https://github.com/google/googletest) and google/benchmark, there should be a way to run only the benchmarks without also running the unit tests. When using both googletest and google/benchmarks, a typical main() function might look like the following:

```c++
int main(int argc, char* argv[]) {
  testing::InitGoogleTest(&argc, argv);
  benchmark::Initialize(&argc, argv);
  benchmark::RunSpecifiedBenchmarks();
  return RUN_ALL_TESTS();
}
```

Which will initialize googletest, then the benchmark library, then it will need to run both of them. However, the result of the above code is that the benchmarks will be run (if specified via --benchmark_filter), and then the unit tests will still be run.

More desirable behavior would be enable the ability to run only the benchmarks without also running the unit tests. Actually, the existing documentation for `benchmark::RunSpecifiedBenchmarks()` indicates that it should exit after running the benchmarks, but this does not happen. That documentation does not match the implementation.

```c++
...
// Otherwise, run all benchmarks specified by the --benchmark_filter flag,
// and exit after running the benchmarks.
void RunSpecifiedBenchmarks();
void RunSpecifiedBenchmarks(BenchmarkReporter* reporter);
...
```

## Possible solutions

* Change `RunSpecifiedBenchmarks()` to exit IFF it ran any benchmarks. This would then match the existing documentation and it would make the example `main()` function I included up top work.

* Change `RunSpecifiedBenchmarks()` to return some indicator as to whether or not it ran some benchmarks. This way, the code in main could then conditionally call Google Test's RUN_ALL_TESTS() function. The return indicator could be bool (true=benchmarks were run), or an int indicating how many benchmarks were run (maybe 0).

* Possibly something else.

**Comment by dominichamon** [comment]
i'd rather not exit from within a library as i think that's unexpected. the documentation should be updated to reflect that.

returning the number of benchmarks run is fine, but may have an edge case if a filter is applied that accidentally filters all the benchmarks. then you'll have the tests run anyway unexpectedly.

can the application add its own flag to run benchmarks or tests or both?

or perhaps it's best to just keep the mains separate and build two different binaries referencing the same tests/benchmarks, again at the application level.

**Comment by EricWF** [comment]
I think returning the number of benchmarks run is the best solution. Since @dominichamon doesn't object I'm going to go ahead and implement it.
