### ISSUE TITLE
[Question] Regarding version tagged as 1.6.2

### ISSUE THREAD

**Issue by jcar87** [google/benchmark#1453]
Hi there! I am one of the maintainers of the [Conan Center Index ](https://github.com/conan-io/conan-center-index )package repository.

Recently we have had users reporting checksum mismatches when building the recipe from source, as it appears version 1.6.2 was re-tagged and the new .tar.gz file has a different checksum.

We have a request to update our recipe for version 1.6.2 to reflect the _newer_ checksum for the `.tar.gz` file currently being returned by GitHub. Out of an abundance of caution, we would like to confirm what the changes were between the _original_ `1.6.2` commit, vs the commit that the `1.6.2` currently points to, so that we can reflect this in our recipes and pull requests for traceability purposes.

Additionally, we would like to identify any cases in which users that download the _newer_ 1.6.2 may experience issues that the original 1.6.2 did not have. In particular, I have noticed https://github.com/google/benchmark/issues/1436, however I have not been able to reproduce this. If this were to be the case, we would consider adding additional patches to the updated 1.6.2 to avoid any regressions that users of the original 1.6.2 did not experience.

**Comment by dominichamon** [comment]
the changes were:

```
d845b7b3a27d54ad96280a29d61fa8988d4fddcf (tag: v1.6.2) Also fix the SOVERSION for benchmark_main
d4bc509bcd54266e80bef26d5829ea43ead2908e Fix SOVERSION of shared library
7a2024e961b8741ce46e83f226378b90e457ead3 v1.6.2 bump
```

there is also v1.7.0 which includes:

```
361e8d1cfe0c6c36d30b39f1b61302ece5507320 (tag: v1.7.0) version bump
ef7f75fb182fc23d03b4a3ecd09cc325ac125dfd simplified code (#1439)
e27c93073fd2c674077bf9dc915cd8c79b562156 use target_compile_definitions (#1440)
7b3ac075177212dd75476253d72db992513e8024 Stop generating the export header and just check it in (#1435)
```

**Comment by jcar87** [comment]
Hi @dominichamon  - thanks so much for the quick reply, will make sure to reference this information when updating our recipe for v1.6.2. 
As a last question, would you be able to confirm that the original tag referred to commit `7a2024e961b8741ce46e83f226378b90e457ead3`? 


We will also be providing version 1.7.0 as well :)

**Comment by dominichamon** [comment]
well, it was actually retagged a couple of times.  :(

it started as 48c2d1c1ee54aaf583a3bec69f2a7e35f19b53da. this is why 7a2024e961b8741ce46e83f226378b90e457ead3 was necessary and then it was retagged to that.

then archlinux maintainers noted an issue with the SOVERSION so we fixed that and retagged again.

**Comment by jcar87** [comment]
I see - thanks a lot for the clarification. This is vital information to make an informed decision with regards to the updated package for 1.6.2 - for traceability purposes (so that users are informed of the changes) and in case users may wish to continue using 1.6.2 for a bit longer before updating to 1.7.0 :)
