### ISSUE TITLE
Purge all references to the int64_t type.

### ISSUE THREAD

**Issue by EricWF** [google/benchmark#147]
Currently the types used in Benchmark are inconsistent. In particular those used in the documentation vs those used in the actual code. I think we have all agreed on using size_t or int instead of int64_t.

I think we should audit the documentation and the public interface for occurrences of int64_t and remove them.

Most internal usages of int64_t can stay so long as they don't need to interact with the API types for now.

**Comment by dominichamon** [comment]
bytes and items processed should remain (u)int64_t. the rest can go, especially taking into account the overhead of 64-bit math on 32-bit systems.

**Comment by divayprakash** [comment]
@EricWF I'd like to take this up. Could you give a little more info on how to go about it?

**Comment by EricWF** [comment]
Honestly last time I checked the status of this bug I used `grep -R int64_t`.

**Comment by divayprakash** [comment]
So just swap out `int` for all occurrences of `int64_t`?

**Comment by pleroy** [comment]
Nope, some of these should be `size_t`.  Also, `int` is typically 32 bits, so you must make sure that you are not introducing overflows.

This is a tricky change, it's certainly not a global substitute.

**Comment by EricWF** [comment]
Exactly what @pleroy said. The remainder of the changes are tricky, most long hanging fruit is gone.

**Comment by dominichamon** [comment]
At some point we started replacing size_t with int64_t explicitly, and I think we're in a position where everything is correct, and we shouldn't monkey around with it further.

If you agree, @EricWF, please close this.
