### ISSUE TITLE
[BUG] go woke go broke

### ISSUE THREAD

**Issue by jll63** [google/benchmark#1478]
**Describe the bug**
```
cmake -DBENCHMARK_DOWNLOAD_DEPENDENCIES=1
```
fails with:
```
CMake Warning at CMakeLists.txt:36 (message):
  Did not find Google Test sources! Fetching from web...


Cloning into 'src'...
fatal: invalid reference: master
CMake Error at tmp/googletest-gitclone.cmake:40 (message):
  Failed to checkout tag: 'master'
```
That's because `master` has been renamed to `main` in `googletest`.

**System**
Any.

**To reproduce**
```
mkdir build
cd build
cmake -DBENCHMARK_DOWNLOAD_DEPENDENCIES=1
```

**Comment by dominichamon** [comment]
i think this might already be fixed in `main`.

**Comment by nmoinvaz** [comment]
This broke our CI as well.

**Comment by matta** [comment]
Yeah, this was fixed in https://github.com/google/benchmark/commit/a07f6d1789193336144e8dd1ece37325c2dcef49 last November. Any Google Benchmark release [v1.6.1](https://github.com/google/benchmark/releases/tag/v1.6.1) or newer should be functional.
