### ISSUE TITLE
[API]How I can pass different arguments to one benchmark using a for loop?

### ISSUE THREAD

**Issue by yszhou2019** [google/benchmark#1503]
How I can pass different arguments to one benchmark using a for loop?
I want to pass each element of {50, 100, 150, 200, ..., 1300} to one benchmark. Each benchmark takes one argument named `mellen`.
I don't want to directly write each benchmark instance which takes 50 / 100 / .... 
I wonder how can I generate different benchmark?
Thank you!
e.g.
```cpp
void HiFiGANONNXRuntime(benchmark::State& state) {
    for (auto _ : state) {
       // ...
    }
}

// just like
BENCHMARK_CAPTURE(TestBenchmark, HiFiGANONNXRuntime)->Args(50)->Iterations(100)->Unit(benchmark::kMillisecond);
BENCHMARK_CAPTURE(TestBenchmark, HiFiGANONNXRuntime)->Args(100)->Iterations(100)->Unit(benchmark::kMillisecond);
BENCHMARK_CAPTURE(TestBenchmark, HiFiGANONNXRuntime)->Args(150)->Iterations(100)->Unit(benchmark::kMillisecond);
BENCHMARK_CAPTURE(TestBenchmark, HiFiGANONNXRuntime)->Args(200)->Iterations(100)->Unit(benchmark::kMillisecond);
BENCHMARK_CAPTURE(TestBenchmark, HiFiGANONNXRuntime)->Args(250)->Iterations(100)->Unit(benchmark::kMillisecond);
...
BENCHMARK_CAPTURE(TestBenchmark, HiFiGANONNXRuntime)->Args(1300)->Iterations(100)->Unit(benchmark::kMillisecond);

```

**Comment by LebedevRI** [comment]
See https://github.com/google/benchmark/blob/main/docs/user_guide.md

> For more complex patterns of inputs, passing a custom function to Apply allows programmatic specification of an arbitrary set of arguments on which to run the benchmark. The following example enumerates a dense range on one parameter, and a sparse range on the second.
> ```
> static void CustomArguments(benchmark::internal::Benchmark* b) {
>   for (int i = 0; i <= 10; ++i)
>     for (int j = 32; j <= 1024*1024; j *= 8)
>       b->Args({i, j});
> }
> BENCHMARK(BM_SetInsert)->Apply(CustomArguments);
```

**Comment by yszhou2019** [comment]
Thank you!
