### ISSUE TITLE
[FR] Consider adopting the same support policies as other google C++ projects

### ISSUE THREAD

**Issue by coryan** [google/benchmark#1509]
Other google C++ projects are adopting (or have adopted) the support policies outlined at

https://opensource.google/documentation/policies/cplusplus-support

(see this [matrix](https://github.com/google/oss-policies-info/blob/main/foundational-cxx-support-matrix.md) for details).

Please consider adopting the same policies in this project.  For example, this project requires CMake >= 3.16.3, which makes it hard to use from other projects.

**Comment by devjgm** [comment]
+1 I'd like to see google/benchmark adopt these same policies

**Comment by dominichamon** [comment]
i don't think we're far off.

https://github.com/google/benchmark/blob/main/docs/dependencies.md has justifications for the cmake support, which i don't think are unreasonable given how widely available 3.16 is at this point.

if someone wants to go through the matrix and see if we're aligned or not, i'm open to that :)

**Comment by devjgm** [comment]
> https://github.com/google/benchmark/blob/main/docs/dependencies.md has justifications for the cmake support, which i don't think are unreasonable given how widely available 3.16 is at this point.

I think that documented policy should be revisited in light of [the C++ support policy][cpp-policy]. I think this feature request is for Google Benchmark to forego its own support policy and instead adopt the common [the C++ support policy][cpp-policy], unless its existing policy offered even more support, which it doesn't.

[cpp-policy]: https://opensource.google/documentation/policies/cplusplus-support

**Comment by dmah42** [comment]
in #1550 i'm creating a CI bot to check cmake 3.10.0 support and i've hit a potential snag: cmake 3.10.0 only supports MSVC generators for VS 15 (2017) and lower.  we currently support VS 16 (2019) and higher.

it may be that we can support these older VS versions but i'm not a windows developer so i don't know for sure.  i will continue to experiment, but this may be a fly in the cmake ointment.

**Comment by dmah42** [comment]
per a comment on the PR from @coryan : we can assume per policy that we're supporting the newer Windows environments only and they have newer cmake available.

**Comment by dmah42** [comment]
i think we're there.  the only nuance we have is that we don't require modern flavours of C++ to use the library, only to build it.  so the header should remain free of any language features that require C++14 or newer (iirc).

so i think we can close this as complete.  feel free to reopen it if i've missed something.
