### ISSUE TITLE
[bazel][FR] Consider a workspace() function to recursively add dependencies

### ISSUE THREAD

**Issue by coryan** [google/benchmark#1510]
**Is your feature request related to a problem? Please describe.**

Starting with #1408 (which was included in v1.7.1) all users for `google/benchmark` via Bazel must provide the `@libpfm` repository **or** must set the `perfcounters` config to `0` 
As you may know, Bazel does not load WORKSPACE files recursively (see bazelbuild/bazel#1943 for history, and [bzlmod](https://bazel.build/build/bzlmod) for the modern thing).  This meas downstream projects must add this dependency to their own `WORKSPACE` files.

**Describe the solution you'd like**

By convention, Bazel projects provide a `*_deps()` or  `workspace()` function to load the dependencies they need.  For example, this is one in Tensorflow:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace2.bzl
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace1.bzl

and here is what grpc does:

https://github.com/grpc/grpc/blob/master/bazel/grpc_deps.bzl

Anything along those lines would be helpful.

**Describe alternatives you've considered**

You could wait until `bzlmod` is ready, but I do not know if that works with `rules_foreign_cc`

**Additional context**

Adding a new dep seems surprising for a patch release.

**Comment by Forchapeatl** [comment]
Hello everyone. @coryan it seems like . Please help me. 

https://github.com/google/benchmark/blob/2257fa4d6afb8e5a2ccd510a70f38fe7fcdf1edf/WORKSPACE#L1
