### ISSUE TITLE
[FR] clang static analyzer: `src/include/benchmark/benchmark.h:1069:3: Potential memory leak [cplusplus.NewDeleteLeaks]`

### ISSUE THREAD

**Issue by LebedevRI** [google/benchmark#1513]
https://github.com/darktable-org/rawspeed/actions/runs/3574871458/jobs/6011864553#step:23:314
https://github.com/google/benchmark/blob/2257fa4d6afb8e5a2ccd510a70f38fe7fcdf1edf/include/benchmark/benchmark.h#L1272-L1276
triggers clang static analyzer reports:
```
[HIGH] /__w/rawspeed/rawspeed/rawspeed-build/src/external/googlebenchmark/src/include/benchmark/benchmark.h:1069:3: Potential memory leak [cplusplus.NewDeleteLeaks]
  return internal::RegisterBenchmarkInternal(
  ^

Found 1 defect(s) in benchmark.h
```
It would be really good to either completely rewrite that code to avoid the issue in the first place,
or at least silence it as a known false-positive.

**Comment by HFTrader** [comment]
I could not replicate this. Using clang 17 (trunk) and benchmark/main as of today.

**Comment by LebedevRI** [comment]
Still happening: https://github.com/darktable-org/rawspeed/actions/runs/4367100895/jobs/7637984919#step:29:275

**Comment by dmah42** [comment]
can we add that static analysis to the benchmark CI bots?

**Comment by LebedevRI** [comment]
> Still happening: https://github.com/darktable-org/rawspeed/actions/runs/4367100895/jobs/7637984919#step:29:275

(Err, of course that is with clang-15, maybe it's gone in clang-16, i don't know yet.)

**Comment by HFTrader** [comment]
How did you run? Just `scan-build make`?

**Comment by LebedevRI** [comment]
As you can see in that very log, by running `CodeChecker` over the `compile_commands.json`.

**Comment by HFTrader** [comment]
It looks like CodeChecker uses scan-build under the hood, right? Let me try with clang-15 or earlier.

**Comment by LebedevRI** [comment]
Yup, the warning is still there with clang-16, as expected:
https://github.com/darktable-org/rawspeed/actions/runs/5428151349/jobs/9872094540?pr=494

Also, is anyone familiar why benchmarks that are linked to shared libraries
may fail with `Exit code 0xc0000135`?
https://github.com/darktable-org/rawspeed/actions/runs/5428151349/jobs/9872096202?pr=494
