### ISSUE TITLE
[BUG] MSVC 2022 linker errors

### ISSUE THREAD

**Issue by jimmyolsson** [google/benchmark#1524]
**Describe the bug**
I get linker errors when trying to link with google benchmark in visual studio 2022. I've tried both manually building it as the guidelines says and with vcpkg, none works.
This guy has the same problem it seems, the answer provided made no difference:
https://stackoverflow.com/questions/73494386/lnk2001-linker-error-while-linking-google-benchmark-lib

I also get this for some reason: 
![image](https://user-images.githubusercontent.com/68332439/211822557-4d6052a5-3180-4599-92f3-5146c82e1fb1.png)

My code:
```#include <benchmark/benchmark.h>
void asd()
{
	int sum = 0;
	for (int i = 0; i < 1000; i++)
		sum += i;
}

static void chunkparse(benchmark::State& state)
{
	for (auto _ : state)
	{
		asd();
	}
}

BENCHMARK(chunkparse)->DenseRange(0, 32);
BENCHMARK_MAIN();
```

`1>main.cpp
1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) int __cdecl benchmark::internal::InitializeStreams(void)" (__imp_?InitializeStreams@internal@benchmark@@YAHXZ)
1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual void __thiscall benchmark::internal::FunctionBenchmark::Run(class benchmark::State &)" (__imp_?Run@FunctionBenchmark@internal@benchmark@@UAEXAAVState@3@@Z)
1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) class benchmark::internal::Benchmark * __cdecl benchmark::internal::RegisterBenchmarkInternal(class benchmark::internal::Benchmark *)" (__imp_?RegisterBenchmarkInternal@internal@benchmark@@YAPAVBenchmark@12@PAV312@@Z)
1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl benchmark::PrintDefaultHelp(void)" (__imp_?PrintDefaultHelp@benchmark@@YAXXZ)
1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) bool __cdecl benchmark::ReportUnrecognizedArguments(int,char * *)" (__imp_?ReportUnrecognizedArguments@benchmark@@YA_NHPAPAD@Z)
1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl benchmark::Initialize(int *,char * *,void (__cdecl*)(void))" (__imp_?Initialize@benchmark@@YAXPAHPAPADP6AXXZ@Z)
1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) private: void __thiscall benchmark::State::FinishKeepRunning(void)" (__imp_?FinishKeepRunning@State@benchmark@@AAEXXZ)
1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) private: void __thiscall benchmark::State::StartKeepRunning(void)" (__imp_?StartKeepRunning@State@benchmark@@AAEXXZ)
1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) unsigned int __cdecl benchmark::RunSpecifiedBenchmarks(void)" (__imp_?RunSpecifiedBenchmarks@benchmark@@YAIXZ)
1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) void __cdecl benchmark::Shutdown(void)" (__imp_?Shutdown@benchmark@@YAXXZ)
1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: virtual __thiscall benchmark::internal::FunctionBenchmark::~FunctionBenchmark(void)" (__imp_??1FunctionBenchmark@internal@benchmark@@UAE@XZ)
1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: __thiscall benchmark::internal::FunctionBenchmark::FunctionBenchmark(char const *,void (__cdecl*)(class benchmark::State &))" (__imp_??0FunctionBenchmark@internal@benchmark@@QAE@PBDP6AXAAVState@2@@Z@Z)
1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: struct benchmark::State::StateIterator __thiscall benchmark::State::end(void)" (__imp_?end@State@benchmark@@QAE?AUStateIterator@12@XZ)
1>main.obj : error LNK2001: unresolved external symbol "__declspec(dllimport) public: struct benchmark::State::StateIterator __thiscall benchmark::State::begin(void)" (__imp_?begin@State@benchmark@@QAE?AUStateIterator@12@XZ)`

Any help is appreciated.

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Windows 10 Pro Version 10.0.19044
  - Compiler and version: 

**To reproduce**
1. Follow the tutorial / vcpkg install benchmark
2. Compile with msvc

**Expected behavior**
It links

**Comment by dmah42** [comment]
i think we're missing some information about how your project is configured but the "function definition" issue sounds like you didn't include benchmark.h.. the linker errors look like you're not linking against the benchmark library.

**Comment by jimmyolsson** [comment]
Ok.
This is my project structure:
![image](https://user-images.githubusercontent.com/68332439/211825746-d02a2bd3-0f93-4205-bfe5-24e1517cee6d.png)
And this is the project properties that i changed:
![image](https://user-images.githubusercontent.com/68332439/211826885-ca32816f-39dc-4b9d-8686-3c57ff8c96f3.png)
![image](https://user-images.githubusercontent.com/68332439/211827557-6bca784c-8850-4aa5-9848-be4e74f52f0e.png)
![image](https://user-images.githubusercontent.com/68332439/211827605-ad13d835-65ff-41b7-ae97-9b7b3e0c20f8.png)

**Comment by adamse** [comment]
I managed to link with VS but I had to compile with `-DBENCHMARK_STATIC_DEFINE` to ensure the right symbols are referenced.
