### ISSUE TITLE
[BUG] Statistics causes high memory usage (OOM)

### ISSUE THREAD

**Issue by zptan** [google/benchmark#1530]
**Describe the bug**
Even with function that does nothing, memory usage is ~7GB when I set repetition to 10'000'000
I checked the memory usage by `htop`, the peak memory usage is: `VIRT 13GB, RES 7GB`
```cc
void do_nothing(benchmark::State& state) {
    // Do nothing
}

BENCHMARK(do_nothing)->Iterations(100)->Repetitions(10'000'000)
->ReportAggregatesOnly()
->DisplayAggregatesOnly();
```

It seems that `Repetitions` is the most important factor, the x-axis the the number of repetitions (million)
![image](https://user-images.githubusercontent.com/17807777/212528167-53c114b2-e232-49fe-83a3-e1e3d1885fa0.png)

**System**
  - OS: Ubuntu-22.04
  - Compiler and version: g++-11, clang-14
  - Google Benchmark version: 1.6.1

**Expected behavior**
I think hundreds of MB memory usage is acceptable

**Comment by LebedevRI** [comment]
So memory consumption is linearly proportional to the number of repetitions, which makes sense.
This is not a bug. Other than trying to reduce the size of the data structures, we can't do anything here.
The point is, we do have to keep all repetitions in memory, because we can not compute the aggregate
until we have *all* the repetitions. Sure, some statistics can be computed without that, but not all.

**Comment by dmah42** [comment]
i haven't prioritised worrying about how much memory each repetition takes or what the right number is.  if you have a number in mind that would be useful to know. if you have an idea of how to take the current code and get it towards that number that would be even more useful.

**Comment by LebedevRI** [comment]
Looks like, as expected, the biggest problem is `BenchmarkReporter::Run`, which is `560 bytes` itself.

> > So every repetition needs 7GB / 10M = 700KB, that's too much memory

Err, you're off by a magnitude. That is 700 *bytes* per iteration.

**Comment by dmah42** [comment]
haha i didn't even check that. yeah i think 700 bytes is fine :)

**Comment by LebedevRI** [comment]
Eh, i do think we could take an order of magnitude less still, but that would require AoS -> SoA refactorings everywhere.
