### ISSUE TITLE
Please provide explicit tar.xz archives for *each* tag, retrospectively.

### ISSUE THREAD

**Issue by LebedevRI** [google/benchmark#1534]
Not sure what kind of drugs they are currently smoking at github, but
https://github.com/orgs/community/discussions/45830
https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/

**Comment by dmah42** [comment]
looks like they're reverting the change

**Comment by LebedevRI** [comment]
> looks like they're reverting the change

Sure, but ignoring the way that happened, they aren't exactly wrong.
Unless you control it, you can't rely on it. Honestly it's not really surprising it happened.
