### ISSUE TITLE
Compilation error using g++

### ISSUE THREAD

**Issue by philippefoubert** [google/benchmark#154]
The `add_cxx_compiler_flag(-Wshorten-64-to-32)` modification done to solve the issue #72  gives some compilation errors while compiling with mingw64 on Windows:
`g++.exe: error: unrecognized command line option '-Wshorten-64-to-32'`

Details:  gcc version 4.8.2 (x86_64-win32-seh, built by MinGW-W64 project)

**Comment by philippefoubert** [comment]
Same problem with the `-Wthread-safety` option which is not recognized by g++.

A way to avoid this kind of problem could be to modify the `add_cxx_compiler_flag` function to test whether a compiler option is supported before adding it (a bit like it is done in `cxx_feature_check`).

This could be done the same way it is done in  OpenCV with the macro `ocv_check_compiler_flag` (more details in https://github.com/Itseez/opencv/blob/master/cmake/OpenCVUtils.cmake).

**Comment by dominichamon** [comment]
Sounds reasonable to me.

**Comment by EricWF** [comment]
This has already been fixed.
