### ISSUE TITLE
[FR] Add option to specify _output format_ in the Python binding

### ISSUE THREAD

**Issue by MattiaMontanari** [google/benchmark#1547]
I use the python binding a I would like to set the BENCHMARK_OUT_FORMAT from the python script

A possible solution could be something as simple as
```
@benchmark.option.out_format("json")
```

**Additional context**
I may be able to help out if this feature is not already available.

**Comment by dmah42** [comment]
sounds reasonable to want to do this.

**Comment by MattiaMontanari** [comment]
@dmah42 I'm not able to build the python wheel to test my changes. I read the [docs](https://github.com/google/benchmark/blob/main/docs/python_bindings.md) and looked at the Actions but I don't know what's wrong.

The command `python3 -m pip wheel . -w wheelhouse` fails:

```
  Building wheel for google-benchmark (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
 ╰─> [30 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-11-x86_64-cpython-310
      creating build/lib.macosx-11-x86_64-cpython-310/google_benchmark
      copying bindings/python/google_benchmark/__init__.py -> build/lib.macosx-11-x86_64-cpython-310/google_benchmark
      copying bindings/python/google_benchmark/example.py -> build/lib.macosx-11-x86_64-cpython-310/google_benchmark
      running build_ext
      bazel build //bindings/python/google_benchmark:_benchmark --symlink_prefix=build/temp.macosx-11-x86_64-cpython-310/bazel- --compilation_mode=opt --cxxopt=-std=c++17 --macos_minimum_os=10.14
      Loading:
      Loading:
      Loading: 0 packages loaded
      Analyzing: target //bindings/python/google_benchmark:_benchmark (1 packages loaded, 0 targets configured)
      Analyzing: target //bindings/python/google_benchmark:_benchmark (24 packages loaded, 250 targets configured)
      INFO: Analyzed target //bindings/python/google_benchmark:_benchmark (25 packages loaded, 299 targets configured).
      INFO: Found 1 target...
      [0 / 4] [Prepa] BazelWorkspaceStatusAction stable-status.txt
      ERROR: /repos/benchmark/bindings/python/google_benchmark/BUILD:12:13: Linking bindings/python/google_benchmark/_benchmark.so failed: (Exit 1): cc_wrapper.sh failed: error executing command (from target //bindings/python/google_benchmark:_benchmark.so) external/local_config_cc/cc_wrapper.sh @bazel-out/darwin-opt/bin/bindings/python/google_benchmark/_benchmark.so-2.params
      
      Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
      ld: unknown option: -no_fixup_chains
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      Error in child process '/usr/bin/xcrun'. 1
      Target //bindings/python/google_benchmark:_benchmark failed to build
      Use --verbose_failures to see the command lines of failed build steps.
      INFO: Elapsed time: 1.679s, Critical Path: 0.06s
      INFO: 2 processes: 2 internal.
      FAILED: Build did NOT complete successfully
      error: command '/usr/local/bin/bazel' failed with exit code 1
      [end of output]
```

Any suggestions? All I'd like to do is to test my changes build and run...

**Comment by dmah42** [comment]
ld: unknown option: -no_fixup_chains

this is the key.  it was changed recently but I don't know a lot about how the wheel building works. that's @nicholasjng  I think.

**Comment by nicholasjng** [comment]
What is your clang/ld version?

Yes, that comes from the recent nanobind bump. The options actually were changed again to use a generated symbol table, but I have not had success in making that file available to Bazel yet. I will file another PR once that works.

For now, it should be safe to roll back to the previous option set, until I find out how we can pass the generated symbol file to Bazel's `linkopts`.

**Comment by MattiaMontanari** [comment]
Thanks! What SHA should I rollback to?

**Comment by nicholasjng** [comment]
You could probably do `git revert 23dadfa4a7812c9ee16812e3b6eff05c57a30745` (this is the SHA of the squashed commit from #1565).

Outside of that: I wonder how this would work exactly? The `@benchmark.option` decorator is in principle setting options local to that particular benchmark, but the print output is (in my view) an all-or-nothing option (i.e., either all benchmark results are output to JSON or to table). How would you reflect the totality of that option in a decorator?

**Comment by MattiaMontanari** [comment]
Answering my own question: turns out to be quite trivial actually
`export BENCHMARK_FORMAT=json && python3 benchmarks.py`
As stated in the manual, it needs the `BENCHMARK_FORMAT` env variable
