### ISSUE TITLE
[FR] Provide public accessors to benchmark name and arguments

### ISSUE THREAD

**Issue by gatorfax** [google/benchmark#1551]
For debug purposes, I want to have generic entry/exit logging of the benchmark state to the output debug stream. 

For example, consider the following RAII class:
```cpp
struct dif_guard
{
public:
    dif_guard() = delete;

    //////////////////////////////////////////////////////////////////////////
    dif_guard( const benchmark_intercept* benchmark, const benchmark::State& state, const char* extra = "" )
#if defined( _DEBUG )
        :
        m_name( std::string( benchmark->GetName() ) + std::string( extra ) ),
        m_state( state )
#endif
    {
#if defined( _DEBUG )
        std::stringstream strstr;
        strstr << m_name.c_str() << " enter.\n";
        strstr << "    max_iterations = " << m_state.max_iterations << "\n";

        if( m_state.threads() > 1 )
            strstr << "    thread_index = " << m_state.thread_index() << " / " << m_state.threads() - 1 << "\n";

        for( uint32_t i = 0; i < benchmark->ArgsCnt(); ++i )
            strstr << "    " << benchmark->GetArgName( i ) << " = " << m_state.range( i ) << "\n";

        OutputDebugString( strstr.str().c_str() );
#endif
    }

    //////////////////////////////////////////////////////////////////////////
    ~dif_guard()
    {
#if defined( _DEBUG )
        std::stringstream strstr;
        strstr << m_name.c_str() << " exit.\n";
        strstr << "    num_iterations = " << m_state.iterations() << "\n";

        if( m_state.threads() > 1 )
            strstr << "    thread_index = " << m_state.thread_index() << " / " << m_state.threads() - 1 << "\n";

        OutputDebugString( strstr.str().c_str() );
#endif
    }

protected:
#if defined( _DEBUG )
    const std::string       m_name;
    const benchmark::State& m_state;
#endif
};

//////////////////////////////////////////////////////////////////////////
#if defined( _DEBUG )
#define BENCHMARK_DIF_GUARD( _state, ... ) dif_guard dif( this, state, __VA_ARGS__ )
#else
#define BENCHMARK_DIF_GUARD( _state, ... )
#endif 
```

The code is used as follows:
```cpp
BENCHMARK_DEFINE_F( MyFixture, MyTestCase )( benchmark::State& state )
{
    BENCHMARK_DIF_GUARD( state );
...
}
BENCHMARK_REGISTER_F_EX(MyFixture, MyTestCase,
    BENCHMARK_ARG_NAMES( "width", "height" )
);
```

The output appears like this:
```txt
MyFixture/MyTestCase enter.
    max_iterations = 573
    width = 128
    height = 128
MyFixture/MyTestCase exit.
    num_iterations = 573
```

Unfortunately, the following attributes do not exist and/or are not public accessible from the benchmark fixture:
+ `Benchmark::GetName() const` - does not exist and `std::string name_` is private
+ `Benchmark::ArgsCnt() const` - exists but is private
+ `Benchmark::GetArgName(int) const` - does not exist and `std::vector<std::string> arg_names_` is private

In order to workaround these constraints, I have to implement custom fixtures to intercept and store duplicate copies of the information:
```cpp
//////////////////////////////////////////////////////////////////////////
/// @brief custom registration needed for intercepts
inline benchmark_intercept* RegisterBenchmark( benchmark_intercept* b )
{
    ::benchmark::internal::RegisterBenchmarkInternal( b );
    return b;
}

//////////////////////////////////////////////////////////////////////////
/// @brief custom registration needed for intercepts
#define BENCHMARK_PRIVATE_REGISTER_F_EX( TestName ) \
    BENCHMARK_PRIVATE_DECLARE( TestName ) = RegisterBenchmark( new TestName() )

//////////////////////////////////////////////////////////////////////////
/// @brief common registration for all benchmarks
#define BENCHMARK_REGISTER_F_EX( BaseClass, Method, Description, Names, ... )             \
    BENCHMARK_PRIVATE_REGISTER_F_EX( BENCHMARK_PRIVATE_CONCAT_NAME( BaseClass, Method ) ) \
    ->ArgNames( Names )

//////////////////////////////////////////////////////////////////////////
#define BENCHMARK_ARG_NAMES( ... ) ( std::vector<std::string>{ __VA_ARGS__ } )

//////////////////////////////////////////////////////////////////////////
/// @brief intercept-layer for capturing and providing access to
///     variables not currently provided by the benchmark framework
class benchmark_intercept : public benchmark::Fixture
{
public:
    auto GetName() const { return m_name.c_str(); }

    benchmark_intercept* ArgNames( const std::vector<std::string>& names ) /*override*/
    {
        benchmark::Fixture::ArgNames( names );
        m_argnames = names;
        return this;
    }

    auto ArgsCnt() const
    {
        return static_cast<uint32_t>( benchmark::Fixture::ArgsCnt() );
    }

    auto GetArgName( const uint32_t i ) const
    {
        return m_argnames[ i ].c_str();
    }

protected:
    void SetName( const char* name ) /*override*/
    {
        m_name = name;
        benchmark::Fixture::SetName( name );
    };

private:
    std::string              m_name;
    std::vector<std::string> m_argnames;
};
```

This works for my purpose but it may not work for all other benchmark cases (e.g., non fixtures, lambdas, etc.).

Therefore, my request is to modify the following in [benchmark.h#L1197](https://github.com/google/benchmark/blob/3b19d7222db7babfdc9b3949408b2294c3bbb540/include/benchmark/benchmark.h#L1197):

```diff
 protected:
  explicit Benchmark(const char* name);
  void SetName(const char* name);

+public:
+ const char* GetName() const;
  int ArgsCnt() const;
+ const char* GetArgName(int arg) const;
```

And [benchmark_register.cc#L472](https://github.com/google/benchmark/blob/3b19d7222db7babfdc9b3949408b2294c3bbb540/src/benchmark_register.cc#L472):
```diff
+const char* Benchmark::GetName() const { return name_.c_str(); }

+const char* Benchmark::GetArgName(int arg) const
+{
+    BM_CHECK_LT(arg, arg_names_.size());
+    return arg_names_[arg].c_str();
+}
```

Thank you for your consideration.

**Comment by dmah42** [comment]
it looks like you're reinventing the reporting part of the library.  when you run the benchmarks, why does the output you get not give you exactly the information you want? what's missing?

**Comment by gatorfax** [comment]
Yes, good question.  There are a few key differences:

1. The benchmark reporter outputs _at the end_ of the run, whereas the desire here is to log the in-order sequence of function calls _during_ execution.  There are also Enter/Exit debug statements for the `SetUp` and `TearDown` routines.  In addition to other functions being called from `SetUp`, `TearDown` and `BenchmarkCase`. For example, if an exception was thrown during execution, I want our debug logs to show where in the calling sequence the error occurred.
2. I've extended the reporting to include parameters not shown by the benchmark reporter, such as the current thread index (shown above) and the current repetition index (not shown for simplicity).
3. I've customized the conversion of the arguments to strings.  For example, if one of the arguments is an enumeration, rather than just displaying `"arg:1"`, I convert this to `"arg:1(name)"` (not shown for simplicity).

Hope this helps.

**Comment by dmah42** [comment]
> Yes, good question. There are a few key differences:
> 
> 1. The benchmark reporter outputs _at the end_ of the run, whereas the desire here is to log the in-order sequence of function calls _during_ execution.  There are also Enter/Exit debug statements for the `SetUp` and `TearDown` routines.  In addition to other functions being called from `SetUp`, `TearDown` and `BenchmarkCase`. For example, if an exception was thrown during execution, I want our debug logs to show where in the calling sequence the error occurred.

i see, so you're looking for something like a debug log or tracing for the benchmarks on top of the benchmark results themselves to be able to track down when errors occur?  i'd have thought a stack trace from an exception would be more useful than tracking every function entry and exit.

> 2. I've extended the reporting to include parameters not shown by the benchmark reporter, such as the current thread index (shown above) and the current repetition index (not shown for simplicity).

> 3. I've customized the conversion of the arguments to strings.  For example, if one of the arguments is an enumeration, rather than just displaying `"arg:1"`, I convert this to `"arg:1(name)"` (not shown for simplicity).
> 
> Hope this helps.

i'm afraid i'm still at a loss as to why this is useful.  if you need to debug a benchmark that's throwing an exception, running it under a debugger is going to be just as useful, or adding logging to your benchmarks directly (as you're doing).  anything at the per-benchmark run level is going to be extremely noisy given the potentially enormous number of iterations (and reruns) you may see.

having said that, making read-only accessors for benchmark information doesn't strike me as overly intrusive so it's probably fine.

i just don't understand why it's useful :)

**Comment by gatorfax** [comment]
> i'm afraid i'm still at a loss as to why this is useful...

Consider a project with ~30K benchmarks that take 10-12 hours to execute. These are submitted to an automated performance lab across the pond, and run nightly across a dozen or so different system configurations. If/when there is an error, crash, etc., the automated system will detect which test group failed. And then rerun with logging enabled and provide the detailed logs to a developer, who most likely will not have access to a similar machine configuration in order to reproduce the error locally.
