### ISSUE TITLE
[FR] Implement unlimited performance counters

### ISSUE THREAD

**Issue by HFTrader** [google/benchmark#1553]
The current limit of 3 performance counters is very limiting. We know several packages already use unlimited counters and there is no reason not to implement these here. 

I have been running my own performance counters inside the BENCHMARK functions for the lack of this feature within Benchmark itself. 

I made a pull request #1552 before this feature request was placed. Bummer. Now I need to figure out how to link the pull request with the feature request.

**Comment by dmah42** [comment]
it's ok, i don't need a FR for a PR to be valid.
