### ISSUE TITLE
[BUG] Release build fails with nvhpc-22.5 (nvc++)

### ISSUE THREAD

**Issue by DiegoKrupitza** [google/benchmark#1556]
**Describe the bug**
I have google benchmark (84c71faa8126e4eedc2bb520352615cb4484d6ad) as dependency in my cmake project. When I trigger a Release build with `-DCMAKE_BUILD_TYPE=Release` using nvhpc-22.5, the build fails because of:

```
"[xxxxx]/master_benchmarks/ext/google-benchmark/src/timers.cc", line 86: error: function "benchmark::<unnamed>::MakeTime(const rusage &)" was declared but never referenced
  double MakeTime(struct rusage const& ru) {
         ^


"[xxxx]/master_benchmarks/ext/google-benchmark/src/benchmark.cc", line 201: error: offsetof applied to a type other than a standard-layout class
    static_assert(offsetof(State, error_occurred_) <=
                           ^
```

Currently I use `set(BENCHMARK_ENABLE_WERROR OFF)` to force the build to pass with warnings.

**System**
Which OS, compiler, and compiler version are you using:
  - OS: `Linux 4.19.0-18-amd64 #1 SMP Debian 4.19.208-1 (2021-09-29) x86_64 GNU/Linux`
  - Compiler and version: `nvc++ 22.5-0 64-bit target on x86-64 Linux -tp zen`

**To reproduce**
1. Use google benchmark (84c71faa8126e4eedc2bb520352615cb4484d6ad) as dependency in cmake
2. run `cmake -DCMAKE_MAKE_PROGRAM=ninja -DCMAKE_CXX_COMPILER=nvc++ -G Ninja -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="-stdpar=multicore" -S . -B ./cmake-build-debug-nvidia`
3. run build ( I use the command `cmake --build cmake-build-debug-nvidia --target master_benchmarks -j 8`)

**Expected behavior**
I expected the build to run without any errors or warnings (since it does so with other compilers e.g. g++)

**Screenshots**
![image](https://user-images.githubusercontent.com/25965672/222701529-72f45b30-1ccc-489b-b0b9-03aa9ecda464.png)

![image](https://user-images.githubusercontent.com/25965672/222701325-e5604673-4235-4bae-a3c4-597f8e0ef672.png)

**Comment by HFTrader** [comment]
On the second error, it seems that the macro `offsetof` is only [conditionally supported](http://eel.is/c++draft/support.types.layout#footnote-189) by the C++17 standard for classes that are not [standard layout](http://eel.is/c++draft/class.prop#3). Standard layout are basically just plain C structs. This means the compiler can choose to support or not more non-standard types. There is a [proposal to extend that definition](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0545r0.html).

So the NVidia compiler seems to be doing the correct thing as `benchmark::State` is not a standard-layout type. I actually think to myself what offsetof means in a class with inheritance for example.

The solution seems to be creating a macro say `BENCHMARK_OFFSET_OF` and make it a particular `#if` case for Nvidia nvcc.

That said, does it compile with warnings-as-errors turned off?

**Comment by DiegoKrupitza** [comment]
> On the second error, it seems that the macro `offsetof` is only [conditionally supported](http://eel.is/c++draft/support.types.layout#footnote-189) by the C++17 standard for classes that are not [standard layout](http://eel.is/c++draft/class.prop#3). Standard layout are basically just plain C structs. This means the compiler can choose to support or not more non-standard types. There is a [proposal to extend that definition](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2017/p0545r0.html).
> 
> So the NVidia compiler seems to be doing the correct thing as `benchmark::State` is not a standard-layout type. I actually think to myself what offsetof means in a class with inheritance for example.
> 
> The solution seems to be creating a macro say `BENCHMARK_OFFSET_OF` and make it a particular `#if` case for Nvidia nvcc.

I like this idea using a macro. Because it may be the case that other compilers also do not support this. 



> That said, does it compile with warnings-as-errors turned off?

Yes, currently I use set(BENCHMARK_ENABLE_WERROR OFF) to force the build to pass with warnings.

**Comment by HFTrader** [comment]
Most are pedantic warnings turned into errors that we could ignore. One I think will have a problem though - with benchmark do not optimize.  We should address these warnings. However I am not sure if it's the intention of the maintainers to add nvc++ as a fully "supported" compiler. @dmah42 Dominic could comment.

**Comment by dmah42** [comment]
we follow https://opensource.google/documentation/policies/cplusplus-support which doesn't mention it explicitly.
