### ISSUE TITLE
[BUG] `DoNotOptimize(T &&)` should not be deprecated

### ISSUE THREAD

**Issue by davidstone** [google/benchmark#1584]
**Describe the bug**

In https://github.com/google/benchmark/pull/1493, the `T const &` overload of `DoNotOptimize` was deprecated because the compiler is still able to make assumptions about the value of the variable. However, it is unclear whether this concern would apply to an rvalue reference overload.

**To reproduce**

```cpp
int f() {
    return 5;
}
void g() {
    benchmark::DoNotOptimize(f());
}
```

**Expected behavior**

No warning is emitted.

**Comment by dmah42** [comment]
@ckennelly is the expert. i defer to them.

**Comment by horenmar** [comment]
Bumping this because I share @davidstone's opinion and also because I have to deal with about 50 warnings caused by this change.
