### ISSUE TITLE
Add cstdio

### ISSUE THREAD

**Issue by RYOBG** [google/benchmark#159]
Hello (great work), 

I have successfully used the library on Cygwin64 with GNU C++ 4.9.3, but I had first to add references to cstdio in the following files: 

_src/console_reporter.cc src/colorprint.cc src/benchmark.cc_ 

Otherwise _vprintf, stdout, printf_ and etc. were not found by the compiler.

**Comment by dominichamon** [comment]
SG. Patches welcome :)

**Comment by RYOBG** [comment]
With pleasure, but I do not have any experience with such activity. Should I use GIT to make a patch file and upload it here?

**Comment by dominichamon** [comment]
@RYOBG https://help.github.com/articles/fork-a-repo/ is a good starting point. if it's too much, let me know and i'll make the changes.

**Comment by RYOBG** [comment]
Was not easy, but I think I have made it. Thank you for the reference.
