### ISSUE TITLE
Template arguments range

### ISSUE THREAD

**Issue by disconnect3d** [google/benchmark#167]
Hello,

What do you think about adding a mechanism to iterate over range of template arguments passed to `TEMPLATE_BENCHMARK`?

Such thing could be implemented using loop template or Boost.Preprocessor (I guess we don't want to have any dependency on that).

I've added some insight on the topic on my blog post:
http://dominikczarnota.blogspot.com/2015/12/how-i-saved-myself-lot-of-writing-with.html

**Comment by dominichamon** [comment]
I think the work you've done is great for your use case, and I appreciate you documenting it so well.

I don't think there's any need to bring that into the library. If we did, we'd either bring in a dependency that I'd rather avoid, or add complexity to an API that is, frankly, already too complex for what it's doing.

**Comment by EricWF** [comment]
I think #259 would allow you to easily right your own  template range registration function.

For example:

```c++
template <class T> void BM_template(benchmark::State&) { /* ... */ }

void swallow(...);
template <class ...Types>
void BenchmarkTemplateRange() {
  swallow(benchmark::RegisterBenchmark(NAME(Types), &BM_template<Types>)...);
}
```

**Comment by EricWF** [comment]
@disconnect3d I'm closing this because I think the solution I proposed allows you to do this already. Please reopen if you disagree.
