### ISSUE TITLE
[BUG] Sanitizer CI builds are broken

### ISSUE THREAD

**Issue by dmah42** [google/benchmark#1670]
**Describe the bug**
Sanitizer builds are broken (again)

**System**
github actions

**To reproduce**
check the sanitizer actions.
for the build libc++ step we have:
`/home/runner/work/benchmark/benchmark/llvm-build/include/c++/v1/__config:37:8: warning: "Libc++ only supports Clang 15 and later" [-W#warnings]`

**Expected behavior**
it builds

**Comment by LebedevRI** [comment]
As i have warned when sanitized LLVM builds were being added...

**Comment by imrichardcole** [comment]
May I please be assigned this issue as I've been wanting to contribute for a while

**Comment by LebedevRI** [comment]
That was fixed in https://github.com/google/benchmark/pull/1703, apparently.
