### ISSUE TITLE
[BUG] Empty benchmark don't stop

### ISSUE THREAD

**Issue by bluealert** [google/benchmark#1673]
**Describe the bug**
I write a empty benchmark, but it always keep running, don't stop.

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Ubuntu 20.04
  - Compiler and version: GCC 9.4

```cpp
#include "benchmark/benchmark.h"

static void BM_StringCopy(benchmark::State& state) {
    std::string x = "hello";
    for (auto _ : state)
        std::string copy(x);
}
BENCHMARK(BM_StringCopy);

static void BM_Empty(benchmark::State& state) {}
BENCHMARK(BM_Empty);

BENCHMARK_MAIN();
```
<img width="1345" alt="image" src="https://github.com/google/benchmark/assets/2254200/50d43444-4a3a-45e9-85a8-d91baaeab441">

**Comment by LebedevRI** [comment]
A registered benchmark **MUST** contain the workloop (`for (auto _ : state) {}` / `while (state.KeepRunning())`).
This is an user error.

**Comment by bluealert** [comment]
@LebedevRI Thank you!

**Comment by LebedevRI** [comment]
Though i must admit the UX is a bit hostile in that case. I'm not sure if it can be cheaply caught, maybe it can be.

**Comment by bluealert** [comment]
@LebedevRI Yes, I'm very confused with this.

**Comment by dmah42** [comment]
maybe if we end an iteration and some iterator method on state was never called?

**Comment by LebedevRI** [comment]
> maybe if we end an iteration and some iterator method on state was never called?

That was my half-idea, yes, to bail e.g. if the iteration count ended up being zero.
