### ISSUE TITLE
BM_memcpy example has wrong SetBytesProcessed

### ISSUE THREAD

**Issue by dimztimz** [google/benchmark#168]
In the readme, the example BM_memcpy has this line

```c++
state.SetBytesProcessed(int64_t(state.iterations()) *
                        int64_t(state.range_x()));
```
The number of processed bytes should be multiplied by 2 as we have both reads from src and writes to dst. So, the correct number is:

```c++
state.SetBytesProcessed(int64_t(state.iterations()) *
                        int64_t(state.range_x()) * 2);
```

**Comment by dominichamon** [comment]
when you think about how much work memcpy is doing, the number of bytes being copied is the length passed in, which in this case is `state.range_x()`.

**Comment by dimztimz** [comment]
When we measure memory bandwidth, we should generally measure how much data flows through the wires so we can compare to the maximum theoretical bandwidth of the hardware.

The way I see it, if one uses asymptotic function (big O) for the work done, one should use ```SetItemsProcessed```. But for memory, we should be precise and count both the loads and the stores.
