### ISSUE TITLE
Benchmarking code that uses threads and UseRealTime

### ISSUE THREAD

**Issue by eliben** [google/benchmark#170]
I just ran into a gotcha with the library and wanted to share - IMHO this issue should be made more discoverable.

Say you implement some algorithm, and then have another implementation that uses multiple threads. Currently `Benchmark` will incorrectly measure the two against each other because it uses CPU time by default - to figure out how many iterations to run, and to report "items/second".

The solution is to set `UseRealTime`. I wonder if this should just be made more prominent in the documentation, or perhaps added as command line option - currently the default is CPU time unless `UseRealTime` is attached on a `Benchmark*`. A command-line flag can reverse this default and affect the whole program.

**Comment by dominichamon** [comment]
i prefer it to be per benchmark to cover your example: to get the CPU time for a baseline, and real time numbers for comparison. ie, you can register the same benchmark twice, once under each timing mode, and get everything you need.

documentation is a good point though. i'm surprised it's not in the readme already. i'll add something (unless you want to)!
