### ISSUE TITLE
[FR] Enforce CMake to find PFM or fail when `BENCHMARK_ENABLE_LIBPFM` is `ON`

### ISSUE THREAD

**Issue by romintomasetti** [google/benchmark#1702]
Currently, setting `BENCHMARK_ENABLE_LIBPFM` to `ON` only *tries* to find `PFM`, but I think it should *find it or fail* since the user wants it.

https://github.com/google/benchmark/blob/93a96a26a6ba36894d7fa6f43513708c595ccb5f/CMakeLists.txt#L314-L316

Does the `find_package` simply need the `REQUIRED` keyword?

**Comment by dmah42** [comment]
yeah, i think that would do it.  and it makes sense to me that if the user has requested it we should find it or fail.

**Comment by ananta** [comment]
@dmah42 added 😄
