### ISSUE TITLE
[FR] Large File Support

### ISSUE THREAD

**Issue by oToToT** [google/benchmark#1725]
**Is your feature request related to a problem? Please describe.**

Google benchmark looks to be using libc functions like `fseeko`, `ftello`, `fopen`. (IIUC, std::ifstream may results in using these functions.)
On some "small" platforms, it might result in EOVERFLOW when dealing with large files.

**Describe the solution you'd like**
Compiles with these three flags enabled:
  `-D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE`.

this is the portable/POSIX method for transparently using 64bit types everywhere.  for details on each define, see:
    # [http://www.gnu.org/s/libc/manual/html_node/Feature-Test-Macros.html](https://www.google.com/url?q=http://www.gnu.org/s/libc/manual/html_node/Feature-Test-Macros.html&sa=D&source=buganizer&usg=AOvVaw20qmkaHe9EbXx97C__k15p)
    # _LARGEFILE_SOURCE: enable support for new LFS funcs (ftello/etc...)
    # _LARGEFILE64_SOURCE: enable support for 64bit variants (off64_t/fseeko64/etc...)
    # _FILE_OFFSET_BITS: default to 64bit variants (off_t is defined as off64_t)

**Describe alternatives you've considered**

N/A

**Additional context**

https://issuetracker.google.com/issues/201531268

**Comment by oToToT** [comment]
(I can work on this.)

**Comment by dmah42** [comment]
have you seen this issue anywhere?  `ifstream` is only used in context of opening sysinfo files ("/proc/cpuinfo" and similar) none of which should be "large".  `ofstream` is used to write out files and i suppose these could become large for larger projects, but maybe not on smaller platforms (as they couldn't run such large projects, i suppose).

**Comment by oToToT** [comment]
Thanks @vapier for clearer information and sorry for my initial vague arguments.

IIUC, for 64-bit `time_t` support (to prevent [Y2K38](https://en.wikipedia.org/wiki/Year_2038_problem)), we only need to add `-D_TIME_BITS=64` to the compile flag if LFS is already there.
If we want to do so, I can adjust #1726 to include it (and rename it to "Enable Large-file Support + 64-bit `time_t`").

**Comment by vapier** [comment]
let's keep the two separate for now.  LFS has been around for a long time and should be easy enough.  64-bit time_t is a newer project and still semi-influx.
