### ISSUE TITLE
[FR] BENCHMARK_VERSION is not set by default

### ISSUE THREAD

**Issue by PhilipDeegan** [google/benchmark#1768]
**Is your feature request related to a problem? Please describe.**
Since a recent addition adding usage of "BENCHMARK_VERSION", this project is now coupled to the official build tools and is not compatible with anything else.

**Describe the solution you'd like**
Default macro variables so we can ignore if they're not set

**Describe alternatives you've considered**
Setting BENCHMARK_VERSION during compilation via `-DBENCHMARK_VERSION=version` doesn't work as the macro is not converted to a string, see below.

**Additional context**
In my experience, converting define inputs to strings is better done via a helper macro like

```
#define STRINGIFY(x) #x
#define TOSTRING(x) STRINGIFY(x)
```

such that inputs like -DBENCHMARK_VERSION=version

can be used like

```
std::string s{TOSTRING(BENCHMARK_VERSION)};
```

This IMO is simpler from a build perspective to not need any fancy escaping

see: https://coliru.stacked-crooked.com/a/ae9e4273382fe470

**Comment by LebedevRI** [comment]
I'm not sure i follow. I think there's some deeper context missing here.
Sure, we could sink wrapping `BENCHMARK_VERSION` into `"` (i.e. stringification)
down into the source code, but why?

**Comment by PhilipDeegan** [comment]
> but why?

to make it easier for anyone not using cmake or bazel to not care about the macro not being set

**Comment by dmah42** [comment]
if you're not using cmake or bazel, i think there's probably other issues that you're going to be working around.

but patches welcome, and doing this would probably clean up the awful BUILD.bazel escaping i had to do to make it work there.

**Comment by PhilipDeegan** [comment]
> i think there's probably other issues that you're going to be working around.

Everything was just fine for me until I updated to HEAD ;)

> but patches welcome

testing [something](https://github.com/PhilipDeegan/benchmark/pull/1/files) on my fork atm
