### ISSUE TITLE
[FR] Remove COMPILER_IBMXL macro for z/OS

### ISSUE THREAD

**Issue by fanbo-meng** [google/benchmark#1776]
**Is your feature request related to a problem? Please describe.**
COMPILER_IBMXL is no longer needed to distinguish compilers on z/OS.

**Describe the solution you'd like**
Remove the macro definition and usage.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by LebedevRI** [comment]
> **Is your feature request related to a problem? Please describe.**
> COMPILER_IBMXL is no longer needed to distinguish compilers on z/OS.

Why?

**Comment by fanbo-meng** [comment]
I added COMPILER_IBMXL to identify the Clang based IBM XL compiler (xlclang) on z/OS. This compiler is obsolete and replaced by the Open XL compiler, so the macro is no longer needed and the existing code would lead to incorrect asm syntax for Open XL. Please review https://github.com/google/benchmark/pull/1777

**Comment by LebedevRI** [comment]
That wording needs to be in the commit message of that PR

**Comment by fanbo-meng** [comment]
closed by https://github.com/google/benchmark/pull/1777
