### ISSUE TITLE
Google Benchmark seems to always be built in DEBUG mode

### ISSUE THREAD

**Issue by izaid** [google/benchmark#178]
I've got Google Benchmark setup as a third party submodule in my repository. This means I simple do `add_subdirectory(benchmarks)` and get Google Benchmark built alongside my library.

However, when I do this, I find I always get the message "***WARNING*** Library was built as DEBUG. Timings may be affected." What is the right way to turn this off? Is it a problem with how I'm doing things or an issue with Google Benchmark?

Looking at Google Benchmark, I see that warning depends on whether or not `NDEBUG` is defined. CMake actually defines NDEBUG in release mode, so this may be undesirable behaviour.

**Comment by dominichamon** [comment]
```cmake -DCMAKE_BUILD_TYPE=Release``` works for me to get rid of the warning. Could you try that and let me know?

**Comment by izaid** [comment]
Yeah, okay, this worked. My bad!

Sorry, closing the issue now.

**Comment by dominichamon** [comment]
added a section to README to cover this. hopefully :)

**Comment by ialokim** [comment]
I actually experience the same issue even when calling `cmake -DCMAKE_BUILD_TYPE=Release`. The warning message is only generated when building `benchmark` along the way using `add_subdirectory(benchmark)`, not when building it first and later linking it manually as described in the readme.

I tested running `cmake` without setting the build type and measurements were significantly higher. Therefore I suspect the library to be correctly built in release mode, but for some reason, the false warning is generated.

**Comment by dominichamon** [comment]
which version of benchmark are you using?

**Comment by ialokim** [comment]
This is building the `main` branch (commit 19026e232c15dfdfd2b4ad80c6766b5ab87e43d3).

**Comment by LebedevRI** [comment]
That means the parent project overrides compilation flags, and `-DNDEBUG` is not present.

**Comment by ialokim** [comment]
Oh wow, true, I'm still a cmake noob. Just explicitly added the flag in the parent project and no the warning is gone. Thank you both for the quick help!

**Comment by denniskb** [comment]
When I specify `-DNDEBUG` in the parent directory, google benchmark flatout refuses to build the `benchmark_main` target.

**Comment by abhishekmittal15** [comment]
Hi, I have the same project structure as OP, wherein I have the library as an external dependency(git submodule). 
I want to build my code in Debug mode, but still use the benchmark library in Release mode. I can prolly build the library separately, but its more convenient for me to build it using the same CMakeLists.txt file that I use to build my code. 
Hence setting the Build Type to a single value is not a solution for me.
Can anyone suggest some ideas? Apologies if this is something trivial, new to Cmake

My current CmakeLists.txt looks as follows

```cmake
cmake_minimum_required(VERSION 3.31)

project(ak27_core LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 14)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

include_directories(include)

enable_testing()
add_subdirectory(src/core) # My lib's source files
add_subdirectory(tests/core) # My lib's test files
add_subdirectory(benchmarks/core) # My lib's benchmarks files
add_subdirectory(extern/googletest) # External Dep
add_subdirectory(extern/googlebenchmark) # External Dep
```

**Comment by dmah42** [comment]
i believe if you use ExternalProject_Add then you can set the build type for that project.

**Comment by abhishekmittal15** [comment]
@dmah42 thanks slot, I was able to make your suggestion work!!
