### ISSUE TITLE
[FR] Please release benchmark 1.8.4

### ISSUE THREAD

**Issue by Pospelove** [google/benchmark#1787]
Dear benchmark maintainers, could you please release 1.8.4 so vcpkg could update its benchmark port without updating to a non-version revision?

This will help landing important fixes such as MinGW build fix. Which is appeared as a vcpkg issue recently.

https://github.com/microsoft/vcpkg/issues/38867

**Comment by dmah42** [comment]
i'll try to get to this this week if i can.

**Comment by LebedevRI** [comment]
Yup, it's time for a release :)

**Comment by dmah42** [comment]
in progress

**Comment by dmah42** [comment]
done
