### ISSUE TITLE
`state.PauseTiming()` and state.ResumeTiming() take a long time

### ISSUE THREAD

**Issue by izaid** [google/benchmark#179]
I'm trying to benchmark a custom map type. I basically want to see how long it takes to look up random keys.

To do so, I'm generating random keys in the `state.KeepRunning()` loop. I obviously don't want the random key generation to be added to the overall time of the benchmark. To prevent this, I tried to use `state.PauseTiming()` and `state.ResumeTiming()`, but I found using those functions added 100s of nanoseconds to my benchmark -- which is much more than the map lookup itself.

Is this a problem with these functions? Or should I be generating my keys a different way?

**Comment by dominichamon** [comment]
This might be a good use for fixtures. You can generate your keys in SetUp and store them in the fixture object as state.

see test/fixture_test.cc for an example.

**Comment by izaid** [comment]
Thanks for the suggestion! I switched to fixtures here.

I guess I need to also modify the normal `state.KeepRunning()` loop to terminate when I run out of keys. I can add a simple check to see if there are no more keys, but what's the right way to signal to state to stop the benchmark?

**Comment by dominichamon** [comment]
does your benchmark do one lookup per 'keep running' iteration? do you want to look up every key?

one thing that comes to mind is that if we passed the state to 'SetUp' you could generate a number of keys based on state::range_x() and then loop through them in the keeprunning loop (like BM_SetInsert in the benchmark_test.cc file). Then you just need to set the number of processed items to state::iterations() * state::range_x(). 

Alternatively, you could pick a random key from your set of keys every time through the loop, but you might get more variation between benchmark runs.

**Comment by izaid** [comment]
One lookup per 'keep running' iteration. I really just want to benchmark the lookup cost, and this seems like the right way to do it. But, if it's not, let me know.

Your example with the SetUp seems reasonable to me. That's what I'm attempting to do now. I've got this working as per the set example. I guess it's slightly annoying that I have to divide the benchmark time by the number of lookups to get the actual cost per lookup, but I can live with that. Is it possible to get access to state::range_x() in the benchmark fixture? (e.g., how should I tell my fixture the size of the random set it should generate?)

**Comment by pleroy** [comment]
I seem to remember that `state.PauseTiming()` and `state.ResumeTiming()` are expensive because they call `CHECK` and `CHECK` is expensive.  It does:
```
# define CHECK(b) ::benchmark::internal::GetNullLogInstance()
```
But it should really do:
```
# define CHECK(b) while (false) ::benchmark::internal::GetNullLogInstance()
```

**Comment by izaid** [comment]
Even if I comment out all the CHECK(...) I can find, it still seems PauseTiming() and ResumeTiming() takes in the 100s of nanoseconds.

**Comment by dominichamon** [comment]
I did some testing (see #181) which required passing a const version of the state to `SetUp`. I'm ok with this change, by the way.

It's clear from the results that there is a significant impact for small maps. So much so that I'm thinking of deprecating `PauseTiming` and `ResumeTiming` now we have the fixtures. I think they cover every use-case for pausing the timer. At least the ones I expected.

Is my test similar to what you had in mind?

**Comment by dominichamon** [comment]
@pleroy I think the cost is likely in the mutex and barrier to handle multiple threads pausing/resuming. Though yes, the CHECK doesn't help.

**Comment by izaid** [comment]
@dominichamon Thanks, your map test is exactly what I have in mind. Would love to see that merged.

As you also found out, `PauseTiming` and `ResumeTiming` basically drown out the map lookup. The fixture is a totally acceptable solution here, so I'd agree we should probably `PauseTiming` and `ResumeTiming` -- I can't imagine they will ever be fast enough to be negligible.

Here's another idea that may be worth considering: What about if we allow the user to specify the number of iterations in state. That way, in something like `BM_MapLookup`, we will have N iterations that correspond to N lookups from the random key set prepared in the fixture. The advantage of this is that the time reported will be exactly the map lookup time, not the total time for N map lookups.

**Comment by dominichamon** [comment]
Merged. I think we'll remove `PauseTiming` and `RemoveTiming`.

Regarding the iterations -- there's an old version that allowed number of iterations to be specified but trying to create an API that supports time-based and iteration-based constraints is complicated. Given they're benchmarks, in general we're interested in doing as many iterations as possible to get good statistics. As such, setting time-based constraints is a more reasonable API.

I understand your specific requirement, but I hope that you can get the results you need with the existing set up.

**Comment by vdidenko** [comment]
Given that the #183 PR was dropped, any ideas on how to deal with the Pause/Resume issues? I think there are couple more illustrations of the issue at the discussion group: https://groups.google.com/forum/#!topic/benchmark-discuss/o5BvqFZIs3Y

**Comment by EricWF** [comment]
I haven't looked into this in depth, but you can do the initialization you need before entering the "keepRunning" loop.

IMO If you need to pause a benchmark in the middle you should try to redesign your benchmark.

**Comment by didenko** [comment]
(reposting under the  proper account, sorry for the confusion)

Given that the #183 PR was dropped, any ideas on how to deal with the Pause/Resume issues? I think there are couple more illustrations of the issue at the discussion group: https://groups.google.com/forum/#!topic/benchmark-discuss/o5BvqFZIs3Y

**Comment by EricWF** [comment]
To clarify the timer isn't actually running until the first iteration of the "keepRunning()" loop. So, like fixtures, your free to initialize whatever you need before starting the loop.

**Comment by didenko** [comment]
@EricWF so the idea is to that after the first call to `state.KeepRunning()` the timer is ON and there is no per-iteration grunt work advised, because it will be included in the time measurement? E.g. in this:

https://github.com/google/benchmark/commit/53068f9#diff-bbda13de265011c415b5604c6db76408R50

The `rand() % size` calc cannot be moved to the top of the iteration outside of the measurement?

**Comment by EricWF** [comment]
Precisely. In that case I would initialize a vector of values using `rand() % size` outside of loop. Unfortunately It's not always optimal or possible to do this.

**Comment by didenko** [comment]
@EricWF Ok, we are on the same page, including the "not always..." part.

Thank you!

**Comment by EricWF** [comment]
Glad to hear :-) 

I think the `startRunning()`/`stopRunning()` discussion is misguided. We could try to make them faster, but they are really meant as a last resort. The quality of a *micro* benchmark will always be greatly affected by executing *any* non-benchmarked code while timing.

Unfortunately `startRunning()` and `stopRunning()` are particularly expensive operations. I don't think we can do anything about that.

**Comment by dominichamon** [comment]
I'm not sure there's much we can do here. I'm happy to have the conversation on record but I'm going to close the issue.
