### ISSUE TITLE
[BUG] Compilation failed for using operator [] for unordered_map

### ISSUE THREAD

**Issue by apachaihop** [google/benchmark#1808]
**Describe the bug**
Compilation failed for using operator [] for unordered_map with clang 17 + stdlibc++  14
 
**System**
Which OS, compiler, and compiler version are you using:
  - OS: Arch
  - Compiler and version: clang 17.0.6

**To reproduce**
https://godbolt.org/z/1sz1hdEsh

**Expected behavior**
Inserting element at unordered_map without CE

**Additional context**
https://github.com/google/benchmark/blob/c2146397ac69e6589a50f6b4fc6a7355669caed5/include/benchmark/benchmark.h#L864C2-L868C4 change here and  https://github.com/google/benchmark/blob/c2146397ac69e6589a50f6b4fc6a7355669caed5/include/benchmark/benchmark.h#L896C3-L900C4 here to insert method with std::make_pair to better cross compilation possibilities and fixing CE

**Comment by LebedevRI** [comment]
Seems to work with clang-18? Looks like a pretty typical "version mismatch" pains
of too new libstdc++ vs clang. It's quite unfortunate, but i doubt it's benchmark-specific.
