### ISSUE TITLE
Trusted publishing should be set up for PyPI 

### ISSUE THREAD

**Issue by nicholasjng** [google/benchmark#1816]
After v1.8.5's release just now, wheels built fine but were not uploaded due to a failure in trusted publishing: https://github.com/google/benchmark/actions/runs/9989674343

To allow subsequent wheel releases for GBM, this needs to be set up in the PyPI organization, or reverted to use token-based authentication again instead of trusted publishing. I don't know what is preferred on your side, but since it concerns the Python bindings, I wanted to offer my help.

**Comment by dmah42** [comment]
i was just about to look into this with hesitation as i don't know much about python wheel publishing.  i have a PyPI account (benchmark-py) but the email address is unverified so i can't do anything with it.  i've filed an issue to recover it.

in the  meantime maybe we need to go back to token-based.

**Comment by nicholasjng** [comment]
This here pretty much covers it: https://docs.pypi.org/trusted-publishers/adding-a-publisher/

I've witnessed one such trusted publishing installation myself, and it did not look too difficult. Once you regain access to the benchmark-py account, running those steps should be all that's needed.

**Comment by dmah42** [comment]
![image](https://github.com/user-attachments/assets/364602f3-b6ee-419d-8716-393d375d9a06)

done
