### ISSUE TITLE
Multithreaded benchmarks question on iteration count.

### ISSUE THREAD

**Issue by mfranzreb** [google/benchmark#1828]
As [this issue](https://github.com/google/benchmark/issues/345) explains, in a multi-threaded benchmark, the threads are synchronized before starting the loop, and after exiting, but not during the iterations. In the following example, the results show that `t_1 == t_2`. How does this then work? My thought is that the number of iterations is set before the loop starts, is this correct? Is there a built-in functionality to have all threads stop once the first is finished? Thank you for the help!

```
// 2 threads
for (auto _ : state) {
    if (state.thread_index() == 0) {
      std::this_thread::sleep_for(std::chrono::milliseconds(10));
      ++t_1;
    } else {
      std::this_thread::sleep_for(std::chrono::milliseconds(100));
      ++t_2;
    }
  }
```

**Comment by dmah42** [comment]
i'm not sure what your expectations are here.  by the end of the run, each thread would have been run the same number of iterations because the iterations are set at the outer loop level.

**Comment by mfranzreb** [comment]
Hi, thank you for the reply! Just wanted to know if there was a built-in way to have all threads stop executing once the first thread is done. The question is settled now though.
