### ISSUE TITLE
[BUG] Warning 'misc-use-anonymous-namespace' should be disabled within `BENCHMARK` macro

### ISSUE THREAD

**Issue by codeinred** [google/benchmark#1860]
**Describe the bug**

Use of the `BENCHMARK` macro results in a clang-tidy warning, because the macro expands to a global variable declared with `static`.

```cpp
bench.cpp:88:1: warning: variable 'benchmark_uniq_5_benchmark_' declared 'static', move to anonymous namespace instead [misc-use-anonymous-namespace]
   88 | BENCHMARK( myFunc );
```

**To reproduce**
Run clang-tidy on any file containing `BENCHMARK` macro, with the `misc-use-anonymous-namespace` check enabled

**Expected behavior**
No warning is emitted (warning should be suppressed)

**Screenshots**
![Image](https://github.com/user-attachments/assets/b6b843a4-9384-4e87-b659-9f36d3af7fa1)

**Additional context:**

This can be fixed by adding `NOLINTNEXTLINE(misc-use-anonymous-namespace)` within the macro declaration. Adding this silences the warning, only for `BENCHMARK` statement itself.

```cpp
#define BENCHMARK_PRIVATE_DECLARE(n)                                 \
  /* NOLINTNEXTLINE(misc-use-anonymous-namespace) */                 \
  static ::benchmark::internal::Benchmark* BENCHMARK_PRIVATE_NAME(n) \
      BENCHMARK_UNUSED
```

**Comment by LebedevRI** [comment]
This was fixed by https://github.com/google/benchmark/pull/1861 but that PR/commit lacked "Fixes:".
