### ISSUE TITLE
package for CMake

### ISSUE THREAD

**Issue by miguelmartin75** [google/benchmark#188]
Is there a package for CMake? So I can do something like:

```
find_package(GoogleBenchmark REQUIRED)
if(GoogleBenchmark_FOUND)
  include_directories(${GoogleBenchmark_INCLUDE_DIR})
  target_link_libraries(${PROJECT_NAME} ${GoogleBenchmark_INCLUDE_DIR})
endif()
```

To easily integrate it into my project.

**Comment by amin-jabri** [comment]
Hi! You could  use your own cmake find module. A basic starter:

```cmake
# Findbenchmark.cmake
# - Try to find benchmark
#
# The following variables are optionally searched for defaults
#  benchmark_ROOT_DIR:  Base directory where all benchmark components are found
#
# Once done this will define
#  benchmark_FOUND - System has benchmark
#  benchmark_INCLUDE_DIRS - The benchmark include directories
#  benchmark_LIBRARIES - The libraries needed to use benchmark

set(benchmark_ROOT_DIR "" CACHE PATH "Folder containing benchmark")

find_path(benchmark_INCLUDE_DIR "benchmark/benchmark.h"
  PATHS ${benchmark_ROOT_DIR}
  PATH_SUFFIXES include
  NO_DEFAULT_PATH)
find_path(benchmark_INCLUDE_DIR "benchmark/benchmark.h")

find_library(benchmark_LIBRARY NAMES "benchmark"
  PATHS ${benchmark_ROOT_DIR}
  PATH_SUFFIXES lib lib64
  NO_DEFAULT_PATH)
find_library(benchmark_LIBRARY NAMES "benchmark")

include(FindPackageHandleStandardArgs)
# handle the QUIETLY and REQUIRED arguments and set benchmark_FOUND to TRUE
# if all listed variables are TRUE
find_package_handle_standard_args(benchmark FOUND_VAR benchmark_FOUND
  REQUIRED_VARS benchmark_LIBRARY
  benchmark_INCLUDE_DIR)

if(benchmark_FOUND)
  set(benchmark_LIBRARIES ${benchmark_LIBRARY})
  set(benchmark_INCLUDE_DIRS ${benchmark_INCLUDE_DIR})
endif()

mark_as_advanced(benchmark_INCLUDE_DIR benchmark_LIBRARY)
```

**Comment by AustinDeric** [comment]
I would also like to see this repo work with cmake's find_package function:
https://cmake.org/cmake/help/v3.0/command/find_package.html

This way we can reference this package in other cmake packages.  If this is something y'all are interested in, i can submit a PR for it. I can do something similar to this:
https://cmake.org/Wiki/CMake/Tutorials/How_to_create_a_ProjectConfig.cmake_file

Thanks and great work!

**Comment by dominichamon** [comment]
I would really like to see this happen too! I know enough about cmake to be
dangerous so a PR would be delightful.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by AustinDeric** [comment]
This is our initial implementation of the find_package() feature for google/benchmark:
https://github.com/AustinDeric/benchmark/tree/feature/cmake-find

currently we can successfully perform find_package(benchmark REQUIRED) in our ubuntu cmake project.

it needs:
- implementation version so we can find_package(benchmark 1.1.0 REQUIRED)
- more testing!

**Comment by EricWF** [comment]
This should work, as of April 3rd, using `find_package(benchmark)` after adding the installation prefix to CMAKE_PREFIX_PATH (if it's not something like /usr/local).

Please re-open this if the problem still persists.

**Comment by ssbanerje** [comment]
I can create a pull request to auto generate the package configuration files
```
benchmarkConfig.cmake
benchmarkTargets.cmake
benchmarkVersion.cmake
```

That way CMake can use the `CONFIG` flag in the find packages, something like this:
```
find_package(benchmark CONFIG REQUIRED)
```

I think this is significantly better than having to write the `Findbenchmark.cmake` file manually. This might require a bump in the minimum CMake version required to 3+. Is that something you are interested in?

**Comment by bryan-lunt** [comment]
@amin-jabri Can you add a license header to the google benchmark finder that you wrote?
Thanks.
