### ISSUE TITLE
Could not delete file 'C:\Users\Administrator\AppData\Local\Temp\ort-DefaultWorkingTreeCache8817070010412163686\.svn\wc.db

### ISSUE THREAD

**Issue by lhl527** [google/benchmark#1888]
Sometimes this problem arises with Could not delete file 'C:\Users\Administrator\AppData\Local\Temp\ort-DefaultWorkingTreeCache8817070010412163686\.svn\wc.db, sometimes there is a problem with “Checkout failure for https://github.com/google/benchmark.git. Sometimes the download fails, causing the process to not move to the benchmark folder."”**"I encounter this issue with both ORT 30 and ORT 31." My jdk is 11 and gradle is 6.1.1 .

**Comment by lhl527** [comment]
![Image](https://github.com/user-attachments/assets/d73b9c4f-2a5d-4f85-be57-da11bedbae46)

**Comment by dmah42** [comment]
i'm not sure what the issue is here, but i don't see anything about benchmark in the screenshot, nor do we have any java/kotlin in our codebase.  i suspect your issue is outside of this library.
