### ISSUE TITLE
Access to significant figures in benchmark timings?

### ISSUE THREAD

**Issue by izaid** [google/benchmark#189]
Google Benchmark, while very useful, does seem to only provide timings in nanoseconds in the report. If I have a very tight function, which takes on the order of 2 nanoseconds, is it possible to get any of the significant figures here?

**Comment by EricWF** [comment]
No? I nanosecond is a pretty tiny amount of time. If you have a function that benchmarks at 2 nanoseconds it's likely the compiler optimized away your benchmark all together. 

2 nanoseconds is like enough time to run 6 CPU instructions at most if I'm not mistaken.

**Comment by dominichamon** [comment]
I don't think any of the methods we use for timing will get more precision. I doubt we get out of the way enough to allow 2ns to be a reasonable measure.

Can you force your benchmark to do the work N times per run and then divide the time measured by N?

**Comment by EricWF** [comment]
I did some tests and I'm 100% sure your benchmark is getting optimized away.

I tested an empty benchmark and a benchmark that only contained ```volatile int x = 42```. The benchmarks ran in 1ns and 3ns respectively.

**Comment by EricWF** [comment]
@izaid I'm going to go ahead and close this issue based on what I think is happening. Do not hesitate to re-open it if you disagree. Sometimes I'm spectacularly wrong :-)

**Comment by izaid** [comment]
@EricWF Thanks, all of the suggestions here were good -- we can simply run N times the benchmark. I appreciate the feedback, you're right that I wasn't quite looking for the right thing.
