### ISSUE TITLE
Iteration control not adequately explained

### ISSUE THREAD

**Issue by OwenArnold** [google/benchmark#194]
To understand how the Iterations worked, I had to dig through the source code. If you had a simple paragraph about the #iteration and how they link to the overall timings on the readme, it would have saved the hassle.

**Comment by dominichamon** [comment]
@OwenArnold can you take a look at the pull request to see if it is satisfactory?

**Comment by OwenArnold** [comment]
@dominichamon Thanks. I think this'll do the trick.
