### ISSUE TITLE
Support for benchmarking externally timed events, such as GPU code

### ISSUE THREAD

**Issue by jknuuttila** [google/benchmark#198]
Hello!

I would be interested to use Google Benchmark to benchmark GPU shaders (e.g. Direct3D or Vulkan draw calls or compute dispatches). Google Benchmark seems to provide a lot of extremely useful functionality that I would not want to roll on my own, such as definition of benchmarks, benchmarking with different arguments, handling iteration counts for statistical robustness, etc.

GPU shader executions are measured using timestamp queries, for which the results are provided asynchronously. The CPU side code sets up the shaders along with the timestamp queries, waits until the GPU is done, and then reads the timestamp results after. The CPU time spent doing all this can significantly overestimate the actual duration of interest (it is at least as much as the actual GPU execution, plus many forms of various overhead), and is usually of no interest. As such, Google Benchmark's default way of measuring time is not useful.

What I would require is a way for benchmark iterations to manually override the timing and be able to tell Google Benchmark that "this benchmark iteration took exactly 3.141 ms", regardless of how much CPU time was actually spent. A hypothetical API for this could look like the following:

``` c++
static void BM_GPUBenchmark(benchmark::State& state) {
  // Disable default time measurement
  state.ManualTiming();
  while (state.KeepRunning()) {
    // Run the actual benchmarked code, wait until it's done,
    // and measure the time spent.
    double seconds = ExecuteAndMeasureShader(state.range_x());
    // Report the actual time spent to Google Benchmark.
    state.SetIterationTiming(seconds);
  }
}
BENCHMARK(BM_GPUBenchmark)
    ->Arg(1)
    ->Arg(2)
    ->Arg(4)
    ->Arg(8);
```

Other possible uses for this could include e.g. benchmarking network latency or throughput using Google Benchmark.

It looks like one possible way to implement this could be to add a new `double manual_time_used_` member variable to `TimerManager`, add a flag to `State` or `TimerManager` to note when manual time is enabled, and then change `RunBenchmark` accordingly to use the `manual_time_used_` as the value of `seconds` when the manual timing mode is set.

If I was to implement this feature, would you be interested in accepting the pull request? If so, I would appreciate feedback on the proposed API.

Regards,
Jussi

**Comment by romanlarionov** [comment]
I second this. It would be cool if I could test compute kernels for either OpenCL or CUDA with this.

**Comment by dominichamon** [comment]
It's a very interesting use-case.. short-term, you could just use `state.SetLabel` to set the total time spent on the GPU, or divide it yourself outside the `KeepRunning` loop to get the mean. something like:

```c++
static void BM_GPU(benchmark::State& state) {
  double mean = 0.0
  while (state.KeepRunning()) {
    mean += ExecuteAndMeasureShader(state.range_x());
  }
  state.SetLabel("mean time: " + std::to_string(mean/stat.iterations()));
}
 ```

This should work without any changes, though it doesn't get you access to the stats breakdown of course.

Why do you want to disable the manual timing? A call to `SetIterationTime` could just override whatever the automated timing would return. It also might allow to supplement it, so in the case of something that uses both CPU and GPU, you would get both times.

**Comment by jknuuttila** [comment]
I suppose there is no need to disable the default timing measurement as such, it's just that replacing  the value of `seconds` in `RunBenchmark` with the manual time seems to be the easiest way to integrate properly with the bytes/items processed functionality and the iteration count functionality, which are both useful for GPU workloads. Otherwise, some of that code would need to be duplicated or made more complicated somehow.

**Comment by jknuuttila** [comment]
I have created a pull request that implements this feature at https://github.com/google/benchmark/pull/199

Usage currently looks like this
```c++
static void BM_ManualTiming(benchmark::State& state) {
  int microseconds = state.range_x();
  std::chrono::duration<double, std::micro> sleep_duration {
    static_cast<double>(microseconds)
  };

  while (state.KeepRunning()) {
    auto start = std::chrono::high_resolution_clock::now();
    // Simulate some useful workload with a sleep
    std::this_thread::sleep_for(sleep_duration);
    auto end   = std::chrono::high_resolution_clock::now();

    auto elapsed_seconds =
      std::chrono::duration_cast<std::chrono::duration<double>>(
        end - start);

    state.SetIterationTime(elapsed_seconds.count());
  }
}
BENCHMARK(BM_ManualTiming)->Range(1, 1<<17)->UseManualTime();
```

**Comment by WilliamTambellini** [comment]
Hi all, I m also interested by such feature specially for GPU computation with ArrayFire.

**Comment by EricWF** [comment]
@WilliamTambellini: @jknuuttila's changes to add `UseManualTime` have landed. It should help you address your problem.

Please re-open if it does not.
