### ISSUE TITLE
Benchmark report lines have superfluous whitespace appended to the end

### ISSUE THREAD

**Issue by StephanDollberg** [google/benchmark#200]
Each line in the benchmark results has superfluous whitespace appended to it. It's kinda annoying as it forces line breaks on smaller terminal windows.

I think the whitespace originates from [this call](https://github.com/google/benchmark/blob/master/src/console_reporter.cc#L110). Not sure what it's supposed to do, though.

**Comment by dominichamon** [comment]
that call should probably be conditional on the lengths of `rate`, `items`, and `report_label` so it only prints them if they exist.

**Comment by StephanDollberg** [comment]
Yep, makes sense. 

What are those attributes actually used for?

**Comment by dominichamon** [comment]
if benchmarks call the `SetBytesProcessed` or `SetItemsProcessed` the benchmark will report that alongside the timing. There's an example at https://github.com/google/benchmark/blob/master/test/benchmark_test.cc#L84

`SetLabel` is useful for appending arbitrary information. Maybe the output of a test: https://github.com/google/benchmark/blob/master/test/benchmark_test.cc#L64

**Comment by StephanDollberg** [comment]
Ah, that's cool. Didn't know about them.

**Comment by StephanDollberg** [comment]
Awesome thanks, that was quick.
