### ISSUE TITLE
warn/error on PauseTiming and ResumeTiming outside the timing loop

### ISSUE THREAD

**Issue by dominichamon** [google/benchmark#204]
there are a number of places that we mark, in comments, a requirement for a function call. we should enforce these with errors if they occur.

**Comment by EricWF** [comment]
Any preference on how we should enforce these? My suggestion would be printf and abort.

**Comment by dominichamon** [comment]
`CHECK` should do it

**Comment by EricWF** [comment]
Right, it's been a long time since I worked on the code :-(. I'll put a patch together.
