### ISSUE TITLE
Allow a way to abort a particular benchmark due to setup/running failure

### ISSUE THREAD

**Issue by CCob** [google/benchmark#206]
When external influences (file I/O, network error, etc..) that can fail during the benchmark there should be a way to abort the benchmark with an error/no results state.

**Comment by dominichamon** [comment]
I can imagine calling some method on `state` when the error occurs.

would you want the single iteration to be dropped from the results with a warning, or would you expect the entire benchmark to be dropped?

**Comment by CCob** [comment]
Hmm, good question.  My preference would be the entire benchmark but I can think of use cases for an iteration to be dropped too.

**Comment by dominichamon** [comment]
i think this is a really good idea. it should be easy to add something to the run such that the reporters can handle errors appropriately. having it per-iteration is probably best, though it will be spammy in a critical situation (network down). i think this is ok.

**Comment by CCob** [comment]
I think having two functions within ```state``` would be beneficial,  

```void AbortBenchmark(const char* reason);```
```void IgnoreIteration();```

One can be used for terminal errors and abort the benchmark the other can be used for ignoring that particular iteration.

**Comment by EricWF** [comment]
I don't think `AbortBenchmark(...)` could actually "abort" cause the benchmark to leave scope (without throwing an exception). The user would still have to manually return. I imagine an interface like:

```c++
void BM_foo(benchmark::State& state) {
  while (state.KeepRunning()) {
     if (error_condition) {
        state.SetError("foo error");
       return; // This is required
    } else {
       return; // Return without SetError would be an error, and would have to be diagnosed.
    }
  }
}

`SetError(...)` could also ensure that `KeepRunning()` returns false for the next iteration, but as mentioned that's not the same as directly leaving scope.

I'm not sure how to handle multi-threaded benchmarks though :-(. If one thread reports an error the rest of the threads would still continue as if nothing happened. Is this behavior acceptable?

**Comment by dominichamon** [comment]
Perhaps just 'ignore iteration' is the best option as in critical failure cases it will run no iterations. we could potentially have a test if we ran 0 iterations? or annotate the run as containing an error?

**Comment by EricWF** [comment]
So `IgnoreIteration()` would not run any iterations? I assumed it wanted to throw away a single iteration of the `KeepRunning()` loop, which is simply not possible to implement.

**Comment by dominichamon** [comment]
`IgnoreIteration()` would skip the current iteration (which is actually just a return.. but it could append an error somewhere.

If every iteration has an error, then we end up skipping all iterations. We may want to append some error information to the report somewhere.

**Comment by EricWF** [comment]
I submitted pull request #217 which adds a "State::SkipWithError(const char*)" which will skip the benchmark and report it as an error.

**Comment by CCob** [comment]
Excellent, look forward to testing this out.  Thanks both

**Comment by EricWF** [comment]
pull request #217 has been merged. Closing this issue.
