### ISSUE TITLE
AppVeyor build chronically broken

### ISSUE THREAD

**Issue by BillyONeal** [google/benchmark#223]
Is VS "supported" at this time? Do versions other than the latest matter? (I say this because several build failures I've seen (like the <chrono> bug I fixed in [PR 209](https://github.com/google/benchmark/pull/209)) are fixed in current versions of VS)

**Comment by dominichamon** [comment]
i've been unable to persuade appveyor to run consistently, which makes it hard to support windows. also, myself and @EricWF have limited access to windows machines.

I'd say it's supported at a best effort level. I accept all patches to improve/fix VS support (and specifically MSVC) but i can't generate them.
