### ISSUE TITLE
Undefined log2

### ISSUE THREAD

**Issue by Bleizo** [google/benchmark#235]
In the file test/complexity_test.cc, log2 is undefined in newer compilers (gcc 6.1.1 and clang 3.8.0). A simple fix is to include <cmath> at the top of the file then it compiles just fine. I suspect that it was being dragged in by other standard library headers in the past but not anymore.

**Comment by ismaelJimenez** [comment]
I just launched a pull request "fix issue #235" that shall fix this issue. Could you please check it? I compiled against gcc 6.1.1 but I could not reproduce the problem, I suppose it might also depend on other configurations.

**Comment by Bleizo** [comment]
Your pull request compiles like a charm with both gcc 6.1.1 and clang 3.8.0 on my end.
