### ISSUE TITLE
How to terminate test on error in fixture SetUp?

### ISSUE THREAD

**Issue by rychale** [google/benchmark#239]
Hi,

Is there any way to call State::SkipWithError in a fixture's SetUp? At the moment it is const.

Or may be there is another way of reporting error inside of SetUp?

Thanks,
Alexey

**Comment by dominichamon** [comment]
SkipWithError is relatively new and we didn't think about applying it to fixtures. I'm a little concerned with making the State mutable during fixture creation. The other alternative is to return a boolean, but that puts boilerplate on everyone using fixtures.

What sorts of errors are you seeing at fixture creation that aren't catastrophic?

**Comment by rychale** [comment]
I think I'm missing something. I want to terminate all tests (with some custom message) because of missing file, for example. What is the right way to do that?

**Comment by dominichamon** [comment]
you can use SkipWithError within the test itself, or you can just assert(..) in the fixture's SetUp. That's what I mean by catastrophic: if the fixture SetUp can't complete, there's no point in running any of the benchmarks, right?
