### ISSUE TITLE
support for additional counters (eg HW counters via PAPI)

### ISSUE THREAD

**Issue by biojppm** [google/benchmark#240]
Hi all,

First of all, thanks for making this library available.

I'm interested in adding additional counters. Time/manual time would still be the main counter, but additionally, I would like to see more counters such as cache or branch prediction misses (in some cases) and shader performance parameters (in other cases). If using PAPI, for example, the results would be something like this:

```
Benchmark              Time(ns)  CPU(ns) Iterations  PAPI_L1_DCM  PAPI_L2_DCM  PAPI_L3_TCM
------------------------------------------------------------------------------------------
BM_SetInsert/1024/1       28928    29349      23853            2            0            0
BM_SetInsert/1024/8       32065    32913      21375            4            2            1
BM_SetInsert/1024/10      33157    33648      21431           30           26           10
```

Above, I've put only cache miss counters. There are more varieties of counters, and not all are interesting to each microbenchmark. So ideally, the actual counters to use would be specifiable in a per-benchmark basis. If that would be too disruptive, then specifying them per-fixture or even per-session (ie once per executable) would also work.

I'm using PAPI here as a common example; this would be a client dependency and the client would be responsible for getting those counters and reporting them to googlebenchmark.

So in essence, this boils down to adding (string) named counters and getting the printers to show them. On the client side I am thinking of doing something like

```
static void BM_SetInsert(benchmark::State& state) {
  while (state.KeepRunning()) {
    //...
  }

  // get counter values
  double cL1, cL2, cL3;
  // ... call PAPI functions
  // report additional counters
  state.AddCounter("PAPI_L1_DCM", cL1);
  state.AddCounter("PAPI_L2_DCM", cL2);
  state.AddCounter("PAPI_L3_TCM", cL3);
}
```
Using c++11 initializer lists, the three AddCounter() calls could be reduced to:
```
  state.AddCounters({{"PAPI_L1_DCM", cL1}, {"PAPI_L2_DCM", cL2}, {"PAPI_L3_TCM", cL3}});
```
I've put double as the type of the counter as it is general enough to accomodate both integer and float-type counters. Also I'm using strings above but if this is too slow, then the client could pre-define the names in a fixture (while getting an integer handle for the name) and offer also an interface working strictly with those integer handles.

So, is this something you're interested in? Would it be too disruptive?

Thanks,
João

**Comment by dominichamon** [comment]
it sounds like this might be a generalisation of the manual timing feature (https://github.com/google/benchmark#manual-timing) .. is that accurate?

If all you want is a double counter with a name,  that should be straight-forward enough and flexible enough for many uses. I assume you'd also plumb it through to the mean/stddev calculations for multiple runs.

Please also think about how these would be reported by each of the different (and custom) reporters.

It sounds good though.. I look forward to seeing a patch.

**Comment by biojppm** [comment]
Well, time or manualtime would still be the main counter just as before. Nothing would change in that regard. The idea is adding *more* counters to each benchmark, with user-defined names.

I'm putting up a patch for this. There is one question I'd like to raise. Forgive me for some context first. 

I've started by creating a UserCounters class (abbreviated):
```
class UserCounters {
public:

  typedef std::vector< std::pair<char[28], float> > container_type;
  typedef container_type::value_type::first_type    name_type;
  typedef container_type::const_iterator            const_iterator;

public:

  UserCounters(size_t initial_capacity = 24);

  size_t Add(const char *name);
  void   Set(size_t id, float value);
  void   Set(const char *name,  float value);

  const_iterator cbegin() const { return counters_.begin(); }
  const_iterator cend  () const { return counters_.end(); }

private:

  container_type counters_;

};
```
I went down with float for the storage, in order to allow for bigger names, which are put right next to the counter (ie, no char* or even less std::string, just a plain char[] to set the name). I am doing this to allow fast lookup/insertion when names are given, as some counters may need to be set in the hot loop. There's also the size_t based lookup of course, but that requires you to add the name to get the handle ahead of the benchmark.

Next I've added to State a UserCounters member and some inline getter/setters. So the usage on the client side is 
```
static void BM_UserCounter(benchmark::State& state) {
  static const int depth = 1024;
  while (state.KeepRunning()) {
    benchmark::DoNotOptimize(CalculatePi(depth));
  }
  state.SetCounter("Foo", 1);
  state.SetCounter("Bar", 2);
  state.SetCounter("Baz", 3);
}
```
To give some context, what is currently shown by the reporter is
```
Benchmark                     Time       CPU Iterations
----------------------------------- -------------------
BM_UserCounter/threads:8   3271 ns  10492 ns      51848
BM_UserCounter/threads:1  10310 ns  10343 ns      70000
```
And I would like the reporter to show this instead:
```
Benchmark                     Time       CPU Iterations   Foo  Bar  Baz
----------------------------------- -----------------------------------
BM_UserCounter/threads:8   3271 ns  10492 ns      51848     1    2    3
BM_UserCounter/threads:1  10310 ns  10343 ns      70000     1    2    3
```
Now I want to relay the counters stored in State to the BenchmarkReporter::Run object such that the Reporter has access to them. But the problem is that these two objects never coexist. Currently, State exists only in the function RunInThread() in benchmark.cc:
```
void RunInThread(const benchmark::internal::Benchmark::Instance* b,
                 size_t iters, int thread_id,
                 ThreadStats* total) EXCLUDES(GetBenchmarkLock()) {
  State st(iters, b->has_arg1, b->arg1, b->has_arg2, b->arg2, thread_id, b->threads);
  b->benchmark->Run(st);
  //... function continues
  // st gets destroyed here
}

void RunBenchmark(...) {
  //...
  RunInThread(&b, iters, 0, &total);
}
```
Since RunInThread() is called by RunBenchmark() which is where the BenchmarkReporter::Run report only ever exists, I'm thinking I could change RunInThread() to receive a State object:
```
void RunInThread(const benchmark::internal::Benchmark::Instance* b, State *st
                 size_t iters, int thread_id,
                 ThreadStats* total) EXCLUDES(GetBenchmarkLock()) {
  b->benchmark->Run(*st);
  //... function continues
}

void RunBenchmark(...) {
  //...
  // create state here instead
  State st(iters, b->has_arg1, b->arg1, b->has_arg2, b->arg2, thread_id, b->threads);
  RunInThread(&b, &st, iters, 0, &total);
  // ...
  // now we can use the counters stored in st to report them to Run
  BenchmarkReporter::Run report;
  report.counters = st.counters; // <--- here 
}
```
So the question is: would you be fine with this change to RunInThread()? Is there an alternative way to do this?

**Comment by dominichamon** [comment]
Thanks for so much detail! Here are some thoughts:

make the user counters a std::string and double as it's going to be more general. If people need to do something in the hot loop (they shouldn't as the counter should be one per benchmark invocation, not per loop) they should accumulate it in some local variable and set it outside the KeepRunning loop.

you probably want to add the counters to `ThreadStats` instead of passing state in to `RunInThread`. Take a look at how the `items_processed` thing is handled as i think this is along the same lines.

in fact, it might be possible to replace items_processed and bytes_processed with the general form that you're proposing here. what do you think?

**Comment by biojppm** [comment]
Thanks for the ThreadStats tip, that seems to be what I was looking for. Of course, you're right about passing state to RunInThread(). I started down that avenue and turns out it's just a dead end because of the threads.

As for the std::string/double combo, you also have a point, specially regarding accumulation in the KeepRunning loop. I'll change from char array/float to std::string/double.

Regarding items_processed/bytes_processed: are you suggesting moving these to UserCounters?

**Comment by biojppm** [comment]
re items_processed: maybe actually moving all the contents of the UserCounters class into ThreadStats? That would make a lot of sense, in my view.

**Comment by dominichamon** [comment]
yes, i think that would work. it feels like the items processed is a subset of the user counters, though we do currently report it as a rate given a count, which isn't going to apply to every counter. i'd suggest extending counters to allow reporters to also calculate rates, but that may make this too complicated.

**Comment by dominichamon** [comment]
0. put a new header line before every benchmark.

let's go through each reporter in turn, actually:

1. json: easy. benchmarks have fields if they have the counters
2. console/tabular: easy-ish. we can have a header per benchmark, as long as we know the user counters at the time we start the benchmark... worst case, only output the benchmark data once we do know the user counters (after the first run?)
3. csv: hard. maybe we don't output any csv data until we have it all, and then we have the header row contain all counters?

**Comment by EricWF** [comment]
Closing this issue since there is a PR tracking it.
