### ISSUE TITLE
build without cmake

### ISSUE THREAD

**Issue by agauniyal** [google/benchmark#268]
Any instructions to build without using cmake build system, in case I use different one? From what I've read, I've got to link against pthread lib. And then I should compile `src/` files and build a static lib and link my project against it? Anything else I might be missing..

**Comment by dominichamon** [comment]
set your include path to the include directory too. you might want to check the build flags and platform definitions.

**Comment by agauniyal** [comment]
ah, I forgot to say include too. I'll be building for linux atm and will report if there are any errors. Thankyou for quick support 😄 .
