### ISSUE TITLE
How to add prefix to benchmark test names?

### ISSUE THREAD

**Issue by OlegJakushkin** [google/benchmark#273]
This question consists of 2 parts:
1. I run same benchmarks on different hardware. I would love to be able to add prefix to each test data item. Having a function like `benchSin` and running `./benchSin --benchmark_prefix="clusterA"` would love to see `clusterA_benchSin` at the beginning of `benchmarks.name` values.
2. If such functionality is added I would love to be able to expand single out file. This would allow to see how changes affected performance e.g.:
```bash
./benchSin --benchmark_out=sin.json  --benchmark_prefix="old"
./benchSin --benchmark_out=sin.json --benchmark_prefix="added_SIMD"
./benchSin --benchmark_out=sin.json --benchmark_prefix="added_OMP"
./benchSin --benchmark_out=sin.json --benchmark_prefix="new"
```

Doing such additions manually requires care and is cause of errors (file overwrites, bad 100k json line merges). Such feature would allow renderers of generated JSON data be more useful and actually track changes.

**Comment by dominichamon** [comment]
having custom benchmark prefixes makes it much harder to post process the json files though, because you have to then remove them.

you should output to different json files with the prefix as this will also allow you to use the processing script that @EricWF recently added to the project, but also will allow you to keep things obvious at the json file level. the contents of the json files will be much more readily comparable.

why is this not an option for you?

**Comment by EricWF** [comment]
Would modifying the `SetLabel(...)` feature so that it has a global default label work for you?

It doesn't change the name but it could act as a unique identifier to distinguish between runs.

**Comment by OlegJakushkin** [comment]
Solved on renderer side using @dominichamon proposal - multiple files based solution. [Renderer code](https://github.com/kiliakis/BLonD-minimal-cpp/tree/master/benchmarks/reports) and [documentation, display multiple results section](https://github.com/kiliakis/BLonD-minimal-cpp/blob/master/docs/FAQ/howToRunBenchmarks.md#display-multiple-results) is available on github. html based (for local `.json` benchmarks visualisation FireFox is your friend)
It can render:
• 1D data + run-time = 2d lines plot
• 2D data + run-time = 3d scatter plot
• 3D+ data + run-time = Parallel Coordinates + results table

**Comment by EricWF** [comment]
Cool. I'm going to close this issue then. If you create some cool tools upstream patches are welcome :-D
