### ISSUE TITLE
Is there a way to assert the result of complexity tests?

### ISSUE THREAD

**Issue by vmrob** [google/benchmark#281]
I would like to integrate Google Benchmark into my project as a means to assert algorithmic complexity but couldn't find a straightforward means to assert Big-O for complexity tests. As in, I want to be able to assert that a particular benchmark runs in linear time.

Is this currently possible? If not, would it be beneficial to the community to include this feature?

**Comment by EricWF** [comment]
The easiest way would be to implement a custom reporter (see `reporters.h`). The custom reporter would receive all of the run data and it could use that to check the expected complexity.

```c++
class TestReporter : public benchmark::ConsoleReporter {
public:
 using Base = benchmark::ConsoleReporter;
 using Base::Base;

 void ReportRuns(const std::vector<Run>& report) {
    for (auto& R : report) assert(CheckRun(R));
    Base::ReportRuns(report);
 }
private:
   bool CheckRun(Run const& R) const; // implement checking here.
};

// Example main with a custom reporter
int main(int argc, char** argv) {
  benchmark::Initialize(&argc, argv);
  TestReporter rep;
  benchmark::RunSpecifiedBenchmarks(&rep);
}
```

**Comment by vmrob** [comment]
Thanks! This is exactly the kind of start I needed.

**Comment by vmrob** [comment]
For future visitor's reference, here is the open source implementation I arrived at: https://github.com/bittorrent/scraps/commit/94e12b77ccbdfba02790d6b7f38a5a1770600807
