### ISSUE TITLE
Add Benchmark::ThreadRange() version with increment instead of multiply

### ISSUE THREAD

**Issue by hydroo** [google/benchmark#282]
Hi,

for my work I want to use a range of threads.
So far the incrementing strategy seems to be limited to just multiplying with a factor.
I.e. you can only use thread counts like 1, 2, 4, 8, 16 or 1, 3, 9, 27.

So I made this small patch.
https://github.com/hydroo/google-benchmark/commit/345d2bac3c132e523b7a7a94160d4dba13c23ead
https://github.com/hydroo/google-benchmark/commit/11aeb3198c4bb8436e9e8892071832ba40cf1546

Should I create a pull request?

Best regards,
Ronny

P.S.: Is ThreadRange() not documented? I only came across it while reading the source.

**Comment by EricWF** [comment]
> Should I create a pull request?

If you have an idea and a patch you should always make a PR. Issues are for people without patches :-P

> for my work I want to use a range of threads

You must have a lot of threads... I'm initially skeptical of the need for this feature. Typically you don't want to exceed the number of threads supported by the hardware (at least by much). Please try and add a motivating example when you open the PR.

I'm closing this issue to make way for the PR.
