### ISSUE TITLE
Invalid JSON format

### ISSUE THREAD

**Issue by jjones646** [google/benchmark#300]
When using `--benchmark_out_format=json`, the _rms_ key does not wrap its value with quotes because of the appended `%` sign. Any script that uses the json is prone to a parsing error.

#### Here's what it currently does:
```
{
    "name": "my_benchmark",
    "rms": 12%
}
```

#### Here's 2 suggestions:

_Option 1_
```
{
    "name": "my_benchmark",
    "rms": 0.12
}
```

_Option 2_
```
{
    "name": "my_benchmark",
    "rms": "12%"
}
```

**Comment by dominichamon** [comment]
assuming the json format is for machine reading, i'd go with 0.12.
