### ISSUE TITLE
No output with gcc 4.8.2

### ISSUE THREAD

**Issue by Dekken** [google/benchmark#306]
OS: Centos 6.7 x86_64
Compiler: gcc version 4.8.2 20140120 (Red Hat 4.8.2-15)
Found: http://people.centos.org/tru/devtools-2/devtools-2.repo

Our compiler uses the system libc, so it could be that glibc is too old

ldd --version
ldd (GNU libc) 2.12

**Comment by dominichamon** [comment]
i'd expect some sort of error at least... given i don't have a centos system to test on, can you run in a debugger and see what happens when you hit a print statement.

**Comment by Dekken** [comment]
The headers print showing time and interations, but there's no results given for any tests, and there's no errors, at least printed errors.

**Comment by EricWF** [comment]
Could you please provide the benchmark your trying to run?

**Comment by Dekken** [comment]
`static void BM_StringCreation(benchmark::State& state) {
  while (state.KeepRunning())
    std::string empty_string;
}
// Register the function as a benchmark
BENCHMARK(BM_StringCreation);

// Define another benchmark
static void BM_StringCopy(benchmark::State& state) {
  std::string x = "hello";
  while (state.KeepRunning())
    std::string copy(x);
}
BENCHMARK(BM_StringCopy);

BENCHMARK_MAIN();`

**Comment by EricWF** [comment]
I can't reproduce with GCC 4.8.5 on Ubuntu 16.04.

**Comment by Dekken** [comment]
It doesn't happen with GCC 4.9.2 / 5.2 / 6.2 or 7, only 4.8.2 with the RPMs noted.

No benchmarks run and it exits immediately after printing the headers.

**Comment by EricWF** [comment]
And your 100% sure it exits with a 0 exit code and doesn't produce any core dumps?

**Comment by EricWF** [comment]
I also can't reproduce with GCC 4.8.0 nor 4.8.2 on Ubuntu 16.04.

**Comment by EricWF** [comment]
What's the output of `cat /opt/rh/devtoolset-2/enable`?

**Comment by Dekken** [comment]
[cat /opt/rh/devtoolset-2/enable](http://pastebin.com/raw/JBhTwVF2)

0 exit code, no coredumps.

**Comment by EricWF** [comment]
OK, I think I've figured this out. Did you compile libbenchmark.a using GCC 4.8.2, or more likely something like 5.2? Versions of the library built with the cxx11 ABI cannot be used with GCC < 5, and libraries built with the old ABI are not compatible with GCC > 5. I suspect if you build the library and test with the same compiler they will work.

However it's very weird that it's not causing a segfault.

**Comment by ctiller** [comment]
I'm seeing this too with https://github.com/grpc/grpc/pull/8500.

**Comment by ctiller** [comment]
`--benchmark_list_tests=true` also outputs an empty list.

**Comment by Dekken** [comment]
Each time a different compiler is used libbenchmark is recompiled with all the same values as the main binary.

**Comment by dominichamon** [comment]
i reproduced this with grpc. the regex is failing to match even when set to the default '.'

my guess is that grpc is building with make so we're not setting the regex machine correctly (we do some hoops in cmake to select it).

still debugging.

**Comment by dominichamon** [comment]
grpc hard-codes STD_REGEX. looks like POSIX_REGEX works better.

**Comment by dominichamon** [comment]
if this also works for you @Dekken, we should consider how we can make this obvious for non-cmake users.

i don't believe it's possible to pick a reasonable default for all platforms, but we could maybe start by documenting the issue?

**Comment by Dekken** [comment]
Switching to -DHAVE_POSIX_REGEX does indeed resolve this.

**Comment by dominichamon** [comment]
great.

i think then either we need to do a better job at exposing the regex machine or have different defaults for the std regex. it's possible that some other default would work with std where '.' fails.

**Comment by dominichamon** [comment]
playing around with this, and i can't actually make the 'std' regex machine run tests at all under gcc 4.8.4.

**Comment by Dekken** [comment]
Is it possible that we could have a warning/error if the regex fails?

**Comment by dominichamon** [comment]
it's expected to fail some matches, though we could warn if we end up with no benchmarks to run.

**Comment by Dekken** [comment]
I support that, I had also hardcoded "-DHAVE_STD_REGEX" into my build mechanism, not ever expecting it to be an issue.

**Comment by dominichamon** [comment]
circling back again, checking a clean 'cmake' run for a g++ 4.8.4 system:

```
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- compiled but failed to run
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
```

so this is "expected".
