### ISSUE TITLE
Benchmark should release a new version

### ISSUE THREAD

**Issue by vser1** [google/benchmark#310]
We are currently 240 commits ahead of v1.0.0, a lot of extensions have been added and bugs have been fixed. It might be time for a v1.1.0, isn't it?

BTW if the tag could be annotated, this would be easier IMHO. Currently `git describe` returns 
 
    v0.1.0-350-g4f8bfea

Because `v1.0.0` isn't annotated. To get a correct description you should use `git describe --tags` (which I think, for a major version is rather counter intuitive) to get:

    v1.0.0-240-g4f8bfea

**Comment by dominichamon** [comment]
v1.1.0 released

**Comment by dominichamon** [comment]
and annotated:

```
~/git/benchmark [master] $ git describe
v1.1.0
~/git/benchmark [master] $ git describe --tags
v1.1.0
```

**Comment by EricWF** [comment]
@dominichamon Awesome thanks!
