### ISSUE TITLE
exception should not be mandatory for compile 

### ISSUE THREAD

**Issue by chshaob1** [google/benchmark#311]
We are trying google benchmark with our code base and find it very attractive, especially it uses the google test style, which we already use today. However, it requires "exception" to compile, which unfortunately we disable for our code base on purpose (Note: this is not another debate on c++ exceptions). It will be very hard to enable exception for such code (I believe a lot others), which gives little chance to use google benchmark (We have similar cases in other third party libraries).

Actually, the exception is only used in one place for regex_error at "re.h", nowhere else. I would suggest to remove the usage of regex_error or at least give a disable-exception compiler option for such cases.

What do you think? if you agree, I can prepare a PR for review.

**Comment by dominichamon** [comment]
I agree, especially as the [google style guide](https://google.github.io/styleguide/cppguide.html) says [no exceptions](https://google.github.io/styleguide/cppguide.html#Exceptions).

**Comment by EricWF** [comment]
Fixed by #317.
