### ISSUE TITLE
BogoMIPS usage is incorrect

### ISSUE THREAD

**Issue by martijncoenen** [google/benchmark#312]
I noticed that google-benchmark parses out BogoMIPS from /proc/cpuinfo, and can use that as its source for 'time spent per cycle'. However, at least on ARM this usage is no longer correct: since the original Bogo loop had two instructions, BogoMIPS is actually twice the timer rate. See https://lkml.org/lkml/2011/4/5/446 for some more context.

**Comment by martijncoenen** [comment]
(Relying on BogoMIPS at all is probably not a good idea, since they are bogus MIPS ;))

**Comment by dominichamon** [comment]
https://github.com/google/benchmark/blob/721c9224b96ad6b6559bf1695ec633a35e69027c/src/sysinfo.cc#L211

acknowledged that we're not happy about using bogomips, but it's only used if we didn't find anything better.

what would you suggest we do instead in that case? we can use a slow estimation method and drop bogomips altogether, but i'm not sure that it's necessarily better.

**Comment by martijncoenen** [comment]
I found this when testing on a Pixel phone; the estimation yields 19.2MHz system clock (which is correct), bogoMIPS says 38MHz, which produces results that are off by a factor of two! Maybe if you only have bogo, run the estimation as well and print a big fat warning if they are significantly different?

Anyway this seems less important in more recent versions, since clockrate appears to be no longer used for measurements directly.

**Comment by dominichamon** [comment]
I'd be ok with dropping bogoMIPS and just using estimation. it doesn't add that much overhead to the overall benchmark run.
