### ISSUE TITLE
`compare_bench.py` won't work with `--benchmark_out=`

### ISSUE THREAD

**Issue by vser1** [google/benchmark#313]
Running (with benchmark v1.1.0)

```
<new_benchmark> --benchmark_out=log.json --benchmark_out_format=json
```

Will generate a `log.json` file but

```
./compare_bench.py <old_benchmark> <new_benchmark> --benchmark_out=log.json --benchmark_out_format=json
```
won't. However it does acknowledge:

```
RUNNING: transmission/transmission_benchmark --benchmark_out=./reports/transmission3.json --benchmark_out_format=json
```

Any hint?

cc @EricWF

**Comment by EricWF** [comment]
The argument handling done by `compare_bench.py` is very sloppy. It secretly inserts another `--benchmark_out=temp_file` after the user provided arguments, which caused your flag to be ignored.

I'll be checking in a rewrite of the argument parsing shortly, and that should make your case work. However passing `--benchmark_out` to both benchmarks will cause the first result to be overwritten, but at least it will sort of work.

**Comment by EricWF** [comment]
Closing this issue because I believe it has been addressed.

**Comment by vser1** [comment]
@EricWF Thanks for the fix!

I'll test it on my side. In case it works, would it be possible to increase google benchmark version (based on semver, it should be 1.1.1 I guess). I'm allowed to use only tagged versions and I'd really love using the compare_bench. If wanted, I'll be happy to share the integration I'm working on with Gitlab CI!

**Comment by EricWF** [comment]
I'll look into releasing a newly tagged release in the next couple days.
