### ISSUE TITLE
No benchmarks registered with clang on Travis CI

### ISSUE THREAD

**Issue by NiklasRosenstein** [google/benchmark#319]
Hello! When I build the benchmarks for my library on Travis CI with Clang, it does not recognize the tests registered with the `BENCHMARK()` macro. Instead, it simply prints

    Failed to match any benchmarks against regex: .

Unfortunately I can only reproduce this on Travis CI. I have tried to reproduce this issue on Ubuntu 16.04 in a Virtual VM but have not been able to, yet. I hope that someone here can give insights on what's going on.

It works fine with GCC-5 and 6.  I've tried clang-3.6 and 3.8. The build logs can be found here:

https://travis-ci.org/NiklasRosenstein/cpp-nr/builds/181055884

Thanks in advance to everyone taking a look into this.

**Comment by NiklasRosenstein** [comment]
Maybe it is `<regex>` that is behaving not  as expected. I currently force it to use the std backend with `HAVE_STD_REGEX`. Will do some tests to check if that could actually be the case.

Anyway, I figured I might be better off asking this on StackOverflow if testing `<regex>` doesn't yield any solutions. It's more likely to be just a configuration error on my side rather than a bug in *benchmark*.

**Comment by NiklasRosenstein** [comment]
I guessed right, it's just a matter of using the right regex backend. I will need update my build script to detect the right backend like the CMake script does, but for now using `HAVE_POSIX_REGEX` works in this scenario!

**Comment by EricWF** [comment]
@NiklasRosenstein Why not just use the CMake build system?

**Comment by NiklasRosenstein** [comment]
I'm writing my own build system, and using it in this project. Plus I don't like CMake all that much.
