### ISSUE TITLE
Report/error unrecognized command line flags

### ISSUE THREAD

**Issue by NiklasRosenstein** [google/benchmark#320]
Are there any use cases where additional flags that are not recognized by `ParseCommandLineFlags()` are handled from another context? I would prefer if, by default, benchmark would report unrecognized command line flags.

Something like

```cpp
// benchmark.cc : ParseCommandLineFlags()
    if (...) {
      // ...
    } else if (IsFlag(argv[i], "help")) {
      PrintUsageAndExit();
    }
    else {
      fprintf(stdout, "unrecognized command line flag: %s\n", argv[i]);
      exit(1);
    }
```

**Comment by pleroy** [comment]
The library being benchmarked might very well have its own flags and want to parse `argc`/`argv`.

**Comment by NiklasRosenstein** [comment]
Very well. Would you agree with me when I'm saying that `BENCHMARK_MAIN()` should report unrecognized flags? Since it is expanded to a full main function, there's no way you're going to handle `argc`/`argv` any further.

**Comment by pleroy** [comment]
I don't care that much about `BENCHMARK_MAIN`, but I don't think we should deviate too much from the Google flags library.  Otherwise it makes it very hard to use different Google libraries together (protocol buffers, gtest, gmock come to mind) just because the handling of flags was "improved" in slightly different manners in different libraries.

**Comment by dominichamon** [comment]
should we start using gflags directly?

**Comment by pleroy** [comment]
I think it would be nicer.  The sad thing though is that gflags is based on the Google flag library as it existed in 2008, so it lags a bit.

**Comment by EricWF** [comment]
We could probably be safe diagnosing unrecognized flags starting with `--benchmark_*`, but like others have said some tests might have to parse their own flags. (For example people frequently use gtest and gbenchmark in the same executable).

**Comment by NiklasRosenstein** [comment]
It does seem like using gflags for both libraries would make things a bit simpler, especially in the case of using the libraries in a single executable. As far as I can tell they both use their own derivative implementation/interface of gflags, `GTEST_DEFINE_...` in googletest, and `DEFINE_...` in benchmark.

@EricWF Unless these flags would then also be consumed by `ParseCommandLineFlags()`, it could lead to problems when you implement your own reporting of unrecognised flags. My [initial comment](https://github.com/google/benchmark/issues/320#issue-193394298) to this issue has the same problem.

For now I'm content with `BENCHMARK_MAIN()` reporting unrecognised flags, which I think is sensible behaviour. Let me know if I should create a PR for NiklasRosenstein@c8b2f2e

**Comment by dominichamon** [comment]
that seems like a reasonable start, yes.

**Comment by EricWF** [comment]
@NiklasRosenstein I would create a PR for your changes. However I would move the actual reporting logic out of the macro and into a function in the library.

**Comment by NiklasRosenstein** [comment]
@EricWF Please check out PR #332

**Comment by EricWF** [comment]
PR #332 has been merged which should address this issue.
