### ISSUE TITLE
benchmark_report_aggregates_only should also report fastest repetition time

### ISSUE THREAD

**Issue by baryluk** [google/benchmark#326]
When doing repeated benchmarks, --benchmark_report_aggregates_only should also print minimum time, not just mean and standard deviation. Minimum is quiet useful for CPU bound benchmarks. 

Selectible percentiles would also be useful, for example for server-client like benchmarks (but, that would be more useful with ability to report some histogram states per benchmark, so it is per-iteration, not per-repetition data, and then aggregating them).

**Comment by EricWF** [comment]
Printing the min and max seems like a good idea to me. Patches welcome :-)

**Comment by LebedevRI** [comment]
I think this can be closed, https://github.com/google/benchmark#user-defined-statistics-for-repeated-benchmarks
```
BENCHMARK(BM_spin_empty)
  ->ComputeStatistics("min", [](const std::vector<double>& v) -> double {
    return *(std::min_element(std::begin(v), std::end(v)));
  })
  ->Arg(512);
```
should do it.

To be noted, it won't be the true minimal time of of the `while(keeprunning)` loop iterations, but the min time of the repetitions.

**Comment by baryluk** [comment]
Honestly, I think this is still not really solved. This should be a default behavior (printing minimum time of the repetitions run), or should require at most one simple flag. Making it few lines of code (plus includes), defeats the purpose, and will make people not use it, and stick to default average (which is almost always bad idea in benchmarks).

**Comment by LebedevRI** [comment]
To be noted, there isn't any way (that i'm aware of) right now to *actually* get the *actual* time of *one* iteration. It will always be somehow averaged, because the timer restart is not free, so it tries to minimize them...
