### ISSUE TITLE
Printing integers as integers

### ISSUE THREAD

**Issue by BRevzin** [google/benchmark#327]
I just ran a benchmark with a list of arguments that are the powers of 10:

    BENCHMARK(foo)->RangeMultiplier(10)->Range(1, 1000000);

This generates test names that are:

    foo/1
    foo/10
    foo/100
    foo/1000
    foo/9.76562k
    foo/97.6562k
    foo/976.562k

This is really confusing. I'm not dealing with memory so it's not readily obvious that the "k" is really 1024 so 9.76562k is really just about 10,000 and not actually 9,765. Would it be possible to either just print the numbers normally (e.g. "10000" and "1000000") or at least add an option to specify how they are printed?

**Comment by dominichamon** [comment]
i think the human readable printer shouldn't be applied to anything outside the results (ie, not the labels). so this is a bug.

i think https://github.com/google/benchmark/blob/56336e70f151f9eb828176e795f7c5dfe6d6bb59/src/benchmark_register.cc#L166 is the line that needs to be changed.

**Comment by BRevzin** [comment]
Submitted a pull request changing that line.

**Comment by kunitoki** [comment]
👍 any idea when this will be pushed upstream ?

**Comment by dominichamon** [comment]
it looks like the pull request was made on @BRevzin's local fork. if it gets made against this repo with this issue linked i'd be happy to take a look.

**Comment by jwakely** [comment]
This seems to be fixed:

https://github.com/google/benchmark/blob/a96ff121b34532bb007c51ffd8e626e38decd732/src/benchmark_register.cc#L178
