### ISSUE TITLE
GPU iterations too many times, Because the iterations is decided by CPU time?

### ISSUE THREAD

**Issue by zhangzhimin** [google/benchmark#333]
Hi, when I run GPU benchmark, I use realtime. but the iterations is still decided by cpu time.
So, the GPU benchmark iterations is too many.

Should decide the iterations times by Realtime When Using RealTime?

Run on (4 X 3506 MHz CPU s)
01/19/17 23:30:42
***WARNING*** Library was built as DEBUG. Timings may be affected.
Benchmark                                                 Time           CPU Iterations
---------------------------------------------------------------------------------------
BM_cu_for_each_gold<byte>/1024/real_time               6708 ns       6334 ns     103601   145.585MB/s
BM_cu_for_each_gold<byte>/4096/real_time               6675 ns       6429 ns     104510   585.215MB/s
BM_cu_for_each_gold<byte>/32768/real_time              6905 ns       6581 ns     102089   4.41937GB/s
BM_cu_for_each_gold<byte>/262144/real_time             6737 ns       6589 ns     104343   36.2376GB/s
BM_cu_for_each_gold<byte>/2097152/real_time           10057 ns       7641 ns      75660   194.197GB/s
BM_cu_for_each_gold<byte>/16777216/real_time          75994 ns       1563 ns      10000   205.607GB/s
BM_cu_for_each_gold<byte>/134217728/real_time        595997 ns          0 ns      10000   209.732GB/s
BM_cu_for_each_gold<byte>/268435456/real_time       1253903 ns       1563 ns      10000   199.377GB/s

**Comment by dominichamon** [comment]
we already do: https://github.com/google/benchmark/blob/master/src/benchmark.cc#L320

perhaps something else is going on?

**Comment by EricWF** [comment]
@zhangzhimin I'm going to close this report for lack of activity. As @dominichamon pointed out the library
already has this behavior. If you figure out what your problem was please re-open this bug.

**Comment by zhangzhimin** [comment]
Thanks, It works well, I didn't  call gpu synchronize before.
