### ISSUE TITLE
iOS Support

### ISSUE THREAD

**Issue by sieren** [google/benchmark#334]
Currently running Benchmark on iOS fails due to `"hw.cpufrequency"` being unavailable on actual physical devices. Unfortunately estimating cycles via `mach_absolute_time` seems unreliable as well, returning values along the lines of `Run on (2 X 24.0256 MHz CPU s)`. 
I'd like to fix this, but I wonder what other options there are other than displaying 0 Mhz, which probably is not a suitable solution for a merge to master.

**Comment by EricWF** [comment]
Well if there is truly no way to detect the CPU clock frequency on such devices then printing "CPU frequency cannot be detected" is probably an OK thing to do.

**Comment by sieren** [comment]
Thanks. Filed a PR at https://github.com/google/benchmark/pull/335

**Comment by sieren** [comment]
I'll go ahead and close this as the PR got merged. Thanks everyone!
