### ISSUE TITLE
Custom Stats

### ISSUE THREAD

**Issue by pgera** [google/benchmark#344]
From the README and the API header, it looks like the supported metrics are bytes processed and items processed. Is it possible to extend these with custom metrics? For example, one might be interested in GFLOPS, or other derived metrics such as raw bandwidth v/s effective bandwidth.

**Comment by dominichamon** [comment]
see https://github.com/google/benchmark/pull/262

it looks like the work stalled, which is a shame.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by pgera** [comment]
The last comment in the PR looks like other than csv output, everything else works as intended. Is it in a usable state ?

**Comment by biojppm** [comment]
Yes I'd say it is usable. Even the csv output will mostly, work. As always, bug reports are welcome :-).

**Comment by EricWF** [comment]
Closing since the custom counters patch has landed.

Please re-open if that patch doesn't address this issue.
