### ISSUE TITLE
Add tests to user counters

### ISSUE THREAD

**Issue by biojppm** [google/benchmark#348]
Now that user counters were integrated, tests should be added. During review of #262, #276 was suggested which added some tests. @EricWF Could you add your tests so that I pick up from there?

**Comment by EricWF** [comment]
I don't recall what I wanted to do. Feel free to proceed without me.

**Comment by biojppm** [comment]
ok.

**Comment by EricWF** [comment]
*You* should still add tests for user defined counters though.

**Comment by biojppm** [comment]
Exactly. Realized pushed the close button.

**Comment by biojppm** [comment]
@dominichamon @EricWF I finally got down and started doing this. It required adding facilities for getting at actual results from the benchmark. The commit above (6452883027b6642157a54cb5ec61c55c34f4948e) allows the following usage:
```c++
void BM_Counters_Simple(benchmark::State& state) {
  while (state.KeepRunning()) {
  }
  state.counters["foo"] = 1;
  state.counters["bar"] = 2;
}
BENCHMARK(BM_Counters_Simple);
// make the results of BM_Counters_Simple be parsed, and call the given lambda.
CHECK_BENCHMARK_RESULTS("BM_Counters_Simple", [](ResultsCheckerEntry const& e) {
  // Check that "foo" read as an int is equal to 1
  // The EQ is appended to CHECK_ so it turns into a call to CHECK_EQ().
  CHECK_COUNTER_VALUE(e, int, "foo", EQ, 1);
  CHECK_COUNTER_VALUE(e, int, "bar", EQ, 2);
});
```
Are you OK with this approach? Look at the commit 6452883027b6642157a54cb5ec61c55c34f4948e and give me your thoughts.

**Comment by EricWF** [comment]
The approach looks good to me. I'll need a couple days before I can look it over.

**Comment by biojppm** [comment]
Ok, I've gone ahead and completed it. Submitting a PR now.
