### ISSUE TITLE
Refactor csv and console reporting to robustly handle counters.

### ISSUE THREAD

**Issue by biojppm** [google/benchmark#349]
I'd like to do this. I was thinking of the following:

- During processing we print only regular data to the console (without user counters). This allows immediate feedback, and saves the trouble of figuring out which counters go on and off in each benchmark.
- After all benchmarks are finished, with the full knowledge of the counters which were set, we print _again_, but this time both regular data AND counters.

What do you think?

**Comment by dominichamon** [comment]
I think the way you've described it would be confusing for users and would
make it harder to write scripts to process the output.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by biojppm** [comment]
ok, closing this. Maybe this is better addressed by #350 ?
