### ISSUE TITLE
Build fails with ICC17u2

### ISSUE THREAD

**Issue by rolandschulz** [google/benchmark#354]
The build fails with ICC17 because of warnings and Werror. What is the correct solution to fix it?
Should a patch
1) disable Werror for ICC (or maybe all non known compilers)
2) disable the false postive warnings for all files. This could be done using:
  add_cxx_compiler_flag(-wd2102) #ICC17u2: Many false positives for Wstrict-aliasing
  add_cxx_compiler_flag(-wd2259) #ICC17u2: non-pointer conversion from "long" to "int" may lose significant bits (even for explicit static cast, sleep.cc(44))
  add_cxx_compiler_flag(-wd654)  #ICC17u2: overloaded virtual function "benchmark::Fixture::SetUp" is only partially overridden (because of deprecated overload)
3) disable warnings at file level or some other granularity

Another warning which isn't clearly a false positive is 
../test/output_test_helper.cc(34): error #3280: declaration hides variable "<unnamed>::dec_re" (declared at line 67 of "../test/output_test.h")
Should the local dec_re be renamed or should that warning be suppressed too for 2/3? 

If I know which solution is preferred I'm happy to create a pull request.

**Comment by dominichamon** [comment]
the best thing to do is probably to disable the compiler flag warnings for
ICC but with a longer-term goal to fix the code where it's a real issue.

i'd say the SetUp overload is also a real issue and we should finish the
deprecation.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*
