### ISSUE TITLE
strange build on msvc: submodule always builded as shared library.

### ISSUE THREAD

**Issue by lysevi** [google/benchmark#369]
hello.

i build benchmarklib as cmake subproject
```cmake
if(DARIADB_ENABLE_BENCHMARKS)
   set(BENCHMARK_ENABLE_TESTING OFF)
   add_subdirectory(extern/benchmark)
   include_directories(extern/benchmark/include)
   set_target_properties(benchmark PROPERTIES FOLDER Extern)
endif(DARIADB_ENABLE_BENCHMARKS)
```

where 'extern/benchmark' is a git submodule. But when i build in msvc 2015, google.benchmark always build as shared dll, not as static. this is a bug? i see you build scripts, and you not set library type of benchmark lib. 

```cmake
add_library(benchmark ${SOURCE_FILES})
```

i think, that should see be like this
```cmake
add_library(benchmark STATIC ${SOURCE_FILES})
```

**Comment by dominichamon** [comment]
what happens if you invoke cmake with:

cmake -DBUILD_SHARED_LIBS=FALSE

(https://cmake.org/cmake/help/v3.0/variable/BUILD_SHARED_LIBS.html)

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by lysevi** [comment]
yes, it helps. thank you
