### ISSUE TITLE
Standard deviation calculation

### ISSUE THREAD

**Issue by yixuan** [google/benchmark#371]
Hi all,
The current calculation for standard deviation uses the **population** version, i.e., `sqrt(sum((x_i - x_mean)^2)/n)`. But by using repetitions, it's more sensible to use the **sample** version `sqrt(sum((x_i - x_mean)^2)/(n - 1))`. This is especially important when computing the confidence interval for the mean values.

**Comment by dominichamon** [comment]
The reason I originally used the population standard deviation is to avoid
generalizing the findings to the population of runs. Ie, what we have is a
sample, but we're interested in the statistics for the sample.

If you think this thinking is in error, please feel free to develop a patch
and show how the data changes under the sample standard deviation. I'm
happy to be wrong!

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by yixuan** [comment]
Hi Dominic, thanks for the quick response. According to your explanation, I think it is exactly where the sample standard deviation can be used. The logic is as follows:

We are interested in the overall elapsed time of one benchmark, whose value is `mu` but unknown. To estimate `mu`, we run the benchmark `n` times and collect a sample of `n` data `x = [x_1, x_2, ..., x_n]`. The sample mean of `x` is `x_mean` and the sample standard deviation is `x_sd`. With these two statistics, we can construct a 95% confidence interval of `mu` as `x_mean ± 1.96 * x_sd / sqrt(n)` (1.96 is obtained from the normal distribution for convenience, a better one is to use the t-distribution). To use this equation, `x_sd` has to be the sample version.

If this makes sense to you, I'm glad to submit a PR later. Thanks.

**Comment by dominichamon** [comment]
makes sense to me! i look forward to the patch.

also, if you think it makes sense to add confidence intervals to the output
i'm happy to support a patch for that too.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by yixuan** [comment]
Hi @dominichamon, when I was creating the patch I noticed one line in the code: https://github.com/google/benchmark/blob/master/src/complexity.cc#L197. Basically it adds a data point to the sample with weight `run.iterations`. May I ask why this weight is set to `run.iterations` instead of 1? I'm asking this since it may cause problems in the calculation of sample variance.

Consider the hypothetical example below. Assume that we have two runs, each with 1000 iterations. The first run takes 2 seconds and the second takes 3 seconds. The first run has the effect of

```
real_accumulated_time_stat += Stat1_d(0.002, 1000)
```

so that inside `real_accumulated_time_stat`, the member variable `numsamples_ = 1000`. Similarly, after adding the second run, the number of samples becomes 2000.

However this is not the sample size used in the calculation of sample standard deviation. What we should have is `numsamples_ = 2`. A quick fix of this is to add the data without a weight (which means weight = 1), so the code looks like this one: https://github.com/yixuan/benchmark/blob/master/src/complexity.cc#L196-L201.

I want to know if the weights have any other use in the code that I have missed. If not, I think I can go and submit the PR. Thanks!

(For the confidence interval, currently there is some difficulty since we need the quantile function of t-distribution, which is not provided by standard C++ libraries.)

**Comment by dominichamon** [comment]
It's been a while since I've looked at the stat classes, but iirc it's
meant to be ensuring the mean is a per-iteration mean. Ie, we pass in the
average time per iteration (yes, we're doing means of means. sorry).

In your example, real_accumulated_time_stat would end up with a value of
(0.002 + 0.003) and a sample size of 2, meaning the mean would be 0.0025.
In the current code, it would be a value of 0.005 and a sample size of
2000, giving a mean of 2.5e-6. However, on
https://github.com/google/benchmark/blob/master/src/complexity.cc#L215 we
multiple the mean back up and end up reporting the right number.

So it looks like this is done to ensure that the standard deviation is
calculated based on the number of iterations, rather than the number of
runs. This could be wrong.

Can you show the output with the std dev for the upstream version and your
version so we can compare and see what is "right"?



Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by yixuan** [comment]
Sure. I'll post the result here later.
The reason why I think the sample size should be 2 instead of 2000 (as in the example I gave above) can be explained as follows:

As you have discovered, the `mean` column is doing means of means, and similarly, `stddev` should be doing standard deviations of means. Sample size characterizes how many data you we really **observed**. If we have the measurements of each iteration, then yes, our sample size would be 2000, but the reality is that we have **aggregated** the data in each run and lost individual measurements per iteration. As a result, what we have really **observed** is the time for each run, so the sample size is equal to the number of runs in this case.

A tiny example can illustrate this idea. Imagine that we have two runs. The first run has two iterations, with time `X1` and `X2`. The second run also has two iterations with time `Y1` and `Y2`. If we have all these four data points, then the standard deviation can be calculated based on a sample size of 4. However, the real process is, we first measure the time for run 1, `X1+X2`, divide it by 2, `Xbar = (X1+X2)/2`, and then add it to the stat class; and then, we similarly measure `Ybar = (Y1+Y2)/2`, and then add it to the stat class. What we really "observe" are `Xbar` and `Ybar`, which are aggregations of the raw data. In this case, we cannot use 4 as the sample size.

**Comment by yixuan** [comment]
This is the result of a simple test based on the current [google/benchmark](https://github.com/google/benchmark):
```
-------------------------------------------------------------
Benchmark                      Time           CPU Iterations
-------------------------------------------------------------
BM_SORT                     7792 ns       7782 ns      72674
BM_SORT                     7775 ns       7766 ns      72674
BM_SORT                     7753 ns       7745 ns      72674
BM_SORT_mean                7774 ns       7764 ns      72674
BM_SORT_stddev                16 ns         15 ns          0
BM_STABLE_SORT              8179 ns       8169 ns      84570
BM_STABLE_SORT              8249 ns       8238 ns      84570
BM_STABLE_SORT              8252 ns       8242 ns      84570
BM_STABLE_SORT_mean         8226 ns       8217 ns      84570
BM_STABLE_SORT_stddev         34 ns         34 ns          0
```

We can manually verify that `sqrt(((7792 - 7774)^2 + (7775 - 7774)^2 + (7753 - 7774)^2) / 3) = 15.98 ~= 16`.

Below is my patched version (https://github.com/yixuan/benchmark/commit/9657621b748001386db2c8338fc3975ea9dc5748, https://github.com/yixuan/benchmark/commit/9f6434da82defb0bdebd3aeb8512258646e861a5):
```
-------------------------------------------------------------
Benchmark                      Time           CPU Iterations
-------------------------------------------------------------
BM_SORT                     7807 ns       7799 ns      83800
BM_SORT                     7782 ns       7775 ns      83800
BM_SORT                     7770 ns       7762 ns      83800
BM_SORT_mean                7786 ns       7779 ns      83800
BM_SORT_stddev                19 ns         19 ns          0
BM_STABLE_SORT              8354 ns       8345 ns      79040
BM_STABLE_SORT              8255 ns       8246 ns      79040
BM_STABLE_SORT              8288 ns       8279 ns      79040
BM_STABLE_SORT_mean         8299 ns       8290 ns      79040
BM_STABLE_SORT_stddev         50 ns         50 ns          0
```

Take the first stddev value as example, it can be verified that `sqrt(((7807 - 7786)^2 + (7782 - 7786)^2 + (7770 - 7786)^2) / 2) = 18.88 ~= 19`

The difference is that one uses 3 as denominator and the other uses 2.

**Comment by dominichamon** [comment]
I notice in your patches you're also changing the sample size for the items
per second and bytes per second. Does that also lead to correct values?

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by yixuan** [comment]
I think so. I used an example derived from the test suite:

```cpp
#include <set>
#include "benchmark/benchmark_api.h"

std::set<int> ConstructRandomSet(int size) {
  std::set<int> s;
  for (int i = 0; i < size; ++i) s.insert(i);
  return s;
}

static void BM_SetInsert(benchmark::State& state) {
  while (state.KeepRunning()) {
    state.PauseTiming();
    std::set<int> data = ConstructRandomSet(state.range(0));
    state.ResumeTiming();
    for (int j = 0; j < state.range(1); ++j) data.insert(rand());
  }
  state.SetItemsProcessed(state.iterations() * state.range(1));
  state.SetBytesProcessed(state.iterations() * state.range(1) * sizeof(int));
}
BENCHMARK(BM_SetInsert)->Args({1024, 1});

BENCHMARK_MAIN();
```

Official version:

```
------------------------------------------------------------------
Benchmark                           Time           CPU Iterations
------------------------------------------------------------------
BM_SetInsert/1024/1             48752 ns      48713 ns      14356   80.1897kB/s   20.0474k items/s
BM_SetInsert/1024/1             48759 ns      48722 ns      14356   80.1743kB/s   20.0436k items/s
BM_SetInsert/1024/1             48773 ns      48733 ns      14356   80.1566kB/s   20.0392k items/s
BM_SetInsert/1024/1_mean        48761 ns      48722 ns      14356   80.1735kB/s   20.0434k items/s
BM_SetInsert/1024/1_stddev          9 ns          8 ns          0    13.8566B/s    3.46415 items/s
```

Patched version:

```
------------------------------------------------------------------
Benchmark                           Time           CPU Iterations
------------------------------------------------------------------
BM_SetInsert/1024/1             48622 ns      48581 ns      14407   80.4065kB/s   20.1016k items/s
BM_SetInsert/1024/1             48764 ns      48722 ns      14407   80.1736kB/s   20.0434k items/s
BM_SetInsert/1024/1             48850 ns      48810 ns      14407   80.0297kB/s   20.0074k items/s
BM_SetInsert/1024/1_mean        48745 ns      48705 ns      14407   80.2033kB/s   20.0508k items/s
BM_SetInsert/1024/1_stddev        116 ns        115 ns          0    194.749B/s    48.6872 items/s
```

**Comment by dominichamon** [comment]
the standard deviation for items/bytes looks suspicious in both cases, but
the mean looks right.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by yixuan** [comment]
Did you notice the different units?

**Comment by dominichamon** [comment]
i didn't! UI failure. I should fix that.

Ok, this looks good.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by yixuan** [comment]
But still, I would say that the current algorithm to calculate standard deviation has large rounding errors, since the numbers passed to the stats class are usually very large (they are in the units of nanoseconds or bytes), and moreover the stats class computes their sum of **squares** that makes the total even larger.

A better algorithm is to compute the mean first and then sum up the square of the difference between each data point and the mean, but it requires storing the whole array.

**Comment by dominichamon** [comment]
Agree on rounding errors. I still think it's worth getting the sample version in first before working on more accuracy.

Would you mind putting a PR together?

**Comment by yixuan** [comment]
Sure. I'll submit the PR later.
I also have some ideas on reducing the rounding error and may open a new issue.

**Comment by pleroy** [comment]
> But still, I would say that the current algorithm to calculate standard deviation has large rounding errors, since the numbers passed to the stats class are usually very large (they are in the units of nanoseconds or bytes), and moreover the stats class computes their sum of squares that makes the total even larger.

I believe that this reasoning is faulty.  Whether the numbers are large or small has no bearing on the accuracy of the result as long as there are no overflows/underflows.  To see why, just imagine multiplying/dividing all the numbers by a power of 2 before the computations: you could make them as large or as small as you want but that wouldn't affect the accuracy of the result.

There are two things that affect the accuracy of the result:
1. The order in which numbers are added.  Ideally you'd want to add them in increasing order of magnitude, but in practice that's expensive so it would be sufficient to use compensated summation.
1. The final subtraction `avg_squares - Sqr(mean)`.  While it might be exact because the two numbers are probably within a factor of 2 or each other, you just end up with a significant cancellation, especially if the results have little dispersion.  Again, compensated summation would help preserve accuracy in the final result.

Having ranted about "numerical analysis is hard" I must add that this is spectacularly unimportant: the deviation is typically computed on a dozen samples or so, so it's not significant beyond the first or second digit.  Nobody cares about getting these last bits right.

**Comment by yixuan** [comment]
Hi @pleroy , thanks for your nice correction, especially for the second point.
What I wanted to say is that the numbers are too large compared to their variations, so instead of adding `[10024, 10025, 10021]` to the sum and sum of squares, it's better to first choose an offset, e.g. 10000, and then use their difference with the offset, `[24, 45, 21]`, for calculation. Ideally the offset is chosen to be the mean, but other choices such as the first value in the sequence is also fine.

**Comment by pleroy** [comment]
@yixuan: Ah, I didn't realize that you wanted to use an offset.  I agree that it's a good solution that's well-conditioned and easy to implement.
