### ISSUE TITLE
Building error in VS2017 community under Windows system. LINK : fatal error LNK1104: cannot open file 'pthread.lib'

### ISSUE THREAD

**Issue by navia1991** [google/benchmark#374]
Hello, I ran into build problem LINK : fatal error LNK1104: cannot open file 'pthread.lib'.
My Cmakelists is:
/******************************************************************************************/
# Set up Google Benchmark as an external project. 
# More or less taken from http://www.kaizou.org/2014/11/gtest-cmake/. 
 
find_package(Threads) 
include(ExternalProject) 
 
ExternalProject_Add( 
    benchmark 
    URL https://github.com/google/benchmark/archive/v1.1.0.tar.gz 
    PREFIX ${CMAKE_CURRENT_BINARY_DIR}/gbench 
    # Disable install step 
    INSTALL_COMMAND "" 
) 
 
# Get GTest source and binary directories from CMake project 
ExternalProject_Get_Property(benchmark source_dir binary_dir) 
 
# Create a libgbench target to be used as a dependency by benchmarks 
add_library(libgbench IMPORTED STATIC GLOBAL) 
add_dependencies(libgbench benchmark) 
 
include_directories("${source_dir}/include") 
set_target_properties(libgbench PROPERTIES 
    "IMPORTED_LOCATION" "${binary_dir}/src/libbenchmark.a" 
    "IMPORTED_LINK_INTERFACE_LIBRARIES" "${CMAKE_THREAD_LIBS_INIT}" 
) 
 
message(STATUS ${binary_dir}) 
 
############################## 
#                            # 
# Building actual benchmarks # 
#                            # 
############################## 
 
include_directories(${CMAKE_SOURCE_DIR}/src) 
add_executable(benchmarks benchmarks.cpp) 
 

target_link_libraries(benchmarks tgv pthread libgbench) 
 
add_custom_target(bench COMMAND ${CMAKE_BINARY_DIR}/benchmarks/benchmarks)
/******************************************************************************************/

And after build in Cmake 3.7, there is some information says something related to pthread not found, but it did not show any error at last. Here is my Cmake configure information:
/******************************************************************************************/
The C compiler identification is MSVC 19.0.24218.2
The CXX compiler identification is MSVC 19.0.24218.2
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/Shared/14.0/VC/bin/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Found OpenCV: D:/opencv-3.2.0/opencv-3.2.0/build/vc15/install (found version "3.2.0") 
Found SWIG: D:/Anaconda/pro/Library/bin/swig.exe (found version "3.0.10") 
Found PythonInterp: D:/Anaconda/pro/python.exe (found suitable version "3.6", minimum required is "3.4") 
Found PythonLibs: D:/Anaconda/pro/libs/python36.lib (found version "3.6.0") 
D:/Anaconda/pro/include
D:/Anaconda/pro/libs/python36.lib
D:/Anaconda/pro/python.exe
Try OpenMP C flag = [/openmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Success
Try OpenMP CXX flag = [/openmp]
Performing Test OpenMP_FLAG_DETECTED
Performing Test OpenMP_FLAG_DETECTED - Success
Found OpenMP: /openmp  
Looking for pthread.h
Looking for pthread.h - found
Looking for pthread_create
Looking for pthread_create - not found
Looking for pthread_create in pthreads
Looking for pthread_create in pthreads - not found
Looking for pthread_create in pthread
Looking for pthread_create in pthread - not found
Check if compiler accepts -pthread
Check if compiler accepts -pthread - no
Found Threads: TRUE  
E:/HIWI/gitclone/tgv_gz - Copy/build/benchmarks/gbench/src/benchmark-build
Configuring done
Generating done
/******************************************************************************************/
Then i opened project and build in VS2017,
there is a fatal error called:
6>LINK : fatal error LNK1104: cannot open file 'pthread.lib'
6>Done building project "benchmarks.vcxproj" -- FAILED.

I know there may something wrong with pthread under Windows system. Then i searched online and downloaded built version which makes pthead works under Windows provided by : https://www.sourceware.org/pthreads-win32/
And then I put three include files 'pthread.h, sched.h, semaphore.h' into C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\include
Then copy files in lib filefolder(both x86 and x64) to C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\VC\lib
Then copy files in dll filefolder, x86 sub-filefolder to C:\Windows\SysWOW64, and x64 sub-filefolder to C:\Windows\System32. 
I use example code given online to test pthread and it worked:
/******************************************************************************************/
//main.cpp  
#include <stdio.h>  
#include <pthread.h>  
#include <assert.h>  
  
#pragma comment(lib,"x86/pthreadVC2.lib")  
  
void* Function_t(void* Param)  
{  
    printf("I am thread! ");  
    pthread_t myid = pthread_self();  
    printf("ThreadID=%d ", myid);  
    return NULL;  
}  
  
int main()  
{  
    pthread_t pid;  
    pthread_attr_t attr;  
    pthread_attr_init(&attr);  
    pthread_attr_setscope(&attr, PTHREAD_SCOPE_PROCESS);  
    pthread_attr_setdetachstate(&attr, PTHREAD_CREATE_DETACHED);  
    pthread_create(&pid, &attr, Function_t, NULL);  
    printf("======================================== ");  
    getchar();  
    pthread_attr_destroy(&attr);  
    return 0;  
}  
/******************************************************************************************/

I am not so familier with compiler and also how windows system works... not got a idea how to solve this problem.....
Does anyone who used this benchmark under Windows? Have you also ran into pthread problem and how did you deal with it? Thanks! : )

**Comment by EricWF** [comment]
Why do you think this is a bug with Google Benchmark and not with your CMake. You explicitly add the problematic `pthread` library here:

> `target_link_libraries(benchmarks tgv pthread libgbench)`

The library currently tests against [10 different Windows configurations](https://ci.appveyor.com/project/google/benchmark), including two which use MinGW, GCC, and pthreads.

Here is [the script](https://github.com/google/benchmark/blob/master/appveyor.yml) that the Windows bots use to configure CMake 

I'm not sure I can help beyond that. I'll leave this bug open for a couple days incase anybody can help further, but after that I plan to close this as WORKSFORME.

**Comment by EricWF** [comment]
Here is another CMake example setup, hopefully it will help: https://gist.github.com/BillyONeal/9da4780049f3fd04765888e7e11564e4

**Comment by navia1991** [comment]
@EricWF  Thanks! Yes, it is probably something wrong with cmakelist... I will take a look at the examples...

**Comment by EricWF** [comment]
Closing this bug since it's not related to Google Benchmark but instead to your configuration.
