### ISSUE TITLE
User Counters ignore Flag parameter

### ISSUE THREAD

**Issue by vladoovtcharov** [google/benchmark#378]
When creating a user counter it display the count as if `kDefaults` flag was used even if explictly setting a different flag
`st.counters["Foo"] = benchmark::Counter(FooCount, benchmark::Counter::kIsRate);`

**Comment by biojppm** [comment]
@vladoovtcharov Thanks for reporting. I will take a look at this.

**Comment by biojppm** [comment]
@vladoovtcharov I think I caught the problem. I'm taking this opportunity to finally get down and write the unit tests for the counters; in the meantime please confirm if this fixes the problem for you.

**Comment by vladoovtcharov** [comment]
That almost fixed it, it was also erasing the flag when coercing it to a double in the update and finish functions. Probably more robust to overload the operators but I just did a quick hack for now.

**Comment by biojppm** [comment]
Good catch, thanks. If you don't mind I'll pull from your repo before submitting my PR.
