### ISSUE TITLE
Integer arguments only ?

### ISSUE THREAD

**Issue by pgera** [google/benchmark#387]
Are only integer arguments supported ? It looks like std::vector<std::vector<int> > args_; is hardcoded to int. Can it be generalized without breaking stuff ?

**Comment by EricWF** [comment]
Would something like this work for you? https://github.com/google/benchmark#passing-arbitrary-arguments-to-a-benchmark

**Comment by pgera** [comment]
Yes, I was just reading that section of the README. I think I can make it work. It's a bit roundabout for simple cases though. As a simple fix though, is it possible to increase the arg's size from 32 bits (int) to 64 bits ? Or would it break the library for 32 bit architectures.

**Comment by EricWF** [comment]
There is no support for changing the type accepted by `Benchmark::Arg` and returned by `state.range(...)`.
There is also no easy way to make the library accept arbitrary argument types (It would require a lot of template magic).

**Comment by tilsche** [comment]
> As a simple fix though, is it possible to increase the arg's size from 32 bits (int) to 64 bits ?

I have to second that request. It is **extremely** inconvenient to use `int` rather than `long` or `ssize_t` for `range`. Even the README example use case uses range for a data size so you can't run `BM_memcpy` for > 2 GiB of data. Also the ugly `int64_t(state.range(0))`.

So please. Whenever you make an ABI-braking version jump anyway. Change the type.

**Comment by guban** [comment]
As a workaround, you can put your arguments into an array (a lookup table) and then pass to your benchmark integer indices into that array. This way, you can even "pass" arguments of your custom data types.

**Comment by LebedevRI** [comment]
Hm, but `Benchmark::Arg()` & friends already take `int64_t`,
and `State::range()` already returns `int64_t`?
It seems like this just works now?
