### ISSUE TITLE
Travis CI build for macOS

### ISSUE THREAD

**Issue by tusharpm** [google/benchmark#388]
[The current Travis config](https://github.com/google/benchmark/blob/cb8a0cc10f8b634fd554251ae086da522b58f50e/.travis.yml) has a few Linux builds with various configurations.
It might be useful to add macOS builds also.

I've attempted it on [my fork](https://github.com/tusharpm/benchmark/tree/travis). The [travis build passed](https://github.com/tusharpm/benchmark/tree/travis).

**Comment by dominichamon** [comment]
Great! Pull Requests always welcome.
