### ISSUE TITLE
Benchmark crashing and other

### ISSUE THREAD

**Issue by advaitraut** [google/benchmark#391]
1. Following is code is crashing in runtime with error `Segmentation fault: 11` on my OS X 10.10 with gcc-7:

```
#include<benchmark/benchmark.h>

static int** int_pp;
static int c=0;

static void BM_newInt(benchmark::State& state){
  int_pp=new int*[20000000];
  while (state.KeepRunning())
  {
    int_pp[c++] = new int;
  }
}

static void BM_deleteInt(benchmark::State& state){
  while (state.KeepRunning())
  {
    delete int_pp[--c];
  }
  delete[] int_pp;
}

BENCHMARK(BM_newInt);
BENCHMARK(BM_deleteInt);

BENCHMARK_MAIN();
```

It crashes after printing benchmarks for `BM_newInt`. Anything wrong with this code ?

2. Apart from this, how can I print **Standard Deviation** of **Time** and **CPU** on the console. By default it prints just mean value.

**Comment by pleroy** [comment]
What makes you think that the two benchmarks are going to loop the same number of times?  If `BM_deleteInt` went into more iterations than `BM_newInt` you'd index into the boonies.

**Comment by advaitraut** [comment]
Thanks, very true.
How can I print Standard Deviation ?

**Comment by advaitraut** [comment]
Can I do something like

```
static void BM_deleteInt(benchmark::State& state){
 while (state.KeepRunning() && c > 0)
  {
    delete int_pp[--c];
  }

// Prost processing ? 
// How ?
// Stop benchmarks early ?

```

**Comment by dominichamon** [comment]
using `benchmark::StatisticsStdDev` should work to print the std deviation, and is added by default[1] when you have multiple repetitions[2].

1. https://github.com/google/benchmark/blob/a271c36af93c7a3b19dfeb2aefa9ca77a58e52e4/src/benchmark_register.cc#L243
2. https://github.com/google/benchmark/blob/25acf220a44ccc41104a690731fcf646cc3e8192/test/reporter_output_test.cc#L314
