### ISSUE TITLE
How to measure cache misses

### ISSUE THREAD

**Issue by schoetbi** [google/benchmark#392]
I have a question: When I want the speed of a function that processes an input byte array according to different rules. How do I simulate that the input data got changed from another thread? I assume that when running multiple times over the same data (which is in L1 cache) the speed is quite high but when running in production (with shared memory and writes from other processes) the speed might differ. 

Is there something like "ReloadFromMainMemory()" in every loop?

**Comment by dominichamon** [comment]
There isn't.

Sorry for the delay, i've been trying to find some time to work out an
answer. Spoiler: I didn't.

I think some combination of spawning threads and pausing timing while
waiting on mutexes to synchronize might work.

I would expect declaring stuff as 'volatile' might help, but that's more a
guideline than a guarantee. maybe you can use some std::atomic and atomic
fences to synchronize writes and reads?

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by schoetbi** [comment]
I will try to create some threads then in the benchmark setup. The mutexes are already in place since I plan to use shared memory.
Thank you.
