### ISSUE TITLE
core dumped when running the demo

### ISSUE THREAD

**Issue by yangguangxu** [google/benchmark#395]
demo code:

#include "benchmark/benchmark.h"

static void BM_StringCreation(benchmark::State& state) {
  while (state.KeepRunning())
    std::string empty_string;
}
// Register the function as a benchmark
BENCHMARK(BM_StringCreation);

// Define another benchmark
static void BM_StringCopy(benchmark::State& state) {
  std::string x = "hello";
  while (state.KeepRunning())
    std::string copy(x);
}
BENCHMARK(BM_StringCopy);

BENCHMARK_MAIN();
------------------------------------------------------
compile command:   g++ -o bm test.cc -lbenchmark
------------------------------------------------------
running command:  ./bm
------------------------------------------------------
error message:
terminate called after throwing an instance of 'std::system_error'
  what():  Unknown error -1
Aborted (core dumped)

**Comment by dominichamon** [comment]
you'll need to link pthread.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by EricWF** [comment]
@yangguangxu Have you managed to solve this problem?

**Comment by yangguangxu** [comment]
@dominichamon Thanks, link pthread can solve the problem.

**Comment by yangguangxu** [comment]
@EricWF   yes, problem has been solved.
