### ISSUE TITLE
RegisterBenchmark and Remove Benchmarks

### ISSUE THREAD

**Issue by elderRex** [google/benchmark#400]
I've been trying to create a class wrapper that can evoke benchmark when the member function is called.
For now the function works on only one instance.
```c++
void foo(const A& event){
        this->CBM_Timer = [this](benchmark::State& st, A event) {
            while (st.KeepRunning())
                this->BM_Routine_E1(event);
        };
        benchmark::RegisterBenchmark("on_timer", this->CBM_Timer, event);
        int fake_argc = 1;
        cout << fake_argc << endl;
        benchmark::Initialize(&fake_argc, nullptr);
        benchmark::RunSpecifiedBenchmarks();
}
```
One of the problem is that invoking the function twice results in broken pipe (tho this particular error could be caused on my end..)
```c++
gzip: 
gzip: stdout: Broken pipe
stdout: Broken pipe
Segmentation fault (core dumped)
```
Another problem is when evoked multiple times, the results are
```
2017-06-13 14:31:46
Benchmark           Time           CPU Iterations
-------------------------------------------------
on_timer        20406 ns      20365 ns      34452
Run on (24 X 2892.93 MHz CPU s)
2017-06-13 14:31:47
Benchmark           Time           CPU Iterations
-------------------------------------------------
on_timer        15129 ns      15114 ns      50346
on_timer        15547 ns      15546 ns      41997
Run on (24 X 2892.93 MHz CPU s)
2017-06-13 14:31:49
Benchmark           Time           CPU Iterations
-------------------------------------------------
on_timer        13793 ns      13793 ns      60930
on_timer        11336 ns      11335 ns      61513
on_timer        12313 ns      12314 ns      61581
```
I've been looking through the repo to find a way of removing registered benchmark. Tho the closest I found is that in the BenchmarkFamilies, the apis are
```c++
  size_t AddBenchmark(std::unique_ptr<Benchmark> family);

  // Extract the list of benchmark instances that match the specified
  // regular expression.
  bool FindBenchmarks(const std::string& re, std::vector<Benchmark::Instance>* benchmarks, std::ostream* Err);
```
So, appears no RemoveBenchmark is avaiable. I was wondering maybe I looked at the wrong place and could not find the utility... would really appreciate the help in pinpoint the code to look at regarding dis-registering benchmark.

Thanks

**Comment by elderRex** [comment]
maybe something as simple as:
```c++
void BenchmarkFamilies::ClearBenchmark() {
  MutexLock l(mutex_);
  families_.clear();
}
```
Tho not sure about the potential complications this might introduce in other parts of the code...

**Comment by dominichamon** [comment]
The library hasn't been designed with that in mind at all. The problem is
going to be on the multiple initialization and running part, which are only
expected to be called once in a program's execution.

It could be changed to work, but I'm not sure that it's worth it because I
don't really understand what you're getting out of doing it this way. Can
you explain what problem you're trying to solve?

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by EricWF** [comment]
I've been meaning to allow registration from within a function, (with direct calls to some register function). I'll look more into this on Friday.

**Comment by elderRex** [comment]
Hi dominic, the goal is to embed the benchmark in a class so that it can be evoked repeatedly with ease. 'cause the function i'm benchmarking is constantly changing... Tho there could be a better design, probably need to figure this out.

also, thanks Eric : D

**Comment by EricWF** [comment]
@elderRex Woops, I misunderstood your original post.

> One of the problem is that invoking the function twice results in broken pipe

Registered benchmarks are always going to be invoked multiple times to determine the iteration count to use in the final (and actually reported) run. You need to design your benchmarks to allow for this.

Is there a reason you can't do this? (Also do I understand your problem now?)

**Comment by elderRex** [comment]
@EricWF Thanks for the clarification! Though the broken pipe problem is probably 'caused by other code in my program & I'm trying to pinpoint the 'cause...

guess my question is more about multiple initialization as dominic said (also removing registered benchmarks)

**Comment by EricWF** [comment]
@elderRex Let me see if I understand. You want to be able to invoke `RunSpecifiedBenchmarks` multiple times, but removing certain benchmarks each time?

**Comment by elderRex** [comment]
yup that's the plan

**Comment by EricWF** [comment]
Hmm, OK. `ClearBenchmarks` might be possible, but individually removing them likely would not be.

The problem is that a single registered benchmark actually represents a "benchmark family", that itself can generate more than one *actual* benchmark test. Trying to remove a family or single benchmark test seems confusing.

However removing all of them seems entirely possible. :-)

**Comment by EricWF** [comment]
@elderRex See https://github.com/google/benchmark/pull/402

**Comment by elderRex** [comment]
@EricWF Thanks for the update! : D

**Comment by EricWF** [comment]
@elderRex Thanks for the report.
