### ISSUE TITLE
Report min / max of a range of benchmarks

### ISSUE THREAD

**Issue by ax487** [google/benchmark#408]
I have a benchmark which uses a `DenseRange` of values to derive parameters (My actual code is more complex than this though.):

    static void BM_memcpy(benchmark::State& state) {
      char value = (char) state.range(0);
      char* src = new char[16];
      char* dst = new char[16];
      memset(src, value, 16);
      while (state.KeepRunning())
        memcpy(dst, src, 16);
      state.SetBytesProcessed(int64_t(state.iterations()) *
                              int64_t(16));
      delete[] src;
      delete[] dst;
    }
    BENCHMARK(BM_memcpy)->DenseRange(10, 20);

As show in this example, I use the range to perform benchmarks which have specified parameters but don't differ in complexity (maybe I am in fact  abusing the range). is it possible to perform runs for the parameters in this range and report the min/max/average running time?

Alternatively, is it possible to programmatically run single benchmarks anywhere in my code and collect and process the results as I see fit?

**Comment by dominichamon** [comment]
Each run with the different range should be reported as a different line in the output, if i'm reading this correctly.

Example output from your example above:
```
BM_memcpy/10                                            8 ns          8 ns   85693300   1.89975GB/s
BM_memcpy/11                                            8 ns          8 ns   89337173   1.83642GB/s
BM_memcpy/12                                            8 ns          8 ns   85161295   1.89563GB/s
BM_memcpy/13                                            8 ns          8 ns   87540678   1.83645GB/s
BM_memcpy/14                                            8 ns          8 ns   86102916   1.90956GB/s
BM_memcpy/15                                            8 ns          8 ns   89331988   1.83621GB/s
BM_memcpy/16                                            8 ns          8 ns   85581982   1.90453GB/s
BM_memcpy/17                                            8 ns          8 ns   88325367    1.7868GB/s
BM_memcpy/18                                            8 ns          8 ns   85018141   1.88911GB/s
BM_memcpy/19                                            8 ns          8 ns   89423704   1.84494GB/s
BM_memcpy/20                                            8 ns          8 ns   86438968   1.90984GB/s

```
