### ISSUE TITLE
Cross Compile libbenchmark.a for aarch64 android

### ISSUE THREAD

**Issue by atrah22** [google/benchmark#415]
Hello,

Maybe this is a novice question. I need intructions on how to compile libbenchmark.a for aarch64 android.

I tried,
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_CXX_COMPILER=aarch64-linux-android-g++ \
-DBENCHMARK_ENABLE_LTO=false -DBENCHMARK_ENABLE_TESTING=false ..

I get error. When I read the "/benchmark/build/CMakeFiles/CMakeError.log", I see the error is cause due to "aarch64-linux-android-g++: error: unrecognized command line option '-Wshorten-64-to-32'".
Hence next, I tried with clang++
cmake -DCMAKE_BUILD_TYPE=Release \
-DCMAKE_CXX_COMPILER=aarch64-linux-android-clang++ \
-DBENCHMARK_ENABLE_LTO=false -DBENCHMARK_ENABLE_TESTING=false ..
make
make install

This creates libbenchmar.a but not for aarch64 android.
My questions are:
1) Is there option not to use g++ instead of clang++?
2) How can i create libbenchmark.a for android aarch64?

**Comment by dominichamon** [comment]
We shouldn't be adding unsupported command line options. Can you share your
logs?

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by EricWF** [comment]
@atrah22 Have you read the [CMake Cross-Compiling docs](https://cmake.org/Wiki/CMake_Cross_Compiling)? In particular you should look at `CMAKE_SYSTEM_NAME`.
