### ISSUE TITLE
ODR violations on gcc 5.4.0

### ISSUE THREAD

**Issue by gnarlie** [google/benchmark#420]
Building master with gcc 5.4, I'm getting ODR violations. I've traced the issue to a9a66c85bbfda1d744c267c5e5aa073ef3d1c1d5

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609

```
[51%] Linking CXX executable cxx03_test
/usr/include/c++/5/bits/stl_tree.h:134:12: error: type ‘struct _Rb_tree_node’ violates one definition rule [-Werror=odr]
     struct _Rb_tree_node : public _Rb_tree_node_base
            ^
/usr/include/c++/5/bits/stl_tree.h:134:12: note: a different type is defined in another translation unit
     struct _Rb_tree_node : public _Rb_tree_node_base
            ^
/usr/include/c++/5/bits/stl_tree.h:139:12: note: the first difference of corresponding definitions is field ‘_M_value_field’
       _Val _M_value_field;
            ^
/usr/include/c++/5/bits/stl_tree.h:149:41: note: a field with different name is defined in another translation unit
       __gnu_cxx::__aligned_membuf<_Val> _M_storage;

                                         ^
[... continues ...]
```

**Comment by dominichamon** [comment]
i just ran a check under the AddressSanitizer (which can detect these) and
nothing got flagged. I'll keep looking.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by gnarlie** [comment]
The error appears to be valid ORD violation - the test cxx03_test (built with std=c++03) is linking libbenchmark.a, built with C++11. At least for this version of gcc, the tree nodes in a std::map appear to have a different layout based on the value of `__cplusplus`.

Disabling LTO works around the problem.

```c++
  template<typename _Val>
    struct _Rb_tree_node : public _Rb_tree_node_base
    {
      typedef _Rb_tree_node<_Val>* _Link_type;

#if __cplusplus < 201103L
      _Val _M_value_field;

      _Val*
      _M_valptr()
      { return std::__addressof(_M_value_field); }

      const _Val*
      _M_valptr() const
      { return std::__addressof(_M_value_field); }
#else
      __gnu_cxx::__aligned_membuf<_Val> _M_storage;

      _Val*
      _M_valptr()
      { return _M_storage._M_ptr(); }

      const _Val*
      _M_valptr() const
      { return _M_storage._M_ptr(); }
#endif
    };
```

**Comment by dominichamon** [comment]
Maybe we should change
https://github.com/google/benchmark/blob/master/test/CMakeLists.txt#L108 so
that we only build the cxx03 tests for cxx03 builds, and then add to travis
a cxx03 build and test.



Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*
