### ISSUE TITLE
Real time averaging for threaded Benchmarks

### ISSUE THREAD

**Issue by bimmlerd** [google/benchmark#429]
From https://github.com/google/benchmark/blob/master/src/benchmark.cc#L325 I understand that the real time reported from threads is being averaged.
I find this behaviour unexpected, I would have intuitively expected the real time in a threaded benchmark to be the max real time a single thread used.

**Comment by dominichamon** [comment]
Example output comparing runs for thread range with and without realtime:

```
BM_CalculatePi/threads:1                 12406 ns      11982 ns      58755
BM_CalculatePi/threads:2                  9306 ns      11808 ns      58672
BM_CalculatePi/threads:4                  6132 ns      11482 ns      60272
BM_CalculatePi/threads:8                  6010 ns      11553 ns      59600
BM_CalculatePi/threads:16                 5508 ns      11668 ns      59728
BM_CalculatePi/threads:32                 4139 ns      11567 ns      59648
BM_CalculatePi/real_time/threads:1       11205 ns      11181 ns      61231
BM_CalculatePi/real_time/threads:2        5761 ns      11214 ns     112944
BM_CalculatePi/real_time/threads:4        4082 ns      11548 ns     164852
BM_CalculatePi/real_time/threads:8        4014 ns      11636 ns     173552
BM_CalculatePi/real_time/threads:16       3732 ns      11613 ns     160000
BM_CalculatePi/real_time/threads:32       3758 ns      11612 ns     213088

```

We do this to make a reasonable comparison between the cpu time, real time,
and, if used, manual time. Using the max (or min, i suppose) would also
work. Ideally we'd show the full distribution through percentiles over
threads, as we could do over repetitions, but the reporting becomes complex.




Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by EricWF** [comment]
I agree with @dominichamon here. Averaging the real-time results provides a more reasonable comparison with CPU time.
