### ISSUE TITLE
Make cross-compiling easier

### ISSUE THREAD

**Issue by pwnall** [google/benchmark#432]
[cmake/CXXFeatureCheck.cmake](https://github.com/google/benchmark/blob/master/cmake/CXXFeatureCheck.cmake) uses try_run, which is bound to fail when cross-compiling. The [try_run documentation](https://cmake.org/cmake/help/git-master/command/try_run.html) warns that the command will be a pain in cross-compiling, and suggests guarding it with an `if(CMAKE_CROSSCOMPILING)` block. Will you please consider adopting that suggestion?

Background: I'm including this in a project of mine, and I'm trying to cross-compile for Android using `-DCMAKE_SYSTEM_NAME=Android -DCMAKE_ANDROID_NDK=$HOME/Library/Android/sdk/ndk-bundle -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DCMAKE_BUILD_TYPE=Release`. I was able work this issue by adding `-DRUN_HAVE_POSIX_REGEX=0`, but that requires looking around.

Thank you for all your hard work!

**Comment by dominichamon** [comment]
I think that would be fine. The danger will be that when cross-compiling users will need to explicitly set up features anyway, much like you have had to, but it should at least work more transparently, maybe?
