### ISSUE TITLE
Add .vs/ to .gitignore

### ISSUE THREAD

**Issue by henrik-jensen** [google/benchmark#434]
To better facilitate the new vs 2017 cmake/folder functionality. ( Just open the benchmark folder from inside VS to create a buildable cmake project) how about adding 
```
# Visual studio poop bag
.vs/
CMakeSettings.json
```
to `.gitignore`, so we don't have changed files after Visual studio has relieved itself. :)
( Visual Studio creates a .vs folder for various project configuration files in same folder as `CMakeLists.txt` when opening a cmake project)
**Edit:**
VS also drops a `CMakeSettings.json` if you need to change the used CMake command line settings from the VS gui. (sadly they don't use .vs/ for that.). VS users can then change the `"buildRoot"` lines generated in `CMakeSettings.json` from
```
"buildRoot":  "${env.LOCALAPPDATA}\\CMakeBuild\\${workspaceHash}\\build\\${name}"
```
which gives "nice" default target paths like
`c:\Users\THE_CURRENT_USER\AppData\Local\CMakeBuild\B6EE9182-8895-46E6-8129-2C208E2E890D\build\x64-Release`
to, say
 ```
"buildRoot": "${projectDir}\\build\\vs2017\${name}"
```
setting output target to `BENCHMARK_ROOT\build\vs2017\x64-Release` which seems more natural in respect to the way the 'benchmark' build is setup.

**Comment by dominichamon** [comment]
Sounds like a great plan. Patches welcome.

**Comment by henrik-jensen** [comment]
Thanks @aJetHorn for the commit #522.
