### ISSUE TITLE
BENCHMARK_TEMPLATE needs more sophisticated compiler check

### ISSUE THREAD

**Issue by NeumannIMT** [google/benchmark#444]
Under Visual Studio 2017 I am unable to use the variadic version of BENCHMARK_TEMPLATE due to the the check:
`#if __cplusplus >= 201103L`
and __cplusplus is still set to 199711L in modern VS versions. 
changing it to 
`#if __cplusplus >= 201103L || _MSC_VER >= 1900`
solves my problem but it feels hacked and may need a more sophisticated solution. 

(Line 819 in benchmark_api.h)

**Comment by EricWF** [comment]
Urg. Of course... @NeumannIMT could you test the suggested patch? Our Appveyor Windows builders seem to be broken (builds have been queued for months).

**Comment by NeumannIMT** [comment]
Build output (ALL_BUILD using default CMAKE settings) from your fix-cxx11 branch:

VS2017: 
[build_output_VS2017.txt](https://github.com/google/benchmark/files/1302261/build_output_VS2017.txt)
clang-cl (LLVM 6.0, fails to build 1 project due to exception settings (bug in cmakelists compiler settings?)):
[build_output_clang-cl_LLVM_6.txt](https://github.com/google/benchmark/files/1302262/build_output_clang-cl_LLVM_6.txt)

Since RUN_TESTS did not work from the VS IDE and also the test adapter for gtest did not work so I ran the test manually using a batch file:

VS2017:
[VS2017_out.txt](https://github.com/google/benchmark/files/1302285/VS2017_out.txt)
[VS2017_err.txt](https://github.com/google/benchmark/files/1302286/VS2017_err.txt)
user_counters_tabular_tests.exe calls abort()

clang-cl(LLVM 6):
[LLVM_out.txt](https://github.com/google/benchmark/files/1302292/LLVM_out.txt)
[LLVM_err.txt](https://github.com/google/benchmark/files/1302293/LLVM_err.txt)
user_counters_tabular_tests.exe also calls abort()

For me the fix seems to work and all other problems seem to be related to other issues
