### ISSUE TITLE
AUTHORS and CONTRIBUTORS not sorted

### ISSUE THREAD

**Issue by jwakely** [google/benchmark#448]
Both files say:

`# Please keep the list sorted.`

and both files are incorrectly sorted.

**Comment by jwakely** [comment]
Not fixed: 
JianXiong < Joao (in `AUTHORS` too)
Kai < Kaito
Tobias < Tom

**Comment by dominichamon** [comment]
haha alphabets are hard

**Comment by jwakely** [comment]
:-)  Thanks - I will try to keep them sorted if/when I add myself!
