### ISSUE TITLE
Empty benchmark running slower than a non empty one

### ISSUE THREAD

**Issue by FredTingaud** [google/benchmark#456]
Hi,
When running the following benchmark: http://quick-bench.com/NBZW9B9t5Xqr2FRIlk7Y8Wzlhj4 with clang3.8 -O3, the first benchmark, that contains no code in the while(state.KeepRunning) body returns a higher time than the next one, that creates a string. (generated assembly for both benchmarks is visible in the bottom right tabs).
The same result happens often enough that I think I can rule out the hypothesis of it being due to noise.
Am I doing something wrong here, or is the compiler actually generating better code for the non-empty benchmark?
In the second case, do you think there is something that could be done to avoid this problem?

The corresponding google benchmark output is as follow:
`  "benchmarks": [
    {
      "name": "DoNothing",
      "iterations": 261491884,
      "real_time": 11,
      "cpu_time": 3,
      "time_unit": "ns"
    },
    {
      "name": "DoSomething",
      "iterations": 305503085,
      "real_time": 9,
      "cpu_time": 2,
      "time_unit": "ns"
    },
    {
      "name": "Noop",
      "iterations": 276862199,
      "real_time": 10,
      "cpu_time": 3,
      "time_unit": "ns"
    }
  ]`

**Comment by dominichamon** [comment]
I'm not sure what this site is doing exactly, but showing the NOOP bar
suggests the reason: CPU time for the first case is the same as NOOP time.
Ie, it does nothing.

Running the same benchmark locally:
"
---------------------------------------------------
Benchmark            Time           CPU Iterations
---------------------------------------------------
DoNothing            4 ns          4 ns  162935671
DoSomething         60 ns         60 ns   11839155
"

which is what i'd expect.


Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by FredTingaud** [comment]
(just to be clear, I am the one who wrote the site).

Yes, the fact that the first bar goes to 1 is expected, both having exactly the same code.
But the second one runs in 0.66 this time, which I clearly didn't expect.

On your machine, the results you get make total sense to me. Which compiler / flags did you use?

**Comment by dominichamon** [comment]
(the site is great! i've been dying for a travis-like/godbolt like
benchmarky thing :))

clang++-3.5 and 'Release' build is this:

---------------------------------------------------
Benchmark            Time           CPU Iterations
---------------------------------------------------
DoNothing            2 ns          2 ns  341417994
DoSomething         46 ns         46 ns   15023047

How do you define 'NOOP time'? Maybe it would be better to just report the
CPU time raw?



Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by FredTingaud** [comment]
(Thanks! I was aiming at something godbolt like.)

The NOOP time is exactly the same code as DoNothing, which is why it gives the same time of 3ns.
But I wonder why with -03 I get a "DoSomething" of 2ns, when it is creating a string on top of running the benchmark.


Also, for the raw time, I wrote an explanation in the "About" section, but the idea is that there is not enough control on the hardware to have a meaningful raw time. I want people to use the site only to compare benchmarks run on the same hardware at the same time, as it is the only way to get meaningful results.

**Comment by dominichamon** [comment]
Got it. Well, if the run is for all the benchmarks and you report the
context alongside the relative timings of each benchmark, i think you're
covering that hardware issue. Ie, a rerun might give you different absolute
numbers, but that doesn't matter.

Some quick tests:

optim = None, Something == 4xNothing
optim = O1, Something == 8xNothing
optim = O2, Something == Nothing (but both == 0.66)
optim = O3, Something == 0.6xNothing


this is not what i'd expect :)

can you show the raw output somewhere? maybe as a json blob on the dev
console in the browser.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by FredTingaud** [comment]
I updated my first message with the raw output from google benchmark (in json mode). I will try to add a way to get that output in the website, but it might take me a bit more time.

**Comment by dominichamon** [comment]
that's very odd. i'm not at all sure what might be going on.

the compiled assembly looks appropriate at each optimisation level.

As a further test I replaced the original version with the one using the new ranged-for loop construct and got this:

```
---------------------------------------------------
Benchmark            Time           CPU Iterations
---------------------------------------------------
DoNothing            0 ns          0 ns 1000000000
DoSomething         44 ns         44 ns   15281068
```
which is exactly what i'd expect from a noop benchmark.

**Comment by FredTingaud** [comment]
The new ranged-for loop is indeed way faster and solves the issue.
Thanks
