### ISSUE TITLE
Better documentation management

### ISSUE THREAD

**Issue by dominichamon** [google/benchmark#470]
We have README.md and we have a copy of that as a comment in benchmark/benchmark.h

I like having the README (it plays well with github) but i'd like to still have documentation for those that have the library installed. Is it totally unreasonable to put the README.md alongside the header (in /usr/local/include/benchmark, for instance) on installation?

**Comment by furkanusta** [comment]
I think instead of putting README in the same place with headers, you can use doc folder. I have lots of documentations installed by third-party libraries in both /usr/share/doc/ and /usr/local/share/doc
