### ISSUE TITLE
Warning C4800 on  MSVC 2015

### ISSUE THREAD

**Issue by ketjow4** [google/benchmark#476]
Hey,

On the release of benchmark 1.3.0 there is a Warning generated for forcing std::size_t to bool in Visual Studio 2015.

Warning	C4800	'std::size_t': forcing value to bool 'true' or 'false' (performance warning)	\benchmark.1.3.0\include\benchmark\benchmark.h	line 436	

Corresponding line of code:
` bool const res = --total_iterations_;
`

Possible solution would be to change this line to:
`bool const res = --total_iterations_ == 0;`

**Comment by dominichamon** [comment]
I think you mean `!= 0`. Fix in #477.
