### ISSUE TITLE
benchmark's LTO support does not work with clang

### ISSUE THREAD

**Issue by madars** [google/benchmark#478]
The `BENCHMARK_ENABLE_LTO` option does not seem to be working with clang. In particular, on Ubuntu 17.10 `CXX=clang++ cmake -GNinja -DBENCHMARK_ENABLE_LTO=ON ..` followed by `ninja` yields:

```
[1/17] : && /usr/bin/clang++  -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -Wshorten-64-to-32  -Wfloat-equal  -fstrict-aliasing  -Wstrict-aliasing  -Wthread-safety  -flto  -rdynamic test/CMakeFiles/complexity_test.dir/complexity_test.cc.o  -o test/complexity_test  test/liboutput_test_helper.a src/libbenchmark.a -lpthread -lrt && :
FAILED: test/complexity_test 
: && /usr/bin/clang++  -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -Wshorten-64-to-32  -Wfloat-equal  -fstrict-aliasing  -Wstrict-aliasing  -Wthread-safety  -flto  -rdynamic test/CMakeFiles/complexity_test.dir/complexity_test.cc.o  -o test/complexity_test  test/liboutput_test_helper.a src/libbenchmark.a -lpthread -lrt && :
test/liboutput_test_helper.a: error adding symbols: Archive has no index; run ranlib to add one
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

I tried setting `CMAKE_AR` and `CMAKE_RANLIB` to equal `llvm-ar` and `llvm-ranlib`, or additionally passing `-fuse-ld=gold` in `CMAKE_EXE_LINKER_FLAGS`, but these didn't resolve the above.

**Comment by dominichamon** [comment]
i wonder if this is because you're overriding CXX directly. 

i just tried using the method from https://stackoverflow.com/questions/30549502/installed-clang3-6-on-ubuntu-cant-select-as-alternative to set the default compiler to clang/clang++ and everything built and worked as expected.

**Comment by dominichamon** [comment]
(i realise this isn't a great solution for switching between compilers on a platform, but i'm curious if it works)

**Comment by madars** [comment]
Very interesting! [CMake FAQ](https://cmake.org/Wiki/CMake_FAQ#How_do_I_use_a_different_compiler.3F) suggests two ways of specifying the compiler; first is setting `CXX` environment variable as above. Second is using the `-DCMAKE_CXX_COMPILER` command line argument. I tried this second way now, but unfortunately with the same results.

**Comment by madars** [comment]
By the way, I just tried the `update-alternatives` approach on a fully-updated Ubuntu 17.10 and it didn't work:

```
$ c++ --version
clang version 4.0.1-6 (tags/RELEASE_401/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
$ ninja -j1 -v
[1/18] : && /usr/bin/c++  -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -Wshorten-64-to-32  -Wfloat-equal  -fstrict-aliasing  -Wstrict-aliasing  -Wthread-safety  -flto  -rdynamic -Wno-odr test/CMakeFiles/cxx03_test.dir/cxx03_test.cc.o  -o test/cxx03_test  src/libbenchmark.a -lpthread -lrt && :
FAILED: test/cxx03_test 
: && /usr/bin/c++  -std=c++11  -Wall  -Wextra  -Wshadow  -pedantic  -pedantic-errors  -Wshorten-64-to-32  -Wfloat-equal  -fstrict-aliasing  -Wstrict-aliasing  -Wthread-safety  -flto  -rdynamic -Wno-odr test/CMakeFiles/cxx03_test.dir/cxx03_test.cc.o  -o test/cxx03_test  src/libbenchmark.a -lpthread -lrt && :
src/libbenchmark.a: error adding symbols: Archive has no index; run ranlib to add one
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.
```

**Comment by madars** [comment]
As another data point, I tried updating clang (more precisely, installing `clang-5.0` package for which `clang++ -v` gives `clang version 5.0.0-3 (tags/RELEASE_500/final)`) and the results here are the same.

**Comment by LebedevRI** [comment]
> or additionally passing -fuse-ld=gold in CMAKE_EXE_LINKER_FLAGS

Why `CMAKE_EXE_LINKER_FLAGS` only?

**Comment by apmanol** [comment]
The trick and explanation is [here](https://stackoverflow.com/questions/39236917/using-gccs-link-time-optimization-with-static-linked-libraries) , I think:

```
CMAKE_AR=/usr/bin/ld.gold
CMAKE_RANLIB=/usr/bin/ld.gold

add_cxx_compiler_flag(-flto)
add_cxx_compiler_flag(-Wodr)

SET(CMAKE_AR  "gcc-ar")
SET(CMAKE_C_ARCHIVE_CREATE "<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>")
SET(CMAKE_C_ARCHIVE_FINISH   true)
set(CMAKE_CXX_ARCHIVE_CREATE "<CMAKE_AR> qcs <TARGET> <LINK_FLAGS> <OBJECTS>")
set(CMAKE_CXX_ARCHIVE_FINISH true)

```
