### ISSUE TITLE
Please add support for s390x arch

### ISSUE THREAD

**Issue by gladk** [google/benchmark#481]
benchmark was added to the Debian archive recently [1]. It was found that the library builds fine almost on all release-relevant architectures except s390x [2]. It ends with the following message:

`/<<PKGBUILDDIR>>/src/cycleclock.h:166:2: error: #error You need to define CycleTimer for your OS and CPU
 #error You need to define CycleTimer for your OS and CPU
  ^~~~~
/<<PKGBUILDDIR>>/src/cycleclock.h: In function 'int64_t benchmark::cycleclock::Now()':
/<<PKGBUILDDIR>>/src/cycleclock.h:168:1: warning: no return statement in function returning non-void [-Wreturn-type]
 } `

It would be good to have the support for this arch as well.

[1] https://tracker.debian.org/pkg/benchmark
[2] https://buildd.debian.org/status/fetch.php?pkg=benchmark&arch=s390x&ver=1.3.0-1&stamp=1510616573&raw=0

Thanks

**Comment by dominichamon** [comment]
fixed? @gladk

**Comment by gladk** [comment]
Yes, thanks! I have cherry-picked the commit and now it builds on s390x also [1].

[1] https://buildd.debian.org/status/package.php?p=benchmark
