### ISSUE TITLE
Extra semicolon warning emitted with GCC when using BENCHMARK_MAIN

### ISSUE THREAD

**Issue by ldionne** [google/benchmark#494]
The following code triggers a warning with GCC when `-Wpedantic` is enabled:

```c++
BENCHMARK_MAIN();
```

The warning is about the semicolon being unnecessary, because `BENCHMARK_MAIN()` expands to

```c++
int main(int, char**) {
  ...
}
```

[(reproduction)](https://wandbox.org/permlink/C80p8zmjacQQQqaS)

This is unfortunate because the macro is used everywhere in the documentation with a semicolon. I propose changing the macro to the following, such that the semicolon becomes mandatory and compilers stop warning:

```c++
#define BENCHMARK_MAIN()              \
  int main(int , char** ) {           \
    ...                               \
  }                                   \
  int main(int, char**)
```

[(example)](https://wandbox.org/permlink/MiUL7hlJfef20yMn)

This should not be a breaking change since AFAICT the macro is always documented with a semicolon after it. For those that will be broken by it, the fix is trivial (just add the semicolon).

**Comment by EricWF** [comment]
Sounds reasonable. Thanks @ldionne. Feel free to submit a PR, if not I'll get to it over christmas.

**Comment by Bu11etmagnet** [comment]
Unfortunately, this makes it impossible to write cross-platform code in the face of `-pedantic -Werror`. Code with the semicolon fails to compile when benchmark.h is the older version:
```
error: extra ';' [-Werror=pedantic]
 BENCHMARK_MAIN();
                 ^
```
