### ISSUE TITLE
Wrong result of cxx_feature_check depends of CMAKE_CXX_FLAGS in top CMakeList.txt file

### ISSUE THREAD

**Issue by Gluttton** [google/benchmark#50]
I have the Project with structure like this:

<pre>
.
├── CMakeLists.txt
├── externals
│   ├── benchmark
│   └── gmock
├── include
├── src
└── test
</pre>

My top level `CMakeLists.txt` has following content:

<pre>
cmake_minimum_required  (VERSION 2.8)
project                 (MasterProject)

add_subdirectory (src)
add_subdirectory (externals/benchmark)
add_subdirectory (externals/gmock)
</pre>

My workflow looks like and it works good:

<pre>
mkdir build
cd build
cmake ..
make
</pre>

But when I add warning options in the  top level `CMakeLists.txt`:

<pre>
set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wzero-as-null-pointer-constant")
</pre>

I will get error on configuration stage:

<pre>
$ cmake ..
-- The C compiler identification is GNU 4.8.2
-- The CXX compiler identification is GNU 4.8.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test HAVE_FLAG_CXX_14
-- Performing Test HAVE_FLAG_CXX_14 - Failed
-- Performing Test HAVE_FLAG_CXX_11
-- Performing Test HAVE_FLAG_CXX_11 - Success
-- Performing Test HAVE_FLAG_CXX_0X
-- Performing Test HAVE_FLAG_CXX_0X - Success
-- Performing Test HAVE_WALL
-- Performing Test HAVE_WALL - Success
-- Performing Test HAVE_WSHADOW
-- Performing Test HAVE_WSHADOW - Success
-- Performing Test HAVE_WERROR
-- Performing Test HAVE_WERROR - Success
-- Performing Test HAVE_PEDANTIC_ERRORS
-- Performing Test HAVE_PEDANTIC_ERRORS - Success
-- Performing Test HAVE_FNO_STRICT_ALIASING
-- Performing Test HAVE_FNO_STRICT_ALIASING - Success
-- git Version: v0.0.0
-- Version: 0.0.0
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- Failed
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- Failed
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- Failed
CMake Error at externals/benchmark/src/CMakeLists.txt:12 (message):
  Failed to determine the source files for the regular expression backend

-- Configuring incomplete, errors occurred!
See also "/home/gluttton/benchmark/build/CMakeFiles/CMakeOutput.log".
See also "/home/gluttton/benchmark/build/CMakeFiles/CMakeError.log".
</pre>

**Comment by dkonik** [comment]
Hi, I see that this was closed, but I am still getting the same 
`CMake Error at CMakeLists.txt:21 (message):
  Failed to determine the source files for the regular expression backend`
error, and I was wondering if this was resolved. There's not much documentation/help online, so I was hoping maybe you guys could help.
