### ISSUE TITLE
COMPILER_MSVC macro redefinition warning in Windows

### ISSUE THREAD

**Issue by f9rocket** [google/benchmark#513]
When building google benchmark in Windows with Bazel and VS2017 I get the following warning:

src\internal_macros.h(13): warning C4005: 'COMPILER_MSVC': macro redefinition
src\internal_macros.h(13): note: command-line arguments:  see previous definition of 'COMPILER_MSVC'

Just in case, this is my bazel BUILD file for google benchmark:

```
cc_library(
    name = "benchmark",

    srcs = glob(["src/*.cc"]),
    hdrs = glob(["include/**/*.h", "src/*.h"]),

    includes = ["include", "."],

    copts = ["-DHAVE_STD_REGEX"],
    linkstatic = 1,

    visibility = ["//visibility:public"],
)
```

**Comment by dominichamon** [comment]
I guess bazel/vs2017 set those macros. we should guard against them in `src/internal_macros.h`

**Comment by f9rocket** [comment]
@dominichamon yep, that seems to be the case: https://github.com/bazelbuild/bazel/blob/master/tools/cpp/CROSSTOOL#L626
