### ISSUE TITLE
benchmark runtime registration won't work with function with non-copyable parameter

### ISSUE THREAD

**Issue by lijinpei** [google/benchmark#515]
As the following code shows: https://gist.github.com/lijinpei/f5c09cbf453e417c559f3e562ef376f2
The problem is caused by by-value capture of lambda in https://github.com/google/benchmark/blob/e1c3a83b8197cf02e794f61228461c27d4e78cfb/include/benchmark/benchmark.h#L927
Statically registered benchmarks won't have this problem because they are registered through this: https://github.com/google/benchmark/blob/e1c3a83b8197cf02e794f61228461c27d4e78cfb/include/benchmark/benchmark.h#L1010
Also, this implies that statically registered captures have by-reference semantics with respect to their parameters, while dynamically registered captures have by-value semantics: https://gist.github.com/lijinpei/6937c10983f8b429ee00b97c09191e3a

**Comment by EricWF** [comment]
No. That lamba is declared as having no captures. All referenced identifiers must be available at global scope. They are not captured either by-value or by-reference -- they are not captured at all.

the BENCHMARK_CAPTURE macro is only intended to be used at global scope.

Closing as NAD. Re-open if you disagree.
