### ISSUE TITLE
`Range(int start, int limit)`-maximum int is too small for number theory.

### ISSUE THREAD

**Issue by NAThompson** [google/benchmark#516]
Many number theoretic algorithms are O(log(log(N)). When benchmarking these using (say)

    BENCHMARK(BM_FloorSqrt)->Range(2, 9223372036854775808LL)->RangeMultiplier(2)->Complexity();

the upper limit overflows. Using only 32 bits for the upper range does not give very much test data.

Changing the arguments to `Range` to `long long`s or `size_t`s would dramatically expand the range or data values that can be probed.

**Comment by dominichamon** [comment]
`int64_t` if you want specifically 64-bits please, and patches welcome :)

**Comment by manparvesh** [comment]
Hi @dominichamon 
I have created a PR (#519) for this issue. Could you please take a look?
