### ISSUE TITLE
Custom context fields

### ISSUE THREAD

**Issue by mmcloughlin** [google/benchmark#525]
I am interested in adding custom context fields to benchmarks. As far as I can tell this isn't possible right now? If not would it be possible to add?

The use case I have in mind is adding our software build version to the context. This way output JSON/CSV data files can be passed around or stored and contain the information required to reproduce results.

Not critical since this information can be stored elsewhere. But it might be nice. Thoughts?

**Comment by dominichamon** [comment]
It sounds like a nice addition. maybe a method that can be called from the
main, or a key-value set passed in to the main macro maybe?

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

On Wed, Feb 7, 2018 at 2:40 PM, Michael McLoughlin <notifications@github.com

**Comment by mmcloughlin** [comment]
Thanks for the quick reply.

I would have thought it made sense to leave the `BENCHMARK_MAIN` macro as it is, since adding context fields doesn't seem like the most common use case. But a method that could be called from a custom `main` function would be ideal.

**Comment by EricWF** [comment]
I think this is a bug we should try to fix on the `v2` branch using JSON.

I think the best way would be to make the `BenchmarkFamilies` class part of the public interface. I'll take a stab at something.

**Comment by mmcloughlin** [comment]
Just thought I'd bump this, since I find myself wishing I had this feature a second time :) Right now I have a benchmark that uses a GPU and I would like to be able to output GPU information to the context.

**Comment by LebedevRI** [comment]
You currently could use `SetLabel()`, though that is not really a proper solution.

**Comment by marehr** [comment]
> You currently could use `SetLabel()`, though that is not really a proper solution.

But, `SetLabel()` is for each individual benchmark, right?

I also wish I could set some global meta-data like the build commit or the used library versions.

**Comment by dominichamon** [comment]
A couple of options then:

1. a flag that takes a key-value pair and can be repeated: `--benchmark_context="myfoo=bar"`
2. a function that can be called from a custom main: `benchmark::AddContext(std::string key, std::string value)`
3. (longer term): Something with the `BenchmarkFamilies` interface.

If anyone wants to take a crack at #2 i think it's the quickest option. #1 is maybe more flexible (or a combination of 1 and 2) but would be a little more work.

**Comment by mmcloughlin** [comment]
Since posting this issue two years ago I now have additional use cases for it. Adding software version information is still useful, but I'd also like to be able to query more information about system and process configuration, for example:

* What is CPU frequency set to? 
* What is the scaling governor set to
* Is intel turbo enabled?
* CPU affinity of the process (how many cores does it have?)
* Process priority (nice or rt priority)
* ...

Essentially I'd like to be able to augment the existing context with various other fields read from sysfs/procfs.

@dominichamon For this use case the `benchmark::AddContext` API from option 2 would be ideal. The CLI flag would still be useful for metadata like software version etc.

**Comment by jkeiser** [comment]
My use case is mainly to support archiving these and sending them around: I'd like to add the version of software being tested, the git commit when available. I also want to get the cpuid, as it's pretty important for my use case (simdjson).

**Comment by dominichamon** [comment]
@mmcloughlin @jkeiser i started with the flag because it's the easiest place to start, but i will add the API after #1127 is merged.
