### ISSUE TITLE
Run each benchmark in a separate process?

### ISSUE THREAD

**Issue by brenoguim** [google/benchmark#537]
I started using this library to benchmark different hash map implementations. At one point, I tried to (ab)use this framework to also report memory overhead on the different benchmarks.

I chose to measure the resident memory on the process before and after filling up the hash map, and use the counter reports to show the measurement.
It failed. That's because after one benchmark runs and raises the resident memory, it may not return all the memory to the OS when the hash map is destroyed. So the next benchmark run will reuse that memory instead of requesting from the OS.

This got me thinking that benchmarks may be affected by the state of the global allocator and skew results depending on the order they run.
I only started using this library two days ago, so I might be missing something.

In case I'm correct, would it make more sense to run each benchmark on a separate process? Could that change yield more precise results? Has anyone else pointed to similar issue?
I suppose they would be more precise, but perhaps less realistic, in the sense that the global allocator isn't "fresh clean"  when most of the code runs.

Thanks for this awesome library :)

**Comment by pleroy** [comment]
I find it hard to be excited about this:

* Forking a process would make the benchmarks considerably slower, so it would have to be optional.
* Forking a process in a way that works on all the OSes where the library runs is no easy feat.  See for instance what googletest does for death tests.  There are also nasty interactions with threads (again, see googletest).
* For benchmarks to be heavily affected by the state of the allocator, they'd have to spend most of their time in the allocator, in which case you are really benchmarking the allocator, not your code.

Overall, it seems like a lot of complexity for little benefits.

**Comment by brenoguim** [comment]
All fair points, although the last one is a bit controversial. Benchmarks could be used to compare implementations and if one implementation heavily relies on the allocator to be warmed up, then it's not a fair comparison.

Still, I fully agree with the conclusion.

Thank you for the answer!

**Comment by brenoguim** [comment]
By the way, I implemented the process launching (linux only of course), and it seems to work.

But I was not happy with the precision of getting the resident memory, so I ended up reverting everything and using malloc hooks :) Works like a charm (though its deprecated).

**Comment by dominichamon** [comment]
For reference, internally there is a version that supports memory tracking but it relies on linking against tcmalloc.

That's certainly something we can consider but it would change the allocation patterns in the cases where benchmarks are meant to be benchmarking against the system allocator.

**Comment by thatsafunnyname** [comment]
WRT "memory overhead".  Cross reference https://github.com/google/benchmark/issues/1217#issuecomment-1808627490 , this contains an example using tcmalloc hooks and custom counters.
