### ISSUE TITLE
gtest/gtest.h not found in statistics_test.cc

### ISSUE THREAD

**Issue by rzuckerm** [google/benchmark#538]
I'm using g++-4.8.4 in Ubuntu 14.04. When I try to build I'm seeing the following error in statistics_test.cc:

`Scanning dependencies of target statistics_test`
`[ 92%] Building CXX object test/CMakeFiles/statistics_test.dir/statistics_test.cc.o`
`/home/xxx/git/benchmark/test/statistics_test.cc:6:25: fatal error: gtest/gtest.h: No such file or directory`
` #include "gtest/gtest.h"`
`                         ^`
`compilation terminated.`

I used the following to build the code:

`git clone https://github.com/google/benchmark.git`
`cd benchmark`
`mkdir build`
`cd build`
`cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON`
`make`

If I use `-DBENCHMARK_ENABLE_GTEST_TESTS=OFF` instead of `-DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON`, the code compiles and links just fine.

Any ideas what's going wrong? I would like to be able to run the unit tests.

**Comment by dominichamon** [comment]
what's the output of the cmake where it tries to download the dependencies?

**Comment by rzuckerm** [comment]
$ cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON
-- git Version: v1.2.0-56f52ee2
-- Version: 1.2.0
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- compiled but failed to run
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/developer/git/benchmark/build

**Comment by dominichamon** [comment]
Here's an example of the equivalent running on travis (g++-4.8.4 on ubuntu): https://travis-ci.org/google/benchmark/jobs/350268756

can you try a clean build (just blow away the build directory entirely) and post the full log of the cmake/make output?

**Comment by rzuckerm** [comment]
~/git/benchmark/build$ **cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON**
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found Git: /usr/bin/git (found version "1.9.1") 
-- git Version: v1.2.0-61497236
-- Version: 1.2.0
-- Performing Test HAVE_CXX_FLAG_STD_CXX11
-- Performing Test HAVE_CXX_FLAG_STD_CXX11 - Success
-- Performing Test HAVE_CXX_FLAG_WALL
-- Performing Test HAVE_CXX_FLAG_WALL - Success
-- Performing Test HAVE_CXX_FLAG_WEXTRA
-- Performing Test HAVE_CXX_FLAG_WEXTRA - Success
-- Performing Test HAVE_CXX_FLAG_WSHADOW
-- Performing Test HAVE_CXX_FLAG_WSHADOW - Success
-- Performing Test HAVE_CXX_FLAG_WERROR
-- Performing Test HAVE_CXX_FLAG_WERROR - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC
-- Performing Test HAVE_CXX_FLAG_PEDANTIC - Success
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS
-- Performing Test HAVE_CXX_FLAG_PEDANTIC_ERRORS - Success
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32
-- Performing Test HAVE_CXX_FLAG_WSHORTEN_64_TO_32 - Failed
-- Performing Test HAVE_CXX_FLAG_WFLOAT_EQUAL
-- Performing Test HAVE_CXX_FLAG_WFLOAT_EQUAL - Success
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_FSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING
-- Performing Test HAVE_CXX_FLAG_WSTRICT_ALIASING - Success
-- Performing Test HAVE_CXX_FLAG_WD654
-- Performing Test HAVE_CXX_FLAG_WD654 - Failed
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY
-- Performing Test HAVE_CXX_FLAG_WTHREAD_SAFETY - Failed
-- Performing Test HAVE_CXX_FLAG_WINVALID_OFFSETOF
-- Performing Test HAVE_CXX_FLAG_WINVALID_OFFSETOF - Success
-- Performing Test HAVE_CXX_FLAG_WNO_INVALID_OFFSETOF
-- Performing Test HAVE_CXX_FLAG_WNO_INVALID_OFFSETOF - Success
-- Performing Test HAVE_CXX_FLAG_COVERAGE
-- Performing Test HAVE_CXX_FLAG_COVERAGE - Success
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX
-- Performing Test HAVE_STD_REGEX -- compiled but failed to run
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
CMake Warning (dev) at /usr/share/cmake-2.8/Modules/ExternalProject.cmake:242 (message):
  value 'EXCLUDE_FROM_ALL' with no previous keyword in ExternalProject_Add
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1762 (_ep_parse_arguments)
  cmake/HandleGTest.cmake:34 (ExternalProject_Add)
  cmake/HandleGTest.cmake:82 (build_external_gtest)
  CMakeLists.txt:217 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/share/cmake-2.8/Modules/ExternalProject.cmake:242 (message):
  value 'ON' with no previous keyword in ExternalProject_Add
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/ExternalProject.cmake:1762 (_ep_parse_arguments)
  cmake/HandleGTest.cmake:34 (ExternalProject_Add)
  cmake/HandleGTest.cmake:82 (build_external_gtest)
  CMakeLists.txt:217 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test BENCHMARK_HAS_O3_FLAG
-- Performing Test BENCHMARK_HAS_O3_FLAG - Success
-- Performing Test BENCHMARK_HAS_CXX03_FLAG
-- Performing Test BENCHMARK_HAS_CXX03_FLAG - Success
-- Performing Test BENCHMARK_HAS_WNO_ODR
-- Performing Test BENCHMARK_HAS_WNO_ODR - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/developer/git/benchmark/build

~/git/benchmark/build$ **make**
Scanning dependencies of target googletest
[  2%] Creating directories for 'googletest'
[  4%] Performing download step (git clone) for 'googletest'
Cloning into 'googletest'...
remote: Counting objects: 10660, done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 10660 (delta 37), reused 58 (delta 30), pack-reused 10580
Receiving objects: 100% (10660/10660), 3.25 MiB | 0 bytes/s, done.
Resolving deltas: 100% (7839/7839), done.
Checking connectivity... done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[  7%] No patch step for 'googletest'
[  9%] Performing update step for 'googletest'
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[ 11%] Performing configure step for 'googletest'
loading initial cache file /home/developer/git/benchmark/build/googletest/tmp/googletest-cache.cmake
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/developer/git/benchmark/build/googletest/src/googletest-build
[ 14%] Performing build step for 'googletest'
Scanning dependencies of target gtest
[ 25%] Building CXX object googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
Linking CXX static library libgtest.a
[ 25%] Built target gtest
Scanning dependencies of target gmock
[ 50%] Building CXX object googlemock/CMakeFiles/gmock.dir/src/gmock-all.cc.o
Linking CXX static library libgmock.a
[ 50%] Built target gmock
Scanning dependencies of target gmock_main
[ 75%] Building CXX object googlemock/CMakeFiles/gmock_main.dir/src/gmock_main.cc.o
Linking CXX static library libgmock_main.a
[ 75%] Built target gmock_main
Scanning dependencies of target gtest_main
[100%] Building CXX object googlemock/gtest/CMakeFiles/gtest_main.dir/src/gtest_main.cc.o
Linking CXX static library libgtest_main.a
[100%] Built target gtest_main
[ 16%] Performing install step for 'googletest'
[ 25%] Built target gtest
[ 50%] Built target gmock
[ 75%] Built target gmock_main
[100%] Built target gtest_main
Install the project...
-- Install configuration: "RELEASE"
-- Installing: /home/developer/git/benchmark/build/googletest/lib/x86_64-linux-gnu/libgmock.a
-- Installing: /home/developer/git/benchmark/build/googletest/lib/x86_64-linux-gnu/libgmock_main.a
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock-generated-function-mockers.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock-generated-actions.h.pump
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock-more-actions.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock-generated-actions.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock-spec-builders.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock-more-matchers.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock-generated-matchers.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock-matchers.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock-generated-function-mockers.h.pump
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock-actions.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock-cardinalities.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock-generated-nice-strict.h.pump
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock-generated-nice-strict.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/internal
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/internal/gmock-port.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/internal/custom
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/internal/custom/gmock-generated-actions.h.pump
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/internal/custom/gmock-generated-actions.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/internal/custom/gmock-port.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/internal/custom/gmock-matchers.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/internal/gmock-internal-utils.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/internal/gmock-generated-internal-utils.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/internal/gmock-generated-internal-utils.h.pump
-- Installing: /home/developer/git/benchmark/build/googletest/include/gmock/gmock-generated-matchers.h.pump
-- Installing: /home/developer/git/benchmark/build/googletest/lib/x86_64-linux-gnu/pkgconfig/gmock.pc
-- Installing: /home/developer/git/benchmark/build/googletest/lib/x86_64-linux-gnu/pkgconfig/gmock_main.pc
-- Installing: /home/developer/git/benchmark/build/googletest/lib/x86_64-linux-gnu/libgtest.a
-- Installing: /home/developer/git/benchmark/build/googletest/lib/x86_64-linux-gnu/libgtest_main.a
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/gtest_pred_impl.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/gtest-param-test.h.pump
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/gtest-death-test.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/gtest-message.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/gtest-spi.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/gtest-param-test.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/gtest_prod.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/gtest-test-part.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/gtest-filepath.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/gtest-tuple.h.pump
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/gtest-type-util.h.pump
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/gtest-internal.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/gtest-param-util.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/gtest-death-test-internal.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/gtest-type-util.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/custom
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/custom/gtest-port.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/custom/gtest-printers.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/custom/gtest.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/gtest-string.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/gtest-port.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/gtest-param-util-generated.h.pump
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/gtest-tuple.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/gtest-linked_ptr.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/gtest-port-arch.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/internal/gtest-param-util-generated.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/gtest-printers.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/gtest.h
-- Installing: /home/developer/git/benchmark/build/googletest/include/gtest/gtest-typed-test.h
-- Installing: /home/developer/git/benchmark/build/googletest/lib/x86_64-linux-gnu/pkgconfig/gtest.pc
-- Installing: /home/developer/git/benchmark/build/googletest/lib/x86_64-linux-gnu/pkgconfig/gtest_main.pc
[ 19%] Completed 'googletest'
[ 19%] Built target googletest
Scanning dependencies of target benchmark
[ 21%] Building CXX object src/CMakeFiles/benchmark.dir/string_util.cc.o
[ 23%] Building CXX object src/CMakeFiles/benchmark.dir/reporter.cc.o
[ 26%] Building CXX object src/CMakeFiles/benchmark.dir/statistics.cc.o
[ 28%] Building CXX object src/CMakeFiles/benchmark.dir/json_reporter.cc.o
[ 30%] Building CXX object src/CMakeFiles/benchmark.dir/colorprint.cc.o
[ 33%] Building CXX object src/CMakeFiles/benchmark.dir/counter.cc.o
[ 35%] Building CXX object src/CMakeFiles/benchmark.dir/benchmark_register.cc.o
[ 38%] Building CXX object src/CMakeFiles/benchmark.dir/commandlineflags.cc.o
[ 40%] Building CXX object src/CMakeFiles/benchmark.dir/csv_reporter.cc.o
[ 42%] Building CXX object src/CMakeFiles/benchmark.dir/console_reporter.cc.o
[ 45%] Building CXX object src/CMakeFiles/benchmark.dir/sleep.cc.o
[ 47%] Building CXX object src/CMakeFiles/benchmark.dir/timers.cc.o
[ 50%] Building CXX object src/CMakeFiles/benchmark.dir/complexity.cc.o
[ 52%] Building CXX object src/CMakeFiles/benchmark.dir/benchmark.cc.o
[ 54%] Building CXX object src/CMakeFiles/benchmark.dir/sysinfo.cc.o
Linking CXX static library libbenchmark.a
[ 54%] Built target benchmark
Scanning dependencies of target basic_test
[ 57%] Building CXX object test/CMakeFiles/basic_test.dir/basic_test.cc.o
Linking CXX executable basic_test
[ 57%] Built target basic_test
Scanning dependencies of target benchmark_test
[ 59%] Building CXX object test/CMakeFiles/benchmark_test.dir/benchmark_test.cc.o
Linking CXX executable benchmark_test
[ 59%] Built target benchmark_test
Scanning dependencies of target output_test_helper
[ 61%] Building CXX object test/CMakeFiles/output_test_helper.dir/output_test_helper.cc.o
Linking CXX static library liboutput_test_helper.a
[ 61%] Built target output_test_helper
Scanning dependencies of target complexity_test
[ 64%] Building CXX object test/CMakeFiles/complexity_test.dir/complexity_test.cc.o
Linking CXX executable complexity_test
[ 64%] Built target complexity_test
Scanning dependencies of target cxx03_test
[ 66%] Building CXX object test/CMakeFiles/cxx03_test.dir/cxx03_test.cc.o
Linking CXX executable cxx03_test
[ 66%] Built target cxx03_test
Scanning dependencies of target diagnostics_test
[ 69%] Building CXX object test/CMakeFiles/diagnostics_test.dir/diagnostics_test.cc.o
Linking CXX executable diagnostics_test
[ 69%] Built target diagnostics_test
Scanning dependencies of target donotoptimize_test
[ 71%] Building CXX object test/CMakeFiles/donotoptimize_test.dir/donotoptimize_test.cc.o
Linking CXX executable donotoptimize_test
[ 71%] Built target donotoptimize_test
Scanning dependencies of target filter_test
[ 73%] Building CXX object test/CMakeFiles/filter_test.dir/filter_test.cc.o
Linking CXX executable filter_test
[ 73%] Built target filter_test
Scanning dependencies of target fixture_test
[ 76%] Building CXX object test/CMakeFiles/fixture_test.dir/fixture_test.cc.o
Linking CXX executable fixture_test
[ 76%] Built target fixture_test
Scanning dependencies of target map_test
[ 78%] Building CXX object test/CMakeFiles/map_test.dir/map_test.cc.o
Linking CXX executable map_test
[ 78%] Built target map_test
Scanning dependencies of target multiple_ranges_test
[ 80%] Building CXX object test/CMakeFiles/multiple_ranges_test.dir/multiple_ranges_test.cc.o
Linking CXX executable multiple_ranges_test
[ 80%] Built target multiple_ranges_test
Scanning dependencies of target options_test
[ 83%] Building CXX object test/CMakeFiles/options_test.dir/options_test.cc.o
Linking CXX executable options_test
[ 83%] Built target options_test
Scanning dependencies of target register_benchmark_test
[ 85%] Building CXX object test/CMakeFiles/register_benchmark_test.dir/register_benchmark_test.cc.o
Linking CXX executable register_benchmark_test
[ 85%] Built target register_benchmark_test
Scanning dependencies of target reporter_output_test
[ 88%] Building CXX object test/CMakeFiles/reporter_output_test.dir/reporter_output_test.cc.o
Linking CXX executable reporter_output_test
[ 88%] Built target reporter_output_test
Scanning dependencies of target skip_with_error_test
[ 90%] Building CXX object test/CMakeFiles/skip_with_error_test.dir/skip_with_error_test.cc.o
Linking CXX executable skip_with_error_test
[ 90%] Built target skip_with_error_test
Scanning dependencies of target statistics_test
[ 92%] Building CXX object test/CMakeFiles/statistics_test.dir/statistics_test.cc.o
/home/developer/git/benchmark/test/statistics_test.cc:6:25: fatal error: gtest/gtest.h: No such file or directory
 #include "gtest/gtest.h"
                         ^
compilation terminated.
make[2]: *** [test/CMakeFiles/statistics_test.dir/statistics_test.cc.o] Error 1
make[1]: *** [test/CMakeFiles/statistics_test.dir/all] Error 2
make: *** [all] Error 2

**Comment by dominichamon** [comment]
other than those suspicious looking warnings around HandleGtest.cmake, i
don't see anything obvious.

Maybe Eric (who added gtest) knows more.


Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by rzuckerm** [comment]
Any word on this?

**Comment by EricWF** [comment]
I'm in the middle of exams. I'll need a couple days before I can look into this.

**Comment by EricWF** [comment]
@rzuckerm What version of CMake are you using?

**Comment by rzuckerm** [comment]
```
$ cmake --version
cmake version 2.8.12.2
```

**Comment by rzuckerm** [comment]
@EricWF I pulled the latest code, and it fixes my issue. Thanks!
