### ISSUE TITLE
Fix some spelling errors

### ISSUE THREAD

**Issue by winksaville** [google/benchmark#542]
Some [spelling errors](https://github.com/ponylang/ponyc/pull/1603) were found by a bot in the ponyc downstream use of benchmark. I've asked the original author, @ka7,  if this is ok and he approved.

[Here is the change](https://github.com/winksaville/benchmark/commit/dfc159d9522382e644b7b4a0031c7bf9bc559f7e) I'd like to submit to fix the misspellings.

**Comment by dominichamon** [comment]
create a pull request and i'll take a look, thanks!

**Comment by winksaville** [comment]
Created PR #543

**Comment by winksaville** [comment]
Closing, fixed with merge of #543
