### ISSUE TITLE
StrCat in string_util.h conflicits with StrCat in Shlwapi.h

### ISSUE THREAD

**Issue by winksaville** [google/benchmark#545]
StrCat is a macro in Shlwapi.h that conflicts with StrCat in string_util.h:
    
       #defines StrCat lstrcatA
    
When Shlwapi.h is included in sysinfo.cc and all references to StrCat are
renamed to lstrcatA in string_util.h and sysinfo.cc, therefore this
renaming is innocuous, although unintended.
    
But if string_util.h is moved above Shlwapi.h then errors occur because StrCat is
not renamed in string_util.h but are renamed in sysinfo.cc. PR #544 renames
StrCat in string_util.h to resolve the issue.

**Comment by dominichamon** [comment]
fixed?

**Comment by winksaville** [comment]
Closing, fixed with #546
