### ISSUE TITLE
Use of offsetof macro on non standard-layout type is undefined at least prior to C++17

### ISSUE THREAD

**Issue by astrelni** [google/benchmark#552]
To the best of my understanding [benchmark.cc#L316](https://github.com/google/benchmark/blob/master/src/benchmark.cc#L316), which calls offsetof on benchmark::State, is undefined behavior.

C++11 18.2.4 [support.types]

> The macro offsetof(type, member-designator) accepts a restricted set of type arguments in this International Standard. If type is not a standard-layout class (Clause 9), the results are undefined.

benchmark::State is a non standard-layout type because all of its non-static members do not have the same access control.

I am not sure what would be lost by just removing the static_assert, so I am starting this off as an issue instead of going straight for a PR.

**Comment by dominichamon** [comment]
@EricWF who added the check.

Simply, the static_assert exists to ensure that we keep the performance-necessary struct layout.

**Comment by astrelni** [comment]
For context, I am currently failing to build a benchmark with gcc because it is triggering Werror=invalid-offsetof on that line.

**Comment by dominichamon** [comment]
I noticed that in the bazel builds. We currently disable that warning for our gcc builds: https://github.com/google/benchmark/blob/master/CMakeLists.txt#L123

**Comment by EricWF** [comment]
yeah, my bad. I figured this might come up. However all compilers seem to support the behavior as an extension even though they generate a warning about it.

**Comment by astrelni** [comment]
Would you be in favor of turning it into a runtime CHECK on `error_occured_ - this` to keep standard compliant?

**Comment by astrelni** [comment]
Ping @EricWF @dominichamon

**Comment by EricWF** [comment]
Are we just complaining the the compiler issues a warning? If so we should just disable the warning. As long as the static assert passes there is no undefined behaviour; because there can't be undiagnosed undefined behaviour at compile time.

**Comment by astrelni** [comment]
So if IIUC we just need to add -Winvalid-offsetof to the bazel copts?

**Comment by EricWF** [comment]
Yeah, either that or we could wrap the static assert in a `#pragma diagnostic disable "-Winvalid-offsetof". Either option seems good to me.

**Comment by dominichamon** [comment]
It's disabled in the cmake, so doing that in bazel sgtm. but only if it's gcc (ie, if the warning is supported).

**Comment by EricWF** [comment]
I decided to disable it in the source instead, just to ensure we don't have invalid applications of `offsetof` in other places we don't intend.

**Comment by astrelni** [comment]
Great, thanks a lot.

**Comment by milladgit** [comment]
Hi everybody,
What is the equivalent of this feature for PGI compiler? 
Does anybody know about this? 
I am trying to compile the benchmark package with PGI. But, it gives me this error:

"/home/m/benchmark/src/benchmark.cc", line 158: error: expression must
          have a constant value
    static_assert(offsetof(State, error_occurred_) <=

Any ideas?
