### ISSUE TITLE
--benchmark_color=auto (the default value) always prints color

### ISSUE THREAD

**Issue by guoyr** [google/benchmark#559]
Benchmark defaults to "auto" for deciding to whether to use color or not, as part of the [following conditional:](https://github.com/google/benchmark/blob/7b03df7ff76844a39359e9233f31ca8cdb073313/src/benchmark.cc#L466-L467) 
```cpp
  if ((FLAGS_benchmark_color == "auto" && IsColorTerminal()) ||
      IsTruthyFlagValue(FLAGS_benchmark_color)) {
    // print color.
}
```

But `IsTruthyFlagValue` is permissive and returns `true` for the string "auto", causing `IsColorTerminal()` to be ignored.

**Comment by dominichamon** [comment]
PR in progress.
