### ISSUE TITLE
Needs m4 folder

### ISSUE THREAD

**Issue by totszwai** [google/benchmark#561]
Following the instructions and building from protobuf gives the following:

```
 ./autogen.sh 
 + autoreconf -f -i -Wall,no-obsolete
 aclocal: couldn't open directory `m4': No such file or directory
 autoreconf: aclocal failed with exit status: 1
```

Running the command that was ran in autogen.sh gives the following:

```
 autoreconf -f -i -Wall,no-obsolete -v
 autoreconf: Entering directory `.'
 autoreconf: configure.ac: not using Gettext
 autoreconf: running: aclocal --force -I m4
 autoreconf: configure.ac: tracing
 autoreconf: configure.ac: adding subdirectory third_party/googletest to autoreconf
 autoreconf: Entering directory `third_party/googletest'
 aclocal: couldn't open directory `m4': No such file or directory
 autoreconf: aclocal failed with exit status: 1
```

Manually creating the m4 folder bypasses the error...

**Comment by dominichamon** [comment]
I think this might be an issue with how the protobuf project have integrated this project, as we don't support autoconf directly. the error also seems to be referencing third_party/googletest which is not part of this project. I'm happy to help, but i don't know what the m4 directory would be or why we'd need it.
