### ISSUE TITLE
Build fails in benchmark.cc

### ISSUE THREAD

**Issue by UCLGuichard** [google/benchmark#568]
Hello,
I've got to these two errors, while trying to build google benchmarks for the project I'm on:
```
/home/ucapgui/BICO/benchmark/src/benchmark.cc(177): error #2259: non-pointer conversion from "long" to "int" may lose significant bits
      results.complexity_n += st.complexity_length_n();
                           ^

/home/ucapgui/BICO/benchmark/src/benchmark.cc(326): error #1875: offsetof applied to non-POD (Plain Old Data) types is nonstandard
    static_assert(offsetof(State, error_occurred_) <=
                  ^
```
Any idea how to fix it ? Thank you.

**Comment by dominichamon** [comment]
The first is a bug that i'll push a fix for now (#569).

The second is a known issue that was already fixed by disabling the warning in source (#552) .

**Comment by UCLGuichard** [comment]
It works for the first although I still get the second. I'm using the Intel compiler for which this fix is not applicable ?

**Comment by dominichamon** [comment]
Ah maybe... @EricWF who knows more about the compiler side and how we might support that. Are you using CMake or bazel to build? I think we have assumed clang, msvc, or g++ at this point.

**Comment by UCLGuichard** [comment]
Yes, I'm using CMake and Intel compiler (2017).

**Comment by EricWF** [comment]
Urg. I hate this warning.

UB is not allowed in constant expressions, so if the static assert passes, the code must be well formed. It's dumb to emit a warning for it.

I'll look into this more tomorrow.

**Comment by dominichamon** [comment]
How was this resolved?

**Comment by UCLGuichard** [comment]
So far we moved to the GNU compiler for which it works.
