### ISSUE TITLE
command line parsing support?

### ISSUE THREAD

**Issue by lijinpei** [google/benchmark#597]
Hi, thank you for the useful tool.
And may I ask how can I add some command line argument to the compiled exe file, without introducing some other command line parsing library. I don't want to use other command line parsing library like boost, because:
1 what we need is simple, benchmark is a light-weight library, I don't want to introduce some complicated, heavy command line parsing library to my micro-benchmarks
2 benchmark parse some command line argument, and use [some O(n^2) to shift the unparsed arguments](https://github.com/google/benchmark/blob/6d74c0625b8e88c1afce72b4f383c91b9a99dbe6/src/benchmark.cc#L593), we can just let the user register some command line argument, and parse them in this process, it won't be some big change.

**Comment by LebedevRI** [comment]
Since as you have linked, the benchmark library pass-throughs the unknown params,
your code will receive them. So your code is fully free to do whatever it wants with them.
So i'm not quite sure what the issue is. This isn't specific to the benchmark library at all.

**Comment by LebedevRI** [comment]
@dominichamon I think this can be closed?
