### ISSUE TITLE
on googletest dependency

### ISSUE THREAD

**Issue by ahsabali** [google/benchmark#614]
1. How googletest is being used in google benchmark? E.g., is it meant for running gtests that test the functionality of google benchmark framework itself? Or, is it there because it allows users to write performance tests in Google test style?

2. In case we build Google Benchmark without Google Test, using “-DBENCHMARK_ENABLE_GTEST_TESTS=OFF” will we loose any Google Benchmark functionality, e.g., ability to write performance tests in Google test style, or some other feature that depends on googletest?

**Comment by dominichamon** [comment]
1. It's used for internal testing of the framework. It is not used as part of the library itself.
2. No features will be lost by disabling the tests.

**Comment by ahsabali** [comment]
Thank you Dominic. It was very helpful.
