### ISSUE TITLE
compile with the library error, thanks for help.

### ISSUE THREAD

**Issue by SJL----** [google/benchmark#615]
make benchmark

g++ -std=c++11 -Wall -Isrc/ -L./ -O3 benchmark/parser_benchmark.cpp benchmark/benchmark.cpp benchmark/queries.cpp benchmark/benchmark_utils.cpp -o bin/benchmark -lbenchmark -lpthread -lsqlparser -lstdc++ -lstdc++fs
benchmark/benchmark.cpp: In function ‘int main(int, char**)’:
benchmark/benchmark.cpp:11:82: error: no matching function for call to ‘RegisterBenchmark(const char*, void (*)(benchmark::State&, const string&), const std::basic_string<char>&)’
     benchmark::RegisterBenchmark(p_name.c_str(), &BM_ParseBenchmark, query.second);
                                                                                  ^
benchmark/benchmark.cpp:11:82: note: candidates are:
In file included from benchmark/benchmark.cpp:1:0:
/usr/local/include/benchmark/benchmark.h:958:29: note: benchmark::internal::Benchmark* benchmark::RegisterBenchmark(const char*, void (*)(benchmark::State&))
 inline internal::Benchmark* RegisterBenchmark(const char* name,
                             ^
/usr/local/include/benchmark/benchmark.h:958:29: note:   candidate expects 2 arguments, 3 provided
/usr/local/include/benchmark/benchmark.h:966:22: note: template<class Lambda> benchmark::internal::Benchmark* benchmark::RegisterBenchmark(const char*, Lambda&&)
 internal::Benchmark* RegisterBenchmark(const char* name, Lambda&& fn) {
                      ^
/usr/local/include/benchmark/benchmark.h:966:22: note:   template argument deduction/substitution failed:
benchmark/benchmark.cpp:11:82: note:   candidate expects 2 arguments, 3 provided
     benchmark::RegisterBenchmark(p_name.c_str(), &BM_ParseBenchmark, query.second);
                                                                                  ^
benchmark/benchmark.cpp:13:85: error: no matching function for call to ‘RegisterBenchmark(const char*, void (*)(benchmark::State&, const string&), const std::basic_string<char>&)’
     benchmark::RegisterBenchmark(t_name.c_str(), &BM_TokenizeBenchmark, query.second);
                                                                                     ^
benchmark/benchmark.cpp:13:85: note: candidates are:
In file included from benchmark/benchmark.cpp:1:0:
/usr/local/include/benchmark/benchmark.h:958:29: note: benchmark::internal::Benchmark* benchmark::RegisterBenchmark(const char*, void (*)(benchmark::State&))
 inline internal::Benchmark* RegisterBenchmark(const char* name,
                             ^
/usr/local/include/benchmark/benchmark.h:958:29: note:   candidate expects 2 arguments, 3 provided
/usr/local/include/benchmark/benchmark.h:966:22: note: template<class Lambda> benchmark::internal::Benchmark* benchmark::RegisterBenchmark(const char*, Lambda&&)
 internal::Benchmark* RegisterBenchmark(const char* name, Lambda&& fn) {
                      ^
/usr/local/include/benchmark/benchmark.h:966:22: note:   template argument deduction/substitution failed:
benchmark/benchmark.cpp:13:85: note:   candidate expects 2 arguments, 3 provided
     benchmark::RegisterBenchmark(t_name.c_str(), &BM_TokenizeBenchmark, query.second);
                                                                                     ^
benchmark/benchmark.cpp:20:82: error: no matching function for call to ‘RegisterBenchmark(const char*, void (*)(benchmark::State&, const string&), const std::basic_string<char>&)’
     benchmark::RegisterBenchmark(p_name.c_str(), &BM_ParseBenchmark, query.second);
                                                                                  ^
benchmark/benchmark.cpp:20:82: note: candidates are:
In file included from benchmark/benchmark.cpp:1:0:
/usr/local/include/benchmark/benchmark.h:958:29: note: benchmark::internal::Benchmark* benchmark::RegisterBenchmark(const char*, void (*)(benchmark::State&))
 inline internal::Benchmark* RegisterBenchmark(const char* name,
                             ^
/usr/local/include/benchmark/benchmark.h:958:29: note:   candidate expects 2 arguments, 3 provided
/usr/local/include/benchmark/benchmark.h:966:22: note: template<class Lambda> benchmark::internal::Benchmark* benchmark::RegisterBenchmark(const char*, Lambda&&)
 internal::Benchmark* RegisterBenchmark(const char* name, Lambda&& fn) {
                      ^
/usr/local/include/benchmark/benchmark.h:966:22: note:   template argument deduction/substitution failed:
benchmark/benchmark.cpp:20:82: note:   candidate expects 2 arguments, 3 provided
     benchmark::RegisterBenchmark(p_name.c_str(), &BM_ParseBenchmark, query.second);
                                                                                  ^
benchmark/benchmark.cpp:23:85: error: no matching function for call to ‘RegisterBenchmark(const char*, void (*)(benchmark::State&, const string&), const std::basic_string<char>&)’
     benchmark::RegisterBenchmark(t_name.c_str(), &BM_TokenizeBenchmark, query.second);
                                                                                     ^
benchmark/benchmark.cpp:23:85: note: candidates are:
In file included from benchmark/benchmark.cpp:1:0:
/usr/local/include/benchmark/benchmark.h:958:29: note: benchmark::internal::Benchmark* benchmark::RegisterBenchmark(const char*, void (*)(benchmark::State&))
 inline internal::Benchmark* RegisterBenchmark(const char* name,
                             ^
/usr/local/include/benchmark/benchmark.h:958:29: note:   candidate expects 2 arguments, 3 provided
/usr/local/include/benchmark/benchmark.h:966:22: note: template<class Lambda> benchmark::internal::Benchmark* benchmark::RegisterBenchmark(const char*, Lambda&&)
 internal::Benchmark* RegisterBenchmark(const char* name, Lambda&& fn) {
                      ^
/usr/local/include/benchmark/benchmark.h:966:22: note:   template argument deduction/substitution failed:
benchmark/benchmark.cpp:23:85: note:   candidate expects 2 arguments, 3 provided
     benchmark::RegisterBenchmark(t_name.c_str(), &BM_TokenizeBenchmark, query.second);
                                                                                     ^
benchmark/queries.cpp:3:35: fatal error: experimental/filesystem: No such file or directory
 #include <experimental/filesystem>
                                   ^
compilation terminated.
make: *** [bin/benchmark] Error 1

**Comment by dominichamon** [comment]
Can you share your source as well? It's hard to know what's going on just from the error messages.

**Comment by SJL----** [comment]
![image](https://user-images.githubusercontent.com/5748729/41235677-d65479c4-6dc1-11e8-9d86-478f7a28d6fc.png)
this the code where call RegisterBenchmark.

**Comment by dominichamon** [comment]
The definition of `BM_ParseBenchmark` should only take a `benchmark::State&` argument. I think your benchmarks are defined to take a `State` and a `std::string`:
