### ISSUE TITLE
Possibly need more Counter::Flags

### ISSUE THREAD

**Issue by LebedevRI** [google/benchmark#618]
I'm thinking of two more flags (well, because i just fixed [two](https://github.com/darktable-org/rawspeed/commit/a1ebe07bea5738f8607b48a7596c172be249590e) [bugs](https://github.com/darktable-org/rawspeed/commit/0891555be56b24f9f4af716604cedfa0da1efc6b) in my code due to the lack of those):
* `* state.iterations()`
  The value is constant for every iteration, and needs to be **multiplied** by the iteration count.
* `/ state.iterations()`
  The is global over all the iterations, and needs to be **divided** by the iteration count.

Additionally, the first one (multiplication) should play nice with `kIsRate`.

**Comment by LebedevRI** [comment]
There is also a slight correlation with #620 - i'd also like to have something like `kIsTimer`, but the more general fix #620 would avoid that.

**Comment by biojppm** [comment]
@LebedevRI Makes sense. I was thinking of the following names for the flags. What do you say?

```c++
class Counter {
 public:
  enum Flags {
    kDefaults = 0,

    // Mark the counter as a rate. It will be presented divided
    // by the duration of the benchmark.
    kIsRate = 1,

    // Mark the counter as a thread-average quantity. It will be
    // presented divided by the number of threads.
    kAvgThreads = 2,

    // Mark the counter as an iteration-average quantity.
    // It will be presented divided by the iteration count.
    // This is incompatible with kMultIters.
    kAvgIters = 4,

    // Mark the counter as an iteration-extensive quantity,
    // It will be presented multiplied by the iteration count.
    // This is incompatible with kAvgIters.
    kMultIters = 8,

    // Mark the counter as a thread-average rate. See above.
    kAvgThreadsRate = kIsRate | kAvgThreads,
  };
  //...
};
```

Of course, owing to their combinatorial nature, adding more flags raises the problem that it becomes difficult to cover all possible combinations. I think it's pointless trying to add an enum entry for each possible combination. So ``kAvgThreadsRate`` could also be deprecated.

But anyway, this is a problem because currently the Counter ctor takes a Flags argument. We can just ignore this and make the flags parameter to the ctor take an int. OTOH, if this interface is to be retained for compatibility reasons, it probably makes sense to make Flags a typedef int, and turn the enumeration into a different type. Something like this:

```c++
class Counter {
 public:
  using Flags = int;
  enum { /*...*/ }; // maybe give some name here; open to suggestions.
  Counter(double v = 0., Flags f=kDefaults) : value(v), flags(f) {}
};
```

**Comment by LebedevRI** [comment]
I'm currently working on a patch.
Right now i only have:
```
    // Mark the counter as a constant value, valid/same for *every* iteration.
    // When reporting, it will be multiplied by the iteration count.
    kIsIterationInvariant = 1U << 2U,
    // Mark the counter as a constant rate.
    // When reporting, it will be multiplied by the iteration count
    // and then divided by the duration of the benchmark.
    kIsPerIterationRate = kIsRate | kIsIterationInvariant
```

**Comment by LebedevRI** [comment]
> I think it's pointless trying to add an enum entry for each possible combination. So kAvgThreadsRate could also be deprecated.

> But anyway, this is a problem because currently the Counter ctor takes a Flags argument. We can just ignore this and make the flags parameter to the ctor take an int. OTOH, if this interface is to be retained for compatibility reasons, it probably makes sense to make Flags a typedef int, and turn the enumeration into a different type.

I'm not sure i follow.
1. Just deprecating it won't hide the conbinatorial explosion.
2. There is indeed no need to "to add an enum entry for each possible combination".
    There is simply no need. Even if it would be an `enum class`.
     One can perfectly fine pass some garbage casted to an enum, and it won't be an UB
3. Similarly, i see absolutely no point in making it an `int`.

**Comment by biojppm** [comment]
Yes, you can bit-or the flags and cast the result to the enum type. In fact, if you use the enum type in the ctor, you _have_ to do this to avoid compiler warnings/errors.

But I'm sure you will agree that this makes the ctor cumbersome to use when a combination can only be obtained from bit-oring other flags. Making the second argument an int cleanly bypasses this problem.

Hence the int type, which lets you combine flags at will without any need for casting.

**Comment by LebedevRI** [comment]
Aha.
But then i still think that is the wrong solution.
https://godbolt.org/g/1qwa24

**Comment by biojppm** [comment]
OK, the operator works too.
