### ISSUE TITLE
V2: set*processed() should go

### ISSUE THREAD

**Issue by LebedevRI** [google/benchmark#627]
They should probably be deprecated in v2.
Custom Counters are more general, more flexible.

**Comment by LebedevRI** [comment]
Hmm, so should i submit a pr (to the master branch) to drop them?
I do see `v2` branch, but i wonder if that one should be called json-wip instead..

**Comment by dominichamon** [comment]
It's up to @EricWF if the v2 branch is really v2 or just JSON-wip. for now marking them as deprecated seems reasonable, but that suggests they're going to be removed Soon (but i don't think we would by 1.6).

**Comment by LebedevRI** [comment]
Removed == api break == major release ==  2.0

**Comment by dbabokin** [comment]
Also, from user prospective SetBytesProcessed() and other deprecated functions are way more convenient, than verbose and generic Custom Counters. Keeping them around as aliases / special case of Custom Counters seems reasonable from usability point of view.

**Comment by LebedevRI** [comment]
https://github.com/google/benchmark/pull/676

**Comment by LebedevRI** [comment]
@dbabokin i hope that addressed it.
