### ISSUE TITLE
[feature] Conan package.

### ISSUE THREAD

**Issue by p-groarke** [google/benchmark#635]
Any chance we can get a conan package? Thank you.

**Comment by Croydon** [comment]
I'm working on something non-official here, but would be nice if we can get official support https://github.com/Croydon/conan-google_benchmark

**Comment by Croydon** [comment]
This would be also required for https://github.com/grpc/grpc/issues/15363

**Comment by p-groarke** [comment]
Bincrafters may be interested in your package once it's ready. Thx for taking the time.

**Comment by Croydon** [comment]
That was indeed my goal with this recipe :)

**Comment by Croydon** [comment]
Linux, macOS and Windows static builds seem to be fine, Windows shared fails and I don't understand why yet 

Ideas would be appreciated 
https://ci.appveyor.com/project/Croydon/conan-google-benchmark-83vi6/build/job/q9nm3togdwumnct8#L1609

**Comment by dominichamon** [comment]
PRs always welcome.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by raulbocanegra** [comment]
Hi! 
As @Croydon referenced I was asked to include my repo a couple of weeks ago.
I am happy to help and also open to receive any suggestions.
One of the issues I found on Windows is building a shared version of the library. After having a look at the code it seems that the symbols are not being exported, so shared builds are not supported on Windows.

**Comment by Croydon** [comment]
@raulbocanegra This is a general problem, not a Conan recipe specific one. See #640

**Comment by Croydon** [comment]
Benchmark has now both a git Conan recipe version and is also in Conan Center.

Done!
