### ISSUE TITLE
Build error on mac.

### ISSUE THREAD

**Issue by DenisYaroshevskiy** [google/benchmark#636]
Hi!

I've been following the instalation instructions and got a compiler error-warning:

`Deniss-MacBook-Air:build denisarosevskij$ make
Scanning dependencies of target benchmark
[  1%] Building CXX object src/CMakeFiles/benchmark.dir/benchmark.cc.o
[  2%] Building CXX object src/CMakeFiles/benchmark.dir/benchmark_register.cc.o
[  4%] Building CXX object src/CMakeFiles/benchmark.dir/colorprint.cc.o
[  5%] Building CXX object src/CMakeFiles/benchmark.dir/commandlineflags.cc.o
[  7%] Building CXX object src/CMakeFiles/benchmark.dir/complexity.cc.o
[  8%] Building CXX object src/CMakeFiles/benchmark.dir/console_reporter.cc.o
[ 10%] Building CXX object src/CMakeFiles/benchmark.dir/counter.cc.o
[ 11%] Building CXX object src/CMakeFiles/benchmark.dir/csv_reporter.cc.o
[ 12%] Building CXX object src/CMakeFiles/benchmark.dir/json_reporter.cc.o
[ 14%] Building CXX object src/CMakeFiles/benchmark.dir/reporter.cc.o
[ 15%] Building CXX object src/CMakeFiles/benchmark.dir/sleep.cc.o
[ 17%] Building CXX object src/CMakeFiles/benchmark.dir/statistics.cc.o
[ 18%] Building CXX object src/CMakeFiles/benchmark.dir/string_util.cc.o
[ 20%] Building CXX object src/CMakeFiles/benchmark.dir/sysinfo.cc.o
[ 21%] Building CXX object src/CMakeFiles/benchmark.dir/timers.cc.o
[ 22%] Linking CXX static library libbenchmark.a
[ 22%] Built target benchmark
Scanning dependencies of target benchmark_main
[ 24%] Building CXX object src/CMakeFiles/benchmark_main.dir/benchmark_main.cc.o
[ 25%] Linking CXX static library libbenchmark_main.a
[ 25%] Built target benchmark_main
Scanning dependencies of target gtest
[ 27%] Building CXX object googletest/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /space/benchmark/googletest/googletest/src/gtest-all.cc:42:
/space/benchmark/googletest/googletest/src/gtest.cc:393:12: error: missing field 'owner_' initializer [-Werror,-Wmissing-field-initializers]
GTEST_API_ GTEST_DEFINE_STATIC_MUTEX_(g_linked_ptr_mutex);
           ^
/space/benchmark/googletest/googletest/include/gtest/internal/gtest-port.h:2096:80: note: expanded from macro 'GTEST_DEFINE_STATIC_MUTEX_'
     ::testing::internal::MutexBase mutex = { PTHREAD_MUTEX_INITIALIZER, false }
                                                                               ^
1 error generated.
make[2]: *** [googletest/googlemock/gtest/CMakeFiles/gtest.dir/src/gtest-all.cc.o] Error 1
make[1]: *** [googletest/googlemock/gtest/CMakeFiles/gtest.dir/all] Error 2
make: *** [all] Error 2
`

Which is true - the macro does not initialise the pthread member variable.
Maybe the issue should go upstream, but I found it while building this library.

**Comment by DenisYaroshevskiy** [comment]
I should really be reading comments better:
'
// Defines and statically (i.e. at link time) initializes a static mutex.
// The initialization list here does not explicitly initialize each field,
// instead relying on default initialization for the unspecified fields. In
// particular, the owner_ field (a pthread_t) is not explicitly initialized.
// This allows initialization to work whether pthread_t is a scalar or struct.
// The flag -Wmissing-field-initializers must not be specified for this to work.
`

**Comment by EricWF** [comment]
Tangentially, that comment doesn't say anything close to what they want it to say.

Default initialization leaves uninitialized fields uninitialized. What I think they're trying to say is they're counting on the zero-initialization which takes place during static initialization.

I'll take my pedant hat off now.
