### ISSUE TITLE
On windows the executable path contain unescaped backslashes and cause an error in compare.py

### ISSUE THREAD

**Issue by monamimani** [google/benchmark#641]
On Windows, when outputing to a file, the executable path contain backslashes which cause issues. They should probably be escaped \\ or use forward slashes '/'. This cause issues with the compare tool. 

If I don't correct the path this is what I get

Executing task: python.exe D:\_Dev\Playground\gBenchmarkVulkan/bazel-gbenchmarkvulkan/external/gbenchmark/tools/compare.py filters D:\_Dev\Playground\gBenchmarkVulkan/benchmark.json NoExceptWithExcept <

Invalid input file: 'D:\_Dev\Playground\gBenchmarkVulkan/benchmark.json' does not name a valid benchmark executable or JSON file

[benchmark.txt](https://github.com/google/benchmark/files/2203766/benchmark.txt)

**Comment by LebedevRI** [comment]
This should have been fixed by #652 (although the commit msg did not include `Fixes #641` :D)

**Comment by BaaMeow** [comment]
I didn't even realize other people were having this problem, aha. Well, it's fixed in #652!

**Comment by LebedevRI** [comment]
@monamimani did that fix the issue you were seeing?
If yes, could you please close the issue.
