### ISSUE TITLE
BENCHMARK_DOWNLOAD_DEPENDENCIES doesn't work with Ninja build

### ISSUE THREAD

**Issue by dbabokin** [google/benchmark#660]
I'm configuring the project in the following way:
`cmake -DCMAKE_BUILD_TYPE=RELEASE -DBENCHMARK_DOWNLOAD_DEPENDENCIES=ON -G Ninja ..`
It configures without any issues, but fails to build:
`> ninja
ninja: error: 'googletest/lib/libgtest.a', needed by 'test/benchmark_gtest', missing and no known rule to make it`

It works well when make is used instead of ninja, i.e. googletest is downloaded and built as expected.

**Comment by LebedevRI** [comment]
Strange that i never see this.
Does it work if you manually place the googletest sources into `googletest` directory?

**Comment by dbabokin** [comment]
Yes, with manually checked-out googletest directory in the source tree, it works like a charm.

**Comment by dominichamon** [comment]
I also can't reproduce this at all.

**Comment by dbabokin** [comment]
The problem was fixed between `v1.4.1` and `v1.5.0`. I've checked that I can reproduce it with `v1.4.1` and it works well with `v1.5.0`. So it's not an environment, but some changes in CMake files.

I'm closing this as the problem is fixed.
