### ISSUE TITLE
1b44120 causes narrowing warning on Windows Appveyor builds

### ISSUE THREAD

**Issue by staffantj** [google/benchmark#688]
See https://ci.appveyor.com/project/google/benchmark/build/1439/job/x656s50cinwy7hve#L89 as an example.

The problem is that in the refactor of the counters, the signatures of [GS]et[Item,Byte]sProcessed the value passed in/out of the library remains an int64_t, but the internal store is in a double.

**Comment by LebedevRI** [comment]
You can submit a PR to make those casts explicit if that is better.
I intentionally left them in the current state, since i don't think we can change the return type of those functions.

**Comment by LebedevRI** [comment]
I think d8c0f27448dfad95b94285e612bba1f7c55c9dd0 fixed it?
