### ISSUE TITLE
Windows Appveyor builds are failing, but are showing green

### ISSUE THREAD

**Issue by staffantj** [google/benchmark#689]
Since 1b44120 the Windows Appveyor builds have been reporting warnings, but they are showing green since warnings aren't set to convert to errors, basically making the integration builds worthless.

**Comment by LebedevRI** [comment]
The Appveyor build is red since https://ci.appveyor.com/project/google/benchmark/build/1401/job/2u8kwhb363sxvg7j anyway.
That failure looked rather cryptic to me, so i did nothing.
I suspect that is why those msvc builds are not warning-as-error in the first place.

**Comment by staffantj** [comment]
It looks as if the build break (as opposed to the warnings) comes out of gmock, with an "no idea what warning 5046 is" error message. 

It doesn't really make sense that it suddenly appears at the point in the build history where it does, unless there's something about the build environment changing that Appveyor isn't showing me.

Certainly it looks as if there has pretty much always been warnings in the Windows build (at least going back some time).

I might try attacking some of those once/if I get the attribution paperwork in order.

I've traced the C4512 warnings down to the State* const parent_ member on the StateIterator. Should that by any chance be a State const* ?
