### ISSUE TITLE
Passing preallocated vectors to benchmarks

### ISSUE THREAD

**Issue by Wheest** [google/benchmark#692]
Howdy folks,

Please forgive my first tentative steps into benchmark.

I have a function that I want to benchmark.  It should take as arguments pointers to some preallocated `std::vector`s.  I.e. I do not want to have the time taken to allocate the vectors to be counted, and I also want to be able to reuse some of the vectors.

Since the function takes many arguments, I tried to follow the [advice from the README](https://github.com/google/benchmark#passing-arguments) on how to pass a more complex set of arguments using `Apply`.

However when I pass the pointers to the benchmark, I get a compile error since it views the arguments of being of `int64_t`, rather than `std::vector*`.  You can see how I attempted to do this in fns `BM_mwe` and `CustomArguments` below.

The [issue here](https://github.com/google/benchmark/issues/387), referenced [this part](https://github.com/google/benchmark#passing-arbitrary-arguments-to-a-benchmark) of the README, where one can pass arbitrary arguments to a benchmark.  I'm still not sure the right way to use this.  My attempt at that is in `BN_mwe2`, and the (incorrect) invocation is commented out at the end of fn `CustomArguments`.

You can see my code here:

```
#include <benchmark/benchmark.h>
#include <random>
#include <vector>
#include <chrono>
#include <algorithm>
#include <thread>         // std::thread
#include <chrono>
#include <iostream>

static void BM_mwe(benchmark::State& state) {
  std::vector<float>* vec_zero = state.range(0);
  std::vector<float>* vec_one = state.range(1);
  std::cout << (*vec_zero)[0] << "\n";
  std::this_thread::sleep_for(std::chrono::milliseconds(1000));
}

static void BM_mwe2(benchmark::State& state,
                   std::vector<float>* vec_zero,
                   std::vector<float>* vec_one)
{
  std::cout << (*vec_zero)[0] << "\n";
  std::this_thread::sleep_for(std::chrono::milliseconds(1000));
}

static void CustomArguments(benchmark::internal::Benchmark* b)
{
  int size_zero = 100;
  int size_one = 150;
  std::vector<float>* vec_zero = new std::vector<float>(size_zero);
  std::vector<float>* vec_one = new std::vector<float>(size_one);

  // fill inputs with random values
  constexpr auto low_bound = std::numeric_limits<float>::min();
  constexpr auto up_bound = std::numeric_limits<float>::max();
  auto seed = std::chrono::system_clock::now().time_since_epoch().count();//seed
  std::default_random_engine dre(seed);//engine
  std::uniform_real_distribution<float> di(low_bound,up_bound);//distribution
  // http://www.cplusplus.com/forum/general/213013/
  std::generate(vec_zero->begin(), vec_zero->end(), [&]{ return di(dre);});
  std::generate(vec_one->begin(), vec_one->end(), [&]{ return di(dre);});
  //http://en.cppreference.com/w/cpp/algorithm/generate
  b->Args({vec_zero, vec_one});

  // BENCHMARK_CAPTURE(BM_mwe2, vec_zero, vec_one);
}
// Register the function as a benchmark
BENCHMARK(BM_mwe)->Apply(CustomArguments);

BENCHMARK_MAIN();
```

Any guidance would be greatly appreciated.

**Comment by LebedevRI** [comment]
> I.e. I do not want to have the time taken to allocate the vectors to be counted,

https://github.com/google/benchmark#basic-usage
> `The benchmark library will measure and report the timing for code within the for(...) loop.`

Anything before the loop will not be counted

> I also want to be able to reuse some of the vectors.

https://github.com/google/benchmark#fixtures ?

**Comment by Wheest** [comment]
Your quick concise response has got me on the right track, thank you

**Comment by LebedevRI** [comment]
Great, i will close this then.
If there are further questions, feel free to open a new issue.
