### ISSUE TITLE
Why benchmark names start with "BM_" in examples?

### ISSUE THREAD

**Issue by ahsabali** [google/benchmark#695]
Is it a requirement that all benchmark names start with "BM_"? What is its significance?

**Comment by LebedevRI** [comment]
As far i'm aware that is nothing more than just short for [B]ench[M]ark, just to visually be able to tell that it is a benchmark target.

**Comment by ahsabali** [comment]
It seems it adds no significant value to the output (everything is a benchmark in the output), and everything in the C++ file must be registered with a BENCHMARK call. Any example where it can be helpful to use "BM_"?

**Comment by LebedevRI** [comment]
It's just an example, as you can see it will work without the prefix too.
But maybe when looking through the list of functions in the IDE?

**Comment by LebedevRI** [comment]
@ahsabali did that answer your question?

**Comment by ahsabali** [comment]
Yes, that answered my question. Thank you.
