### ISSUE TITLE
Windows build is not ready

### ISSUE THREAD

**Issue by syoyo** [google/benchmark#7]
Some part of code is Windows-aware(ifdef'ed with OS_WINDOWS), but still incomplete(e.g. pthread.h in benchmark.h)

**Comment by dominichamon** [comment]
#64 has landed which gives us a working mingw port. does that help?

**Comment by mattyclarkson** [comment]
@dominichamon, I tried having a go at getting VS2013 up and going but there are a few things missing with the C++11 support. I'll just brain dump here in case anyone can pick it up:

 * gettimeofday needs to be [polyfilled](http://stackoverflow.com/a/26085827/192993) in [`walltime.cc`](https://github.com/google/benchmark/blob/65ed470c0f5e340723da76c1b7a1eee7c0ac798a/src/walltime.cc)
  * `constexpr` support is sketchy so things don't compile
  * `noexcept` wasn't supported
  * CMakeList.txt needs `if (MSVC)` to avoid all the GCC/Clang flag checks (not an issue as the fail gracefully, just looks weird)
  * By default `cmake` adds `/Wall` which turns on warnings that even the STL that is shipped with Visual Studio doesn't compile with. I'd suggest starting with `/W0` and slowly cranking that up to `/W4` putting the necessary `/wdXXXX` in the `CMakeList.txt` or the `pragma warning()` around the offending areas. It would be great to have a clean MSVC build at high warning levels as it might catch things that GCC/Clang might miss

It's almost there, just needs a bit of love. `cmake -G "Visual Studio 12 2013"` gets things going.

Once the Visual Studio build is going the appveyor support to continuously check for MSVC support can be added by implementing `msbuild` like `cppformat` does [here](https://github.com/cppformat/cppformat/blob/d2387999ece1117527d93f947e9cc3436c1881a3/support/appveyor-build.py#L18). Will just have to add the necessary lines to `appveyor.yml` when `if "%compiler_name%"=="msvc"`.

**Comment by KindDragon** [comment]
Relate to PR #175

**Comment by EricWF** [comment]
Closing since the Windows build seems to be working and Appveyor is testing it on every commit.

**Comment by syoyo** [comment]
Super cool! Thank you!
