### ISSUE TITLE
assertion crashes in debug mode

### ISSUE THREAD

**Issue by romange** [google/benchmark#71]
I get the following crash:
third_party/benchmark/src/benchmark.cc:1130: bool benchmark::State::FinishInterval(): Assertion `false' failed.

int64 GetCurrentTimeMicros() {
  timespec ts;
  clock_gettime(CLOCK_REALTIME, &ts);
  return ts.tv_sec * 1000000 + ts.tv_nsec / 1000;
}

static void BM_GetCurrentTimeMicros(benchmark::State& state) {
  while (state.KeepRunning()) {
    int64 x = GetCurrentTimeMicros();
  }
}
BENCHMARK(BM_GetCurrentTimeMicros);

**Comment by romange** [comment]
Sorry, it happens on the other test
  
while (state.KeepRunning()) {
    sink_result(time(NULL));
  }

which probably happens due to almost no-op code in the loop. Still framework code should be protected against this

**Comment by dominichamon** [comment]
That's odd. The assertion on 1129 should have failed first. This means that total_overhead was negative.

```
1128  const double total_overhead = overhead * iterations_;
1129  CHECK_LT(pause_real_time_, accumulated_time);
1130  CHECK_LT(pause_real_time_ + total_overhead, accumulated_time);
```

**Comment by EricWF** [comment]
Is it possible that the line number just changed? Also a better implementation of CHECK would be nice. One that contains the expression would be nice.

**Comment by dominichamon** [comment]
we don't calculate overhead any more.
