### ISSUE TITLE
Test arguments printed with 32 bit precision

### ISSUE THREAD

**Issue by mknejp** [google/benchmark#714]
The arguments passed to benchmarks are of type `int64_t` however when they get reported they get truncated to 32 bits. The following is output where the argument keeps increasing beyond `int` precision and is printed incorrectly (but the benchmark does the right thing).
```
baseline_push_back/std::vector<int>/67108864/manual_time              33079613 ns   32812500 ns         20
baseline_push_back/std::vector<int>/134217728/manual_time             71565844 ns   71428571 ns          7
baseline_push_back/std::vector<int>/536870912/manual_time            539197109 ns  531250000 ns          1
baseline_push_back/std::vector<int>/1073741824/manual_time           914751775 ns  890625000 ns          1
baseline_push_back/std::vector<int>/-2147483648/manual_time         1806131008 ns 1796875000 ns          1
baseline_push_back/std::vector<int>/0/manual_time                   3629563138 ns 3625000000 ns          1
```
 I think the problem is that https://github.com/google/benchmark/blob/edc77a3669026eddc380721d5a3cdccd752b76cb/src/benchmark_register.cc#L185
should use the `%lld` format specifier instead.

**Comment by dominichamon** [comment]
Sounds about right. PR welcome :)

**Comment by LebedevRI** [comment]
Is `-Wformat` not enabled? Why isn't compiler complaining about that..
