### ISSUE TITLE
host computer identification

### ISSUE THREAD

**Issue by peterlauro1973** [google/benchmark#722]
Would be possible to enhance benchmark output json file with an information about the host name on which the test was triggered?

just simple "uname -n" on Linux or "hostname" on windows.

This kind of information can be useful in situation when CI may trigger the benchmark tests on different hosts. The post-processing script can identify, select and compare the results not only based on cpu identification but also base the hostname.

**Comment by dominichamon** [comment]
That sounds completely reasonable. Patches welcome :)

**Comment by tesch1** [comment]
Closeable?

**Comment by LebedevRI** [comment]
Right, thanks.
