### ISSUE TITLE
AppVeyor is enabled but doesn't report status back

### ISSUE THREAD

**Issue by Croydon** [google/benchmark#729]
AppVeyor is enabled and builds commits and pull requests: https://ci.appveyor.com/project/google/benchmark/history

However, it never reports back the status to the GitHub status API and therefore GitHub never displays if Windows builds succeeded or did fail, but rather spams the status as comments.

This should be fixed. Seems like the Github repo <-> AppVeyor integration only works somewhat. 

Maybe it uses some old integration and not the AppVeyor GitHub app?

**Comment by dominichamon** [comment]
It's using the webhook, which isn't deprecated. However, i'll look into the
app version.
