### ISSUE TITLE
Behavior of --benchmark_filter="" doesn't match the documentation

### ISSUE THREAD

**Issue by derekmauro** [google/benchmark#736]
There is a contradiction in the documentation of this flag and the behavior of the code. The documentation says the empty string runs no benchmarks, but the code actually runs all of them.

https://github.com/google/benchmark/blob/99d1356c041f49dccfc55104e79e282f815f6849/src/benchmark.cc#L58-L62
https://github.com/google/benchmark/blob/99d1356c041f49dccfc55104e79e282f815f6849/src/benchmark.cc#L349-L351

I think the correct behavior for the empty string should be to run none of them, as I think there might be CI systems that by default don't want to run time consuming benchmarks, and to do this they might want to override this flag with the empty string.

**Comment by dominichamon** [comment]
You're right that this is a mistake in the documentation.

Running all of them is the expected design as that is the default case. See also gtest_filter in google test which works the same way.

**Comment by LebedevRI** [comment]
By default, obviously everything should be run.
But i think the question is about explicitly passing `--benchmark_filter=""`.

**Comment by dominichamon** [comment]
sorry, yes. i just reparsed that as i was updating the documentation :)

I think that is a good idea.

**Comment by LebedevRI** [comment]
(Actually, i'm not seeing any contradiction)

**Comment by dominichamon** [comment]
Hang on, sorry, let me think about this again.

Why would you want to pass ""? If you're _running_ the code but not running any of the benchmarks, what are you doing?

**Comment by derekmauro** [comment]
The short story is that I had a benchmark that I thought had to be declared `cc_test` (in Bazel) to get around a dependency check, but I didn't want the benchmark to actually run when `bazel test` was invoked because it would take too long. I found a solution for my specific problem (`cc_binary` with `testonly = 1`), so for now simply updating the documentation is fine.
