### ISSUE TITLE
Problems building with clang++ >= 3.3

### ISSUE THREAD

**Issue by dominichamon** [google/benchmark#74]
None of the regex checks in cmake pass when clang++ is version > 3.3 and std is set to c++14. This is due to a libc mismatch where ::gets has been removed from the global namespace.

The fix is to define -stdlib=libc++ and make sure that is installed. However, this doesn't link:

[22/22] Linking CXX executable test/re_test
FAILED: : && /usr/bin/clang++-3.5   --std=c++14 --stdlib=libc++ -Wall -Wshadow -Werror -pedantic-errors   test/CMakeFiles/re_test.dir/re_test.cc.o  -o test/re_test -L/home/dominic/git/benchmark/_build/third_party/src/googletest-build -rdynamic src/libbenchmark_re.a -lgtest -lgtest_main -lpthread -Wl,-rpath,/home/dominic/git/benchmark/_build/third_party/src/googletest-build && :
test/CMakeFiles/re_test.dir/re_test.cc.o: In function `testing::internal::PrintTo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >*)':
../test/re_test.cc:(.text._ZN7testing8internal7PrintToERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPNS1_13basic_ostreamIcS4_EE[_ZN7testing8internal7PrintToERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEEPNS1_13basic_ostreamIcS4_EE]+0x19): undefined reference to `testing::internal::PrintStringTo(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_ostream<char, std::__1::char_traits<char> >*)'
/home/dominic/git/benchmark/_build/third_party/src/googletest-build/libgtest.a(gtest-all.cc.o): In function `testing::internal::BoolFromGTestEnv(char const*, bool)':
/home/dominic/git/benchmark/_build/third_party/gtest/src/gtest-all.cc:(.text+0x2a): undefined reference to `std::string::c_str() const'
/home/dominic/git/benchmark/_build/third_party/gtest/src/gtest-all.cc:(.text+0x97): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/dominic/git/benchmark/_build/third_party/gtest/src/gtest-all.cc:(.text+0xb7): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/dominic/git/benchmark/_build/third_party/src/googletest-build/libgtest.a(gtest-all.cc.o): In function `testing::internal::StringFromGTestEnv(char const*, char const*)':
/home/dominic/git/benchmark/_build/third_party/gtest/src/gtest-all.cc:(.text+0x106): undefined reference to `std::string::c_str() const'
/home/dominic/git/benchmark/_build/third_party/gtest/src/gtest-all.cc:(.text+0x164): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
/home/dominic/git/benchmark/_build/third_party/gtest/src/gtest-all.cc:(.text+0x180): undefined reference to `std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
....

**Comment by EricWF** [comment]
Why would we want to build in C++14 when we don't use c++14? I think we should just drop that option from CMake.

Also the link error you are seeing is that gtest is built against libstdc++ while benchmark is built against libc++. We need to somehow propagate -stdlib=libc++ to gtest.

**Comment by dominichamon** [comment]
i'm happy to drop the option from the cmake. we should make sure it doesn't also happen with c++11 though as the standard did drop ::gets.

**Comment by EricWF** [comment]
I've encountered this error before and it only triggers when your using the C11 standard. As far as I'm aware c++11 uses C99 and C++14 uses C11. So it should only happen in C++14 and beyond.

**Comment by dominichamon** [comment]
Why did you close this? The issue still happens and will until we remove c++14.

**Comment by EricWF** [comment]
I did remove c++14 from the CMakelists.txt. did I miss something?

**Comment by dominichamon** [comment]
Oh! I didn't see that commit go through. Thanks!
