### ISSUE TITLE
Strings in JSON output are not escaped.

### ISSUE THREAD

**Issue by ZbigniewRA** [google/benchmark#745]
Function FormatKV() in json_reporter.cc does not escape strings that are being serialized.
As a result calling for example:
```
state.SkipWithError("File not found c:\\hello.txt.");
```
results in json with syntax error "Invalid escape \h":
```
    {
      "name": "BM_Calc_Big1/extensions_pgpu_zscore",
      "error_occurred": true,
      "error_message": "File not found c:\hello.txt.",
      "iterations": 1,
      "real_time": 0.0000000000000000e+00,
      "cpu_time": 0.0000000000000000e+00,
      "time_unit": "ns"
    },
```

This problem is in both 1.4.1 and v2 versions.

**Comment by tesch1** [comment]
Can this be closed now?

**Comment by LebedevRI** [comment]
Looks like github decided to be picky and not auto-closed this.
