### ISSUE TITLE
bug in compile_gtest macro (test/CMakeLists.txt)

### ISSUE THREAD

**Issue by andreprager** [google/benchmark#757]
Generated projects with cmake-gui (at least for Visual Studio 2017 64bit) leads to linker error for benchmark_gtest, statistics_gtest and string_util_gtest.
Reason is missing target_link_libraries entry to benchmark_main. I added it locally and it worked afterwards. I'm not very familiar with how the git pull request stuff works, but I could provide patch for this, solution seems quite simple.

**Comment by dominichamon** [comment]
i'm not familiar with cmake-gui, but my guess is that this is related to the benchmark macros that can request cmake to download the dependency.

given cmake-generated projects work from cli (Makefile and ninja, at least... those are what i use) i don't think we need to add the link libraries more generally.

**Comment by andreprager** [comment]
cmake-gui is just a convient tool for setting all the cache-values etc.
I don't download the dependencies, I use prebuilt binaries for gtest (same setup as for gbenchmark).
From a technical point of view the appropriate test project (executables) need a main-entry point which is actually missing if I do not link against the benchmark_main target. So my question would be, how is that entry point added if not via the target?

**Comment by dominichamon** [comment]
i believe this is working as intended. as per [the documentation](https://github.com/google/benchmark#usage-with-cmake): "If using CMake, it is recommended to link against the project-provided benchmark::benchmark and benchmark::benchmark_main targets using target_link_libraries."
