### ISSUE TITLE
Android - how to integrate the benchmark?

### ISSUE THREAD

**Issue by NikolaMr** [google/benchmark#759]
Hi!

I'm trying to integrate the Google benchmark library into an Android NDK project in order to test my company's product. The problem I'm encountering is that I can't display the output of the library in the logcat. 

Just to mention, since Android doesn't have a `main` function but provides onCreate and other lifecycle methods I have called the benchmark inside the onCreate method which invokes NDK method. The function that is invoked looks like:

`void performTests() {`

    int argc = 1;
    char* argv[1] = {"test"};
    benchmark::ConsoleReporter reporter;
    benchmark::Initialize(&argc, argv);
    if (benchmark::ReportUnrecognizedArguments(argc, argv)) return;
    benchmark::RunSpecifiedBenchmarks(&reporter, nullptr);
    std::stringstream strOutStream;
    strOutStream << reporter.GetOutputStream().rdbuf();
    std::string strOutput = strOutStream.str();
    LOGD("%s", strOutput.c_str());
`}`

All I get is an empty string inside the strOutput. 

Is there a way to achieve the display in logcat or writing the output to json from ndk?

**Comment by dominichamon** [comment]
Hi

I'm not sure anyone has tried that before, but maybe someone will pipe up.

In the mean time, your best bet is likely a custom reporter that uses Log,
or (if you think it would be useful) changing the console reporter in the
library to use a Log class on android. The former is likely going to be
easier.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*

**Comment by NikolaMr** [comment]
Thank you, Dominic. I will surely give it a try!

**Comment by NikolaMr** [comment]
In the end, I have acomplished this by calling a native method that invokes the performTests() method that is visible in the code. The method redirects the output of the `ConsoleReporter` to the `BenchmarkStream` as it can be seen in the code below. Hope it will be of some use to others.

```
struct BenchmarkStream : std::ostream, std::streambuf
{
    BenchmarkStream() : std::ostream(this) {}

    std::vector<char> buffer;

    int overflow(int c)
    {
        buffer.push_back(c);
        return 0;
    }
};

std::string benchmarkResults = "";

void performTests() {
    int argc = 1;
    std::string argument = "";
    char* argv[1] = {"test"};
    benchmark::ConsoleReporter reporter;
    BenchmarkStream outStream;
    reporter.SetOutputStream(&outStream);
    benchmark::Initialize(&argc, argv);
    if (benchmark::ReportUnrecognizedArguments(argc, argv)) return;
    benchmark::RunSpecifiedBenchmarks(&reporter, nullptr);

    benchmarkResults = "";
    for (auto c : outStream.buffer) {
        benchmarkResults += c;
    }

    LOGI("%s", benchmarkResults.c_str());
}
```
