### ISSUE TITLE
Negative inputs have unexpected behavior

### ISSUE THREAD

**Issue by NAThompson** [google/benchmark#762]
I have a question about negative arguments to ranges. Here's my code:

```cpp
#include <benchmark/benchmark.h>
#include <array>
#include <random>
#include <iostream>
#include <algorithm>
#include <boost/math/special_functions/hypergeometric_0F1.hpp>

template<class Real>
void BM_1F0(benchmark::State& state)
{
    using boost::math::hypergeometric_0F1;

    std::default_random_engine gen;
    std::uniform_real_distribution<Real> x_dis(state.range(0), 2*state.range(0));
    Real b = 7.2;

    for (auto _ : state)
    {
        benchmark::DoNotOptimize(hypergeometric_0F1(b, x_dis(gen)));
    }
}

BENCHMARK_TEMPLATE(BM_1F0, double)->RangeMultiplier(2)->Range(-8, 8);

BENCHMARK_MAIN();
```

My expectation is that I would get `state.range(0)` to take values in the set `{-8, -4, -2, -1, 0, 1, 2, 4, 8}`. However, only the first negative argument is selected, and then we obtain positive arguments:

```
------------------------------------------------------------------
Benchmark                           Time           CPU Iterations
------------------------------------------------------------------
BM_1F0<double>/-8                 297 ns        296 ns    2362295
BM_1F0<double>/1                   83 ns         83 ns    8470167
BM_1F0<double>/2                   92 ns         92 ns    7639503
BM_1F0<double>/4                  104 ns        104 ns    6663176
BM_1F0<double>/8                  118 ns        118 ns    5918060
```

What is the idiomatic way to step through a range of negative arguments?

**Comment by dominichamon** [comment]
I'd expect that too, but i think that negative ranges haven't come up often. `range` is an `int64_t` so it should work in that respect, but my guess is the interpolation code doesn't actually support it.. let's see!

https://github.com/google/benchmark/blob/d8584bda67320937334b038e736f5bffcd438875/src/benchmark_register.h#L10

we have a CHECK that `lo` is `>= 0` which isn't encouraging, and then we insert `lo` followed by a loop starting at 1. So we don't actually support negative ranges.

I'm really surprised this hasn't come up before...

**Comment by pleroy** [comment]
I have run into this with `DenseRange`, [fixed it in my fork](https://github.com/mockingbirdnest/benchmark/commit/7d8abdbd89807198e0013af7704abeeba3ce3099), never upstreamed it (shame).

**Comment by dharvey1986** [comment]
I'm happy to take a look at this unless anyone has a patch ready to go.

**Comment by danielharvey458** [comment]
Should we definitely include 0 in the range if lo and hi straddle zero? The current behaviour is to include powers of the range multiplier between lo and hi, which would naturally extend to e.g. `{-8, -4, -2, -1, 1, 2, 4, 8}`. I can see that special-casing 0 might be desirable, though.

**Comment by LebedevRI** [comment]
I *think* `0` should be included.
