### ISSUE TITLE
Build error on freebsd 10

### ISSUE THREAD

**Issue by pdavydov108** [google/benchmark#77]
Hi, thanks for this awesome library! Unfortunatelly, I ran into a small issue with it. I tried to build it on freebsd 10.0 RELEASE and build failed. Compiler reported that header <sys/sysctl.h> has undefiened type u_int. The problem is that <sys/types.h> header should be included before it, cause this type is defined there. Can you please fix it, if you support freebsd?

**Comment by dominichamon** [comment]
i don't have a bsd machine to test on. could you send a pull request with the right header in place for BSD? And any cmake changes necessary to detect bsd.

**Comment by pdavydov108** [comment]
I sent a pull request, maybe I did something wrong, cause it didn't appear here..
