### ISSUE TITLE
PauseTiming and ResumeTiming don't work as expected.

### ISSUE THREAD

**Issue by assassin5615** [google/benchmark#797]
I used following code to measure the timing for push_back, and the result I got is 
> BM_pushback/32/16           1580 ns         1579 ns       443328

```
void BM_pushback(benchmark::State& state)
{
    for (auto _ : state)
    {
        state.PauseTiming();
        std::vector<char*> vec;
        vec.reserve(state.range(0));
        state.ResumeTiming();
        for (int i = 0; i < state.range(1); ++i)
        {
            vec.push_back(nullptr);
        }
    }

}

BENCHMARK(BM_pushback)->Args({32, 16});
```
the number doesn't look right as push_back should be very fast. I changed the code to be 
```
void BM_pushback(benchmark::State& state)
{
    std::vector<char*> vec;
    vec.reserve(state.range(0));
    for (auto _ : state)
    {
        vec.clear();
        for (int i = 0; i < state.range(1); ++i)
        {
            vec.push_back(nullptr);
        }
    }

}
```
and now the result is 

> BM_pushback/32/16           16.2 ns         16.2 ns     43646671

just wondering what went wrong? is my understanding of PauseTiming/ResumeTiming incorrect? thanks

**Comment by brenoguim** [comment]
You've got the vector desctructor being called (and timed) in the first sample, and not on the second.

**Comment by assassin5615** [comment]
@brenoguim I changed my code to be as below, and the result I got still not right. commenting PauseTiming and ResumeTiming will give me 16 ns.

> BM_pushback/32/16           1549 ns         1549 ns       451033

    ```
std::vector<char*> vec;
    vec.reserve(state.range(0));
    for (auto _ : state)
    {
        state.PauseTiming();
        vec.clear();
        state.ResumeTiming();
        for (int i = 0; i < state.range(1); ++i)
        {
            vec.push_back(nullptr);
        }
    }
```

**Comment by brenoguim** [comment]
Indeed: http://quick-bench.com/JhOx8VzByZ_ed1uGYky5WAgci-w

Maybe the cost of pausing/resuming is too large compared to the actual workload? I don't know...

**Comment by LebedevRI** [comment]
> Maybe the cost of pausing/resuming is too large compared to the actual workload? I don't know...

Most likely. Also, calling them every iteration of `for (auto _ : state)` is really bad.
That being said, i'm not sure what that graph says.
I would expect that the *benchmarking* would take longer,
but `PauseTiming()`/`ResumeTiming()` should not affect the measured values.

**Comment by pleroy** [comment]
I seem to remember that the `CHECK` macros in `PauseTiming/ResumeTiming` (defined [here](https://github.com/google/benchmark/blob/d8584bda67320937334b038e736f5bffcd438875/src/check.h#L62)) were pretty expensive, at least on Windows.

**Comment by assassin5615** [comment]
> Maybe the cost of pausing/resuming is too large compared to the actual workload? I don't know...
> 
> Most likely. Also, calling them every iteration of for (auto _ : state) is really bad.
> That being said, i'm not sure what that graph says.
> I would expect that the benchmarking would take longer,
> but PauseTiming()/ResumeTiming() should not affect the measured values.

so is this a defect? as PauseTiming()/ResumeTiming() does affect the measured values.

**Comment by dominichamon** [comment]
In an optimized compilation, your examples boil down to a loop over a single instruction (https://godbolt.org/z/5zH1_w) while calling PauseTiming and ResumeTiming take much more than that. Essentially, Pause and Resume are only useful if you're doing more work outside of them.

If you have something very fast to benchmark, try to avoid pausing and resuming. One option, in your case, would be something like this: http://quick-bench.com/MX3vyXTpfG3Aw6vQP5j2ReUIWeU

this shows that 'clear' is negligible compared to the pushback loop, and you can happily ignore it.

**Comment by assassin5615** [comment]
@dominichamon  I understand that PauseTiming/ResumeTiming is much slower than vec.clear(), so I expect that it would take much longer to run the test but it should not affect the measured result. do you have a theory for this?

what really concerns me here is that if PauseTiming/ResumeTiming does have a bug, how can I trust the output in a more complicated(practical) test case?

**Comment by LebedevRI** [comment]
How did you build your benchmark library?
With what `CMAKE_BUILD_TYPE`?
Does this still happen with `-DCMAKE_BUILD_TYPE=RELEASE`?

**Comment by assassin5615** [comment]
@LebedevRI  I build both my testcases and google-benchmark with -DCMAKE_BUILD_TYPE=RELEASE,  I also tried to build my testcases with  -DCMAKE_BUILD_TYPE=debug, the output is always incorrect.

**Comment by LebedevRI** [comment]
I'm guessing https://github.com/google/benchmark/issues/797#issuecomment-483100651 is the last version of code?
I can only echo https://github.com/google/benchmark/issues/797#issuecomment-483235342, `PauseTiming()` *has* to cost something, in terms of time.
If the actual work done that is measured is small (not sure of the exact numbers, less than 2x..10x the cost of empty loop with just `PauseTiming(); ResumeTiming()` ?), then sure, the results will be "incorrect".

**Comment by xorz57** [comment]
I am experiencing the same problem #842

**Comment by dominichamon** [comment]
Pause and Resume timer will of course add overhead. I don't see a way around that. There have been attempts to account for the pause/resume timing overhead but that _also_ adds complexity which we would then have to measure, etc, etc.

The best way to handle this case is to measure the expensive bit and the combined code as separate benchmarks, then subtract them, avoiding the overhead altogether.

Pause and Resume are useful when the workload you're benchmarking is expected to be expensive and you want to take out a significant amount of processing from the timed loop.
