### ISSUE TITLE
Allow global installation of the library into /usr/lib64/

### ISSUE THREAD

**Issue by lockywolf** [google/benchmark#807]
Hello, everyone.

I'd be very happy if the cmake file allowed not just setting the prefix (/usr), but also the libdir suffix, that is, in my case, "64", that is, I'd like to install the library into /usr/lib64/, because that's how multilib is organized in my distribution.

Would it be possible?

**Comment by LebedevRI** [comment]
One would simply need to replace https://github.com/google/benchmark/blob/d8584bda67320937334b038e736f5bffcd438875/src/CMakeLists.txt#L58-L62
with
https://cmake.org/cmake/help/latest/module/GNUInstallDirs.html (available at least since cmake-2.8.6+ or so)
Patches welcomed, should be simple.

**Comment by lockywolf** [comment]
https://github.com/google/benchmark/pull/808
