### ISSUE TITLE
The "B" bytes suffix isn't really printed

### ISSUE THREAD

**Issue by MuAlphaOmegaEpsilon** [google/benchmark#819]
From the README.md file:
```
Benchmark                               Time(ns)    CPU(ns) Iterations
----------------------------------------------------------------------
BM_SetInsert/1024/1                        28928      29349      23853  133.097kB/s   33.2742k items/s
BM_SetInsert/1024/8                        32065      32913      21375  949.487kB/s   237.372k items/s
BM_SetInsert/1024/10                       33157      33648      21431  1.13369MB/s   290.225k items/s

```
The `B` suffix of bytes isn't printed.

**Comment by aespondac** [comment]
This part of [README.md](https://github.com/google/benchmark/commit/201b981abd3a0bc63d2c2f5efd6871bdaceb2ccd#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L339-L345) code no longer exists, has been deleted at #1211.

@dmah42 , this Issue should be still open?

**Comment by LebedevRI** [comment]
It's still in `docs/user_guide.md` though, isn't it?
