### ISSUE TITLE
Bad git tag version format

### ISSUE THREAD

**Issue by dscole** [google/benchmark#823]
The newest release tag `v1.5` should be `v1.5.0`. There is code in the CMake file `GetGitVersion.cmake` to extract the version from a git tag and it uses this regex `v[0-9]*.[0-9]*.[0-9]*`, which doesn't match `v1.5`. At the moment the cmake code picks up the version as `v1.4.1`.

**Comment by dominichamon** [comment]
apologies. fixed.
