### ISSUE TITLE
Release tag 1.5.0 vs 1.5

### ISSUE THREAD

**Issue by chenrui333** [google/benchmark#827]
Relates to https://github.com/Homebrew/homebrew-core/pull/40530
https://github.com/Homebrew/homebrew-core/pull/40054

We have two homebrew formula PRs for v1.5.0, v1.5. 
So filed a bug report in here to confirm which one is desired (NOTE, currently homebrew-core is shipped with v1.5).

Thanks!

**Comment by dominichamon** [comment]
v1.5 should have been removed from the repo. v1.5.0 is the correct version.

Dominic Hamon | Google
*There are no bad ideas; only good ideas that go horribly wrong.*
