### ISSUE TITLE
Speedup using -O3 on benchmark when benchmarking library functions 

### ISSUE THREAD

**Issue by jsiever** [google/benchmark#828]
I am not 100% sure this is an issue, but I do not understand it:

I have a static library functions.a. I benchmark a function in library.a like:
```
for (auto _ : state) {
    function(arg);
}
```
and compile the benchmark.cpp to benchmark.o with g++ 5.4.0 and -O3. After linking there is a speedup of 2 for the measured times compared to omitting -O3 when compiling benchmark.o.

Shouldn't the benchmark results for the functions in functions.a be unaffected by this? 

Thank you!

**Comment by dominichamon** [comment]
If you look at the output
<https://github.com/google/benchmark/blob/f6e96861a373c90ea0c727177fc68d2984e048bb/src/reporter.cc#L74>
from benchmark when it's compiled in "debug" mode (as per cmake):

"***WARNING*** Library was built as DEBUG. Timings may be affected.

If you're compiling the library without using cmake I don't know if NDEBUG
is going to be set appropriately so we may not be outputting that warning,
but the point is still valid: The benchmark library itself should be
compiled to be optimized to ensure it has minimal overhead.

If you want to see the overhead I suggest you look at the generated
assembly for -O3 vs not. My guess is you'll see that in O3 the for loop is
optimised away (it's intended to be, and we check it is in our unit tests)
but in non-optimized builds it isn't.

**Comment by jsiever** [comment]
Was built with
`cmake -DCMAKE_BUILD_TYPE=Release`
and NDEBUG seems to be set appropriately.

If I use -O3 and look at the assembler for benchmark.o it looks fine to me:
```
        call    benchmark::State::StartKeepRunning()
        testq   %rbx, %rbx
        je      .L7
        .p2align 4,,10
        .p2align 3
.L27:
        movsd   .LC2(%rip), %xmm1
        leaq    32(%rsp), %rdi
        movapd  %xmm1, %xmm0
        call    my_function(double, double) const
        movq    %xmm0, %rax
        subq    $1, %rbx
        jne     .L27
.L7:
        movq    %r12, %rdi
        call    benchmark::State::FinishKeepRunning()
```
but without -O3 it is
```
        call    benchmark::State::StartKeepRunning()
        movq    $0, -128(%rbp)
        movq    $0, -120(%rbp)
        movq    -128(%rbp), %rax
        movq    -120(%rbp), %rdx
        movq    %rax, -128(%rbp)
        movq    %rdx, -120(%rbp)
.L14:
        movq    -176(%rbp), %rax
        testq   %rax, %rax
        setne   %al
        movzbl  %al, %eax
        testq   %rax, %rax
        je      .L8
        movl    $1, %eax
        jmp     .L9
.L8:
        movq    -168(%rbp), %rax
        movq    %rax, %rdi
        call    benchmark::State::FinishKeepRunning()
        movl    $0, %eax
.L9:
        testb   %al, %al
        je      .L10
        movsd   .LC2(%rip), %xmm0
        movabsq $4609884578576439706, %rdx
        leaq    -96(%rbp), %rax
        movapd  %xmm0, %xmm1
        movq    %rdx, -240(%rbp)
        movsd   -240(%rbp), %xmm0
        movq    %rax, %rdi
        call    BM_Interpolation::interpolate_bilinear(double, double) const
```

Guess I will just use -O3 for my benchmarks, thank you!
