### ISSUE TITLE
--benchmark_counters_tabular is invalid for --benchmark_out

### ISSUE THREAD

**Issue by zhongpan** [google/benchmark#834]
when set --benchmark_counters_tabular=true and --benchmark_output_format=console，It does not take effect on the output file. The output file still looks like:
```
------------------------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations UserCounters...
------------------------------------------------------------------------------------
l4cp_a_c/32/manual_time      3349447 ns        74761 ns          209 flush=0.68267 items_per_second=298.557/s
l4cp_a_c/512/manual_time    20886315 ns        0.000 ns           34 flush=0.707233 items_per_second=47.8782/s
l4cp_a_f/32/manual_time        62964 ns        45752 ns        10587 flush=0.0637161 items_per_second=15.8821k/s
l4cp_a_f/512/manual_time      182277 ns        50457 ns         3716 flush=0.216913 items_per_second=5.48616k/s
```

**Comment by dominichamon** [comment]
It's benchmark_out_format, though it defaults to console so i don't think
you're using the right args for what you want.

what are you trying to do?

**Comment by zhongpan** [comment]
I want the output file to look like this:
```
------------------------------------------------------------------------------------
Benchmark                          Time             CPU   Iterations     flush  items_per_second
------------------------------------------------------------------------------------
l4cp_a_c/32/manual_time      3349447 ns        74761 ns          209   0.68267         298.557/s
l4cp_a_c/512/manual_time    20886315 ns        0.000 ns           34  0.707233         47.8782/s
l4cp_a_f/32/manual_time        62964 ns        45752 ns        10587 0.0637161        15.8821k/s
l4cp_a_f/512/manual_time      182277 ns        50457 ns         3716  0.216913        5.48616k/s
```

**Comment by zhongpan** [comment]
The command option is "--benchmark_counters_tabular=true --benchmark_output_format=console --benchmark_output=result.txt".

**Comment by dominichamon** [comment]
with the latest version, the command line should be

$ ./bm --benchmark_out=result.txt --benchmark_out_format=console
--benchmark_counters_tabular=true

However, i agree: it looks like counters_tabular doesn't apply to file
outputs. that's a bug :)

**Comment by dmah42** [comment]
i believe it's still an issue, yes.

**Comment by varshneydevansh** [comment]
I will solve this problem in a couple of days. Currently working on my writing stuff. As soon as I am finished with that, I will notify you.

**Comment by varshneydevansh** [comment]
I sat down, last night to understand the code where the possible problem is and after spending a couple of hours in the morning I kinda pinpointed where it is.

**This is what I have added -**

https://github.com/varshneydevansh/benchmark/blob/02a354f3f323ae8256948e1dc77ddcb1dfc297da/src/benchmark.cc#L576

```cpp
    if (!file_reporter) {
      ConsoleReporter::OutputOptions options = ConsoleReporter::OO_None;
      if (FLAGS_benchmark_out_format == "console" &&
          FLAGS_benchmark_counters_tabular) {
        options | ConsoleReporter::OO_Tabular;
      }
```

creating the PR
