### ISSUE TITLE
Error C2146 and error C4430 in benchmark_runner.cc(62).

### ISSUE THREAD

**Issue by joe2018Outlookcom** [google/benchmark#853]
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x86 error messages :
src\benchmark_runner.cc(62): error C2146: syntax error : missing ';' before identifier 'IterationCount'
src\benchmark_runner.cc(62): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
![Annotation 2019-08-21 112221](https://user-images.githubusercontent.com/42833718/63400502-962ead00-c406-11e9-957d-23de680069b7.png)
Here is the point:
https://github.com/google/benchmark/blob/7d97a057e16597e8020d0aca110480fe82c9ca67/src/benchmark_runner.cc#L62

The suggestion is to replace ‘constexpr’ with 'const'.

**Comment by EricWF** [comment]
I don't believe that compiler is supportive. it's choking over the
constexpr keyword.

**Comment by joe2018Outlookcom** [comment]
However, it's ture (in Visual Studio 2013 Update 5).
[https://github.com/google/benchmark/blob/master/README.md#requirements](https://github.com/google/benchmark/blob/master/README.md#requirements)

**Comment by EricWF** [comment]
thanks for bringing this to my attention.

Unfortunately it appears the documentation is out of date, especially after
the migration to C++11.

At this points Google test assumes a fully compliant and bug-free c++11
implementation.

**Comment by LebedevRI** [comment]
Sorry about that, fixed docs in https://github.com/google/benchmark/commit/3523f11d36caf2ffe4acffe2e9fb15775cec8112.
