### ISSUE TITLE
Fix potential ambiguity in floating point imprecision handling for Sqrt lambda.

### ISSUE THREAD

**Issue by aerosayan** [google/benchmark#860]
The `Sqrt` lambda in `statistics.cc` is implemented as such:

```c++
auto Sqrt = [](const double dat) {
  // Avoid NaN due to imprecision in the calculations
  if (dat < 0.0) return 0.0;   // POTENTIAL BUG DUE TO AMBIGUITY
  return std::sqrt(dat);
};
```
I have included `// POTENTIAL BUG DUE TO AMBIGUITY` to mark the issue.

As can be seen, the original author's intention was to handle small deviations around `0.0` due to floating point imprecision effects. However the issue is that, here the code isn't checking for small deviations around `0.0`. 

So, even if a user/developer gives `dat = -10000000.0`, instead of throwing an error or returning `-nan`, it would just return `0.0`. This can lead to complications and bugs later on.

An epsilon value of something like `#define BENCHMARK_EPS_ALMOST_ZERO 1e-9` should be used to do the check if `dat` is actually suffering from floating point imprecision or should it just throw an error or run it normally.

Thanks

**Comment by aerosayan** [comment]
On second thought, a better option than using `#define BENCHMARK_EPS_ALMOST ZERO 1e-9` macro would be to create an `double eps_almost_zero = 1e-9;` variable. This way the user/developer can modify it easily for their use.

**Comment by EricWF** [comment]
This isn't a customization point, and users can't call `Sqrt` directly.

I'm also pretty sure there's a precondition that all quantities passed to the statistics algorithms are not negative. 

What problem are you actually trying to solve? Like what caused you to notice this particular behavior?

**Comment by pleroy** [comment]
Magic numbers like the one proposed above are *always* a terrible idea from the numerical analysis perspective.

Furthermore, this modified `Sqrt` function is a bug waiting to happen because if someone uses it in another context the truncation of negative numbers may not be appropriate.

The right way to deal with inaccuracies is to check the sign of `avg_squares - Sqr(mean)` near line 74, return 0 if it's negative, and use the vanilla `std::sqrt` otherwise.

**Comment by aerosayan** [comment]
`Sqrt` is currently only being used in `StatisticsStdDev` to take the square root of the variance to get the standard deviation. 

Mathematically, variance is guaranteed to never be negative.

Moreover, most of the general statistics formulas available which do use a `sqrt` seem to take the `sqrt` of a non-negative value.

Thus, if the current `Sqrt` implementation is used only with expressions that evaluate to guaranteed non-negative values, it will be okay.

If it will be valuable to the project to handle negative values gracefully with `Sqrt` then [PEP-485](https://www.python.org/dev/peps/pep-0485/) will probably be helpful.

Thanks

**Comment by pleroy** [comment]
Closeness checkers like PEP-485 are useful for writing tests that are change detectors for numerical algorithm.  They should not be used in the body of the algorithms themselves.

**Comment by aerosayan** [comment]
Thanks for the feedback ! I am closing the issue.
