### ISSUE TITLE
Add gitignore rule to ignore CMakeLists.txt.user file created by Qt-Creator.

### ISSUE THREAD

**Issue by aerosayan** [google/benchmark#862]
Using Qt-Creator to load the benchmark project using the `CMakeLists.txt` creates an XML file called `CMakeLists.txt.user` which pollutes `git status`.

Here is a snippet of the file extracted using `head` command.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE QtCreatorProject>
<!-- Written by QtCreator 4.3.0, 2019-08-24T07:07:21. -->
<qtcreator>
 <data>
  <variable>EnvironmentId</variable>
  <value type="QByteArray">{9168f244-edbf-4147-a8e1-44e12895c44b}</value>
 </data>
 <data>
  <variable>ProjectExplorer.Project.ActiveTarget</variable>
```

A rule is to be added to `.gitignore` to prevent the pollution of `git status`.

**Comment by LebedevRI** [comment]
I was actually holding off on doing this because then it would be getting deleted during  `git clean -f -d -x`, which isn't what i'd want to happen/

**Comment by aerosayan** [comment]
> I was actually holding off on doing this because then it would be getting deleted during `git clean -f -d -x`, which isn't what i'd want to happen.

I tried your command and I found that the file was getting deleted even when the rule was not added.
PS : I don't know much about `git clean`

**Comment by LebedevRI** [comment]
That's because i meant `clean -d -f -X` apparently (it's an aliased as full-clean for me, so i don't recall)
