### ISSUE TITLE
License Question

### ISSUE THREAD

**Issue by mstankus** [google/benchmark#864]
I have created a new repository (see   https://github.com/mstankus/benchmarking-cpp-std-using-google-benchmarks) with the MIT License. I have added a version of the "Basic Usage" example from your your README file to my repository. It is in the directory std::string/std::string::constructor.

If Google wants me to change my license from MIT to Apache because of this, let me know.

Also, feel free to contribute to my repository.

Thanks

**Comment by dominichamon** [comment]
disclaimer: IANAL but i know how to search stack exchange :)

https://opensource.stackexchange.com/questions/1711/combining-code-written-under-different-licenses-eiffel-forum-license-mit-and-a

you should at least include a copy of the Apache 2.0 license in a NOTICE file in your repo (alongside the MIT license) as your repo is now multi-licensed. this is in line with section 4 of the Apache license.

**Comment by LebedevRI** [comment]
IANAL too, but right now it's literally just a standard benchmark stub,
not the actual code of benchmark library. I'm not sure you need to
specify license of the library you use then,
there is no actual code combining happening.
