### ISSUE TITLE
Cannot set -DGOOGLETEST_PATH as cmake argument.

### ISSUE THREAD

**Issue by ambitslix** [google/benchmark#867]
The following will not work:

$cmake -DGOOGLETEST_PATH=$HOME/googletest

-- Looking for Google Test sources in /home/alian/Desktop/Projects/etf-framework/submodules/benchmark/googletest
CMake Error at CMakeLists.txt:34 (message):
  Did not find Google Test sources! Either pass correct path in
  GOOGLETEST_PATH, or enable ALLOW_DOWNLOADING_GOOGLETEST, or disable
  BENCHMARK_ENABLE_GTEST_TESTS / BENCHMARK_ENABLE_TESTING.

**Comment by LebedevRI** [comment]
And `$ ls -lah $HOME/googletest` output?

**Comment by ambitslix** [comment]
The directory exists:

total 88K
drwxrwxr-x 5 alian alian 4.0K Aug 30 22:03 .
drwxrwxr-x 6 alian alian 4.0K Sep 15 08:30 ..
-rw-rw-r-- 1 alian alian 5.0K Aug 30 22:03 appveyor.yml
-rw-rw-r-- 1 alian alian 5.4K Aug 30 22:03 BUILD.bazel
drwxrwxr-x 2 alian alian 4.0K Aug 30 22:03 ci
-rw-rw-r-- 1 alian alian  116 Aug 30 22:03 .clang-format
-rw-rw-r-- 1 alian alian  886 Aug 30 22:03 CMakeLists.txt
-rw-rw-r-- 1 alian alian 6.1K Aug 30 22:03 CONTRIBUTING.md
-rw-rw-r-- 1 alian alian   49 Aug 30 22:03 .git
-rw-rw-r-- 1 alian alian 1.6K Aug 30 22:03 .gitignore
drwxrwxr-x 8 alian alian 4.0K Aug 30 22:03 googlemock
drwxrwxr-x 9 alian alian 4.0K Aug 30 22:03 googletest
-rw-rw-r-- 1 alian alian 2.0K Aug 30 22:03 library.json
-rw-rw-r-- 1 alian alian 1.5K Aug 30 22:03 LICENSE
-rw-rw-r-- 1 alian alian 1.2K Aug 30 22:03 platformio.ini
-rw-rw-r-- 1 alian alian 4.6K Aug 30 22:03 README.md
-rw-rw-r-- 1 alian alian 2.4K Aug 30 22:03 .travis.yml
-rw-rw-r-- 1 alian alian  600 Aug 30 22:03 WORKSPACE

I created patch for this in a fork:

https://github.com/ambitslix/benchmark/pullsl/1

**Comment by LebedevRI** [comment]
Ah yes. But the fix is
```diff
- set(GOOGLETEST_PATH "${CMAKE_CURRENT_SOURCE_DIR}/googletest") # Mind the quotes
+ set(GOOGLETEST_PATH "${CMAKE_CURRENT_SOURCE_DIR}/googletest" CACHE PATH "") # Mind the quotes
```
Please feel free to submit that as a PR.

**Comment by ambitslix** [comment]
Should PR should be good now.
