### ISSUE TITLE
HOST_NAME_MAX undefined for NaCl, Movidius Myriad, (others?)

### ISSUE THREAD

**Issue by GMNGeoffrey** [google/benchmark#871]
The sysinfo.cc [GetSystemName function](https://github.com/google/benchmark/blob/b988639f316ed0aca69297effbf67015c3bf0640/src/sysinfo.cc#L413) uses HOST_NAME_MAX, but this is not defined for all systems. In particular, I'm currently getting build errors on NaCl and Movidious Myriad. The former has a BENCHMARK_OS_* macro already defined, but the latter does not, I think.

Also note that NaCl actually does have a HOST_NAME_MAX defined in local_lim.h, but that only ends up getting included in limits.h if __USE_POSIX is defined (http://stackoverflow.com/q/30084116). So unconditionally defining HOST_NAME_MAX there seems inadvisable, since with posix set it will error on redefinition.

Also since this is just a debug function for getting the system name, it seems better if this is not a build-stopping error. We could assume some default value for HOST_NAME_MAX, return the empty string if it's not set, or something else. Either way, could issue a #warning if HOST_NAME_MAX is not set.

If the host name is too big to fit in the length passed to gethostname, it's [undefined](http://man7.org/linux/man-pages/man2/gethostname.2.html) whether there's an error and whether the buffer is null terminated. I think since we're constructing the std::string from an array, it will work either way though, so we should be fine just using some default for HOST_NAME_MAX.

I'm thinking something like:

```
std::string GetSystemName() {
// ...
#else // defined(BENCHMARK_OS_WINDOWS)
#ifndef HOST_NAME_MAX
#ifdef BENCHMARK_HAS_SYSCTL // BSD/Mac Doesnt have HOST_NAME_MAX defined
#define HOST_NAME_MAX 64
#elif defined(BENCHMARK_OS_NACL)
#define HOST_NAME_MAX 64
#elif defined(BENCHMARK_OS_QNX)
#define HOST_NAME_MAX 154
#else
#warning "HOST_NAME_MAX not defined. using 64"
#define HOST_NAME_MAX 64
#endif
#endif // def HOST_NAME_MAX
  char hostname[HOST_NAME_MAX];
  int retVal = gethostname(hostname, HOST_NAME_MAX);
  if (retVal != 0) return std::string("");
  return std::string(hostname);
#endif // Catch-all POSIX block.
}
```

Thoughts?

**Comment by GMNGeoffrey** [comment]
Oh rtems is the OS on the myriad, which is probably actually the thing to check for

**Comment by GMNGeoffrey** [comment]
Which has a BENCHMARK_OS setting already and sets MAXHOSTNAMELEN to 256. I think we can use that as the reference (https://github.com/RTEMS/rtems/blob/master/cpukit/librpc/src/rpc/netname.c#L62)

**Comment by dominichamon** [comment]
Yep, that seems reasonable.

**Comment by barracuda156** [comment]
On macOS `sys/param.h` has:
```
#define MAXHOSTNAMELEN	256		/* max hostname size */
```
