### ISSUE TITLE
Deprecate Prefix

### ISSUE THREAD

**Issue by dominichamon** [google/benchmark#88]
We currently print 'DEBUG' at the start of every line of output when built in debug mode. This is noisy and the same warning can be captured with a header stanza instead.

**Comment by EricWF** [comment]
I have a change that does somthing like this

**Comment by EricWF** [comment]
Sorry, I didn't mean to close this. I just wanted to say I have a possible fix in my patch.

**Comment by dominichamon** [comment]
i checked your patch before writing this and didn't notice.

happy for yours to go in instead :)
