### ISSUE TITLE
Read options from environment

### ISSUE THREAD

**Issue by mablanchard** [google/benchmark#881]
Benchmark execution options can be specified using the CLI (eg. `--benchmark_out=<filename>` for the results file location). Would be nice to also be able to read these options from the execution environment:  setting `BENCHMARK_OUT_FORMAT=<filename>` would be equivent of `--benchmark_out_format=json`. Google test has a [similar mechanism](https://github.com/google/googletest/blob/master/googletest/docs/advanced.md#controlling-test-output).

It seems like Benchmark [already has some helper code for this](https://github.com/google/benchmark/blob/1d41de84633bf40ddf0ad50165d77200e3d8b5fd/src/commandlineflags.cc#L80). Activating it would help integrating benchmarks execution in CI pipelines driven by env. variables for example.

**Comment by LebedevRI** [comment]
I honestly first thought that was already supported when i first saw the code, but guess not.

**Comment by dominichamon** [comment]
i'm sure this used to be supported too.
