### ISSUE TITLE
Why I got this error: no member named 'MeasureProcessCPUTime' in 'benchmark::internal::Benchmark'

### ISSUE THREAD

**Issue by weilunpeng** [google/benchmark#882]
I got this error:
`no member named 'MeasureProcessCPUTime' in 'benchmark::internal::Benchmark'`
Any helps?

**Comment by LebedevRI** [comment]
Version mismatch between the headers and the library

**Comment by weilunpeng** [comment]
@LebedevRI So will it be only in v1.5.0?

**Comment by LebedevRI** [comment]
There's already v1.5.0 release, no?

**Comment by weilunpeng** [comment]
I'm in v1.4.1 release, now

**Comment by LebedevRI** [comment]
(I'm gonna close this since i believe the question was answered)

**Comment by weilunpeng** [comment]
@LebedevRI Sorry, if I'm in v1.4.1, can I use MeasureProcessCPUTime?

**Comment by LebedevRI** [comment]
There is no such thing in v1.4.1 https://github.com/google/benchmark/blob/v1.4.1/include/benchmark/benchmark.h
