### ISSUE TITLE
Cache size unit in JSON output

### ISSUE THREAD

**Issue by leanil** [google/benchmark#884]
I see overscaled cache sizes in the json output, like
```
"caches": [
      {
        "type": "Data",
        "level": 1,
        "size": 32000000,
        "num_sharing": 2
      } ...
```
while the console output is ok.
```
CPU Caches:
  L1 Data 32K (x6)
```
The problem seems to be that the size is multiplied by 1000 again [here](https://github.com/google/benchmark/blob/master/src/json_reporter.cc#L138), though it's already in bytes from [here](https://github.com/google/benchmark/blob/b8bce0c7ed4e02426fa4de21fec385fbaa84a7b2/src/sysinfo.cc#L273).

**Comment by dominichamon** [comment]
Nice catch.

**Comment by dominichamon** [comment]
in [OSX](https://github.com/google/benchmark/blob/b8bce0c7ed4e02426fa4de21fec385fbaa84a7b2/src/sysinfo.cc#L310) we don't multiply but it might be coming in in bytes. Ditto in [Windows](https://github.com/google/benchmark/blob/b8bce0c7ed4e02426fa4de21fec385fbaa84a7b2/src/sysinfo.cc#L343), and QNX looks like [bytes](https://github.com/google/benchmark/blob/b8bce0c7ed4e02426fa4de21fec385fbaa84a7b2/src/sysinfo.cc#L392).

So I think the right thing to do is just fix up the JSON reporter, right?

**Comment by LebedevRI** [comment]
> So I think the right thing to do is just fix up the JSON reporter, right?

I'd say so. Storing it in bytes internally makes sense.

**Comment by LebedevRI** [comment]
@leanil will you be interested in trying to provide a patch for this?
I don't think that code can have test coverage thought.

**Comment by LebedevRI** [comment]
> So is that the patch you'd like?

Yes, please.
I grepped a bit, and i think that is a single-line change.
