### ISSUE TITLE
Building on Windows with VS2017 and BUILD_SHARED_LIBS=ON doesn't create .lib files

### ISSUE THREAD

**Issue by KyleFromKitware** [google/benchmark#888]
When I configure on Windows with:

```
cmake .. -GNinja -DBUILD_SHARED_LIBS=ON
```

and build, no .lib file is generated for the .dlls. Furthermore, running `dumpbin` on one of the .dlls:

```
dumpbin /exports src\benchmark.dll
```

confirms that no symbols are exported in the .dll. I suspect they are not given the proper `__declspec(dllexport)` directive.

**Comment by ura1286** [comment]
can you share the steps of building on windows with Visual 2017?

**Comment by KyleFromKitware** [comment]
```
"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"
cmake .. -GNinja -DBUILD_SHARED_LIBS=ON -DBENCHMARK_ENABLE_GTEST_TESTS=OFF
ninja
```

I disabled tests so I wouldn't have to deal with building GTest.
