### ISSUE TITLE
Undefined reference to UseRealTime

### ISSUE THREAD

**Issue by kode9** [google/benchmark#89]
Hello,

I tried to use the function to use realtime instead of CPU time:

```c++
// If a particular benchmark is I/O bound, or if for some reason CPU
// timings are not representative, call this method from within the
// benchmark routine.  If called, the elapsed time will be used to
// control how many iterations are run, and in the printing of
// items/second or MB/seconds values.  If not called, the cpu time
// used by the benchmark will be used.
void UseRealTime();
```

like this: 

```c++
static void BM_foo(benchmark::State& state) {
  benchmark::UseRealTime();
  while (state.KeepRunning()) {
    // Stuff
  }
}
```

But this won't link.

The function is actually defined in the `benchmark::internal` namespace. Simply moving it to the `benchmark` namespace _seems_ to work (at least to compile).

Is this function supposed to be used like this ? 

Also the function `void SetLabel(const std::string& label);` (the free function, not the `State` member) is not defined at all.

Cheers,

**Comment by dominichamon** [comment]
It looks like we don't have tests for `UseRealTime` so it may be an oversight. I'll prepare a patch (unless you want to?).

The `SetLabel` issue will be fixed with PR #86
