### ISSUE TITLE
Compilation fails for iOS

### ISSUE THREAD

**Issue by nfrechette** [google/benchmark#891]
Using Xcode 10.3
Build version 10G8
GBench v1.5.0

When generating the solution using CMake and XCode generator, the build fails here:
CMake Error at external/benchmark/CMakeLists.txt:251 (message):
  Failed to determine the source files for the regular expression backend

I am hooking up this great benchmark library to the [Realtime Math library](https://github.com/nfrechette/rtm) and I would greatly appreciate iOS support at some point. Once the library is integrated for the other platforms and merged into develop, I will create a branch to reproduce this issue and update this ticket accordingly.

**Comment by dominichamon** [comment]
Can you attach the full cmake logs so I can see what regular expression backend it's trying and where it's failing?

**Comment by nfrechette** [comment]
All 3 regex backends it tries fail. They also fail for android with NVIDIA CodeWorks.
I looked at the try_compile output for android and saw that it failed due to having warnings as errors and having warnings set to the highest level (in particular, it complains about `#include_next` being an extension). By turning warnings off, compilation works and STD and POSIX regex backends compile fine. I imagine iOS has a similar issue, I'll check later this week.

Semi related, the first generation works (from a clean build) but if I modify a CMakeLists.txt file, it runs again and it complains that we failed to compile the regex backends. Seems like a variable caching issue.

Also worth noting that on android, we output to std::cout for console but by default that is redirected to dev/null and nothing is visible. It would be nice if the output was readable from logcat.

**Comment by EricWF** [comment]
Do you know if `-Wsystem-headers` is being passed?

**Comment by nfrechette** [comment]
Seems like I must have missed something. I started over and iOS works but only on the first cmake invocation. I get an error due to the variable caching issue I also observed on android mentioned earlier. If I start from a clean build, it works. I'll close this issue but android remains wonky with codeworks.

Great stuff, keep it up!
