### ISSUE TITLE
Conan ARM gcc build fails due to -m32/-m64 flags not supported

### ISSUE THREAD

**Issue by michkrom** [google/benchmark#892]
The _conan create_ or (build as dependency) fails on ARM targets (such as RPi)  as the -m32/-m64  flags are not supported by arm gcc compiler. 

Possibly, fence setting BENCHMARK_BUILD_32_BITS when ARM target is detected (conanfile.py). E.g.:

cmake.definitions["BENCHMARK_BUILD_32_BITS"] = "ON" if "64" not in str(self.settings.arch) **and 'arm' not in str(self.settings.arch)** else "OFF"

However, clang seems to support -m32/64  bit so the above suggestion may not be the best.

**Comment by dominichamon** [comment]
@Croydon who did the conan integration.

**Comment by Croydon** [comment]
@michkrom For issues with Conan packages please fill an issue in the [Conan Center Index](https://github.com/conan-io/conan-center-index) 

Upstream maintainers might not be involved in the Conan recipes so their issue trackers are most of the time the wrong place to report issues

Thanks! 😄

**Comment by Croydon** [comment]
Actually, I forgot that we have a conanfile directly in this repository too. Never mind then 

It is still an open question how to handle such a hybrid setup: https://github.com/conan-io/conan-center-index/issues/22

**Comment by Croydon** [comment]
This might be issue https://github.com/conan-io/conan-center-index/issues/370

@michkrom You are cross-compiling to ARM, right?

**Comment by michkrom** [comment]
Actually, I was just compiling on the target, a rpi4.

**Comment by dnilosek** [comment]
Not to revive a zombie thread here, but the issue still exists even with the prior fix. The string check for "64" doesnt work for most ARM arch types in Conan (for example, `armv8`). I ran into it building for a Jetson TX2. The CMake-only solution you have to this was to pass the responsibility of adding `-m32` compiler flag to to user (https://github.com/google/benchmark/blob/master/CMakeLists.txt#L22). 

Unless Conan has a decent way of understanding when a 32-bit build needs to be made, I would recommend doing the same here and forcing the user to add the compiler flag themselves.

**Comment by Croydon** [comment]
I guess this has been fixed in the Conan Center Index recipe via https://github.com/conan-io/conan-center-index/pull/4653
