### ISSUE TITLE
Save the time value

### ISSUE THREAD

**Issue by TeodoraB21** [google/benchmark#898]
Hello!

Is there a way to save the time value in a variable?

Benchmark                                                         Time             CPU         Iterations
----------------------------------------------------------------------------------
BM_VRP/Test1/iterations:10/real_time        400 ms           402 ms           10
BM_VRP/Test2/iterations:10                        396 ms           395 ms           10

For example to get that "396"ms value in a variable.

**Comment by dominichamon** [comment]
Hello!

It would probably help to understand what you're trying to do. I assume by
variable you mean "part of the State that is accessible from the
benchmark". Is that correct? If so, why do you think that would be useful?
:)

**Comment by TeodoraB21** [comment]
I want to compare 2 versions of the program. So with the first version I will receive 200ms and with the second one I receive 396ms, and the to do something regarding this.

**Comment by LebedevRI** [comment]
> I assume by variable you mean "part of the State that is accessible from the benchmark". Is that correct? If so, why do you think that would be useful

If specified like that, i'd like that, i'd be interested in that, like previously mentioned.
Custom user counters are great, but they are not flexible enough, they use default timer only.
One might reasonably want more flexibility: https://github.com/darktable-org/rawspeed/blob/142a0dcd21f4ec04ac5060c3024d789481d6e21d/src/utilities/rsbench/main.cpp#L131-L156

> I want to compare 2 versions of the program. So with the first version I will receive 200ms and with the second one I receive 396ms, and then to do something regarding this.

I think you might want https://github.com/google/benchmark/blob/master/tools/compare.py

**Comment by dominichamon** [comment]
In the tools directory you can find some scripts to help you with the
comparison of two outputs. If you want to do something in the executable
that contains the benchmarks, you would need to provide a custom reporter
to get the results as they come in and then decide what to do with them.

**Comment by TeodoraB21** [comment]
I tried with JSONReporter, but i don't know how to get the results.

BENCHMARK_CAPTURE(BM_VRP, VRPTest2, input)->Unit(benchmark::kMillisecond)->Iterations(10);
benchmark::BenchmarkReporter* reporter= new benchmark::JSONReporter();
benchmark::RunSpecifiedBenchmarks(reporter);
std::ostream& os=reporter->GetOutputStream();

when I try to get the string from "os" i returns an empty string.

How do I get the time value that is shown in the JSON?

**Comment by dominichamon** [comment]
The JSON reporter is expecting to write out to the output stream which
usually means to your console. Ie, you could from the command line trigger
the benchmark executable to use JSON as output and then capture that in a
separate script for comparison. As I mentioned above, creating a custom
reporter that can capture the results and not output them to console is
likely what you're after.
