### ISSUE TITLE
Cache size kB binary or SI?

### ISSUE THREAD

**Issue by leanil** [google/benchmark#899]
Shouldn't the scaling factor [here](https://github.com/google/benchmark/blob/cf446a18bf37d5cc9b116f59cf9e6a9be89e58cc/src/sysinfo.cc#L273) be `1024` instead of `1000`?
I know SI says 1kB = 1000 byte, but I think cache sizes are usually binary multiples (at least those that I could check).

https://www.kernel.org/doc/Documentation/ABI/testing/sysfs-devices-system-cpu
https://en.wikipedia.org/wiki/Kilobyte

**Comment by dominichamon** [comment]
then it would be kiB <https://en.wikipedia.org/wiki/Kibibyte> or maybe KB.
We could support that if it makes more sense to report in kiB for cache
sizes.

**Comment by LebedevRI** [comment]
`lscpu` agrees:
```
$ cat /sys/devices/system/cpu/cpu0/cache/index*/size 
16K
64K
2048K
8192K
$ lscpu | grep "cache"
L1d cache:                       64 KiB
L1i cache:                       256 KiB
L2 cache:                        8 MiB
L3 cache:                        8 MiB
```

**Comment by leanil** [comment]
> We could support that if it makes more sense to report in kiB for cache sizes.

I wouldn't change the reporting (K in console, bytes in json), the question seems to be if you want to store the correct number of bytes internally.

So what's the conclusion? Can I make another 1 line PR changing that scale factor to 1024?
It seems there are no related tests.

**Comment by dominichamon** [comment]
If you did want to change it to binary K, then the unit in the reporting
should also change to kiB.

**Comment by LebedevRI** [comment]
This isn't just an UI issue though.
Those cache sizes are exposed via `CPUInfo` (or whats-it-called),
and they can be used by benchmarks. So this really is a correctness issue.
Right now i //think// the `*1000` is incorrect.

**Comment by LebedevRI** [comment]
git blame says that was introduced in https://github.com/google/benchmark/commit/27e0b439cf0f9be329f617056795b4e5c3612f34#diff-374e7bbe55f23379d7a8ac1d378a9d2dR211 and not modified since.
@EricWF comments?

**Comment by LebedevRI** [comment]
So, i've briefly chatted with @craig.topper, and while there doesn't seem to be
a definitive guaranteed answer, if we look at the raw data
```
<ctopper> lebedevri: looks like all the low level pieces are also in /sys/devices/system/cpu/cpu0/cache/index*/
<ctopper> lebedevri: total size is coherency_line_size * number_of_sets * ways_of_associativity
```
Which is for me is:
```
# cat /sys/devices/system/cpu/cpu0/cache/index*/coherency_line_size
64
64
64
64
# cat /sys/devices/system/cpu/cpu0/cache/index*/number_of_sets
64
512
2048
2048
# cat /sys/devices/system/cpu/cpu0/cache/index*/ways_of_associativity
4
2
16
64
```
So it looks like the multiplier is 1024; i'd be okay with fixing this.
Unless someone else can quote a better source stating the opposite?
