### ISSUE TITLE
Supporting Arg arguments with double (or other) data types

### ISSUE THREAD

**Issue by milladgit** [google/benchmark#900]
It would be great if we can pass arguments other than integer type to the benchmarks to be retrieved by state.range(i).

For example: passing double values
BENCHMARK(BM_Bench)->Arg(3.14);

I did a search on this but did not find anything. All I found was that all the inputs were integers.

**Comment by dominichamon** [comment]
The assumption was that if the function under test would respond different to different args, you can get the same performance trend by using integers. Ie, testing with arg 3.14, 6.28, 9.42, etc to get a trend for how the performance scales with the arg is equivalent to testing with args 3, 6, 9, etc.

if you want to test with specific doubles as args, then you can work around this by having an array of doubles and using the args as indices into that array (i recognise that isn't necessarily the nicest workaround).

So I can understand better if our assumption has been premature, what exactly is your use-case?

**Comment by milladgit** [comment]
I like your workaround solution. It can help me in my cases. Frankly, I didn't think it like that. I looked at the "Arg" examples and they were simply passing the values. So, I was expecting the same for the double values (or any other data types). It is not mentioned in the README that the "Arg" is limited to integer values. 

Your first solution, however, is a little bit tricky since I might pass arbitrary values (like 0.1, PI, Euler's number, and so on to one single benchmark). 

The use case that I am pursuing is to measure, for instance, the execution time of a mathematical function for edge cases. Or even, in some other instances, edge cases for particular functions.

**Comment by dominichamon** [comment]
i think this is also resolvable now with https://github.com/google/benchmark#passing-arbitrary-arguments-to-a-benchmark
