### ISSUE TITLE
[Feature request] A way to influence the ammount of iterations for a benchmark besides MinTime

### ISSUE THREAD

**Issue by TinyAtoms** [google/benchmark#908]
Currently, the number of iterations is determined dynamically, like 
"Concretely, the number of iterations is at least one, not more than 1e9, until CPU time is greater than the minimum time, or the wallclock time is 5x minimum time. The minimum time is set per benchmark by calling MinTime on the registered benchmark object."

A method to specify our own MinIterations and MaxIterations would be really helpful

**Comment by dominichamon** [comment]
This comes up a lot .. I should add it to a faq.

It almost certainly won't help you like you think. It was part of the
initial API but was removed once we thought a bit about it.

Essentially as soon as you control iterations, you lose any (even loose)
guarantees of statistical significance of the results. I think ideally we
would offer something that would run until some specific confidence
interval is satisfied but until then, time is the best proxy as it's what
we are measuring. Iterations isn't.

It's a bit more complicated too when you implement both time and iterations
to offer an API that can handle both being set (which users immediately
request :))

**Comment by TinyAtoms** [comment]
ok, that makes sense

**Comment by TinyAtoms** [comment]
Ok, I understand.

"Essentially as soon as you control iterations, you lose any (even loose)
guarantees of statistical significance of the results." 
Could you explain this?

As an amateur hobbyist, I'd usually just do a 10k(depending on how fast what I'm doing is. I usually try to set that number so it all the itterations finish in ~5 mins) loop with whatever I want to time plus adding and asm volatile so the loop doesn't get optimized away, then dividing by 10k.
And if I want to get "fancy", i repeat it a number of times to get a mean and std.

Is the part that I quoted specific to google-benchmark, or just benchmarking in general?

Also, this really isn't the place to ask, but could you perhaps recommend some resources for how to do good benchmarking? 
 I've watched a few cppcon talks about benchmarking, but your quote is kind of making me doubt that I've been very rigorous in my benchmarking process.

**Comment by LebedevRI** [comment]
> As an amateur hobbyist, I'd usually just do a 10k(depending on how fast what I'm doing is. I usually try to set that number so it all the itterations finish in ~5 mins)

So you just want to run it for sufficiently long time, why hardcode iteration count and not time wanted?
You likely want
https://github.com/google/benchmark/blob/7d97a057e16597e8020d0aca110480fe82c9ca67/include/benchmark/benchmark.h#L853-L856
or better it's command-line version `--benchmark_min_time=`.
Or maybe `--benchmark_repetitions=`?

**Comment by TinyAtoms** [comment]
No. That was what I usually do. I was just questioning if what I usually do didn't have any meaningful statistical significance.

In this case I really want to limit the iterations and not the time. I'm trying to benchmark insertions into some hashmap implementations at various sizes, and if for example, the benchmark inserts a 50k size hashmap with another 20k items, I'm not sure how much I can say that it's a data point for 50k. I was hoping I could limit it to do only 0.05* size iterations.


I guess I could use the not recommended methods to temporarily pause timing, erase a random item and resume timing, or just time it with a random erase, and then separately benchmark random erases.
Ehh, I'll figure something out. Thanks for the help
