### ISSUE TITLE
Re-add support for per-thread timing and run results.

### ISSUE THREAD

**Issue by EricWF** [google/benchmark#91]
Issue #86 is going to remove this functionality. In #86 tests that are run on more than one thread report as a single result. 

Dominic would like to see this functionality readded.

**Comment by EricWF** [comment]
I don't think we can support per-thread timings. Currently we measure CPU time using `getrusage`. However `getrusage` seems to work on a per-process basis and not a per-thread basis.

Until we have a way to measure per-thread CPU usage we cannot change this.

**Comment by dominichamon** [comment]
Agreed.
