### ISSUE TITLE
does not build with Visual Studio 2019

### ISSUE THREAD

**Issue by ramitrathore** [google/benchmark#912]
1> CMake generation started for configuration: 'x64-Debug'.
1> Command line: "cmd.exe" /c ""C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\xxx\Source\Repos\benchmark\out\install\x64-Debug" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/HostX64/x64/cl.exe" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\Usr\Source\Repos\benchmark" 2>&1"
1> Working directory: C:\Users\Usr\Source\Repos\benchmark\out\build\x64-Debug
1> [CMake] -- The CXX compiler identification is MSVC 19.23.28107.0
1> [CMake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/HostX64/x64/cl.exe
1> [CMake] -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/HostX64/x64/cl.exe -- works
1> [CMake] -- Detecting CXX compiler ABI info
1> [CMake] -- Detecting CXX compiler ABI info - done
1> [CMake] -- Detecting CXX compile features
1> [CMake] -- Detecting CXX compile features - done
1> [CMake] -- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.21.0.windows.1") 
1> [CMake] -- git Version: v1.5.0-36711948
1> [CMake] -- Version: 1.5.0
1> [CMake] -- Performing Test HAVE_STD_REGEX
1> [CMake] -- Performing Test HAVE_STD_REGEX
1> [CMake] -- Performing Test HAVE_STD_REGEX -- success
1> [CMake] -- Performing Test HAVE_GNU_POSIX_REGEX
1> [CMake] -- Performing Test HAVE_GNU_POSIX_REGEX
1> [CMake] -- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
1> [CMake] -- Performing Test HAVE_POSIX_REGEX
1> [CMake] -- Performing Test HAVE_POSIX_REGEX
1> [CMake] -- Performing Test HAVE_POSIX_REGEX -- failed to compile
1> [CMake] -- Performing Test HAVE_STEADY_CLOCK
1> [CMake] -- Performing Test HAVE_STEADY_CLOCK
1> [CMake] -- Performing Test HAVE_STEADY_CLOCK -- success
1> [CMake] -- Looking for C++ include pthread.h
1> [CMake] -- Looking for C++ include pthread.h - not found
1> [CMake] -- Found Threads: TRUE  
1> [CMake] -- Looking for Google Test sources
1> [CMake] -- Looking for Google Test sources in C:/Users/Usr/source/repos/benchmark/googletest
1> [CMake] CMake Error at C:\Users\Usr\Source\Repos\benchmark\CMakeLists.txt:34 (message):
1> [CMake]   Did not find Google Test sources! Either pass correct path in
1> [CMake]   GOOGLETEST_PATH, or enable ALLOW_DOWNLOADING_GOOGLETEST, or disable
1> [CMake]   BENCHMARK_ENABLE_GTEST_TESTS / BENCHMARK_ENABLE_TESTING.
1> [CMake] 
1> [CMake] 
1> [CMake] CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/ExternalProject.cmake:1772 (get_property):
1> [CMake]   get_property could not find TARGET googletest.  Perhaps it has not yet been
1> [CMake]   created.
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:54 (ExternalProject_Get_Property)
1> [CMake] CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.15/Modules/ExternalProject.cmake:1774 (message):
1> cmd.exe /c ""C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\CMake\bin\cmake.exe"  -G "Ninja" -DCMAKE_INSTALL_PREFIX:PATH="C:\Users\Usr\Source\Repos\benchmark\out\install\x64-Debug" -DCMAKE_CXX_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/HostX64/x64/cl.exe" -DCMAKE_C_COMPILER:FILEPATH="C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.23.28105/bin/HostX64/x64/cl.exe"  -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="C:\PROGRAM FILES (X86)\MICROSOFT VISUAL STUDIO\2019\ENTERPRISE\COMMON7\IDE\COMMONEXTENSIONS\MICROSOFT\CMAKE\Ninja\ninja.exe" "C:\Users\Usr\Source\Repos\benchmark" 2>&1" returned with exit code: 1
1> [CMake]   External project "googletest" has no SOURCE_DIR
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:54 (ExternalProject_Get_Property)
1> [CMake] -- Configuring incomplete, errors occurred!
1> [CMake] See also "C:/Users/Usr/source/repos/benchmark/out/build/x64-Debug/third_party/googletest/CMakeFiles/CMakeOutput.log".
1> [CMake] CMake Error at cmake/GoogleTest.cmake:13 (message):
1> [CMake]   CMake step for googletest failed: 1
1> [CMake] Call Stack (most recent call first):
1> [CMake]   CMakeLists.txt:274 (include)
1> [CMake] -- Configuring incomplete, errors occurred!
1> [CMake] See also "C:/Users/Usr/source/repos/benchmark/out/build/x64-Debug/CMakeFiles/CMakeOutput.log".
1> [CMake] See also "C:/Users/Usr/source/repos/benchmark/out/build/x64-Debug/CMakeFiles/CMakeError.log".
1> [CMake]

**Comment by ramitrathore** [comment]
Let me know if you need to see the error logs

**Comment by LebedevRI** [comment]
> 1> [CMake] -- Looking for Google Test sources
> 1> [CMake] -- Looking for Google Test sources in C:/Users/Usr/source/repos/benchmark/googletest
> 1> [CMake] CMake Error at C:\Users\Usr\Source\Repos\benchmark\CMakeLists.txt:34 (message):
> 1> [CMake] Did not find Google Test sources! Either pass correct path in
> 1> [CMake] GOOGLETEST_PATH, or enable ALLOW_DOWNLOADING_GOOGLETEST, or disable
> 1> [CMake] BENCHMARK_ENABLE_GTEST_TESTS / BENCHMARK_ENABLE_TESTING.

That seems self-explanatory?

**Comment by ramitrathore** [comment]
@LebedevRI  Do you know how to fix this?

**Comment by LebedevRI** [comment]
> Either pass correct path in GOOGLETEST_PATH, or enable ALLOW_DOWNLOADING_GOOGLETEST, or disable BENCHMARK_ENABLE_GTEST_TESTS / BENCHMARK_ENABLE_TESTING.

**Comment by ramitrathore** [comment]
Thanks anyway
option(BENCHMARK_ENABLE_GTEST_TESTS "Enable building the unit tests which depend on gtest" ON)
Chang to :
option(BENCHMARK_ENABLE_GTEST_TESTS "Enable building the unit tests which depend on gtest" OFF)

**Comment by ramitrathore** [comment]
But the bug still stands

**Comment by pleroy** [comment]
> But the bug still stands

How so?  What is the bug exactly?  When cmake doesn't find Google Test, it gives you three options to choose from.  What do you think should happen instead?

**Comment by ramitrathore** [comment]
@pleroy My bad, you are correct. It was an issue how I was using CMake
