### ISSUE TITLE
Environment variables don't work

### ISSUE THREAD

**Issue by pitrou** [google/benchmark#913]
I'm trying the new environment variable support but environment variables seem to be ignored. 
```
$ ./build-test/debug/arrow-bit-util-benchmark --benchmark_filter=xxx
Failed to match any benchmarks against regex: xxx
$ BENCHMARK_FILTER=xxx ./build-test/debug/arrow-bit-util-benchmark 
[...]
-------------------------------------------------------------------------------------------------
Benchmark                                       Time             CPU   Iterations UserCounters...
-------------------------------------------------------------------------------------------------
BitmapReader/8192                         1184368 ns      1184102 ns          591 bytes_per_second=13.1957M/s
[etc.]
```

I'm using changeset 367119482ff4abc3d73e4a109b410090fc281337.

**Comment by dominichamon** [comment]
On Thu, Dec 5, 2019 at 8:38 AM Antoine Pitrou <notifications@github.com>
wrote:

> I'm trying the new environment variable support but environment variables
> seem to be ignored in most cases. There is own benchmark executable where
> it seems to work:
>
> $ ./build-test/debug/arrow-compression-benchmark --benchmark_filter=xxx
> Failed to match any benchmarks against regex: xxx
> $ BENCHMARK_FILTER=xxx ./build-test/debug/arrow-compression-benchmark
> Failed to match any benchmarks against regex: .
>
> (note the weird message though: why regex "."?)
>

The default filter is "." which suggests that it is indeed using the
default here. I'm not sure how it's not matching any though.

**Comment by pitrou** [comment]
@dominichamon The answer to your question is that by default `arrow-compression-benchmark` does not have any benchmarks. This makes my original report confusing (I was confused myself :-)) so I edited that part out.

**Comment by pdrocaldeira** [comment]
I'm trying to use BENCHMARK_FORMAT and is not working too.

```
BENCHMARK_FORMAT=json ./mybenchmark
2020-02-19 11:31:49
Running ./mybenchmark
Run on (8 X 3600 MHz CPU s)
CPU Caches:
  L1 Data 32 KiB (x4)
  L1 Instruction 32 KiB (x4)
  L2 Unified 256 KiB (x4)
  L3 Unified 6144 KiB (x1)
***WARNING*** CPU scaling is enabled, the benchmark real time measurements may be noisy and will incur extra overhead.
---------------------------------------------------------------------------
Benchmark                                 Time             CPU   Iterations
---------------------------------------------------------------------------
BM_MYBENCH/128                        19922202 ns     19922996 ns           35

```

**Comment by krzikalla** [comment]
Bump.

This is a bug in the handling of flag names: in FlagToEnvVar a "BENCHMARK_" is added to the flag name. However the flag name has already a "BENCHMARK_" in it. Thus `BENCHMARK_BENCHMARK_FORMAT=json ./mybenchmark`
should work for the moment (at least BENCHMARK_BENCHMARK_FILTER works for me).

**Comment by LebedevRI** [comment]
I believe this should be fixed in the last release.

**Comment by dominichamon** [comment]
#997 should have fixed this.
