### ISSUE TITLE
How to use PauseTiming?

### ISSUE THREAD

**Issue by only976** [google/benchmark#920]
An error is
benchmark/src/benchmark.cc:197: StartKeepRunning: Check `!started_ && !finished_' failed.
I just fellow the document, but something wrong happened.

**Comment by LebedevRI** [comment]
Can you actually show your benchmark?
You can only use it within the `for (auto _ : state) {}` workloop.

**Comment by only976** [comment]
got it！
thanks!

**Comment by LebedevRI** [comment]
Cool
