### ISSUE TITLE
Cannot install different configurations

### ISSUE THREAD

**Issue by pixxon** [google/benchmark#922]
Both the release and debug versions share the same `benchmark` and `benchmark_main` names, making it impossible to install them under the same location.

This caused overwrites when installing and later linker errors when trying to use the libraries.

**Comment by pixxon** [comment]
Maybe installing the pdb-s could be a good idea as well.
MSVC complains if they are not found while linking.

**Comment by dominichamon** [comment]
As per #947 this has ramifications. i'm going to close it out until someone has an idea how to resolve it.

**Comment by Unarmed1000** [comment]
What about just enabling it for MSVC builds on windows to begin with. This should not conflict with pkg-config as that is rarely used on windows.
