### ISSUE TITLE
How to measure the time of a piece of code without destruction

### ISSUE THREAD

**Issue by KirillLykov** [google/benchmark#924]
I want to measure the time spent during the execution of one method but not the destructor or memory allocation. 
I found that there are several ways for doing this, yet I don't know which one is the best. 
The easiest is the following:

```C++
MemoryBuffer myBuffer(nbytes);
state.PauseTiming();
for (auto _ : state) {
    MyAllocator alloc(myBuffer);
    shared_ptr<MyClass> myObj = createMyObject(alloc);
    
    state.ResumeTiming();
    auto res = myObj->doTheJob();
    state.PauseTiming();

    benchmark::DoNotOptimize(res);
    benchmark::ClobberMemory();
    // at this point destructor for MyClass will be called,
   // it might be expensive and I don't want to measure it
}
```

I can also skip these pause/resume timing calls by measuring time manually:
```C++
MemoryBuffer myBuffer(nbytes);
state.PauseTiming();
for (auto _ : state) {
    MyAllocator alloc(myBuffer);
    shared_ptr<MyClass> myObj = createMyObject(alloc);
    
    auto start = std::chrono::high_resolution_clock::now();
    auto res = myObj->doTheJob();
    auto end = std::chrono::high_resolution_clock::now();
    auto elapsed_seconds = std::chrono::duration_cast<std::chrono::duration<double>>(end - start);
    time += elapsed_seconds.count();

    benchmark::DoNotOptimize(res);
    benchmark::ClobberMemory();
}
state.SetLabel("mean time: " + std::to_string(time/stat.iterations()));
```
But in this case, as far as I understand, the convergence will be measured towards the overall time so it might be inaccurate.

Another way is to use `UseManualTime` and `SetIterationTime`  but I found that it leads to the significant benchmark performance degradation (like x10). Let me know if it is something unexpected.

**Comment by dominichamon** [comment]
I personally prefer this model which makes the exceptional bits (non-timed) stand out more:

```c++
MemoryBuffer myBuffer(nbytes);
for (auto _ : state) {
    state.PauseTiming();
    MyAllocator alloc(myBuffer);
    shared_ptr<MyClass> myObj = createMyObject(alloc);
    state.ResumeTiming();

    auto res = myObj->doTheJob();

    state.PauseTiming();
    benchmark::DoNotOptimize(res);
    benchmark::ClobberMemory();
    // at this point destructor for MyClass will be called,
    // it might be expensive and I don't want to measure it
    state.ResumeTiming();
}
```

However, why do you need to create the object fresh every time? why not just


```c++
MemoryBuffer myBuffer(nbytes);
MyAllocator alloc(myBuffer);
shared_ptr<MyClass> myObj = createMyObject(alloc);

for (auto _ : state) {
    auto res = myObj->doTheJob();

    benchmark::DoNotOptimize(res);
    benchmark::ClobberMemory();
}
```

**Comment by KirillLykov** [comment]
Thanks for the answer. 
I want to create it every time due to allocator, actually. One of the commonly used allocation strategy here implies usage of big continuous chunks of memory which are never freed until the allocator is destroyed.
In case if I reuse the heavy object, as I, in fact, did initially, the memory will be growing at each iteration.
So for the benchmark I decided to preallocate a buffer in advance and later create an allocator which uses this buffer. This way I control the memory allocation completely and do not measure the cost of allocation as well as avoid dealing with the artifacts of using different amount of memory for each consequent iteration.
