### ISSUE TITLE
Deprecated CSVReporter warnings with Bazel build

### ISSUE THREAD

**Issue by tehbelinda** [google/benchmark#927]
When building with Bazel, deprecated warnings for CSV Reporter causes builds with warning as errors to fail. Similar to #608 

```
INFO: From Compiling external/googlebenchmark/src/benchmark.cc:
external/googlebenchmark/src/benchmark.cc: In function 'std::unique_ptr<benchmark::BenchmarkReporter> benchmark::internal::{anonymous}::CreateReporter(const string&, benchmark::ConsoleReporter::OutputOptions)':
external/googlebenchmark/src/benchmark.cc:300:24: warning: 'CSVReporter' is deprecated: The CSV Reporter will be removed in a future release [-Wdeprecated-declarations]
     return PtrType(new CSVReporter);
                        ^~~~~~~~~~~
In file included from external/googlebenchmark/src/benchmark.cc:15:0:
bazel-out/k8-opt/bin/external/googlebenchmark/_virtual_includes/benchmark/benchmark/benchmark.h:1520:61: note: declared here
     "The CSV Reporter will be removed in a future release") CSVReporter
```

Currently we're getting around this by patching the BUILD.bazel file with `copts = ["-Wno-deprecated-declarations"]`

**Comment by dominichamon** [comment]
i'm not sure what the right approach is here. there are at least four options i can think of:

1. finish deprecating csv reporter :)
2. turn off the warnings in the bazel build
3. turn off warnings as errors in the bazel build
4. disable the bazel build in favour of cmake

**Comment by tehbelinda** [comment]
1. would be great :)

but what about:
5. adding to the copts to turn off just those warning (as opposed to all warnings, I'm not sure if that's what you meant in 2.) I'm happy to make a PR with the patch we're using if you'd like?

**Comment by dominichamon** [comment]
I deliberately left 5 off because the deprecation warnings exist to, you know, warn folks that it might be deprecated soon :)

**Comment by tehbelinda** [comment]
Ok fair :)

**Comment by KeithMoyer** [comment]
It appears there was already an attempt in c408461983dd3adf49d450d7db926fc46f1d99a0 (last August) to mask these warnings. Unfortunately, it just used the wrong warning flag. I created PR #956 to address this last week. PTAL.

**Comment by dominichamon** [comment]
Did #956 resolve this issue for you?

**Comment by jwnimmer-tri** [comment]
@tehbelinda had filed this on behalf of our project over at https://github.com/RobotLocomotion/drake.  For us, I can confirm that #956 resolved it.  In https://github.com/RobotLocomotion/drake/pull/14965, we were able to remove our work-around.  Thanks!
