### ISSUE TITLE
pkg-config reports incorrect library with Debug build: gcc/Linux

### ISSUE THREAD

**Issue by ambitslix** [google/benchmark#928]
pkg-config --libs reports benchmark and benchmark_main when in reality Debug builds end up as "libbenchmarkd.a" &  "libbenchmark_maind.a". Solution is to configure benchmark.pc according to build type or just have the same name. Probably different build types should reside in different locations to avoid name collisions.

**Comment by LebedevRI** [comment]
Hmm, interesting. I guess googletests pkgconfig files are also broken in that configuration.
In principle i guess this may be solvable by asking cmake "what is the filename of the library",
and using the variable you stored that answer in in `.pc.in` instead of hardcoded value.
If you'd like to take a look, i could review i suppose.

**Comment by ambitslix** [comment]
Hello, yes  common problem encountered with other libraries as well. I can take a look at it on the weekend, as you said I would configure .pc according to actual file names from cmake.

**Comment by LebedevRI** [comment]
@dominichamon to make progress here we mainly need to decide *what* is the solution
* do nothing
* revert original problematic pr
* drop pkg-config support
* merge this as-is. i mean, this does solve the problem.. (best course of action?)
* bump cmake to 3.15, and fix this properly (i advise against this.)
* ???

this is more of an executive decision, not for me to make it here.

**Comment by ambitslix** [comment]
Drop pkg-config support is my number one vote, then second would be merge this fix.

**Comment by dominichamon** [comment]
revert the original PR i think. it solved a relatively niche problem but has clearly opened up more issues so needs more thought.
