### ISSUE TITLE
Does anyone know a benchmark database and/or plotting over time?

### ISSUE THREAD

**Issue by emmenlau** [google/benchmark#936]
We use google benchmark quite a lot and like it for performance regression sheriffing. But currently this involves mostly hard-coded runtime expectations and some manual work. This would be much simplified if we could plot performance over time (i.e. over the series of the last X commits).

Does anyone know of any efforts to do this, to memorize and plot benchmark results over time?

I've seen that https://chromium.googlesource.com/chromium/src/+/master/docs/speed/perf_regression_sheriffing.md spends quite some effort to monitor performance over time. Specifically it can generate the top performance improvements and drops in https://chromeperf.appspot.com/, and render interactive performance plots like in https://chromeperf.appspot.com/group_report?keys=agxzfmNocm9tZXBlcmZyFAsSB0Fub21hbHkYgICIk76E-gsM. This would probably be of value to many people performing software benchmarks. But I could not see how their magic works...

Does anyone know of projects doing this with google benchmark?

**Comment by dominichamon** [comment]
One of the inspirations behind the JSON output was to enable that sort of project. There's also https://github.com/google/benchmark/issues/190 which is a similar request for HTML reporting.

http://quick-bench.com also exists which runs benchmarks and plots them, but isn't persistent.

The chrome stuff might be https://github.com/catapult-project/catapult/tree/master/dashboard (mirrored from https://chromium.googlesource.com/catapult).
