### ISSUE TITLE
Assert failure because of SkipWithError()

### ISSUE THREAD

**Issue by chfast** [google/benchmark#937]
If `SkipWithError()` is used before the benchmark loop, and we also early exit before the benchmark loop starts the assert failure is triggered:

```
src/benchmark_runner.cc:120: RunInThread: Check `st.iterations() >= st.max_iterations' failed. Benchmark returned before State::KeepRunning() returned false!
```

at https://github.com/google/benchmark/blob/master/src/benchmark_runner.cc#L120.

The example unit test:
```cpp
void BM_error_no_running(benchmark::State& state) {
  state.SkipWithError("error message");
}
BENCHMARK(BM_error_no_running);
ADD_CASES("BM_error_before_running", {{"", true, "error message"}});
```

I was thinking about fixing the issue by modifying the assert condition allow it pass if there was a failure in the benchmark. But there is no API to read this information from a `State` object.

**Comment by LebedevRI** [comment]
Hm, that sounds wrong/weird, then the tests https://github.com/google/benchmark/blob/58588476ce52c0af4cb54f9c596c4579f78bc953/test/skip_with_error_test.cc would be failing..

**Comment by LebedevRI** [comment]
Hm yes, that seems unfortunate.
`State::SkipWithError()` sets `State::error_occurred_` flag
https://github.com/google/benchmark/blob/a8b3693321807b82a3407744d694059f77d1b972/src/benchmark.cc#L175
which is private
https://github.com/google/benchmark/blob/8982e1ee6aef31e48170400b7d1dc9969b156e5e/include/benchmark/benchmark.h#L657

But the assert happens here:
https://github.com/google/benchmark/blob/8982e1ee6aef31e48170400b7d1dc9969b156e5e/src/benchmark_runner.cc#L120
I think that `State st` is the `State` in question?
So just add a public getter `State::error_occurred()` and do
```diff
-   CHECK(st.iterations() >= st.max_iterations)
-      << "Benchmark returned before State::KeepRunning() returned false!";
+   CHECK(Sterror_occurred() || st.iterations() >= st.max_iterations)
+      << "Benchmark returned before State::KeepRunning() returned false!";
```
?

I'm not sure if we actually need to try to enter the workloop, but i guess you'll see either assertion failures, or failed tests.

**Comment by chfast** [comment]
Ok, I will do. Thanks.
