### ISSUE TITLE
[FR] Time for v1.5.1 ?

### ISSUE THREAD

**Issue by LebedevRI** [google/benchmark#945]
it's been some time since last release, it might be good to cut a new one..
Are there any particular blockers?
- [x] #928
- ???

**Comment by dominichamon** [comment]
looking at what's in the log since 1.5, i'm not sure there's anything significant.

as a matter of record, i'd prefer 1.6.0 unless we're applying a bugfix to 1.5.0.

**Comment by LebedevRI** [comment]
Is anyone aware of any other blockers, regressions since last release?

**Comment by LebedevRI** [comment]
@dominichamon any further thoughts on doing the release?
v1.5.0 is 1 year old now :)

**Comment by dominichamon** [comment]
testing things locally and googletest now needs absl so i'm adding that as a dependency in our bazel `WORKSPACE`.

**Comment by dominichamon** [comment]
next issue: new python bindings are failing (on my machine) with 

```
bindings/python/benchmark/example.py", line 16, in <module>
    import benchmark
ModuleNotFoundError: No module named 'benchmark'
```

**Comment by dominichamon** [comment]
i'm using python2 which i believe is the issue.

**Comment by LebedevRI** [comment]
> testing things locally and googletest now needs absl so i'm adding that as a dependency in our bazel `WORKSPACE`.

bazel doesn't track that transitively? I'd think that's googletest `WORKSPACE` issue.

**Comment by chr1sj0nes** [comment]
> next issue: new python bindings are failing (on my machine) with
> 
> ```
> bindings/python/benchmark/example.py", line 16, in <module>
>     import benchmark
> ModuleNotFoundError: No module named 'benchmark'
> ```
> 
> @chr1sj0nes any ideas?

Yeah, you need to install the package. I'll add some docs.

**Comment by dominichamon** [comment]
@LebedevRI it reported as part of googletest but i think we _also_ need it for the new python bindings.

**Comment by dominichamon** [comment]
blocked on #975.

**Comment by dominichamon** [comment]
making one change to travis and then i'll start marking up the release.

**Comment by dominichamon** [comment]
https://github.com/google/benchmark/releases/tag/v1.5.1
