### ISSUE TITLE
check.h(41): warning C4722: 'benchmark::internal::CheckHandler::~CheckHandler': destructor never returns, potential memory leak

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [google/benchmark#948]
check.h(41): warning C4722: 'benchmark::internal::CheckHandler::~CheckHandler': destructor never returns, potential memory leak

Compiled with Visual Studio 2019 Professional 16.5.1 on Windows 10 Prof. 1903.

**Comment by dominichamon** [comment]
duplicate of #826
