### ISSUE TITLE
Warnings C4244 and C4305 'argument': truncation / conversion from 'double' to 'RawType' / 'const M' to 'const Element'

### ISSUE THREAD

**Issue by Andreas-Schniertshauer** [google/benchmark#949]
compiled with Visual Studio 2019 Professional 16.5.1 on windows 10 1903.

`\src\benchmark_runner.cc(267,13): warning C4244: 'initializing': conversion from 'double' to 'benchmark::IterationCount', possible loss of data
\src\benchmark_runner.cc(266,41): warning C4244: 'initializing': conversion from 'double' to 'const benchmark::IterationCount', possible loss of data
\test\statistics_gtest.cc(25,1): warning C4305: 'argument': truncation from 'double' to 'RawType' \test\statistics_gtest.cc(24,1): warning C4244: 'argument': conversion from 'double' to 'RawType', possible loss of data
\test\../src/benchmark_register.h(25,1): warning C4244: '*=': conversion from 'int' to 'T', possible loss of data
\src\googlemock\include\gmock/gmock-matchers.h(368,12): warning C4244: 'argument': conversion from 'const M' to 'const Element', possible loss of data

**Comment by benvanik** [comment]
These would be great to fix - since benchmark overrides default warnings and forces these on it should be warning clean:
https://github.com/google/benchmark/blob/e30cac6b06cf05416a9358df8be868ab01602a68/CMakeLists.txt#L103-L104

**Comment by dominichamon** [comment]
Agreed. It used to be (sigh).

I'll take a look.

**Comment by LebedevRI** [comment]
Why didn't CI fail with that warning?
Is warning-as-error not enabled for that compiler?
