### ISSUE TITLE
[BUG] Benchmark function is called multiple times for the same arguments

### ISSUE THREAD

**Issue by Climax777** [google/benchmark#952]
My benchmark functions are called multiple times, even when filtering and specifying one set of arguments. This causes setup code to run often, making benchmarks run very long.

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Ubuntu 19.10 x86_64
  - Compiler and version: g++ (Ubuntu 9.2.1-9ubuntu2) 9.2.1 2019100

**To reproduce**
1. sync to commit b23d355
I'm working on a minimal example, without all my external dependencies, however a basic example with long sleeps, have proven un-reproducing. I'm hoping this is for some reason expected and I am just ignorant.

**Expected behavior**
Expect benchmark function to run once per thread, and state loop to handle iterations, except here the benchmark function is run multiple times too.

**Comment by LebedevRI** [comment]
This is not a bug, but intentional behavior.
Have you tried using fixtures for setup code?

The thing is, if we are told to run the benchmark for 0.5s, we can't know for how many iterations
do we need to run your benchmark function. What the code does is it runs the function for
some number `N` of iterations, sees how much time `T` it took, and if that is less than the time required, given just measured time per iteration, it estimates how many iterations
would be needed to run for the required time, and runs again from the start.

The code is in https://github.com/google/benchmark/blob/master/src/benchmark_runner.cc, if you wish to take a look.

**Comment by Climax777** [comment]
Thanks for clarifying that. I will use the class based fixture startup code
then. Thanks!

**Comment by Climax777** [comment]
> This is not a bug, but intentional behavior.
> Have you tried using fixtures for setup code?
> 
> The thing is, if we are told to run the benchmark for 0.5s, we can't know for how many iterations
> do we need to run your benchmark function. What the code does is it runs the function for
> some number `N` of iterations, sees how much time `T` it took, and if that is less than the time required, given just measured time per iteration, it estimates how many iterations
> would be needed to run for the required time, and runs again from the start.
> 
> The code is in https://github.com/google/benchmark/blob/master/src/benchmark_runner.cc, if you wish to take a look.

Exactly the same happens with the `SetUp` and `TearDown` class methods. I'm assuming you are suggesting to use the constructor/destructor pair rather?

**Comment by LebedevRI** [comment]
Ah right, i always forget that detail.
https://github.com/google/benchmark/blob/c078337494086f9372a46b4ed31a3ae7b3f1a6a2/include/benchmark/benchmark.h#L1067-L1071
I guess this makes sense in general, generally benchmarking only makes sense if
the starting point is the exactly the same, so if there's persistent, mutated state between
runs then the results may be different. 

> I'm assuming you are suggesting to use the constructor/destructor pair rather?

Can those be overriden there? If that works then i guess that is what i was suggesting..

**Comment by Climax777** [comment]
Yes indeed one can. I have however come to a different solution with static
variables.

**Comment by LebedevRI** [comment]
> Yes indeed one can. I have however come to a different solution with static variables.

That would be my other suggestion, yes.
Glad that it worked for you.

It _might_ be good to improve documentation about this,
but i don't know what would be the best wording.
