### ISSUE TITLE
[BUG] statistics are not reported

### ISSUE THREAD

**Issue by henrydcase** [google/benchmark#958]
**Describe the bug**
statistics are not reported when number of repetitions is not set.

**System**
Which OS, compiler, and compiler version are you using:
  - OS: any
  - Compiler and version: any

**To reproduce**
1. sync to commit 8cead007830bdbe94b7cc259e873179d0ef84da6f
2. cmake
3. make 

**Expected behavior**
I would like to run code for X amount of time and have statistics reported as soon as number of iterations is > 1.

**Comment by dominichamon** [comment]
Working as intended.

Statistics are computed across repetitions, not iterations. https://github.com/google/benchmark/#runtime-and-reporting-considerations

**Comment by henrydcase** [comment]
why?

**Comment by LebedevRI** [comment]
Because within one repetition, the benchmark doesn't run each iteration separately,
but runs them all back-to-back, so you only have the total time it takes to run 1 repetition
consisting of N iterations, so you just can't compute the stdev of run times.

**Comment by henrydcase** [comment]
nop, you definitely can compute mean and stdev for N iterations. I wonder why it has been decided not to allow it in google benchmark and how complicated it would be to add it.

**Comment by LebedevRI** [comment]
> nop, you definitely can compute mean and stdev for N iterations.

Could you please tell me stdev of the number `8`?

**Comment by henrydcase** [comment]
nop, this question makes no sense. 
you have N iterations, each take time. so what you get from running a banchmark is not 8 but array of numbers

**Comment by LebedevRI** [comment]
> nop, this question makes no sense.
> you have N iterations, each take time. so what you get from running a banchmark is not 8 but array of numbers

As i was saying in https://github.com/google/benchmark/issues/958#issuecomment-614769705, that is precisely opposite from what we have.
We don't measure each separate iteration, we measure the *TOTAL* time spent on all iterations.
So no, we don't have an array with per-iteration times, and we can't compute statistics on it.
Only when there are multiple repetitions. But obviously that is misleadingly not the same thing,
and i agree it may be good to be able to compute per-iteration statistics, 
https://github.com/google/benchmark/pull/709 / https://github.com/google/benchmark/pull/710 is supposed to handle that.

**Comment by pleroy** [comment]
I am running benchmarks where an iteration takes ~10 ns.  I hope that nobody is going to measure the CPU/elapsed time after each iteration (which would be necessary to have statistics across iterations).

**Comment by LebedevRI** [comment]
> an iteration takes ~10 ns

Yeah, there's likely some lower bound (1ms..10ms?) below which it won't be meaningful
to measure each iteration separately

**Comment by henrydcase** [comment]
at some point CPU cycles per iteration make more sense than time.
Thanks! This tool is great, but probably I'm looking for something else.
