### ISSUE TITLE
[FR] Add a way to output benchmark ranges as string names

### ISSUE THREAD

**Issue by emmenlau** [google/benchmark#962]
**Is your feature request related to a problem? Please describe.**
We have a large matrix of enums over which we run benchmarks. This works generally well. But in the output, its quite hard to map benchmark identifiers back to an actual meaning. For example, our current top candidate is `benchmark/7/3/0/2/1` :)

This also makes plotting harder, because meaning has to be re-associated at plotting time (where the connection to the benchmark code is long lost).

**Describe the solution you'd like**
Ideally, I'd like a way to use, or print, strings for ranges. To use string ranges, I could envision an API like `Benchmark::Args("MyType::Value1")` that is passed as std::string via `State::range()` and also printed as this string (like `benchmark/MyType::Value1/OtherType/1024/AnotherType/Last::Type`). Strings could be set freely and must be parsed by the user from `State::range()` in benchmark methods. If that is not good, then a good workaround would be if benchmark ranges could be associated with a string identifier that, if set, is printed instead of the raw numeric value.

**Describe alternatives you've considered**
I've looked at `Counter`s to print the parsed enum values as strings. But `Counter` is limited to numeric values, so I can not print hand-crafted strings there. Another alternative, that we might consider now, is to print a custom header with the json file, with a mapping of numeric values to enum identifiers. However this is not straightforward because the json can not be easily manipulated from within the benchmark.

**Additional context**
I'm under the impression that string identifiers can help in automatic plotting of results.

**Comment by dominichamon** [comment]
Have you seen [`SetLabel`](https://github.com/google/benchmark/blob/master/include/benchmark/benchmark.h#L618)?

If this doesn't work, then I wonder if instead of using ranges for enums (they're meant to be ranges after all) the enum should be passed through as a [template instead](https://github.com/google/benchmark#templated-benchmarks):

```c++
enum E {                                                                          
  Match,                                                                          
  NoMatch,                                                                        
};                                                                                

template<E e>                                                                     
static void BM_Enum(benchmark::State& state) {                                                                                  
  char c = (e == Match ? '-' : '+');                                              
  size_t len = static_cast<size_t>(state.range(0));                               
  std::string s1(len, '-');                                                       
  std::string s2(len, c);                                                         
  for (auto _ : state) benchmark::DoNotOptimize(s1.compare(s2));                  
}                                                                                 

BENCHMARK_TEMPLATE(BM_Enum, E::Match)->Range(1,1<<10);                            
BENCHMARK_TEMPLATE(BM_Enum, E::NoMatch)->Range(1,1<<10);                          
```

```
-------------------------------------------------------------------
Benchmark                         Time             CPU   Iterations
-------------------------------------------------------------------
BM_Enum<E::Match>/1            6.32 ns         6.29 ns     85928633
BM_Enum<E::Match>/8            8.14 ns         8.06 ns     83227924
BM_Enum<E::Match>/64           7.93 ns         7.83 ns    101114206
BM_Enum<E::Match>/512          15.7 ns         15.5 ns     46329702
BM_Enum<E::Match>/1024         25.2 ns         24.8 ns     29033683
BM_Enum<E::NoMatch>/1          9.63 ns         9.49 ns     84438032
BM_Enum<E::NoMatch>/8          9.25 ns         9.09 ns     85846063
BM_Enum<E::NoMatch>/64         9.08 ns         8.89 ns     59900028
BM_Enum<E::NoMatch>/512        8.20 ns         8.07 ns     77970462
BM_Enum<E::NoMatch>/1024       8.15 ns         8.01 ns     86669270
```

**Comment by emmenlau** [comment]
Thanks a lot for this super quick and helpful reply! I have not seen `SetLabel()`, somehow I missed looking into the source :-( This is really helpful, actually it should be perfect for our needs. But its also good to see this template example, I missed how useful it is for custom attributes.

Closing as fixed, thanks!
