### ISSUE TITLE
[BUG] bytes_per_second seems wrong

### ISSUE THREAD

**Issue by krzikalla** [google/benchmark#969]
I get the following output of two simple benchmarks zeroing out a memory area:

```
---------------------------------------------------------------------------------
Benchmark                       Time             CPU   Iterations UserCounters...
---------------------------------------------------------------------------------
BM_ComputeArraySetZero        120 ms          120 ms            5 bytes_per_second=1.86444G/s
BM_VectorSetZero              120 ms          120 ms            6 bytes_per_second=1.55646G/s
```

Both benchmarks process the same number of bytes. Since both report the same time (which is expected), they should also report the same bytes_per_second rate. However the lower rate is 5/6 times the upper rate, which correlates with the reported iteration count.
It looks like the iteration count is wrongly respected. 
I would expect  bytes_per_second = (average time) / (number of processed bytes).

**Comment by LebedevRI** [comment]
Can you show the benchmark in question?

**Comment by krzikalla** [comment]
```
static void BM_ComputeArraySetZero(benchmark::State& state)
{
  constexpr size_t blocksize = 5;
  const size_t size = 30000000;

  std::vector<double> array(size * blocksize, 0);

  for (auto _ : state) {
#pragma omp parallel for
    for (size_t i = 0; i < size * blocksize; ++i)
      array[i] = .0;
  }
  int64_t bp = blocksize * size * sizeof(double);
  state.SetBytesProcessed(bp);
}
```

The second one looks similar, it just uses a class encapsulating std::vector.

**Comment by LebedevRI** [comment]
>   int64_t bp = blocksize * size * sizeof(double);
>   state.SetBytesProcessed(bp);

Eh, no. This should be

>   int64_t bp = state.iterations() * blocksize * size * sizeof(double);

as you can see in https://github.com/google/benchmark#passing-arguments and https://github.com/google/benchmark#templated-benchmarks

**Comment by krzikalla** [comment]
Is there a world, where the bytes processed by the problem should not be multiplied by state.iterations()? I guess not. Then IMHO it would be better to do the multiplication inside SetBytesProcessed. At least to me the current behavior is surprising.
Anyway, thanks for the fast help.

**Comment by LebedevRI** [comment]
You tell `SetBytesProcessed()` how many bytes total you processed during that benchmark.
In your case each iteration processes the same number of bytes,
so said multiplication is the right thing to do.
But is it given that each iteration always processes the same number of bytes in a benchmark?
While it is what should happen for the statistical significanse reasons,
i don't think we can really enforce that. Also, that would be an API break.
