### ISSUE TITLE
Unguarded ICC option -wd654

### ISSUE THREAD

**Issue by aaronsm** [google/benchmark#991]
I would think this icc option needs a guard?

https://github.com/google/benchmark/blob/39b6e703f8cdf87284db2aaca2f9b214f02e5673/CMakeLists.txt#L176

if (CMAKE_CXX_COMPILER_ID STREQUAL "Intel")
  add_cxx_compiler_flag(-wd654)
endif()

**Comment by LebedevRI** [comment]
`add_cxx_compiler_flag()` is a macro that checks that compiler doesn't barf on the flag in question,
and only then adds it. Is there some more specific problem?

**Comment by aaronsm** [comment]
Ah, that helps. The is was the python version not the extra flag.

$ cmake ..
$ cat build/CMakeFiles/CMakeError.log 
clang: error: unknown argument: '-wd654'

$ cmake -DPYTHON_EXECUTABLE=/usr/local/bin/python3 ..
-- Generating done
-- Build files have been written [snip]
