### ISSUE TITLE
[BUG] BENCHMARK_OUT_FORMAT and BENCHMARK_OUT env variables are not working

### ISSUE THREAD

**Issue by Lectem** [google/benchmark#995]
**Describe the bug**

According to the documentation

> Write benchmark results to a file with the --benchmark_out=<filename> option (or set BENCHMARK_OUT). Specify the output format with --benchmark_out_format={json|console|csv} (or set BENCHMARK_OUT_FORMAT={json|console|csv}). Note that specifying --benchmark_out does not suppress the console output.

However setting those environment variables does not work.
This is because the command argument names already start by `benchmark` so the function `FlagToEnvVar` adds the `BENCHMARK_` prefix again
https://github.com/google/benchmark/blob/8982e1ee6aef31e48170400b7d1dc9969b156e5e/src/commandlineflags.cc#L91

So the actual variables that the code checks are `BENCHMARK_BENCHMARK_OUT_FORMAT` and `BENCHMARK_BENCHMARK_OUT`.

**System**
Which OS, compiler, and compiler version are you using:
  - OS: Any
  - Compiler and version: Any

**To reproduce**
1. sync to tag v1.5.1
2. cmake/bazel...
3. make ...
4. Try any example with `BENCHMARK_OUT` set to `test_out.json` and `BENCHMARK_OUT_FORMAT` to `json` 

**Expected behavior**

`BENCHMARK_OUT` and `BENCHMARK_OUT_FORMAT` should have the same effect as the flags `--benchmark_out` and `--benchmark_out_format` respectively, or the documentation should give the correct environment variables.

**Comment by dominichamon** [comment]
Nice catch.
