### ISSUE TITLE
[FR] [Python] Distribute Python 3.8 wheels on pip

### ISSUE THREAD

**Issue by skye** [google/benchmark#998]
For the google-benchmark Python package, it looks like only Python 3.6 and 3.7 wheels are created: https://pypi.org/project/google-benchmark/#files

[JAX](https://github.com/google/jax) also supports Python 3.8. We'd like to use the google-benchmark package, so ideally it would also be easily usable with Python 3.8. I'm not sure how hard this is to do, I can help if necessary.

cc @chr1sj0nes

**Comment by chr1sj0nes** [comment]
I'll sort it.

**Comment by nicholasjng** [comment]
> I'll sort it.

Quick question @chr1sj0nes , do you have access to `google-benchmark`'s PyPI account? If so, could you issue a PyPI token for use with GitHub Actions wheel uploads to this repo?
